### ISSUE TITLE
Edit without scrolling

### ISSUE THREAD

**Issue by cmyr** [lapce/lapce#1]
re: your comment on IRC earlier: what you're describing isn't currently possible. It sounds like you probably want a plugin, although I appreciate that it's a bit annoying to write plugins right now. If you can explain what you're trying to do a little bit maybe I can be more useful?

**Comment by dzhou121** [comment]
Thanks for your prompt reply. 

I’m trying to embed vim emulation in my front-end and doing lots of motion logic at the front-end side. The ones I couldn’t do right now is the d commands in vim. I could get around with selection first and delete but that would cause flickering in the front-end. So I’m wondering if front-end could directly modify content. It would be easy to achieve my goals including “join lines” (delete the \n of the current line), yank paste multiple times, etc.

**Comment by dzhou121** [comment]
I guess I'll just wait for the core to evolve more then. My ultimate goal is to replace the neovim backend of https://github.com/dzhou121/gonvim with Xi core.

On a separate note, neovim's front-end (external UI) and remote plugins are using the same API so they can call the same API. Also, they can send to and listen to RPC channels so it's very easy for them to talk to each other. The benefit is that in gonvim (take the fuzzy search for example), other plugins can extend the GUI fuzzy search implementation.

**Comment by cmyr** [comment]
Yea, that's interesting. I hadn't really been following neovim architecturally, although it is my daily editor right now.

The question of what commands should be supported in xi-core is a tricky one for sure.

Something raph and I have been talking about a bit lately is just how similar a frontend and a plugin are; there's a lot of overlap in certain areas. In other areas this is less true; a plugin might care about spans, but it doesn't need text to actually be _styled_. Lots of room for exploration here, though.

**Comment by dzhou121** [comment]
I would really love to see frontend and a plugin can call the same set of commands supported by xi-core. It's also easier for writing API libraries since you only need one for both frontend and plugins.

**Comment by cmyr** [comment]
@dzhou121 I'll give that some thought. It isn't clear to me that this makes total sense, though; for instance I don't think a plugin should be sending `Click` events, or things like `MoveLeft`. (A plugin might want to move the cursor, but it would do that by passing an explicit selection, not by emulating a keyboard event).

Writing an API library that supports both shouldn't be that hard as is; the core RPC mechanism is all shared, there are just two sets of commands you need to describe. That they're distinct doesn't make it much more complicated than having them be unified?

**Comment by dzhou121** [comment]
Take the vim easy motion plugin(https://github.com/easymotion/vim-easymotion) for example, it needs the ability to Click. What I’m talking is maximum flexibility of the API since we couldn’t imagine what kind of things front end or plugin developers want to achieve. 

Also personally it’s easier to put in mind that I can do everything than I can only do these in front end and those in my plugins. A front end author is very likely to write plugins.

**Comment by cmyr** [comment]
I've thought about this some more, and maybe one solution is to handle these types of actions through custom plugin commands; so when you encounter a vim command like `di<` which requires access to the buffer, you send a custom command to a companion plugin that can access the buffer and perform  the task.

This would let you do much of what you want today, although there are certain things plugins can't currently do (if only because we haven't gotten around to it) such as modify a user's selections. They do support custom commands, though, at least in theory; I don't believe this functionality is in the rust plugin library, but it was in the python plugin library (which is broken at the moment but could definitely be fixed)

**Comment by dzhou121** [comment]
I'll try this approach then. But I do hope front-end can also have access to the buffer as it would be much easier.
