### ISSUE TITLE
How to make auto-completion window pop-up?

### ISSUE THREAD

**Issue by yisonPylkita** [lapce/lapce#10]
I downloaded `.msi` package and installed it on Windows 10. After launching lapce I opened this repos source code and tried editing one of the files to see how lapce performs. 

On README.md screenshot you showed autocompletion box, yet I it doesn't show for me. Do I have to make additional steps in order for it to work?

![image](https://user-images.githubusercontent.com/8435296/145970186-cd2475dd-e492-4783-b0a6-49e516b3877a.png)

**Comment by ghishadow** [comment]
this works in latest build after installing Rust Extension

![image](https://user-images.githubusercontent.com/9583775/147799606-affb78b3-e358-4543-a0a1-ba22e437da49.png)

autocompletion looks like this
![image](https://user-images.githubusercontent.com/9583775/147799635-d7e176b5-af17-45b0-bc71-93e46f09147d.png)

**Comment by yisonPylkita** [comment]
I wasn't able to run it on Windows, but on Linux I was able to make autocompletion window pop up the way you @ghishadow showed so I guess I can close this.
One note here - you have to have open folder with Rust code to be able to install this extension
