### ISSUE TITLE
`Cargo.lock` file is out of sync for v0.0.10

### ISSUE THREAD

**Issue by papojari** [lapce/lapce#101]
[Someone tried to create a nix package recipe for this program since someone requested it](https://github.com/NixOS/nixpkgs/pull/162984) but a patch is currently needed because `Cargo.lock` is out of sync. Please bring back `Cargo.lock` in sync for the next version.

**Comment by bugadani** [comment]
Thanks for reporting this issue! Could you please specify if this is still a problem in the most recent release?

**Comment by papojari** [comment]
No it isn't anymore. They merged the pr with the patched lock file.
