### ISSUE TITLE
How to start contributing

### ISSUE THREAD

**Issue by ThilinaTLM** [lapce/lapce#103]
### Great work
Great work! This is what I have been looking for a long time. 
- Vim like Modal editing 
- VSCode like UI, Extension System, LSP
- Fast (No Chromium)

### Want to contribute
I am developer new to rust. I would really like to contribute to both development and documentation. Please someone give me contribution guideline. I would like to know the prerequisites.

**Comment by klvenky** [comment]
I'm an engineer with zero knowledge of Rust language. I'm comfortable in others. So I may not be able to immediately help as a dev but I'd like to contribute to the docs or QA. please let me know if there's something I can contribute

**Comment by jayy-lmao** [comment]
Some codebase specific docs would be great - but if you're getting started with Rust my first recommendation is reading `The Book`. It's free, and the best source of learning the fundamentals :) 
After that point you can find more specialized textbooks. My favourite has been "Microservices In Rust", "Functional Programming in Rust", and "Zero to Production in Rust"/

Best of luck!

**Comment by dzhou121** [comment]
https://github.com/lapce/lapce/blob/master/CONTRIBUTING.md Added now.

Please let me know if it's missing anything.
