### ISSUE TITLE
High CPU and GPU usage on idle with no files open on Windows 11

### ISSUE THREAD

**Issue by stephc-int13** [lapce/lapce#1043]
I was curious about this editor after seeing a post on Hacker News.

I downloaded and quickly tested it.

In my opinion a good canary test is looking for memory usage and idle CPU usage just after launch.

133 MBytes of memory use
25% of CPU use on idle
40% of GPU us on idle

**Comment by seomwan** [comment]
Same on first try for me. Subsequent runs fixed it.

Memory usage is still ~ 160 MB, of which:
30 MB is shell/console
128 MB is Lapce itself

**Comment by NotAgentBilly** [comment]
same, i commented here: https://github.com/lapce/lapce/issues/503#issuecomment-1236320569

**Comment by lilx2018** [comment]
Windows 10, when idle , 1% cpu and 0% gpu, but if I move mouse, 10+% cpu and ~70% gpu.

**Comment by lnicola** [comment]
I noticed this with the Settings tab open, but I think it's already reported.

**Comment by panekj** [comment]
Should be fixed via https://github.com/lapce/lapce/pull/1072
