### ISSUE TITLE
Feature Request: Show the last 3-5 commands used on command palette launch.

### ISSUE THREAD

**Issue by manaskarekar** [lapce/lapce#1054]
This makes it easy to access the last command, if not the last few, instead of having to type it out each time. 

Example, changing themes. Each time a new theme is applied, you have to go back and type 'Change Theme'  from the command palette. 

As a follow up to this example, the currently selected theme should show when the theme picker is launched. I presume the theme picker itself is ripe for further development where you can preview on the fly.

I'd love to jump in and contribute but would love to see what the team has decided about this (and whether the architecture allows buffering previously use commands).

**Comment by panekj** [comment]
Commands are now sorted according to usage
