### ISSUE TITLE
Settings pane renders continously

### ISSUE THREAD

**Issue by kennylevinsen** [lapce/lapce#1059]
Tested with wlhax on Wayland.

When displaying the Settings pane, Lapce submits new buffers continously and unconditionally, causing very high CPU utilization. The situation is very similar to https://github.com/lapce/lapce/issues/1058 where Lapce submits new buffers whenever there is cursor activity, except when the settings pane is open there is no such condition. As a result, my laptop attempts to turn itself into a space heater.

**Comment by dzhou121** [comment]
Should be fixed by https://github.com/lapce/lapce/commit/9f0120df85e3aaaef7fbb43385bb15d88443260a

**Comment by kennylevinsen** [comment]
Indeed, thanks!
