### ISSUE TITLE
Font rendering

### ISSUE THREAD

**Issue by flowHater** [lapce/lapce#106]
Config:
OS: Arch Linux x86_64
Kernel: 5.16.11-zen1-2-zen
Uptime: 2 days, 4 hours, 55 mins
Packages: 1132 (pacman)
Shell: zsh 5.8.1
Resolution: 1920x1080
WM: sway
Theme: Breeze [GTK2/3]
Icons: breeze [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 7 2700X (16) @ 3.700GHz
GPU: AMD ATI Radeon VII

I got some chat that does not render correctly when they are highlighted. As you can see on the command palette on my screenshot.
![image](https://user-images.githubusercontent.com/45258763/157061366-3ed1ad51-7209-4d53-a1f7-20414210e1e5.png)
![image](https://user-images.githubusercontent.com/45258763/157061766-b3d9c022-be94-4a92-bccd-0cfafd32e366.png)

It's always present. So I just have to open Lapce and `ctrl + shift + p` to write `Open` to see the issue.

Ps: Very nice project. Good to see something else than the promising but dead Xi-editor

**Comment by bugadani** [comment]
Thanks for reporting this issue!

Could you please specify, if this is only present in the command palette, or in other places of the UI?

**Comment by flowHater** [comment]
It has been fixed since the last update. So we can close this one. I cannot reproduce with the last version. I updated my packages since too. Can't specify what you ask

**Comment by bugadani** [comment]
Thanks!
