### ISSUE TITLE
Duplicate line with Alt+Shift+(ArrowUp / ArrowDown)

### ISSUE THREAD

**Issue by Bellisario** [lapce/lapce#1060]
## Is your feature request related to a problem? Please describe.

Currently there isn't a way to duplicate line like VSCode using the keys in the title.

## Describe the solution you'd like

I'd like this functionality to help people coming from VSCode finding at home into this editor.

## Describe alternatives you've considered

You can copy and paste the entire line manually but this is not very productive.

## Additional context

> VSCode example line duplication with this shortcut

![Lapce - Duplicate line Issue](https://user-images.githubusercontent.com/72039923/188615876-7cf912a9-9bf3-456d-a0ef-a49cd211efc2.gif)

**Comment by cindRoberta** [comment]
I prefer `Ctrl + Shift + ArrowUp` and `Ctrl + Shift + ArrowDown`
