### ISSUE TITLE
Opensuse

### ISSUE THREAD

**Issue by RafikSF** [lapce/lapce#1063]
## Opensuse

Opensuse os not supported even when i try to install it with tricky way still show a lot of weird bugs
(like freezing ect .. )
i want to see it added to "**zypper**" with one click install <3

## hope you get time to make it work good , thanks to your efforts

**Comment by Peter015** [comment]
worked for me, zypper in lapse from main repository. Are you on tumbleweed or leap?

**Comment by pgonin** [comment]
It worked for me with a flatpak
it seems also available from the 'editors' opensuse build service https://build.opensuse.org/package/show/editors/lapce

**Comment by panekj** [comment]
Closing since there is already community maintained lapce package for opensuse and our own distribution would be handled by RPM packaging
