### ISSUE TITLE
[Feature Request] Android build

### ISSUE THREAD

**Issue by linuxmobile** [lapce/lapce#1074]
Is there a possibility to add android support? there is currently no app good enough to work as a fullstack developer

**Comment by panekj** [comment]
What kind of graphical environment Android is using?
How big is the userbase that has hardware setup for proper software development on Android?

**Comment by linuxmobile** [comment]
> big is the userbase that has hardware setup for proper software development on Android

I don't know, but with new galaxy tabs i can work very well. I'm using s8 ultra as my laptop and with dex it's really good. I can use vscode-server but it's not funny to open vscode in browser

**Comment by Kelvinlby** [comment]
If we already know that Android has a large userbase, it means that there is already an excellent Android version of the code editor and has gained a large number of users, then it will be difficult for lapsce to gain users. And work with great tablet like ipad pro, galay tab is the current trend, lapce should seize the opportunity.

**Comment by panekj** [comment]
This is currently not planned
