### ISSUE TITLE
Bad Text Showing In UI

### ISSUE THREAD

**Issue by mohsenjavidpanah** [lapce/lapce#1075]
## Lapce Version

0.2.0

## System information

Windows 10 Enterprise

## Describe the bug

Text in the Lapce is not readable

## Additional information

![lapce](https://user-images.githubusercontent.com/28291175/188782101-cbe2b111-f9be-4065-9f80-c3664983de77.png)

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/940
