### ISSUE TITLE
Unable to view extensions

### ISSUE THREAD

**Issue by shree675** [lapce/lapce#1077]
## Lapce Version

0.2.0

## System information

Windows 10 21H1

## Describe the bug

I am unable to view the extensions available. There is no response on clicking on an extension causing all the details to be hidden. The  icons are also missing.
Additionally, some icons are distorted, like the settings icon and the close icon on my computer.

## Additional information

![image](https://user-images.githubusercontent.com/58718144/188805977-57e667cd-fda7-420e-84a8-ae075d9e0882.png)

**Comment by panekj** [comment]
> The icons are also missing.

Which icons are missing? Mind that plugins don't have icons/logos, and that padding in extensions tab is intentionally blank for now.

> Additionally, some icons are distorted, like the settings icon and the close icon on my computer.

Can you show screenshot? Are you using different DPI scaling?

**Comment by shree675** [comment]
> Mind that plugins don't have icons/logos, and that padding in extensions tab is intentionally blank for now.

I am sorry, I didn't know. But are they clickable?

> Can you show screenshot?

![image](https://user-images.githubusercontent.com/58718144/188948655-de9646b6-2a03-49b9-b222-e464f1fd3274.png)

![image](https://user-images.githubusercontent.com/58718144/188948765-9ec5288b-6afc-49b0-b8ad-86f9b8715445.png)

![image](https://user-images.githubusercontent.com/58718144/188948809-c84f7e26-4d67-44ce-8593-29e15964668f.png)

![image](https://user-images.githubusercontent.com/58718144/188948961-acc1fc29-7d21-47f6-b5fe-61b7b2ab645c.png)

Some icons are clipped or distorted. My default DPI scaling is set at 125%, and all other apps work well.

**Comment by panekj** [comment]
This should be fixed now. DPI issue is tracked elsewhere.
