### ISSUE TITLE
C++ code highlighting

### ISSUE THREAD

**Issue by saadman-sakib** [lapce/lapce#1080]
# Code highlighting for C++ language is not supported.

Even though It is supported for C, but doesn't highlight C++ codes  

![image](https://user-images.githubusercontent.com/65564521/188842471-2843e677-c348-414d-a06b-fe1e57a13128.png)

**Comment by ghishadow** [comment]
it will be fixed after https://github.com/lapce/lapce/pull/957 as we are adding new scopes requires for many languages. here is how it gonna look
![image](https://user-images.githubusercontent.com/9583775/188848272-4904dc20-6cb9-430c-b397-700825075af1.png)
