### ISSUE TITLE
Github-Copilot

### ISSUE THREAD

**Issue by Gako358** [lapce/lapce#1081]
Support for use of github copilot would be nice

**Comment by panekj** [comment]
Github Copilot is proprietary

**Comment by Gako358** [comment]
Due to the fact Copilot is proprietary would it not be possible to ask if possible to write an extension/plugin to use with lapce?
It will only increase the marked for Github Copilot, it exist for Neovim, VScode, VS and Jetbrains tools..

**Comment by panekj** [comment]
All those plugins are or contain proprietary code from GitHub and require Node.JS to run, it's definitely not in lapce scope to provide such integration. We are working on providing proper API for plugins to interact with editor which will enable someone to make such plugin if they want.

**Comment by Gako358** [comment]
Understandable, will close. 
Thanks for replying

**Comment by jonathanhecl** [comment]
I  would like to see copilot on Lapse :)
