### ISSUE TITLE
Emmet for Lapce??

### ISSUE THREAD

**Issue by bonfiglioalessio** [lapce/lapce#1090]
## Is your feature request related to a problem? Please describe.

How can web developers write code more efficiently from scratch?

## Describe the solution you'd like

Emmet is a set of plug-ins for text editors that allow for high-speed coding and editing in HTML, XML, XSLT, and other structured code formats via content assist.

## Additional context

<img width="643" alt="Schermata 2022-09-08 alle 10 20 16" src="https://user-images.githubusercontent.com/52224078/189072549-5c3487ee-c77e-4c5c-8c4d-5bccca4efc11.png">

**Comment by panekj** [comment]
There are few available as LSPs so that would be best implemented via plugin
