### ISSUE TITLE
Emojis are rendered outside of a tooltip 

### ISSUE THREAD

**Issue by rtimush** [lapce/lapce#1098]
## Lapce Version

0.2.0

## System information

macOS 12.5.1

## Describe the bug

Emojis in tooltips are rendered outside of the tooltip, at least for Rust when hoovering over the `String` type.

## Additional information

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/831307/189205423-f529c094-25df-4db1-a290-5c68f4776f55.png">

It feels like the screen positions for emojis have doubled coordinates, compared to the regular characters.

**Comment by bugadani** [comment]
Same on windows, emojis seem to exist on a different layer.
