### ISSUE TITLE
LaTeX syntax highlighting

### ISSUE THREAD

**Issue by msiniscalchi** [lapce/lapce#1105]
Is there a plan to enable LaTeX syntax highlighting? There exists a treesitter parser for it: 

https://github.com/latex-lsp/tree-sitter-latex

**Comment by panekj** [comment]
We have one issue for all the tree-sitter grammars: https://github.com/lapce/lapce/issues/272

**Comment by msiniscalchi** [comment]
Cool. So should I close this issue and add to #272?

**Comment by bugadani** [comment]
I've added it to the list, and I'm closing this one because I don't see how #1104 is relevant :) Thanks for the request!
