### ISSUE TITLE
Disable OpenGL

### ISSUE THREAD

**Issue by DUOLabs333** [lapce/lapce#1108]
## Is your feature request related to a problem? Please describe.

My computer does not support ES 3.30, but only 3.00, so I would like to be able to disable OpenGL to use the app (especially since it doesn't seem required, but just for better rendering)

## Describe the solution you'd like
Start with OpenGL off, and offer to turn it on when first opened.

## Describe alternatives you've considered

Have a option to turn it off in the config file.

**Comment by sanxiyn** [comment]
Where did you get the impression "it doesn't seem required"? As far as I know it is required, so this issue can't be fixed.

**Comment by DUOLabs333** [comment]
I meant that it isn't required to make the app work --- not too long ago, lapce didn't even use opengl, so I'm assuming nothing specifically needs opengl to work.

**Comment by sanxiyn** [comment]
Ah. Looking at history, 4abb0fa "switched to OpenGL backend" in April. I can't find why the switch was made, but probably @dzhou121 can answer.

**Comment by ghishadow** [comment]
it changed from wgpu to opengl in this release, first line says why https://github.com/lapce/lapce/releases/tag/v0.1.0 

![image](https://user-images.githubusercontent.com/9583775/189467194-440404f1-ce8f-4426-a7c8-e7e7f2542d9a.png)

![image](https://user-images.githubusercontent.com/9583775/189467241-87f4d62b-e2ea-435b-a468-0c0cbeed4a04.png)

if you are on Linux, does `LIBGL_ALWAYS_SOFTWARE=1` works ?

**Comment by DUOLabs333** [comment]
It does --- doesn't seem to be too slow either. Maybe allow something like `LAPCE_SOFTWARE_RENDER`, so it won't interfere with other GPU-powered applications?

**Comment by ghishadow** [comment]
it will not interfere with others if you run `LIBGL_ALWAYS_SOFTWARE=1 lapce`, maybe add to your Desktop file

**Comment by DUOLabs333** [comment]
Yes, but if I update, the desktop file will be overwritten.

**Comment by ghishadow** [comment]
there is systemwide Dekstop file which resides in `/usr/share/applications` which is updated with Application and User specific in  `~/.local/share/applications` which doesn't get updated and higher preference 
https://wiki.archlinux.org/title/Desktop_entries
![image](https://user-images.githubusercontent.com/9583775/189530419-823628cb-ec78-437a-8a90-dfaa4b9d61d2.png)
so 
``` bash
cp /usr/share/applications/dev.lapce.lapce.desktop ~/.local/share/applications/dev.lapce.lapce.desktop
``` 
and modify it

**Comment by DUOLabs333** [comment]
Fair enough --- hopefully nothing changes, so I don't have to keep updating it, though I would still like some configuration option.

**Comment by bugadani** [comment]
I wonder if we can set `LIBGL_ALWAYS_SOFTWARE` in Lapce, based on a setting. I don't know if it would do anything when the program is running, but maybe we could show a message that a reload is required, if we have to. Feels really hacky, but it would be a start.

**Comment by ghishadow** [comment]
![image](https://user-images.githubusercontent.com/9583775/189564010-d8257f03-1b5c-4ec9-9432-fb69513865e7.png)
Vscode has this flag to disable gpu, maybe we can something similar in future

**Comment by DUOLabs333** [comment]
Are there any features that are used that is not supported by 3.00?

**Comment by midzer** [comment]
Current lapce v0.3 works for me without addition command line flags.

```
OpenGL version string: 2.1
```
via `glxinfo`
