### ISSUE TITLE
Update Deprecated mio Imports

### ISSUE THREAD

**Issue by therealstork** [lapce/lapce#111]
There's a couple places in the codebase (all under lapce-proxy and lapce-rpc) where there are deprecated mio inputs. (e.g. [here](https://github.com/lapce/lapce/blob/4d3a4918646656fb372055b64d6549554e6fba73/lapce-proxy/src/terminal.rs) )

These should be replaced with updated mio imports at some point.

**Comment by bugadani** [comment]
Thanks for opening this issue!

Duplicate dependencies and their effect on compile time and binary size are in general tracked by #24 so I'm closing this in favour of that ticket.
