### ISSUE TITLE
Support top navigation bar

### ISSUE THREAD

**Issue by zyxkad** [lapce/lapce#1111]
## Is your feature request related to a problem? Please describe.

It's hard to find the key binding for do something _~~(when I opened the issue, I'm still trying to find which shortcut key can build my project)~~_

The top nav bar is too empty:
<img width="1066" alt="Screen Shot 2022-09-09 at 3 05 23 PM" src="https://user-images.githubusercontent.com/91082411/189445704-cd004279-c638-49f0-a890-fb8fcffc2e20.png">

## Describe the solution you'd like

Add something to the nav bar

**Comment by MinusGix** [comment]
I believe you're referring to the 'File' (with options like save, save-as, quit), 'Edit', etcetera that other programs (such as VSCode) have?

**Comment by zyxkad** [comment]
> I believe you're referring to the 'File' (with options like save, save-as, quit), 'Edit', etcetera that other programs (such as VSCode) have?

Yes, you are right, but not only the 'File'

**Comment by panekj** [comment]
Resolved via https://github.com/lapce/lapce/pull/1880
