### ISSUE TITLE
Minimize `open editors` at the side bar as a single line

### ISSUE THREAD

**Issue by zyxkad** [lapce/lapce#1114]
## Is your feature request related to a problem? Please describe.

We already have opened files on the top bar, the side bar one seems unnecessary most of times

## Describe the solution you'd like

We can let `Open Editors` which at the sidebar can be minimize as a single line

## Additional context

The `Open Editors` takes me 25% space in the sidebar
<img width="253" alt="Screen Shot 2022-09-09 at 3 45 50 PM" src="https://user-images.githubusercontent.com/91082411/189450171-d4ee7d0a-4009-4dd6-b2d6-cda6c8443ece.png">

**Comment by Timmmm** [comment]
VSCode lets you hide this entirely by right-clicking on it. Seems like a decent option:

![image](https://user-images.githubusercontent.com/376842/193676117-2584f6bc-3a31-4f88-b5cd-c2b26cec6add.png)

**Comment by superlou** [comment]
This is related to #1398.

**Comment by zyxkad** [comment]
> This is related to #1398.

No it isn't, 1398 is a bug for lapce, this is only a feature request

**Comment by superlou** [comment]
I'm not saying it's a duplicate, just that someone looking at this may see similar comments in that issue, or someone in that issue may see this one as a mechanism to resolve the issue.

**Comment by zyxkad** [comment]
> I'm not saying it's a duplicate, just that someone looking at this may see similar comments in that issue, or someone in that issue may see this one as a mechanism to resolve the issue.

In that case, you should comment in 1398, not this issue. Because 1398 cannot affect this issue
