### ISSUE TITLE
Let terminal use tag to switch, not divide

### ISSUE THREAD

**Issue by zyxkad** [lapce/lapce#1115]
## Is your feature request related to a problem? Please describe.

If I want to open multi terminal, I must use the divide button divide a terminal to two.
And the space become less, is not good for operation

## Describe the solution you'd like

Add tags at the left or top side that can switch terminal

## Additional context

Single is ok:
<img width="1009" alt="Screen Shot 2022-09-09 at 5 27 16 PM" src="https://user-images.githubusercontent.com/91082411/189458564-b3fdea5e-c07a-452c-878a-bcd9df8edaee.png">

Multi is not good:
<img width="1017" alt="Screen Shot 2022-09-09 at 5 27 45 PM" src="https://user-images.githubusercontent.com/91082411/189458579-013eb21c-5acf-4f9f-be5b-8ec5cc359e1e.png">

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/1770
