### ISSUE TITLE
Adding a Flutter Batterie

### ISSUE THREAD

**Issue by LimaneGaya** [lapce/lapce#1125]
Adding a flutter batterie allowing syntax highlighting ...

**Comment by Conrad306** [comment]
I'll try and work on a plugin for it, im doing so right now. I'll see how it goes and start testing it.

**Comment by LimaneGaya** [comment]
That would be really great if it can happen, it will make me switch from vs code

**Comment by franklinblanco** [comment]
Let's close this Issue
