### ISSUE TITLE
Support Japanese

### ISSUE THREAD

**Issue by tasuren** [lapce/lapce#1129]
## Is your feature request related to a problem? Please describe.
When I try to input Japanese, the English characters on the keys I press are input as they are, and I cannot input Japanese.
And lapce can't render Japanese.
Also I tried change font but it dosen't work.

## Describe the solution you'd like
lapse should be able to render Japanese characters and be able to input Japanese characters gracefully.

## Describe alternatives you've considered
None

## Additional context
None

**Comment by VarLad** [comment]
Duplicate of https://github.com/lapce/lapce/issues/319

**Comment by tasuren** [comment]
Oh sorry.
Should I close this issue?

**Comment by VarLad** [comment]
@panekj Not really completed xD
Also I think this should be re-opened. 
From https://github.com/lapce/fount/blob/master/src/data.rs#L270 I think that the intended behavior is to support displaying Japanese if the the Noto Sans CJK JP fonts are found. 
It does work for Chinese but I can't get Japanese characters to display (I have fonts for both) 

Should we reopen it or should @tasuren make a new issue for _displaying_ Japanese? (Thats a valid bug)

**Comment by panekj** [comment]
> displaying Japanese if the the Noto Sans CJK JP fonts are found.

https://github.com/lapce/lapce/issues/737

**Comment by VarLad** [comment]
@panekj I think they just forgot to close the issue xD
But yeah, we can use that one :D

**Comment by tasuren** [comment]
I'm going to use #737.
