### ISSUE TITLE
Open Lapce here not working on Windows 10

### ISSUE THREAD

**Issue by cindRoberta** [lapce/lapce#1134]
## Lapce Version
0.2.0

## System information
Edition: Windows 10 Pro x64
Version: 21H2
OS Compilation: 19044.1889
Experience: Windows Feature Experience Pack 120.2212.4180.0

## Describe the bug
Open Lapce here not working on Windows 10

**Comment by panekj** [comment]
Fixed in https://github.com/lapce/lapce/pull/1158
