### ISSUE TITLE
Can't Open Lapce On Windows 10

### ISSUE THREAD

**Issue by W0lfDev** [lapce/lapce#1136]
## Lapce Version
Can't open the app, so I don't know the version, but I downloaded the latest build from the official website on 11th of september 2022

## System information
Windows 10 - Cracked ):

## Describe the bug
After I installed the app, I tried to launch it via the start menu (btw can you add a desktop shortcut), and It gave me an error

## Additional information

![Screenshot (60)](https://user-images.githubusercontent.com/96019707/189517844-209b0e9b-c12a-4449-ae51-67247d4b2ec5.png)

**Comment by panekj** [comment]
What Windows version are you using?
`Win` + `R` then type `winver` and run

**Comment by BraedenCallahan** [comment]
I am running windows 10, and I do not share this issue. Make sure you downloaded the correct version from the website, you might need Portable 64 bit as apposed to the system installer, which I could not get working.

**Comment by seomwan** [comment]
FYI, the system installer also worked for me at with 0.20 https://github.com/lapce/lapce/issues/1014#issuecomment-1237861719, haven't tried the latest  yet

**Comment by korodarn** [comment]
I'm having the same issue, application won't launch.  First time windows defender comes up, I say to run anyway, and then it won't launch.  I have tried both the nightly and 0.20

**Comment by mpcref** [comment]
Same here:

- Using Windows 10 Pro N 21H1
- Downloaded both System Installer and Portable just now
- Same issue with both: after clicking "Run anyway" the app doesn't open

**Comment by seokkuuu** [comment]
I have a similar bug, but it doesn't open anyway, I checked the task manager and I saw a new task (the lapce task) but it desappears after seconds.

The logs and more information of my bug #1614

**Comment by panekj** [comment]
This was most likely a druid issue
