### ISSUE TITLE
Entry Point not found

### ISSUE THREAD

**Issue by a-rabin** [lapce/lapce#1137]
Version 0.2.0
Windows 8.1 

When I ran Lapce for the first time I got this error:
```The procedure entry point ResizePseudoConsole could not be located in the dll C:\Program Files\lapce.exe```

![image](https://user-images.githubusercontent.com/60351015/189517977-f61cda85-01a6-4d30-b694-d99879168e30.png)
Any fixes?

**Comment by panekj** [comment]
You need at least Windows 10 1809 to use Lapce

**Comment by a-rabin** [comment]
well thats disappointing

**Comment by panekj** [comment]
Duplicate of #132
