### ISSUE TITLE
Request | Keyboard Shortcuts

### ISSUE THREAD

**Issue by cindRoberta** [lapce/lapce#1138]
- [ ] Copy Line Up | Ctrl + Shift + ArrowUp
- [ ] Copy Line Down | Ctrl + Shift + ArrowDown
- [ ] Reopen Closed Tab | Ctrl + Shift + T
- [ ] Next Tab | Ctrl + PageDown (or Alt + ArrowRight)
- [ ] Previous Tab | Ctrl + PageUp (or Alt + ArrowLeft)

### Change
- [ ] Scroll Up | Ctrl + ArrowUp (current: Ctrl + PageUp)
- [ ] Scroll Down | Ctrl + ArrowDown (current: Ctrl + PageDown)

**Comment by panekj** [comment]
You can rebind keys yourself

**Comment by cindRoberta** [comment]
relateds:
https://github.com/lapce/lapce/issues/1065
https://github.com/lapce/lapce/issues/1060
https://github.com/lapce/lapce/issues/178

**Comment by cindRoberta** [comment]
> Except for `Reopen closed tab` and `Copy line {up,down}` (since those are not yet implemented), you can rebind keys yourself

I think that `Ctrl + {PageUp, PageDown}` for scrolling must be rethought, but it's just my opinion

What's the commands to Next tab and Previous Tab?

**Comment by panekj** [comment]
`Next editor tab`, `Previous editor tab`

**Comment by cindRoberta** [comment]
> `Next editor tab` (`Ctrl` + `Tab`) `Previous editor tab` (`Ctrl` + `Shift` + `Tab`)

`Ctrl +  Tab` is ok, but `Ctrl + Shift + Tab` is cursed, I will change it for `Ctrl + '`

**Comment by cindRoberta** [comment]
@panekj what's the command for back off indentation?

**Comment by zachhuang610** [comment]
related: #1727

**Comment by cindRoberta** [comment]
> @panekj what's the command for back off indentation?

`Ctrl + [`
