### ISSUE TITLE
lapce- entry point is not found

### ISSUE THREAD

**Issue by dove88** [lapce/lapce#1144]
![IMG_20220911_181237.jpg](https://user-images.githubusercontent.com/85496354/189528146-86c4d809-e921-4c31-bb98-617bfd849304.jpg)

Please check the bug report in the photo attached.

**Comment by sebastian-de** [comment]
Duplicate of https://github.com/lapce/lapce/issues/1137

**Comment by dove88** [comment]
I have windows 10,

**Comment by panekj** [comment]
You need at least `Windows 10 October 2018 Update (version 1809)`

**Comment by dove88** [comment]
Ok
