### ISSUE TITLE
Fix settings: Enable customised titlebar and disable OS native one......

### ISSUE THREAD

**Issue by ashusharmasigdev** [lapce/lapce#1147]
## Lapce version
0.2.0

## System information

Ubuntu 21.10

## Describe the bug
It is good yet, but when the setting **Enable customised titlebar...** get uncheck, it hide its customised titlebar and do not show native of os without being it restarted.

## Solving
Do not hide the **customised titlebar** in opened session (or the session in the setting is modified).

## Additional information
![image](https://user-images.githubusercontent.com/95996311/189530138-a9742428-dd82-4bcc-b573-eb8c07d6fa21.png)

**Comment by sokorototo** [comment]
Hey in the latest version of lapce, turning this on and off reinstalls the window controls. I'm running version `0.2.0` from the releases page, on Arch Linux KDE Kernel 5.18. Maybe try checking out the latest version of lapce in the `Releases`

**Comment by panekj** [comment]
> Maybe try checking out the latest version of lapce in the [`Releases`](https://github.com/lapce/lapce/releases/tag/v0.2.0)

They are using latest release

**Comment by ashusharmasigdev** [comment]
@sokorototo I have previously downloaded it from its website, also i tested it right now from the **Releases** page, both are same, the problem is also same. @panekj  is right.

**Comment by sokorototo** [comment]
@ashusharmasigdev then I guess it's a genuine bug

**Comment by panekj** [comment]
Titlebar now doesn't change after modifying setting
