### ISSUE TITLE
Use select dropdown for theme selector instead of textbox

### ISSUE THREAD

**Issue by sokorototo** [lapce/lapce#1148]
## Is your feature request related to a problem? Please describe.

The issue is once a user installs a theme, they don't know the exact technical name the editor uses to identify the theme. The theme selector expects the user to enter this name into a textbox. This makes changing themes an exercise in guessing and memory gymnastics

## Describe the solution you'd like

Use a select dropdown for the theme selector instead of a textbox.

## Describe alternatives you've considered

A select dropdown is best, but some radio buttons could work. The issue with radio buttons is that more themes mean more buttons, cluttering the UI.

## Additional context

`lapce` allows users to install themes from the marketplace. A user only knows the friendly marketplace name and not the technical identifier. Making changing themes non-trivial

**Comment by bugadani** [comment]
cc #302

In the meanwhile, you can select themes using the command palette. Press `F1`, type in `Theme`, Select `Change theme` and you have a (well hidden) dropdown.

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/1938
