### ISSUE TITLE
[Win11] Terminal Shell Option Shows No Effect

### ISSUE THREAD

**Issue by rondDev** [lapce/lapce#1155]
## Lapce Version
Version 0.2.0

## System information
Windows 11 Pro 22H2 Build 22621.590

## Describe the bug
Tried changing terminal shell, but no change occured. Option changed "Shell (Set the terminal shell)"

Attempted:
"C:\Program Files\Git\git-bash.exe"
C:\Program Files\Git\git-bash.exe
git-bash.exe

No errors occured, but shell did not change. Powershell still persists even after restarting the program multiple times after the changes mentioned above.

## Additional information
No ongoing theories thus far.

**Comment by bugadani** [comment]
I'm marking this as C-feature because I'm not even sure if we have an implementation in place.

**Comment by bugadani** [comment]
This line is a bit naive as it doesn't allow for spaces in paths: https://github.com/lapce/lapce/blob/master/lapce-proxy/src/terminal.rs#L63

This means that the `program` in `which::which(program)` is basically `C:\Program` which is nonsense.

I'm not sure if `which` could find `git-bash.exe`. In my case, it's not in PATH so I'm pretty sure it can't, but I'm not sure otherwise.

**Comment by rondDev** [comment]
Update;

Adding path to "C:\Program Files\Git" makes you able to set git-bash.exe as Shell

The downside to this is that it spawns it in a seperate window.

![lapce_9u3U98y2ZL](https://user-images.githubusercontent.com/30192333/189541737-dcc5f52d-a969-4a25-81fd-cc36073a4e8f.png)

**Comment by Bigous** [comment]
Mine doesn't work too. Trying to set to "C:\Program Files\PowerShell\7\pwsh.exe" for the updated version of powershell and it still opens the old one.

![image](https://user-images.githubusercontent.com/6886560/191368941-f1957e02-b2bd-457e-9f6e-1a79aada292a.png)

From there, I can open pwsh:
![image](https://user-images.githubusercontent.com/6886560/191369097-0fb0afce-08e5-4357-84d2-a669fb4f2e51.png)

**Comment by sfc9982** [comment]
Mine doesn't work too.

**Comment by schwrzstrbn** [comment]
> Mine doesn't work too. Trying to set to "C:\Program Files\PowerShell\7\pwsh.exe" for the updated version of powershell and it still opens the old one.

I had similar problem. I actually found a solution but I can no longer recall what I did to fixed that problem. I don't think this problem is lapce's terminal specific.

**Comment by ShayBox** [comment]
It doesn't resolve spaces in the path, which most shells will have since Windows puts a space in Program Files and Program Files (x86), a temporary solution is to put the path of the binary in your system PATH, which Powershell already is, just enter `pwsh` and it'll work.

**Comment by sfc9982** [comment]
> It doesn't resolve spaces in the path, which most shells will have since Windows puts a space in Program Files and Program Files (x86), a temporary solution is to put the path of the binary in your system PATH, which Powershell already is, just enter `pwsh` and it'll work.

Works on my Lapce (v0.2.1)

**Comment by DexSlender** [comment]
I make a BATC file `C:\bash.cmd` in another more accessible directory with this content
```bat
@"%~dp0\Program Files\Git\bin\bash.exe"   %*
```
and that's works

_yarn does something similar_

![lapce_NZBrCi6W7m](https://user-images.githubusercontent.com/91853649/200451022-e5ce09ca-04ff-4f4c-ac20-2bcacd64042d.png)

**Comment by ShayBox** [comment]
The `bin` folder of Git (and any other program) is supposed to be in your system `PATH` environment variable, on linux this folder would have been installed to a location already in `PATH`, but on windows the Git for Windows installer is supposed to do this for you.  
If `bash` isn't available in your command prompt or powershell, you may have to manually add it to `PATH`

**Comment by xlsigned** [comment]
You can use `dir /X C:\` in a CMD-Window on Windows to figure out what the **8dot3** name of  `C:\Program Files` is on your system, e. g. `C:\PROGRA~1`, and then use this to specify the shell, e. g.
```
C:\PROGRA~1\git\bin\bash.exe -i -l
```
