### ISSUE TITLE
Keybinds don't work

### ISSUE THREAD

**Issue by CatDevz** [lapce/lapce#116]
Typing in the document itself works as expected, however no keybinds works. There is no context in which keybinds worked. I tested from both the latest release version and built from source.

**Comment by SoulDrivenDev** [comment]
Perhaps relevant: I loaded lapce for the first time and got Ctrl+shift+P working for the command palette, but then no keyboard shortcuts worked after that.

**Comment by bugadani** [comment]
Hi and thanks for reporting this issue!

There have been a number of changes made to the key bindings. Could you please test if this issue has been resolved or not?

**Comment by SoulDrivenDev** [comment]
Latest release works wonderfully for me :)

**Comment by bugadani** [comment]
Glad to hear it! :)
