### ISSUE TITLE
Open in File Explorer (Menu item)

### ISSUE THREAD

**Issue by franklinblanco** [lapce/lapce#1164]
## Is your feature request related to a problem? Please describe.
No, just a feature I intend on adding.
## Describe the solution you'd like
I want to add a new MenuItem called Open in file explorer
## Additional context
The reason I open an Issue for this is I have a few questions: 
What are the steps run a Command on the terminal? I have looked around in the project and there seems to be a LapceCommand enum, then an implementation. Not very experienced with LapceProxy, ExtEventSink, nor do I think there needs to be any feedback/callback to the code, right?
Thinking of just depending on the platform, executing the command to open the file/dir.
Following [this guide](https://stackoverflow.com/questions/66485945/with-rust-open-explorer-on-a-file)
Sorry if I'm not too familiar with the project yet, I want to waste as little time as possible for the maintainers and developers, that's why instead of guessing with a PR I'd rather ask. 
Thanks in advance.

**Comment by panekj** [comment]
There isn't necessary backend code to achieve that on any platform

**Comment by franklinblanco** [comment]
> There isn't necessary backend code to achieve that on any platform

So it should all just be in Lapce-ui?

**Comment by panekj** [comment]
> So it should all just be in Lapce-ui?

For basic implementation, yes, it will be mostly in `lapce-ui`

**Comment by panekj** [comment]
But as I mentioned, we don't have backend code for that (`druid`) so it's not possible to properly reveal items in system file explorer.
hacky way available that doesn't highlight items: https://github.com/lapce/lapce/commit/673e68cf14d8476b7f4f4d5eb2eddd2daa775291

**Comment by franklinblanco** [comment]
You're too quick man, amazing. Implementing it right now

**Comment by franklinblanco** [comment]
@panekj Hey, sorry to bring this back up again, just read your comment four times over and I think we aren't on the same page. Just to be clear, this is what I mean:
<img width="486" alt="Screen Shot 2022-09-11 at 11 10 47 PM" src="https://user-images.githubusercontent.com/72827992/189567055-6e4e08d9-7a7e-4a27-8fcd-7dbd63e2c94e.png">

If that's what you meant in the first place then still, how does druid have to do with the rust code not being able to call a command in the terminal like: 

```rust
use std::process::Command;

fn main( ) {
    println!( "Opening" );
    Command::new( "open" )
        .arg( "." ) // <- Specify the directory you'd like to open.
        .spawn( )
        .unwrap( );
}
```

**Comment by panekj** [comment]
File explorer can be opened with certain files selected (at least on Windows) and that's platform specific behaviour using platform API which would fit into druid. Your example is how it can currently be implemented but its not ideal.

**Comment by franklinblanco** [comment]
So is there no way of getting the platform as an enum/string and performing the correct operation based on it? Last question on the topic

**Comment by panekj** [comment]
Yes but that's now how it should be done. There are attribute macros in Rust to enable conditional compilation for specific targets since platform APIs are just bindings to C/C++ code.

**Comment by franklinblanco** [comment]
Perfect now I fully understand, thank you for the time taken to explain it thoroughly!
