### ISSUE TITLE
Control-Clicking (goto definition) disrupts multi-cursor shortcut

### ISSUE THREAD

**Issue by rondDev** [lapce/lapce#1172]
## Lapce Version

Version 0.2.0

## System information

Windows 11 Pro 22H2 Build 22621.590

## Describe the bug

Ctrl+Click goes to definition, so trying to click to add multi-cursor (Ctrl+Alt+Click) gets tedious as it also opens definition. 

It does add a _n_th cursor, but it's annoying to be brought to the definition each time.

**Comment by dzhou121** [comment]
You don't need Ctrl for multi-cursor. It's Alt+Click.

**Comment by rondDev** [comment]
Wow, I am dumb, apologies.
