### ISSUE TITLE
The mouse press position is still incorrect

### ISSUE THREAD

**Issue by 745404527** [lapce/lapce#1173]
## Lapce Version

**0.2.0**

## System information

**Windows 10**

## Describe the bug
The mouse press position is still incorrect.
**(deflect downwards)**

**Comment by panekj** [comment]
A little bit more information?

**Comment by 745404527** [comment]
I will offer it tomorrow

**Comment by 745404527** [comment]
> I will offer it tomorrow

I'm already sleeping

**Comment by bugadani** [comment]
I suspect the window is opening without the custom title bar, and the contents are a bit stretched (this is what I experience). Resizing the window makes everything appear for me correctly. Please confirm if something similar is happening to you.

**Comment by 745404527** [comment]
Yes, that's what happened to me

**Comment by 745404527** [comment]
Sorry for wasting your time.
