### ISSUE TITLE
`Unknown option -n`

### ISSUE THREAD

**Issue by howardjohn** [lapce/lapce#1178]
## Lapce Version
0.2.0

## System information

Linux debian

## Describe the bug
```
$ lapce -V
Lapce 0.2.0
$ lapce -h
Lapce 0.2.0

USAGE:
    lapce [OPTIONS] [PATHS]...

ARGS:
    <PATHS>...

OPTIONS:
    -h, --help       Print help information
    -n, --new
    -V, --version    Print version information
$ lapce -n
Unknown option -n
```

## Additional information

I would expect either the `-n` flag is not documented, or it doesn't report "unknown option"

**Comment by panekj** [comment]
can't reproduce
