### ISSUE TITLE
如何设置插件，比如rust插件。

### ISSUE THREAD

**Issue by SmiteWindows** [lapce/lapce#118]

**Comment by U007D** [comment]
Google Translate:
How to setup plugins, like rust plugins.

**Comment by panekj** [comment]
Rust plugin should pretty much work out of the box after installation

**Comment by HainanWinter-l** [comment]
我尝试在wsl和我的服务器中安装插件，但语言插件在点击安装后会一直显示“安装中”
i try to install plugins in wsl and my server, but when i click install, it will always say "installing".(language plugins)

**Comment by HainanWinter-l** [comment]
> Rust plugin should pretty much work out of the box after installation

【无法安装】我尝试在wsl和我的服务器中安装插件，但语言插件在点击安装后会一直显示“安装中”。
[ cant not install ] i try to install plugins in wsl and my server, but when i click install, it will always say "installing".(language plugins)

**Comment by panekj** [comment]
@HainanWinter-l https://github.com/lapce/lapce/issues/1551 - currently it doesn't work

**Comment by HainanWinter-l** [comment]
> currently it doesn't work
我想我理解了，谢谢您的帮助
i see, thank u for your help
