### ISSUE TITLE
Ability to drop files into the editor

### ISSUE THREAD

**Issue by sokorototo** [lapce/lapce#1181]
## Is your feature request related to a problem? Please describe.

Say I have the editor open and I see a file in my file manager I want to quickly open. I try dragging and dropping into the editor, _no dice_.

## Describe the solution you'd like

It's quite simple: open a new editor for the dropped file; if the file lives in the current workspace/folder, behave as though it was opened via the Side Bar.

## Describe alternatives you've considered

`lapce` could open a small dialogue asking whether the user trusts the given file. Also whether to enable advanced editor features like `LSP`.

## Additional context

None, I just like `lapce`

**Comment by Jieiku** [comment]
I was about to open the same feature request. This is how I previously used Atom, and how I currently use Kate.

**Comment by codecat** [comment]
Additionally, the ability to drag and drop entire folders to make Lapce open the folder.

**Comment by spartanatreyu** [comment]
If Lapce supports multiple panes, what should happen when dragging-and-dropping:

1. Dropping a file anywhere onto a pane should open the file in that pane.
2. Dropping a file near the center of a pane should open the file in that pane, but dropping a file near an edge of a pane should split the pane and put the dropped file into the new pane.

**Comment by tinyaustralia** [comment]
Such basic functionality which makes me sad as I love Lapce otherwise. No drag/drop support anywhere and this has been a longstanding request from the community. Back to VS code I guess.

**Comment by jm-observer** [comment]
I am also very sad. As you can see, there are too few developers now, and many basic functions are missing. I can only slowly make up for it.

**Comment by rschiang** [comment]
@tinyaustralia I think we should all cherish open source project developers more. As you could see, for the longstanding request from the community to really happen, either someone funds staff to work on the project, or some of community members actually contribute code.

The way Lapce implements its cross-platform UI makes this a hassle to achieve, as you’ll need to actually get Druid to implement the API reliably across different platforms. I’d suggest starting from there.

**Comment by panekj** [comment]
> The way Lapce implements its cross-platform UI makes this a hassle to achieve, as you’ll need to actually get Druid to implement the API reliably across different platforms. I’d suggest starting from there.

Slightly off-topic, but since the issue was opened we replaced Druid (since it was deprecated) with [our own GUI toolkit](https://github.com/lapce/floem).

**Comment by rschiang** [comment]
@panekj Ah thanks! Haven’t digged into the UI stack for a while. Will definitely look what can be done in Floem!

**Comment by dzhou121** [comment]
should be implemented now in latest v0.4.1

**Comment by tinyaustralia** [comment]
> should be implemented now in latest v0.4.1

What a nice surprise! Thank you.

**Comment by dzhou121** [comment]
> > should be implemented now in latest v0.4.1
> 
> What a nice surprise! Thank you.

You have @jm-observer to thank who implemented this feature among a lot of other new features.

**Comment by Jieiku** [comment]
I started using Lapce again recently, drag and drop is working for folders and files, YAY!

Thank You!
