### ISSUE TITLE
Putting a period in find box crashes lapce

### ISSUE THREAD

**Issue by ConnorSMorrison** [lapce/lapce#1183]
## Lapce Version

0.2.0

## System information

Manjaro Ruah 21.3.7

## Describe the bug

Whenever you press ctrl+f and put a period in the box that comes up, lapce will freeze and crash.

## Additional information

The terminal doesn't say anything about it. I don't know what would cause this.

**Comment by tzAcee** [comment]
The problem has probably something to do with the regex-match functionality.
While '.' stands for any character.

The same "crash" can be invoked with putting for example \D in the search bar, which matches all non digits. Im not even sure if it's a crash or the matcher is just searching so long.

**Comment by Carol25170** [comment]
[transfer.pcloud.nsH6KJ4u.zip](https://github.com/user-attachments/files/20601622/transfer.pcloud.nsH6KJ4u.zip)
