### ISSUE TITLE
Typescript highlighting does not work for .tsx files

### ISSUE THREAD

**Issue by EgoistGray** [lapce/lapce#1186]
## Lapce Version

nightly-99c4fd4

## System information

Windows 11 21H2

## Describe the bug
As the title says, it appears the highlighting works perfectly for typescript files however does not seem to recognize the ".tsx" extension. 

![image](https://user-images.githubusercontent.com/64579881/189877923-5ff23377-2217-4cf7-b6be-3193aeb061e2.png)

![image](https://user-images.githubusercontent.com/64579881/189877641-a12b58e5-70ac-418d-a966-a4ec6d4c3f9a.png)

**Comment by ghishadow** [comment]
looks like I missed TSX and JSX in https://github.com/lapce/lapce/pull/1145, it is small change, I will fix in sometime or you can follow that pr and add it
