### ISSUE TITLE
Flickering in Wayland

### ISSUE THREAD

**Issue by dharrington** [lapce/lapce#119]
I'm trying this out with Gnome/Wayland. The window sometimes goes all white or transparent, and then back to normal. It flickers quite a lot while typing into the terminal, but also sometimes just moving the mouse triggers it. I didn't see this in X11.

**Comment by flrnd** [comment]
Yes, [It doesn't seem to like wayland.](https://ibb.co/ZY1KLgF).

**Comment by dzhou121** [comment]
Can you try to run WGPU_BACKEND=gl ./lapce

**Comment by flrnd** [comment]
> Can you try to run WGPU_BACKEND=gl ./lapce

Same result, I'm afraid. I tried Xorg session and it works fine, so 

Some info:
system: openSUSE tumbleweed
Kernel version 5.16.14
Mesa  21.3.7
xf86-video-amdgpu 22.0.0-1

If you need anything else just ask. 

Great project by the way!

**Comment by dharrington** [comment]
I went ahead and ran an example app from the druid repo, and it didn't flicker. Then I noticed it was using xwayland, but lapce was not. Maybe lapce can configure druid to use xwayland for now? I was going to try to figure that out, but lapce is using a heavily patched and dated version of druid, so maybe that's the root cause.

**Comment by flukejones** [comment]
@dharrington use `env -u WAYLAND_DISPLAY lapce` to force use on xwayland for now.

**Comment by panekj** [comment]
Should be fixed after switch to OpenGL
