### ISSUE TITLE
Vim command `a` incorrect behaviour

### ISSUE THREAD

**Issue by Thatguyjs** [lapce/lapce#1193]
## Lapce Version

0.2.0

## System information

Ubuntu 22.04.1

## Describe the bug

When `a` (the `Append` command) is pressed from `Normal` mode while the cursor is on an empty line, the cursor will move down to the next line.

## Additional information

Not sure what could be causing this; in the source it seems like the cursor is only moved right, not up or down.

**Comment by LukaOber** [comment]
I opened a pull request ( #1219 ) with a fix for this
