### ISSUE TITLE
Need to close fixed issues.

### ISSUE THREAD

**Issue by Jerrody** [lapce/lapce#1194]
https://github.com/lapce/lapce/issues/1031
https://github.com/lapce/lapce/issues/1033

**Comment by panekj** [comment]
You can comment on issues if you believe they are fixed

**Comment by Jerrody** [comment]
> You can comment on issues if you believe they are fixed

If  it's not why these issues mentioned in the merged PR?
![image](https://user-images.githubusercontent.com/68968657/190134419-ff504e97-516e-4034-b6a5-0df76ef82ea2.png)

**Comment by panekj** [comment]
> If it's not why these issues mentioned in the merged PR?

Because they can potentially fix the issue? Anyway you should comment on specific issues rather than opening new issue for 2 other...
