### ISSUE TITLE
Store panic info in error log

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#1200]
## Is your feature request related to a problem? Please describe.

Users sometimes attach their error logs to crash reports. This is nice, but unfortunately, this log doesn't include info about the panic that crashes Lapce. While we probably should integrate some crash reporting service, capturing and saving panic messages in the log would also be helpful.

## Describe the solution you'd like

We can set panic hooks using `https://doc.rust-lang.org/std/panic/fn.set_hook.html`. 

## Describe alternatives you've considered

https://github.com/EmbarkStudios/crash-handling/tree/main/crash-handler might catch more cases.

**Comment by Jerrody** [comment]
I think we should refactor and remake log system.
As a good variant is `tracing` where we can:
- Don't insert in compile-time logging like `info!`, `warn!`, `error!` and so on. It's useful when we compile a target release.
- Write in two threads logs, for example in to the console and also in to the file.
- Use logging_guard:
```rs
logging_guard: tracing_appender::non_blocking::WorkerGuard,
```
What it gives?
For the docs:

> A guard that flushes spans/events associated to a [NonBlocking](https://docs.rs/tracing-appender/latest/tracing_appender/non_blocking/struct.NonBlocking.html) on a drop
> 
> Writing to a [NonBlocking](https://docs.rs/tracing-appender/latest/tracing_appender/non_blocking/struct.NonBlocking.html) writer will not immediately write a span or event to the underlying output. Instead, the span or event will be written by a dedicated logging thread at some later point. To increase throughput, the non-blocking writer will flush to the underlying output on a periodic basis rather than every time a span or event is written. This means that if the program terminates abruptly (such as through an uncaught panic or a std::process::exit), some spans or events may not be written.

If shortly it gives to write all logs on the crash moment.

**Comment by panekj** [comment]
> * Don't insert in compile-time logging like `info!`, `warn!`, `error!` and so on. It's useful when we compile a target release to keep only necessary logs.

Why

> * Write logs in the two threads, for example in to the console and also in to the file.

That's how it works currently. https://github.com/lapce/lapce/blob/a41bf067659e36ac73e990c736f53d69c7bf88fb/lapce-ui/src/app.rs#L72

> And as a bonus we can use `tracing-tracy` for visual profiling that integrates with `tracing`.

You can already visually trace program with xperf/WPA on Windows.

> * Use logging guard (`tracing_appender`):

will check it out when I'll get back to reworking logging

**Comment by bugadani** [comment]
Good points, but logging is out of the scope of this issue.

**Comment by panekj** [comment]
Feel free to hide the offtopic comments, I'm going to create new issue to track logging design since I've spent some time thinking about it already

**Comment by Jerrody** [comment]
> > * Don't insert in compile-time logging like `info!`, `warn!`, `error!` and so on. It's useful when we compile a target release to keep only necessary logs.
> 
> Why

This is an option, I think exists some logs that are only for the development.

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/1404
