### ISSUE TITLE
Extention Tabs not showing Extentions

### ISSUE THREAD

**Issue by deepraj02** [lapce/lapce#1205]
## Lapce Version
0.2.0

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 

## System information
Windows 11 home Version 22H2(build 22622.590)

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04

## Describe the bug

Extension Tab not showing extentions 
![Screenshot_3](https://user-images.githubusercontent.com/63138398/190205385-0a40e464-b73c-4ce1-9a2e-2b3bcb88729c.png)

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

**Comment by deepraj02** [comment]
@MinusGix  any update on the issue??

**Comment by panekj** [comment]
Please don't ping maintainers unless they are part of conversation.
