### ISSUE TITLE
Sticky header line height changes during scrolling

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#1211]
## Lapce Version

`master` build

## System information

Windows 11

## Describe the bug

Sticky header line spacing changes while scrolling

## Additional information

https://user-images.githubusercontent.com/977627/190254415-3a49c7f9-39e5-4719-9776-74e88143e023.mp4

**Comment by dzhou121** [comment]
If you scroll slowly, you'll see there's a fade in. That's why.

**Comment by bugadani** [comment]
I can also do this
![image](https://user-images.githubusercontent.com/977627/190255394-2e60bbc8-a6df-4e8f-8cb5-3f9bf659e160.png)

😅

**Comment by bugadani** [comment]
Oh I understand what you're saying, but I literally can't scroll any slower - this is what normal mouse scroll does on windows, without any smooth scrolling. I don't think this behaviour is ideal because it can result in cases like this:
![image](https://user-images.githubusercontent.com/977627/190256080-dcf4f9da-331d-4813-b686-64aa12054863.png)

**Comment by dzhou121** [comment]
It's "scrolling in" with the last line.

**Comment by dzhou121** [comment]
> Oh I understand what you're saying, but I literally can't scroll any slower - this is what normal mouse scroll does on windows, without any smooth scrolling. I don't think this behaviour is ideal because it can result in cases like this: ![image](https://user-images.githubusercontent.com/977627/190256080-dcf4f9da-331d-4813-b686-64aa12054863.png)

This is on purpose, so that the last line can always be visible.

**Comment by bugadani** [comment]
A single scroll position on my mouse scroll 5 lines and I don't think this is a good UX. I get the intent, but there is no "scrolling in" in my window, just a line jumping seemingly randomly around. I would consider this bad UX in this state, however we might want to explain it.

I'm sure it's pretty with smooth scrolling, but I don't see that.

**Comment by bugadani** [comment]
VSCode implementation is a lot less jarring when smooth scrolling is disabled. I think they somehow differentiate mouse scrolling and scrollbar scrolling because headers fade out with the scrollbar, but do not (I think? I can trigger a similar partial fade-out with setting up a position with the scrollbar, then scrolling with my mouse) display headers when they would be partially hidden.
