### ISSUE TITLE
Open Editor Sidebar disappear

### ISSUE THREAD

**Issue by eribol** [lapce/lapce#1214]
## Lapce Version

0.2.0

## System information

Manjaro linux

## Describe the bug
With a fresh directory, sidebar opening but that sidebar have files, git and extensions tabs. If i click file tab when its already active, sidebar disappear and i could not find a way to get it back. It is not affect new project directory but if a project sidebar disappeared, it always keeps that settings for this project.

**Comment by MinusGix** [comment]
You can reopen the panels/sidebars by moving your mouse to the side that they were at. You'll see a white line appear, and you can drag that in the opposite direction to bring the panel back out. (There's also keybinds for showing specific panels, like the file explorer)

**Comment by dzhou121** [comment]
Alternatively you can use the buttons at the middle of the status bar.

**Comment by eribol** [comment]
> You can reopen the panels/sidebars by moving your mouse to the side that they were at. You'll see a white line appear, and you can drag that in the opposite direction to bring the panel back out. (There's also keybinds for showing specific panels, like the file explorer)

I could not do this. 


> Alternatively you can use the buttons at the middle of the status bar.

It was a nice way to get it back.

Also i rebuild with latest branch it get fix.
