### ISSUE TITLE
Flutter Dart Support

### ISSUE THREAD

**Issue by abdorizak** [lapce/lapce#1215]
is lapce supports Flutter?

<img width="998" alt="Screen Shot 2022-09-15 at 9 15 18 AM" src="https://user-images.githubusercontent.com/59319407/190328332-67b79ded-1a59-4ea3-9d28-f736034c1645.png">

**Comment by erf** [comment]
Dart LSP support is added in the [nightly](https://github.com/lapce/lapce/releases/tag/nightly) build as mentioned [here](https://github.com/lapce/lapce/issues/272)

It will probably take some time until a Flutter package like the VSCode extension is made .. or maybe someone is already on the case 🤷‍♂️

**Comment by zarathir** [comment]
I thought about starting to work on a flutter plugin, since I'm working on a flutter app with some rust code.

But I'm currently on vacation and my laptop died, so this will have to wait until I get back home 😄🤷.

**Comment by bugadani** [comment]
Syntax highlighting was merged a few days ago: https://github.com/lapce/lapce/pull/1153

**Comment by erf** [comment]
I think adding Dart linter rules (https://dart.dev/tools/linter-rules) would be a nice enchantment for Dart/Flutter next. Not sure how this could be added to the editor but `dart analyze` will scan for problems.

**Comment by AurelienKun** [comment]
What's the current state of flutter/dart support in lapce ?
