### ISSUE TITLE
Scroll bars too narrow

### ISSUE THREAD

**Issue by guymarshall** [lapce/lapce#1220]
## Is your feature request related to a problem? Please describe.

My problem is the scroll bars for horizontal and vertical navigation are too thin. This results in either the window being resized or text being highlighted. This can be fixed by doubling the width of the scroll bars.

## Describe the solution you'd like

A simple solution would be to make the scroll bars wider, maybe 2x wider, so they are easier to grab for users that still use scroll bars.

**Comment by ghishadow** [comment]
Go to Settings > UI Settings > Scrollbar width and set width which suits you

**Comment by guymarshall** [comment]
Hi ghishadow, thank you for your comment! Apologies, I missed that setting! I will change it when I go to work tomorrow :)
