### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by suyash222** [lapce/lapce#1221]
## Lapce Version

0.2.0

## System information

windows 10

## Describe the bug

I was unable to install extension i even reinstall lapce

## Additional information

![lapceBHD4JiQdyH](https://user-images.githubusercontent.com/43377834/190424702-f05dafa5-ae0d-4a11-ba91-5517544c6d19.gif)

**Comment by panekj** [comment]
This is fixed on master
