### ISSUE TITLE
Extension registry for lapce

### ISSUE THREAD

**Issue by coffee-is-power** [lapce/lapce#1222]
I'm working on a registry for lapce so everyone can easily publish and install lapce plugins.
The source code is at [coffee-is-power/lapce-extensions](https://github.com/coffee-is-power/lapce-extensions)
The back end uses rust with rocket.rs, and the front end uses svelte. The API is still a WIP, but it can already login with GitHub.

**Comment by panekj** [comment]
This was resolved #1643
