### ISSUE TITLE
Feature request: search and replace

### ISSUE THREAD

**Issue by NatanFreeman** [lapce/lapce#1223]
## Is your feature request related to a problem? Please describe.

Coming from using VScode, I've noticed some missing functionality which would be very useful. Pressing <kbd>Ctrl</kbd>+<kbd>f</kbd> brings up the search box. However, there is no option to toggle case-sensitive search, regex search or matching the whole snippet. In addition, there is not an option to replace matches. This very inconvenient when trying to refactor code.

There is also no way to search across all files as far as I can tell.

## Describe the solution you'd like
A few simple buttons to toggle search settings next to the find box should make it easy enough to do more advanced searches. A collapsible text field which replaces the text with the input will also allow replacing matching text. This is how it's done in VScode and I have found it too work fine, though some other UI can also work.

For searching globally throughout all the files, I think a dock tab like the git UI is a good idea because it can show you many matches throughout the entire project.

## Additional context
Search box in VScode:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/86922687/190477665-388bc3fc-d4cf-4664-843f-03d5b8ebe8ac.png">
VScode global search tab:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/86922687/190478375-83f4a0aa-f9cb-431c-a627-d2edf4e9ba85.png">

**Comment by NatanFreeman** [comment]
> There is also no way to search across all files as far as I can tell.

So there is a search tab but it is still missing the search/replace features which I described.
<img width="257" alt="image" src="https://user-images.githubusercontent.com/86922687/190482397-8301f685-acec-45d7-8a59-8795cfc9ebbd.png">

**Comment by hum4nizer** [comment]
Hello!

First I want to say that I really like this project and for me this editor fills up a need that I cant find on other editors with its lightweight nature.

I would also really like to see a search and replace option in this wonderful code editor.

Thanks,
Johnny

**Comment by matklad** [comment]
For search/replace, it might be fun to explore search-editor based UI to leverage multiple cursors: https://code.visualstudio.com/docs/editor/codebasics#_search-editor

The TL;DR is that searching for `foo` would bring all the occurances of foo in in the file/project into a single editable buffer, and then "replace" functionality could be achieved by multi-cursor UI

**Comment by rMazeiks** [comment]
A search editor might be useful it it also lets you edit the results individually (otherwise I don't really see a point).

But I also sometimes find the need to replace strings matching a Regex with strings interpolating variables matched in that regex. I can't imagine how this option could be integrated in a search editor. So perhaps these could be complementary features.

**Comment by coosir** [comment]
Upvote. Text Find & Replace should be a basic function for an IDE or editor.

**Comment by panekj** [comment]
> Upvote. Text Find & Replace should be a basic function for an IDE or editor.

Please do not post upvotes as comments, it distracts and clutters the issue. You can use reactions on the original post.

**Comment by ignorantshr** [comment]
Are there any plans to add this feature?

**Comment by panekj** [comment]
> Are there any plans to add this feature?

Yes

**Comment by mikeyhew** [comment]
> Yes

Yes, as in you are planning on working on it / you know that someone is planning on working on it? I'm just asking because my next question:

Assuming you were going to implement find and replace in a similar way to how it works in vscode, how would you do that? I'm not familiar with Lapce or any other editor's codebase, but I'm familiar with Rust, and if it's not a huge amount of work or something that requires a deep understanding of how Lapce works, I might be able to try to implement it in my spare time, given some guidance.

**Comment by panekj** [comment]
> Yes, as in you are planning on working on it / you know that someone is planning on working on it?

Yes as in we're not opposed to adding it and someone will implement it once they have time to do so.

**Comment by ernstki** [comment]
Thanks to the (unpaid, volunteer) developers doing the work to implement requested features like this. It's appreciated!

Apropos of that:

> If it's important, keep in mind that these projects are self-service: if you need a feature, you might get it faster if you do the work.

[source](https://invisible-island.net/personal/self-service.html)
