### ISSUE TITLE
Support for a pure terminal UI frontend?

### ISSUE THREAD

**Issue by erf** [lapce/lapce#1228]
Does the architecture lend itself to potentially add a pure terminal UI front-end? (at some later stage)

**Comment by ghishadow** [comment]
what you mean by pure terminal UI ? Lapce currently uses `alacritty_terminal`

**Comment by panekj** [comment]
> what you mean by pure terminal UI ? Lapce currently uses `alacritty_terminal`

They want frontend like neovim or helix, but backed by lapce.

**Comment by ghishadow** [comment]
> They want frontend like neovim or helix, but backed by lapce.
oh thanks for explaining, so like Neovide

**Comment by panekj** [comment]
I believe it is non-goal for lapce itself as well as our limited manpower wouldn't allow that. One could probably build terminal frontend based on `lapce-proxy`, `lapce-core` & `lapce-data`.
