### ISSUE TITLE
Automatic Line Height

### ISSUE THREAD

**Issue by DuckDuckWhale** [lapce/lapce#1230]
## Is your feature request related to a problem? Please describe.

When adjusting the font size, line height doesn't change, leaving the fonts overlapping or spaced out. Having to manually calculate the ratio (which is not even a thing that I remember) shouldn't be necessary. Also, this looks like a bug to someone who isn't willing to dig around the settings.

## Describe the solution you'd like

Automatic line height. Maybe what VS Code does:
> Editor: Line Height
> Controls the line height.
>
> Use 0 to automatically compute the line height from the font size.
> Values between 0 and 8 will be used as a multiplier with the font size.
> Values greater than or equal to 8 will be used as effective values.

## Describe alternatives you've considered

A suggested ratio, but it's nowhere as good as automatic.

**Comment by bugadani** [comment]
Thanks! Technically a duplicate, but I've closed my own since you stated the problem a lot better :)

**Comment by DuckDuckWhale** [comment]
Ah, the one time I didn't search for an exiting issue :stuck_out_tongue_closed_eyes:
