### ISSUE TITLE
Feature request: register new Rust files in mod

### ISSUE THREAD

**Issue by NatanFreeman** [lapce/lapce#1233]
## Is your feature request related to a problem? Please describe.
Rust's module system works in a way that Rust files relating to your program must be stated in the appropriate mod.rs/lib.rs/main.rs file. It would be a nice convenience if when creating a new Rust file in the file explorer it will also automatically be added as part of your project. New Rust files are part of your codebase more often than not so I can see this saving a bit of time.

## Describe the solution you'd like
I think this functionality should be the default behaviour with perhaps the ability to disable it in setting for those who really need to. Seeing how this is Rust specific, it might be a good idea to include this with the Rust extension but a version of this could also work for CMake and other such tools.

## Describe alternatives you've considered
Adding an option to the right click menu in file explorer to skip this behaviour could also work. Maybe it can be a sub option of "new file". I don't think this is too necessary though. The option to disable this feature or just modifying the mod file manually will probably suffice in my opinion.

**Comment by bugadani** [comment]
I'm not sure modifying source code automatically like this should be done by the editor. The LSP knows much more about the code than Lapce will ever know by itself, and I think automatically inserting code based on filesystem events is rather risky because of this.

Rust-analyzer already has commands like "insert `mod <modname>`" if it encounters files outside of the module tree, although I think we don't have a visual indicator for commands like this yet.

**Comment by NatanFreeman** [comment]
Will this be considered with the use of Rust-analyzer and other such LSPs?

**Comment by panekj** [comment]
Most likely yes, but as said already, we don't have visual indication nor interaction for that

**Comment by lukaslihotzki** [comment]
The alternative way is to type `mod <modname>;` and then let the language server create the file. These suggestions already appear in this case:
- Create module at \`\<modname\>.rs\`
- Create module at \`\<modname\>/mod.rs\`

However, nothing happens when clicking on one of these suggestions.

**Comment by NatanFreeman** [comment]
Clicking the suggestion sounds like a good way of implementing this.

**Comment by lukaslihotzki** [comment]
The create module quickfixes are defined like this by the language server:
```
{
  "jsonrpc": "2.0",
  "id": 39,
  "result": [
    {
      "title": "Create module at `foo.rs`",
      "kind": "quickfix",
      "edit": {
        "documentChanges": [
          {
            "kind": "create",
            "uri": "file:///tmp/src/foo.rs"
          }
        ]
      }
    },
    {
      "title": "Create module at `foo/mod.rs`",
      "kind": "quickfix",
      "edit": {
        "documentChanges": [
          {
            "kind": "create",
            "uri": "file:///tmp/src/foo/mod.rs"
          }
        ]
      }
    }
  ]
}
```

This is parsed into [ResourceOp](https://docs.rs/lsp-types/latest/lsp_types/enum.ResourceOp.html), but ignored by lapce in https://github.com/lapce/lapce/blob/master/lapce-data/src/editor.rs#L2548 (`DocumentChangeOperation::Op(_op) => None`).

**Comment by NatanFreeman** [comment]
<img width="227" alt="image" src="https://user-images.githubusercontent.com/86922687/192484133-1ff12f85-eb8d-44c4-a193-9b4307eb55ff.png">
<img width="191" alt="image" src="https://user-images.githubusercontent.com/86922687/192484188-84b24844-77f8-4cc7-8e2a-d917f4d3b698.png">
Blazingly awesome! 🚀🦀
