### ISSUE TITLE
Currently, `lapce` cannot be built on Windows using Rust nightly.

### ISSUE THREAD

**Issue by Jerrody** [lapce/lapce#1236]
This problem appeared due to `FileTypeExt` in `std` was sealed and as the result `cap_primitives` cannot not be built (https://github.com/bytecodealliance/cap-std/issues/270) and at the same time `wasi-common` depends on it.
This issue was fixed in https://github.com/bytecodealliance/cap-std/commit/949f251bccbb84513fe81a427a46864c1e8ad82c.

I tried to fix this issue by changing a version of `wasi-common`. but this issue didn't disapear.

```rs
error[E0277]: the trait bound `file_type::FileType: std::sealed::Sealed` is not satisfied
   --> C:\Users\hunte\.cargo\registry\src\github.com-1ecc6299db9ec823\cap-primitives-0.25.3\src\fs\file_type.rs:134:6    
    |
134 | impl std::os::windows::fs::FileTypeExt for FileType {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::sealed::Sealed` is not implemented for `file_type::FileType`
    |
    = help: the following other types implement trait `std::sealed::Sealed`:
              Child
              Command
              ExitCode
              ExitStatus
              ExitStatusError
              OsStr
              OsString
              Simd<f32, N>
            and 2 others
note: required by a bound in `std::os::windows::fs::FileTypeExt`
   --> C:\Users\hunte\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\windows\fs.rs:507:24
    |
507 | pub trait FileTypeExt: Sealed {
    |                        ^^^^^^ required by this bound in `std::os::windows::fs::FileTypeExt`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `cap-primitives` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by Jerrody** [comment]
I suggest to pin this issue and investigate it.

**Comment by panekj** [comment]
Don't use nightly.

**Comment by Jerrody** [comment]
> Don't use nightly.
Hm, nice suggestion, but later it will be part of stable in the future.

**Comment by Jerrody** [comment]
> Don't use nightly.

And don't be so fast to close an issue without any descussion. Very tactless.

**Comment by panekj** [comment]
> And don't be so fast to close an issue without any descussion. Very tactless.

Don't edit post and repost your comment as separate. There is no reason to do so and it's unnecessary notification for others.

> **I suggest to pin this issue and investigate it.**

**Comment by Jerrody** [comment]
> > And don't be so fast to close an issue without any descussion. Very tactless.
> 
> Don't edit post and repost your comment as separate. There is no reason to do so and it's unnecessary notification for others.
> 
> > **I suggest to pin this issue and investigate it.**

Alright, anyway, "new" version of `FileTypeExt` will be part of `stable` in the future. So closing the issue only delays the inevitable.

**Comment by panekj** [comment]
You have to update `wasi-experimental-http-wasmtime` as well

**Comment by panekj** [comment]
I'll leave the issue open for dzhou to bump the deps, but it doesn't warrant pinning or heavy investigation

**Comment by Jerrody** [comment]
> You have to update `wasi-experimental-http-wasmtime` as well

Well, yes, I understand, because it won't compile. I repeat that problem is still exists.

**Comment by ghishadow** [comment]
@Jerrody it is fixed in https://github.com/bytecodealliance/wasmtime/pull/4940, but we still need to update `wasi-experimental-http-wasmtime`

**Comment by RivenSkaye** [comment]
I just made a fresh, seemingly functional build with a nightly toolchain without a single change to the codebase.
`RUSTFLAGS="-Z threads=6" cargo +nightly-x86_64-pc-windows-gnu build --profile release-lto --config strip=true --timings` just works:tm: so this issue seems to be outdated?

**Comment by panekj** [comment]
> this issue seems to be outdated?

yes
