### ISSUE TITLE
Can't run on my parrot os after installation

### ISSUE THREAD

**Issue by ochecodes7** [lapce/lapce#1240]
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /root/.cargo/git/checkouts/winit-58efae9df3f5264a/59eb01c/src/platform_impl/linux/mod.rs:626:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ghishadow** [comment]
which version of lapce is this, this error used to come in old version ?

**Comment by ochecodes7** [comment]
> which version of lapce is this, this error used to come in old version ?

i  can't even see the version

**Comment by panekj** [comment]
> > which version of lapce is this, this error used to come in old version ?
> 
> i can't even see the version

in terminal run `lapce --version`

**Comment by ochecodes7** [comment]
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /root/.cargo/git/checkouts/winit-58efae9df3f5264a/59eb01c/src/platform_impl/linux/mod.rs:626:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



this error came back again

**Comment by ochecodes7** [comment]
> > > which version of lapce is this, this error used to come in old version ?
> > 
> > 
> > i can't even see the version
> 
> in terminal run `lapce --version` if it doesn't output anything, then you are using too old version
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /root/.cargo/git/checkouts/winit-58efae9df3f5264a/59eb01c/src/platform_impl/linux/mod.rs:626:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


what should i do next?

**Comment by panekj** [comment]
> what should i do next?

upgrade lapce

**Comment by ochecodes7** [comment]
> > what should i do next?
> 
> upgrade lapce

sudo apt upgrade isn't working

**Comment by panekj** [comment]
Lapce is not distributed via `apt`

**Comment by ochecodes7** [comment]
> Lapce is not distributed via `apt`

my bad what's the command?

**Comment by panekj** [comment]
You have to install it like you did previously or download it from github releases

**Comment by ochecodes7** [comment]
> You have to install it like you did previously or download it from github releases

after that? cause i dowload one from the official site but there's a package in it that i can't open

**Comment by Sate04** [comment]
I am also having this same issue on Ubuntu

**Comment by Sate04** [comment]
![image](https://user-images.githubusercontent.com/50961365/190867769-1b3ba58e-abff-4a07-b875-363678416769.png)

I get this issue both when running from the .tar.gz and from the snap store

**Comment by panekj** [comment]
Try installing `libxcursor`

**Comment by Sate04** [comment]
it seems like I already have libxcursor

**Comment by panekj** [comment]
Then it's not ABI compatible and you will have to compile lapce yourself

**Comment by ghishadow** [comment]
> I get this issue both when running from the .tar.gz and from the snap store
snap is last updated on 22 April 2022 (0.0.12), a lot has changed after that

**Comment by Sate04** [comment]
Works now, seems like I was accidentally running the snap version when trying to run from the extracted file

**Comment by ochecodes7** [comment]
> ![image](https://user-images.githubusercontent.com/50961365/190867769-1b3ba58e-abff-4a07-b875-363678416769.png)
> 
> I get this issue both when running from the .tar.gz and from the snap store
> 
> I have rust version 1.63

Exactly same here

**Comment by Sate04** [comment]
try `./lapce` instead of `lapce`

> > ![image](https://user-images.githubusercontent.com/50961365/190867769-1b3ba58e-abff-4a07-b875-363678416769.png)
> > I get this issue both when running from the .tar.gz and from the snap store
> > I have rust version 1.63
> 
> Exactly same here

**Comment by ochecodes7** [comment]
./lapce works but is there anyway it could be like I just search for the app

**Comment by Sate04** [comment]
if you move that binary to your `/usr/local/bin` folder you can open lapce anywhere from the command line, and then you can make a `lapce.desktop` file to run lapce. Making it show up as a searchable application is beyond my expertise

**Comment by Sate04** [comment]
actually its really easy, just put that `lapce.desktop` file in `usr/share/applications` and it'll do exactly what you want

here's a tutorial to follow
https://www.maketecheasier.com/create-desktop-file-linux/

**Comment by ochecodes7** [comment]
thanks  I'll check out

**Comment by Sate04** [comment]
I assume since everything on lapce's side is working correctly this issue can be closed?

Unless someone wants to contact the owner of the lapce snap and try and get it updated, or maybe make an official snap so this doesn't happen again

**Comment by panekj** [comment]
I filed claim for lapce on snapstore

**Comment by ochecodes7** [comment]
I finally fixed the issue I'll look for how i solved it
