### ISSUE TITLE
Install plugin from URL

### ISSUE THREAD

**Issue by mayel** [lapce/lapce#1247]
## Is your feature request related to a problem? Please describe.

I am developing a plugin, and had change the URL in `load_volts` in `plugin.rs` to a JSON that includes this new plugin to be able to install it. 

## Describe the solution you'd like

A way to enter the URL of a plugin (could be its git repo or directly to its `plugin.json`) to install it would probably make sense.

**Comment by panekj** [comment]
I once contributed such setting and it was decided to not support it.
You can copy the plugin to plugins directory to test it.

**Comment by mayel** [comment]
Ah yes I just found info for that: https://github.com/lapce/lapce/issues/1232
I guess it's an ok temporary solution, but longer term URL based install makes sense to facilitate a plugin ecosystem...

**Comment by panekj** [comment]
Once we have defined plugin format for plugins and their distribution, we can add option to install plugin straight from URL

**Comment by mayel** [comment]
(I was confused because I found an old `~./lapce/plugins` directory and tried copying my plugin there, but Lapce is now using a different directory.

**Comment by panekj** [comment]
You can open plugins directory via palette command
![Screenshot 2022-09-17 at 12 03 21](https://user-images.githubusercontent.com/50457605/190851380-13dacc5d-b815-47ff-8ac2-2fd28e3db277.png)
