### ISSUE TITLE
feature-request: make the close, minimize and maximize buttons fit on native title bar.

### ISSUE THREAD

**Issue by schwrzstrbn** [lapce/lapce#1249]
## Is your feature request related to a problem? Please describe.

The native title bar look really weird. Macos version of lapce looks good but the linux one is kinda weird, it happens when you turn off the custom title bar.

## Describe the solution you'd like

It would be better if the native one fits perfectly just like how it does on macos.

- This is how it looks like on my linux machine.
![image](https://user-images.githubusercontent.com/45195351/190855852-5d7d5eb7-a272-4611-97b2-10699d20fb77.png)

**Comment by panekj** [comment]
Isn't this the same as https://github.com/lapce/lapce/issues/859

**Comment by schwrzstrbn** [comment]
> Isn't this the same as #859

yeah, but this time it's the native one looks kinda off. But you already explained it on the discord server, so I closed this issue. I will close the prev. one too.
