### ISSUE TITLE
Automatic line height need a sensible default

### ISSUE THREAD

**Issue by DuckDuckWhale** [lapce/lapce#1255]
## Lapce Version

666c4afac532670d7f22353ceab9c6f599ec6abf

## System information

Ubuntu 22.04 Gnome

## Describe the bug

Follow up of #1230.

Automatic line height defaults to 25.0, meaning that adjusting the font size is not enough to auto adjust the line height. This is a problem because it's expected that adjusting the font size not also change the line height by default. Try:
- `trash ~/.config/lapce-stable`
- Adjust font size fo 36
- Everything looks squashed
- Adjust font size to 10
- Everything is spaced out

I suggest either use 0 as a place holder for an automatic default ratio like VS Code does or specify a default number and repeat it in the field description. This helps in two ways:
1. The line height changes as font size changes by default as opposed to a hard coded 25.0
2. People who want to revert to a default ratio after messing around but forgot what it was don't have to read the source code or delete their configuration

A default of 1.35 is used by VS Code. Relevant PR for VS Code: microsoft/vscode#125601

**Comment by bugadani** [comment]
> Automatic line height defaults to 25.0

Line height defaults to 25, which is not automatic :P This was intentional to not change the current default behaviour, as I didn't want to go that far. Changing a default would affect more users and it is a change that could be received in different ways.

> This is a problem because it's expected that adjusting the font size not also change the line height by default

Keep in mind, your expectations might night be the same as other people's.

I'm fine with either option, and this isn't a terribly complicated change, so I think it'll be done if someone gets fed up enough with the current solution.

**Comment by DuckDuckWhale** [comment]
> This is a problem because it's expected that adjusting the font size not also change the line height by default

Sorry, I phrased this poorly. I meant to say that people would generally expect adjusting the font size alone be sufficient to keep everything good-looking, which necessitates a change in absolute line height and no change in the ratio between the font size and the line height. I claim that this is the expectation in general because existing tools behave this way, including Gnome Terminal, Gedit, and VS Code. All of them automatically adjust the absolute line height when you change the font size, at least by default. If inexperienced people familiar with the existing tools (who don't know that the line height setting item exist) try adjusting the font size and their lines looks squashed, they'd think there's a bug.

> Line height defaults to 25, which is not automatic :P This was intentional to not change the current default behaviour, as I didn't want to go that far. Changing a default would affect more users and it is a change that could be received in different ways.

I think this is suboptimal. As argued above the general expectation is for automatic line height to be default. Let's consider the people who are affected. Those who are familiar with other tools and have just tried out Lapce would be most benefited by such a default, for it makes it easy for them and fits their existing expectation and workflow with other tools (which do automatic line height by default). Since they are new, they won't have a configuration set yet, so it won't affect their Lapce workflow (which doesn't exist yet). Those who would like to stick with an absolute value would probably have it changed to another value anyway, and even if they didn't I doubt a ratio of 1.35 would look bad, and if it does for them they can always go put in a 25. I'd guess that it is pretty unlikely for people to have never changed the line height to depend on it being absolute. This have the added benefit of it wouldn't change on them in the future (since only changed settings are saved). For these who changed the value at least once a change in default will not impact them in anyway. So I think the pros outweigh the cons here and doubt that this change would receive any bad rap.

If the state of this is PR-welcome, I might be able to help.
