### ISSUE TITLE
Please make it able to select and copy text from console

### ISSUE THREAD

**Issue by trsh** [lapce/lapce#1258]
## Is your feature request related to a problem? Please describe.

Lot's of times console reveals runtime errors that you want to share with others for different reasons (get help, register bug, etc.), but I am not able to do that. 

## Describe the solution you'd like

I would be able to select and copy text from console in traditional way. 

## Describe alternatives you've considered

Current workaround is to not use Lapce console.

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/871
