### ISSUE TITLE
libEGL warning: DRI2: failed to authenticate

### ISSUE THREAD

**Issue by frafra** [lapce/lapce#126]
Cannot run lapce v0.0.10 on Ubuntu 18.04 in a virtual desktop (VMWare Horizon).
The window is blank and I read in the terminal `libEGL warning: DRI2: failed to authenticate`.

**Comment by bugadani** [comment]
Thanks for reporting this issue!

While you've reported this first, #127 has a bit more detail for this exact error, so I'm closing this one in favour of that.
