### ISSUE TITLE
Trouble building on Ubuntu 22.04

### ISSUE THREAD

**Issue by bcer-dev** [lapce/lapce#1264]
I've been following the build steps for Ubuntu, including installing all of the Rust dependencies, but when I run `cargo build --release`, I get the following error:
```
error: failed to load manifest for workspace member `/home/brayden/lapce/lapce-ui`

Caused by:
  failed to load manifest for dependency `lapce-core`

Caused by:
  failed to parse manifest at `/home/brayden/lapce/lapce-core/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
```

**Comment by ghishadow** [comment]
what is your rust version ?

**Comment by Jerrody** [comment]
> I've been following the build steps for Ubuntu, including installing all of the Rust dependencies, but when I run `cargo build --release`, I get the following error:
> ```
> error: failed to load manifest for workspace member `/home/brayden/lapce/lapce-ui`
> 
> Caused by:
>   failed to load manifest for dependency `lapce-core`
> 
> Caused by:
>   failed to parse manifest at `/home/brayden/lapce/lapce-core/Cargo.toml`
> 
> Caused by:
>   namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
> ```

try to use command `rustup update && rustup default stable`.

**Comment by bcer-dev** [comment]
> Try to use command `rustup update && rustup default stable`.
Thank you, it worked!

**Comment by Jerrody** [comment]
> > Try to use command `rustup update && rustup default stable`.
> 
> Thank you, it worked!
> 

Yep.
