### ISSUE TITLE
Git commit silently fails when user.name is unset

### ISSUE THREAD

**Issue by DuckDuckWhale** [lapce/lapce#1277]
## Lapce Version

666c4afac532670d7f22353ceab9c6f599ec6abf

## System information

Ubuntu 22.04 Gnome

## Describe the bug

When trying to commit without `user.name` set (I set `user.name` on a per repo basis), the commit eats the commit message then silently fails. Terminal logs show `config value 'user.name' was not found; class=Config (7); code=NotFound (-3)`.

**Comment by holmar** [comment]
I'll add to this that `user.email` also has to be set for the commit to work.
