### ISSUE TITLE
Windows panic: Other(no avaible pixel format)

### ISSUE THREAD

**Issue by rialpamu** [lapce/lapce#1286]
## Lapce Version

Lapce doesn't start up.  Downloaded The  `Lapce-windows-portable.zip` today (2022-09-20).
`./lapce.exe --version` shows nothing.

## System information

Windows 10

## Describe the bug

Lapce doesn't start up. Panic in main

## Additional information

	$ RUST_BACKTRACE=full ./lapce.exe
	thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(no avaible pixel format)', C:\Users\runneradmin\.cargo\git\checkouts\druid-f6980810fb848923\3e53ab2\druid-shell\src\backend\windows\window.rs:843:26
	stack backtrace:
	   0:     0x7ff6b5fe9b0e - git_filter_source_repo
	   1:     0x7ff6b4fbfd4a - <unknown>
	   2:     0x7ff6b5fc83c9 - git_filter_source_repo
	   3:     0x7ff6b5feb2ab - git_filter_source_repo
	   4:     0x7ff6b5febea7 - git_filter_source_repo
	   5:     0x7ff6b5feba73 - git_filter_source_repo
	   6:     0x7ff6b5feb9d9 - git_filter_source_repo
	   7:     0x7ff6b5feb994 - git_filter_source_repo
	   8:     0x7ff6b68bc805 - tree_sitter_rust
	   9:     0x7ff6b68bcac3 - tree_sitter_rust
	  10:     0x7ff6b5198375 - git_filter_source_repo
	  11:     0x7ff6b51881f8 - git_filter_source_repo
	  12:     0x7ff6b517f301 - git_filter_source_repo
	  13:     0x7ff9f0b6e858 - CallWindowProcW
	  14:     0x7ff9f0b6e3dc - DispatchMessageW
	  15:     0x7ff9f0b82bf7 - InitDManipHook
	  16:     0x7ff9f23d0d74 - KiUserCallbackDispatcher
	  17:     0x7ff9f0101ec4 - NtUserCreateWindowEx
	  18:     0x7ff9f0b67d8b - CreateWindowExW
	  19:     0x7ff9f0b67958 - CreateWindowExW
	  20:     0x7ff9f0b677a2 - CreateWindowExW
	  21:     0x7ff6b5c16018 - git_filter_source_repo
	  22:     0x7ff6b5c0785f - git_filter_source_repo
	  23:     0x7ff6b4f01006 - <unknown>
	  24:     0x7ff6b4f01185 - <unknown>
	  25:     0x7ff6b68b6f30 - tree_sitter_rust
	  26:     0x7ff9f06a7034 - BaseThreadInitThunk
	  27:     0x7ff9f2382651 - RtlUserThreadStart

**Comment by panekj** [comment]
What Windows build version you have and what kind of GPU (vendor/model)?

**Comment by ghishadow** [comment]
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(no avaible pixel format)'

is this VM ?

**Comment by rattlecattle** [comment]
Same error here.

The environment is a VPS running Windows Server 2019 connected over RDP.

**Comment by panekj** [comment]
> The environment is a VPS running Windows Server 2019 connected over RDP.

You need machine with proper GPU attached to run Lapce
