### ISSUE TITLE
R support

### ISSUE THREAD

**Issue by kongdd** [lapce/lapce#1288]
lapce not support R language, which is also a very popular language. 
Hope lapce could support R syntax highlight at least.

Thank you.

**Comment by ghishadow** [comment]
tree-sitter for R https://github.com/r-lib/tree-sitter-r 
lsp: https://github.com/REditorSupport/languageserver

looks like syntax highlighting and autocompletion is possible, better name this issue "R support" as there is Meta Issue for highlight support https://github.com/lapce/lapce/issues/272.

**Comment by panekj** [comment]
> looks like syntax highlighting and autocompletion is possible, better name this issue "R support" as there is Meta Issue for highlight support #272.

we generally should not keep issues open for LSPs/plugins since it's not in lapce repo scope

**Comment by bugadani** [comment]
I've added the tree-sitter link to #272. Since the LSP is not something that will be included here, I've marked this issue as better-as-plugin. Thanks for the request :)
