### ISSUE TITLE
Windows 11 - Emoji support

### ISSUE THREAD

**Issue by kierenj** [lapce/lapce#129]
Is support for emojis planned in the terminal? On my machine at least, a blank space appears instead.

**Comment by bugadani** [comment]
Thanks for opening this issue!

It's not only the terminal but the editor don't support emojis as well. I'm fairly certain emojis are not high on the priority list, unfortunately, so I'm marking this issue with the `help wanted` label.

**Comment by bugadani** [comment]
Emojis should be displayed on master now. Emoji input using the emoji picker doesn't work yet.

**Comment by bugadani** [comment]
`win + .` emoji input has been fixed somewhere along the line.
