### ISSUE TITLE
Cant use the Cozette font

### ISSUE THREAD

**Issue by erf** [lapce/lapce#1306]
## Lapce Version

nightly-3a09f51

## System information

macOS 12.6 (21G115)

## Describe the bug

Won't use the Cozette font: 
https://github.com/slavfox/Cozette

I've tried both the bitmap `Cozette` and vector `CozetteVector` versions.

There is no indication if the font is loaded correctly (or rather wrongly).

The font is a type of User font. Although `Fira Code` seem to work.

**Comment by ghishadow** [comment]
I am using same font in MacOS 12.6, can you show me Editor Settings ? 
<img width="894" alt="cozette" src="https://user-images.githubusercontent.com/9583775/191639017-22080d8c-4f36-41ba-ad91-c5d568965cb0.png">

**Comment by erf** [comment]
<img width="474" alt="Screenshot 2022-09-22 at 04 40 25" src="https://user-images.githubusercontent.com/1562523/191646600-8036adc6-3119-467b-b85b-5de5136d5f49.png">

<img width="588" alt="Screenshot 2022-09-22 at 04 40 32" src="https://user-images.githubusercontent.com/1562523/191646602-e5344d57-8747-4abc-ad48-51c2a995c24a.png">

<img width="765" alt="Screenshot 2022-09-22 at 04 43 33" src="https://user-images.githubusercontent.com/1562523/191646940-b5ae0b86-19c6-475f-b5ad-0b9ce0739fb1.png">

**Comment by erf** [comment]
The `CozetteVector` font seem to work in `nightly-d2f2437`
