### ISSUE TITLE
Syntax highlighting support for template engines

### ISSUE THREAD

**Issue by fokusuma** [lapce/lapce#1311]
Problem : 
Currently html inside php, blade and django-html is not well rendered using syntax highlight

Screenshot :

<img width="1552" alt="Screen Shot 2022-09-22 at 2 06 16 PM" src="https://user-images.githubusercontent.com/47457477/191671122-11401b60-7be4-4393-bc9b-b8440e75e7e8.png">
<img width="1552" alt="Screen Shot 2022-09-22 at 2 07 57 PM" src="https://user-images.githubusercontent.com/47457477/191671145-367b3a97-da8f-4968-8e3e-452c3af074be.png">

**Comment by panekj** [comment]
- [x] HTML inside PHP/Blade
  - This should be fixed on master since we now support syntax injections for PHP
- [ ] Django-HTML
  - This requires tree-sitter for django-html and automatic code detection / selecting language manually
