### ISSUE TITLE
CreatePseudoConsole: Lapce and Windows 7

### ISSUE THREAD

**Issue by marnunez** [lapce/lapce#132]
Hi! When trying to run Lapce in Windows 7, I get

![image](https://user-images.githubusercontent.com/1470552/158808190-4b0e5629-cacb-4e91-a371-48da1d98ed16.png)

CreatePseudoConsole seems to be available for Windows 10 1809 onwards, so maybe set that in the docs?

**Comment by Moth-Tolias** [comment]
happens on win8 as well.

**Comment by evywang** [comment]
also happens on Win10 x64, with x64 Lapce-windows.msn installer.

**Comment by cnbac** [comment]
![image](https://user-images.githubusercontent.com/87373326/161085186-f931cedc-413b-4fd3-b4ef-93c07732d969.png)

**Comment by cnbac** [comment]
![image](https://user-images.githubusercontent.com/87373326/161085597-c2d87385-79ce-41e4-a8af-70f0216ef651.png)

**Comment by panekj** [comment]
Windows 7 is not supported
