### ISSUE TITLE
LSP notifications UI

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#1321]

**Comment by bugadani** [comment]
@nheuillet do you think displaying [showMessage](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessage) is a good enough MVP?

**Comment by nheuillet** [comment]
@bugadani yes I think displaying it nicely would be great already

**Comment by bugadani** [comment]
> nicely

That's not me, probably :D But I'll do my best
