### ISSUE TITLE
Feature request: match system theme

### ISSUE THREAD

**Issue by NatanFreeman** [lapce/lapce#1324]
## Is your feature request related to a problem? Please describe.
It would be nice if Lapce had an option match the system theme without needing to change it manually. E.g. Lapce light when in light mode and Lapce dark when in dark mode.

## Describe the solution you'd like
It would probably be a good idea to use a third party crate for picking up the system theme. This would ease the strain on making this work cross-platform. In addition, because Lapce allows for third party themes via the use of plugins, it is important to allow the user to choose which theme is selected. A drop down for which theme is used when in light mode and which in dark mode should be straight forward enough. Plugins can even offer to configure this automatically. 

## Describe alternatives you've considered
This behaviour could be implemented through a plugin but I don't believe that's necessary.

**Comment by panekj** [comment]
I'll close it in favour of #83

**Comment by tasmo** [comment]
> I'll close it in favour of #83

But this part isn't solved and the linked issue is closed already.
