### ISSUE TITLE
How to support VUE?How do I support multiple Windows，Only one project at a time？

### ISSUE THREAD

**Issue by c85442** [lapce/lapce#1325]
## Lapce Version

0.2.0
## System information

macos
## Describe the bug
How to support VUE?How do I support multiple Windows，Only one project at a time？

The first question is：how can i use VUE plugin? you can see  that there is no highlighting in my VUE file.

The second question is : Don't you support multiple projects open at the same time？

<img width="615" alt="image" src="https://user-images.githubusercontent.com/95679426/191916622-b399dfc4-39d4-416c-ab66-36e60380e929.png">

**Comment by panekj** [comment]
> How to support VUE?

VUE highlighting has not been added to Lapce, there are some people working on adding Vue/Vue3

> How do I support multiple Windows，Only one project at a time？

In command palette, run `Create new window tab` 

> Don't you support multiple projects open at the same time？

We have tabs for opening different projects but we don't support opening multiple projects in a workspace (like VSCode)

**Comment by panekj** [comment]
Syntax highlight fixed via #1326
