### ISSUE TITLE
If there is undo... where is redo!?

### ISSUE THREAD

**Issue by Oglo12** [lapce/lapce#1330]
## Is your feature request related to a problem? Please describe.

Hello, I just wanted to request a simple feature, the ability to redo a change! There is an undo feature with CTRL + Z, but where is the redo feature!? Why can't I press CTRL + Y to redo a change? Please fix this! BTW, love how far this editor has come so far!

## Describe the solution you'd like

Could you please add the redo feature under the standard keybind of CTRL + Y?

## Describe alternatives you've considered

Just add the redo feature somehow!

## Additional context

Having no redo feature really hurts workflow! And it is something an editor should have from the same day that an undo feature is added!

**Comment by panekj** [comment]
`redo` is already in lapce, default keybinding for macos is `cmd` + `shift` + `z` and for non-macos `ctrl` + `shift` + `z`

**Comment by bugadani** [comment]
If you don't like `ctrl` + `shift` + `z` you can rebind it in settings, but as panekj said, redo exists and it is working.
