### ISSUE TITLE
remote failed by ssh

### ISSUE THREAD

**Issue by chuan-xu** [lapce/lapce#1339]
![image](https://user-images.githubusercontent.com/92707056/192108610-826844dc-e302-4986-b264-ad19ed17d2fa.png)

![image](https://user-images.githubusercontent.com/92707056/192108647-a652fc1a-1bfc-4d19-8979-57f01c9a4372.png)

config
```
Host sgx27
  HostName 127.0.0.1
  User root
  Port 9025
  IdentityFile C:\\Users\\PC\\.ssh\\id_rsa
```

**Comment by onichandame** [comment]
@chuan-xu I am encountering the same issue. How did you resolve this? Is it just slow and we should wait?

**Comment by chuan-xu** [comment]
@onichandame 我记得是远程主机下载proxy太慢，可以自行下载proxy替换。可以试试！
