### ISSUE TITLE
cargo.toml failed parce

### ISSUE THREAD

**Issue by dronov-dmitry** [lapce/lapce#1346]
Whet try to build at linux mint - it show me error:

"""
failed to parse manifest at `/home/Lapce/lapce-core/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
"""

**Comment by panekj** [comment]
You need at least Rust 1.62

**Comment by panekj** [comment]
Duplicate of #1095
