### ISSUE TITLE
Add an option to disable ligatures

### ISSUE THREAD

**Issue by Looky1173** [lapce/lapce#1372]
## Is your feature request related to a problem? Please describe.

Some people may want to disable code ligatures for reasons outlined in [this article](https://practicaltypography.com/ligatures-in-programming-fonts-hell-no.html).

## Describe the solution you'd like

A new option should be added to the settings to allow disabling (or enabling) code ligatures.

## Describe alternatives you've considered

None.

## Additional context

None.

**Comment by lukaslihotzki** [comment]
This would also disable "good lignatures" like "fi", which are supported by the linked article. The obvious solution would be to simply use fonts without programming lignatures.

**Comment by panekj** [comment]
Closing in favour of #74
