### ISSUE TITLE
Lapce crashes at character insertion then deletion when one of the cursors is at offset 0

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#1379]
## Lapce Version

`master`

## System information

Windows 11

## Describe the bug

- Place a cursor at offset 0, and another somewhere else
- Press spacebar
- Press backspace
- Observe the following crash: `thread 'main' panicked at 'attempt to subtract with overflow', lapce-core\src\syntax\edit.rs:118:13`

**Comment by dzhou121** [comment]
Does this https://github.com/lapce/lapce/pull/1366 fix it?

**Comment by bugadani** [comment]
no

**Comment by bugadani** [comment]
It fixes the insert, but then after deleting what I inserted, Lapce still crashes on the same line. I updated the issue with the new line number and new instructions

**Comment by dzhou121** [comment]
@MinusGix Can you please have a look at this?

**Comment by gokhanettin** [comment]
I don't think we really need that crashing line and shift calculation at all with `CountMatcher::NonZero`. It properly iterates deleted lines.
