### ISSUE TITLE
my typescript is not showing the highlight?

### ISSUE THREAD

**Issue by bijakbercoli** [lapce/lapce#1382]
how do i add a highlight to typescript? for js everything went smoothly

**Comment by ghishadow** [comment]
what is your Lapce version ? please fill issue form when submitting

**Comment by bijakbercoli** [comment]
> what is your Lapce version ? please fill issue form when submitting

i using lapce v.0.2.0

**Comment by ghishadow** [comment]
it is fixed in master https://github.com/lapce/lapce/pull/1145, try nightly https://github.com/lapce/lapce/releases/tag/nightly
