### ISSUE TITLE
remote-ssh is too slow, i can drink over a cup of coffer :）

### ISSUE THREAD

**Issue by gzhang91** [lapce/lapce#1383]
## Lapce Version
![image](https://user-images.githubusercontent.com/28834180/192668355-644555f2-f3ea-43f9-b21e-fd21b0d9852a.png)

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 

## System information

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

**Comment by panekj** [comment]
Can you elaborate where it's slow

**Comment by gzhang91** [comment]
when i open a new ssh windows, which is my virtual machine, i should wait 1minute for the buttow change to green. also for open folder for code. i use lapce for c/c++ coding

**Comment by gzhang91** [comment]
my virtual machie is centos7 or ubuntu18(lapce in windows11), i had tried both, the result is same - slow. on ubuntu18, i tried to install clangd plugin, but i cannot make it effect

**Comment by onichandame** [comment]
A possible improvement of UX might be showing the progress of preparing the remote environment. As a reference, the vscode remote does show the progress of `starting dev container` at launch.

**Comment by zonorti** [comment]
Trying to connect to the same rpi3 on the local network
From MacOS, v0.2.4 connection is almost instant
From Windows 10, v0.2.4 - it takes around a minute to be ready to open files.
Normal ssh from Windows ( outside of Lapse ) or VScode - significantly faster.
Any input on how to debug this?

**Comment by qaqland** [comment]
I got the same sleeping. How can I debug more information?

**Comment by peterjc123** [comment]
Please refer to this [post](https://github.com/lapce/lapce/issues/1993#issuecomment-1382682252) for resolving slow SSH remote connections on Windows.
