### ISSUE TITLE
settings/editor: An option to show and hide the scrollbar.

### ISSUE THREAD

**Issue by seanmrnda** [lapce/lapce#1384]
## Description:
An option to show and hide the scrollbar inside the editor is a good addition to the editor settings. I noticed that it does hide itself when you click outside the editor, but the fact that it looks big annoys me every time I make the window smaller, because it blocks a portion of the user's view inside the editor.

### Screenshot:
> We need an option to hide this blocky thing. XD

![image](https://user-images.githubusercontent.com/45195351/192714745-e5e8e3ff-f1b8-4835-aa88-377fb5d06221.png)

### Alternative:
Making it slimmer is also a good solution because it is way too chunky.

**Comment by Looky1173** [comment]
You can already adjust the width of the scrollbar in Settings > UI Settings > Scroll Width. You can make it completely disappear too by setting the scroll width to 0.

**Comment by schwrzstrbn** [comment]
> You can already adjust the width of the scrollbar in Settings > UI Settings > Scroll Width. You can make it completely disappear too by setting the scroll width to 0.

Really? I missed that while looking for the option throughout the settings.
