### ISSUE TITLE
Needs the ability to create a new file

### ISSUE THREAD

**Issue by SamOrozco** [lapce/lapce#139]
I wanted to design a new JSON file in this editor, but I had to create a file in another editor and then open it in this one. That is a huge issue.

**Comment by miguelpragier** [comment]
Same thing here, on Windows 11.
I was looking for shortcuts or commands for "file edit", "new file", "create file", but couldn't find any.
Is it a bug, Or is there another way for creating a new file?

**Comment by bugadani** [comment]
Thanks for reporting! Creating files is not yet implemented, I'm afraid, so I've marked this issue as a feature request.

**Comment by dzhou121** [comment]
This should be fixed now by the latest v0.1.0 release.

**Comment by bugadani** [comment]
There is a "New file" command now.
