### ISSUE TITLE
Default key binding to open Folder

### ISSUE THREAD

**Issue by erf** [lapce/lapce#1392]
## Is your feature request related to a problem? Please describe.

Suggestion: Add `CTRL+SHIFT+o` as default key binding to open a folder.

**Comment by MinusGix** [comment]
`Ctrl+Shift+o` is already used for `palette.symbol` (jumping to a symbol in the workspace), like in other editors. Open folder can be done through the UI pretty easily, and is not as common as `palette.symbol`.
