### ISSUE TITLE
Visualise whitespace

### ISSUE THREAD

**Issue by Timmmm** [lapce/lapce#1400]
Basically implement the visualise whitespace feature that is common to most IDEs. It renders spaces as a grey centre dot and tabs as a grey right arrow. In VSCode this is called "render whitespace" and has the following settings:

* None
* Boundary: Render whitespace except single spaces between non-whitespace characters.
* Selection (the default): Render all whitespace in the selection.
* Trailing: Render only trailing whitespace characters.
* All: Render all whitespace characters.

Seems like a good set of options to me. I would also add this for completeness:

* Leading: Render only leading whitespace characters.

**Comment by panekj** [comment]
Fixed in #1284
