### ISSUE TITLE
Lapce won't compile using the most recent commit

### ISSUE THREAD

**Issue by eliasjonsson023** [lapce/lapce#1405]
## Lapce Version
0.2.0

## System information
Debian Linux Bullseye

## Describe the bug
Lapce won't compile. 61 errors
`
    |
102 |     pub const PANEL_HOVERED: &str = "panel.hovered";
    |                              ^ expected named lifetime parameter
`
are displayed.

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

workarounds that i used:
in lapce-data/src/config.rs:
`&'static str` instead of `& str`

**Comment by panekj** [comment]
You have conflicting rust versions installed, for some users `rustup update` fixed the issue
