### ISSUE TITLE
Installing Plugin Sometimes Does not get removed from available plugins

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#1406]
**Version**: Current HEAD.

**System information**: Linux.

## Describe the bug
Installing some volts (`Amolapce` and `Black Iris`, so potentially theme-specific) works, but they do not get removed from the available list after installation. The plugins staying in the list persists after a restart of Lapce. The themes themselves work, so they are properly installed.  
Other themes work properly, even ones that at a glance appear to have the same format of {plugin,volt}.toml.   
Low-credence-guess: case-sensitivity issue?

**Comment by I-am-mimic** [comment]
I'm having this same issue on Windows 10. 
![image](https://user-images.githubusercontent.com/74016811/195964120-79aa98aa-aa25-46e4-915f-2a2fb508f2f2.png)

**Comment by I-am-mimic** [comment]
Using Lapce 0.2.1

**Comment by panekj** [comment]
Resolved via implementing plugin registry
