### ISSUE TITLE
Scaling issues (Windows)

### ISSUE THREAD

**Issue by mrchip2k** [lapce/lapce#1412]
## Lapce Version

0.2.0

## System information

Windows 11. 1920x1080 display, set to 125% scale in Windows settings.

## Describe the bug
> None of this happens at 100% OS render scale.
> I have not tested on other OS, devices, and scale above 175% or below 100%.

- **Windows compatibility settings to try to launch the application with default 100% scaling has no effect whatsoever.**

- **Edge lines are inconsistent (sometimes 1 pixel width, sometimes 2 pixels)**
  Inconsistent lines happened on 125, 150 and 175%.
  One place where this can be observed, is by resizing the left/right panel - and looking at the blue line. You can clearly see it growing/shrinking by 1 pixel, as the line's position changes.
  I have also noticed that the cursor width can be inconsistent (see #1410) - it probably happens because of the same reason.

- **Icons can be very, or slightly, "messed up".**
  Window size affects how the icons look. (Sometimes they might look almost fine).
  _Potentially_ related to the line issue, in that the relationship between "application layout units" and "real pixels" alternating at different scales ends up snapping things to one or the other side of the real pixel.

## Additional information

Here's some screenshots.
#### 125%
![image](https://user-images.githubusercontent.com/20379339/193287154-11ccd662-5956-400b-8c2c-ac61acfb4934.png)
(Icon pixellation)

![image](https://user-images.githubusercontent.com/20379339/193287715-08375986-8791-46b1-b759-b215dcb63d48.png)
![image](https://user-images.githubusercontent.com/20379339/193289379-97aa877f-cf8b-4e48-b5b4-0dc849984624.png)
(Inconsistent and changing line thickness all over the place)

**Comment by MatthiasPortzel** [comment]
@izzues That looks like the infamous #1083. This is a separate issue I think.

**Comment by wangzhichao1990** [comment]
I have the same problem.

**Comment by patsore** [comment]
Same here. A few examples
![image](https://github.com/lapce/lapce/assets/80210497/7a686be8-6335-4969-beec-1a3cd4edca2e)

![image](https://github.com/lapce/lapce/assets/80210497/0e9775a4-e2cf-4ebc-a4b2-b94e49776e8a)

**Comment by panekj** [comment]
This is fixed now
