### ISSUE TITLE
Availability  of extensions

### ISSUE THREAD

**Issue by captainwycliffe** [lapce/lapce#1418]
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 

## System information

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

**Comment by captainwycliffe** [comment]
The code editor by rust is good...so far i have not experience  any bugs...but i would recommend to add extensions  icon so as to make it more efficient

**Comment by panekj** [comment]
So what's the actual problem?

**Comment by captainwycliffe** [comment]
Can't  run the html and css file on the code editor.

**Comment by panekj** [comment]
Lapce can open HTML/CSS and has basic syntax highlighting which is good enough default for now.
Anything more will have to be supplied by plugin with LSP server which is out of scope for Lapce itself.

**Comment by captainwycliffe** [comment]
okay
