### ISSUE TITLE
Dead in linux

### ISSUE THREAD

**Issue by zifahm** [lapce/lapce#142]
I tried running it and I see this

![Screenshot from 2022-03-18 00-29-29](https://user-images.githubusercontent.com/3761062/158876674-137904a6-b62a-4eff-914d-4ff9736e44b3.png)

**Comment by carandev** [comment]
I have the same problem

**Comment by bugadani** [comment]
Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

**Comment by carandev** [comment]
Now I have this problem 
![image](https://user-images.githubusercontent.com/72842040/168147476-3235f885-2e9a-4d4c-883a-18c328cf7683.png)

**Comment by bugadani** [comment]
@carandev you'll need to update your rust compiler.

**Comment by carandev** [comment]
@bugadani Thanks, Now lapce is working in these version

**Comment by panekj** [comment]
Has been fixed
