### ISSUE TITLE
terminal messed up PATH variable in Windows 10

### ISSUE THREAD

**Issue by tredmon** [lapce/lapce#1433]
## Lapce Version
0.2.0

## System information
Windows 10

## Describe the bug
The terminal adds the lapce parent directory to the PATH variable using an invalid path separator. The bug was experienced with both cmd and powershell as the defined shell, but oddly it didn't modify the PATH variable at all for git bash.

## Additional information
- When running under cmd the PATH can be checked with `echo %PATH%`
- When running under powershell the PATH can be checked with `$Env:PATH`

In both cases it prepends the lapce parent directory followed by a `:` to the path. The appropriate separator on Windows is a `;`.

**Comment by panekj** [comment]
should be fixed via #1434 & #1436
