### ISSUE TITLE
Graphical glitches and poor performance (on old hardware)

### ISSUE THREAD

**Issue by avelican** [lapce/lapce#144]
![lapce](https://user-images.githubusercontent.com/5946367/158887822-1a8043bf-38ff-4562-9001-0f2ca6c22e3b.jpg)

When resizing the window, parts of the GUI end up "outside" the window (hidden), and parts of the window become "see-through".
Also, there is significant lag (on the order of 500ms) on every interaction with the GUI, including typing text. Also during GUI interaction or typing, CPU usage is between 60-70%. (For reference, Sublime Text hovers around 5% while typing, animating GUI, dragging tabs etc.)

This is on Windows 10, 64 bit, on an old laptop (Lenovo X220 from 2011, with Intel HD Graphics 3000, 4GB RAM). The GPU is pretty old, only supports OpenGL 3.1 and DirectX 10.1. With this old GPU, I regularly run into games that either won't start or just show a black screen, so I wonder if Wgpu is failing to initialize something and falling back to software rendering? That would account for the poor performance and CPU usage.

(Not sure if it's related, but I didn't get any syntax highlighting for C++ — does it need to be enabled manually?)

---

Took a look at Wgpu's GitHub readme page, looks like they support DX12 on Windows and DX11 support is WIP. (My GPU supports DX10, lol.) That seems to confirm my suspicion that it's falling back to CPU rendering? I am not sure how to check which backend is being used. I thought perhaps Lapce would output some diagnostic info to the terminal, but even with --verbose I wasn't able to get a peep out of it :)

I understand this is probably a "wontfix" — most people don't have such old machines. Just thought you should know my experience trying Lapce today! :)

Best wishes with the project.

**Comment by bugadani** [comment]
Hi and thanks for reporting your issue! We know that Lapce may not run on older hardware, or may have issues. We are working on solving these.

I can't comment on your performance issues, I don't know if fallback to CPU rendering is even possible. It would be a good bet, and the slowdown you experience corresponds to that, but I'm not certain.

Lapce stores logs in `<user dir>/AppData/Roaming/Lapce/config`

C++ support should be implemented in #276.

**Comment by bugadani** [comment]
Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

**Comment by Nindaleth** [comment]
@liam-clink trying out the stable release, I found logs in `~/.local/share/lapce-stable/logs`

**Comment by liam-clink** [comment]
I just build lapce and the problem I was having appears to be no longer present. Could you try it again @avelican ? This issue could possibly be closed

**Comment by avelican** [comment]
I'm sorry, I didn't see the notifications. I can't boot that laptop anymore (long story but it's in poor condition and needs an external keyboard, which I don't have) so you can probably just close it if nobody else has this issue.
