### ISSUE TITLE
Wrong version number in macOS  download 0.2.0

### ISSUE THREAD

**Issue by suschizu** [lapce/lapce#1442]
## Lapce Version
download https://github.com/lapce/lapce/releases/download/v0.2.0/Lapce-macos.dmg
shows 0.10.0-dev - but it should be 0.2.0 

<img width="309" alt="Screenshot 2022-10-05 at 15 02 53" src="https://user-images.githubusercontent.com/16004333/194067183-98e10f29-7c22-406d-9444-61065b0b2e68.png">

## System information
macOS 12.6

## Describe the bug

the info.plist wasn't updated:

```
CFBundleIdentifier:
io.lapce

CFBundleShortVersionString:
0.10.0-dev

CFBundleVersion:
1
```

**Comment by MatthiasPortzel** [comment]
It looks like this number was updated with 0.2.1. This issue can be closed.

**Comment by suschizu** [comment]
great thanks - I can confirm that version 0.2.1 shows the version number correctly now!

<img width="227" alt="Screenshot 2022-10-13 at 10 43 54" src="https://user-images.githubusercontent.com/16004333/195548148-761bd31e-3920-4dd2-b9ca-78499ba096c1.png">
