### ISSUE TITLE
Error trying to use the app on windows

### ISSUE THREAD

**Issue by Withervoid77** [lapce/lapce#1444]
## Lapce Version

I can't see the version due to the bug

## System information

Windows 10 (10.0.19043) Home

## Describe the bug
The buttons don't work, and the text does not load, I have already tried restarting my computer, I tried reinstalling the app, but it is still the same.

## Additional information

- screenshots
![image](https://user-images.githubusercontent.com/95507613/194155431-3540487e-dda1-4958-9576-6cd6ffa6087b.png)

**Comment by DandevMS** [comment]
I also have the same problem
