### ISSUE TITLE
How get it working with pylsp?

### ISSUE THREAD

**Issue by erickod** [lapce/lapce#1447]
I trying get it working with pylsp, but until now I have no success;
Maybe I'm doing something wrong, but what I've done is install pylsp and install the lapce-python plugin, but even after that, I have no code completation or jump to definition or any LSP feature;

I'm here to ask some help.

**Comment by superlou** [comment]
Are you using the [lapce-python](https://github.com/superlou/lapce-python) plugin?
What version of Lapce are you running?
Did you install pylsp via "pip install python-lsp-server"?

**Comment by erickod** [comment]
The lapce version is 2.0.1 and I got it from the Copr Fedora Repo. 
But I've discovered how to solved the problem, the error happens because volt.toml lacks the keys below:

[activation] key with 
language = ["python"]

**Comment by panekj** [comment]
> lapce version is 2.0.1

such version doesn't exists

**Comment by erickod** [comment]
@panekj  You're right.  The right version is 0.2.0

**Comment by panekj** [comment]
Given that this is an issue with plugin and not lapce, I'm closing it
