### ISSUE TITLE
File type icon sometimes hard to read -- icon colors do not depend on theme

### ISSUE THREAD

**Issue by virtualritz** [lapce/lapce#1451]
## Issue

Icon colors ignore theme colors. This makes icons hard to read depending on choosen theme.
Example: default theme is dark but icon for Rust files is a black Rust logo. Should be white/gray.

A related issue is multi-colored file icons. For example the icon for `toml` files uses two different shades of gray. Icons that are this small should have a single color.

## Solutions

Different options:

1. Invert the icon color depending on theme background color's lightness. E.g. if it is <50%, invert.
2. Draw an outline around icons, based on the theme's background and the icon color. Difficult since it requires more clever logic depending on the icon's native color. If the icon is white, drawing a white outline is not only superfluous in a dark theme but will make the icon look bad. I.e. the outline must have a high contrast ratio to both the icon's color and the background color in the problem case at hand.
4. Let the theme define the icon color per file type. I.e. make the icon b&w then colorize it with the choosen icon color for the file type in the theme.

**Comment by sokorototo** [comment]
Maybe we can replicate vscode's icon system?

https://code.visualstudio.com/api/extension-guides/file-icon-theme
