### ISSUE TITLE
Ctrl + Shift + letter keybinds not working

### ISSUE THREAD

**Issue by aalhitennf** [lapce/lapce#1456]
## Lapce Version
0.2.0

## System information
Arch Linux, Hyprland wm on Wayland

## Describe the bug
Binding i.e. **Toggle Line Comment** to `Ctrl + Shift + a` does nothing. Binding to `Ctrl + Alt + a` does work as expected. Binding to `Ctrl + Alt + F8` does work properly.

## Additional information
Maybe shift key and letter capitalization could be the problem?

**Comment by oknozor** [comment]
Are you using lapce 0.2.0 ? Not 100% sure but I think this is already fixed on latest master.

**Comment by aalhitennf** [comment]
Stable release 0.2.0 from arch repository. I'll try building the git master, will close if its fixed.

**Comment by aalhitennf** [comment]
Works with nightly so ill close this :+1:
