### ISSUE TITLE
Lapce become unresponsive and freeze when using workspace symbol search

### ISSUE THREAD

**Issue by oknozor** [lapce/lapce#1462]
## Lapce Version
Latest master -> 7c993f94

## System information

os: `Linux archlinux 5.19.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 28 Sep 2022 13:21:25 +0000 x86_64 GNU/Linux` 
wm: sway 1.7 (wayland)

I think given the nature of the bug it's worthy to note that I am having this issue on a relatively low-end machine (AMD Ryzen 5 4500U 8Gb of RAM).

## Describe the bug

When using workspace symbol search with any LSP server, lapce become unresponsive and then completely freeze. 

## Additional information

Lapce doesn't crash, it just completely freeze. 

There are no error in the log but it seems lapce and the LSP server are doing some intensive work.
I tried with both rust-analyzer and the java lsp server getting the same result. 

![screenshot-2022-10-09T10:50:29](https://user-images.githubusercontent.com/24563836/194747393-8d5eb388-82d4-4867-892d-672b6cbeae67.png)

**Comment by MinusGix** [comment]
This seems to be due to some code setting the input and then updating it, which alerts it to set the input again. Thus if you type fast enough, then you can have a cycle where it modifies the input repeatedly. This has happened before, though I thought I fixed it last time. I'll fix this issue.
