### ISSUE TITLE
Github codespaces

### ISSUE THREAD

**Issue by Nv7-GitHub** [lapce/lapce#1467]
## Is your feature request related to a problem? Please describe.

I want to be able to edit Github codespaces from Lapce.

## Describe the solution you'd like

Support for opening Github codespaces.

## Describe alternatives you've considered

Currently I'm using VSCode but I want to be able to use Lapce.

**Comment by panekj** [comment]
Not possible since it's proprietary product that doesn't provide option to connect via SSH
