### ISSUE TITLE
Crash when trying to open folder

### ISSUE THREAD

**Issue by shinobu-uwu** [lapce/lapce#147]
Sometimes when clicking to open a folder in the top left corner it crashes (happened twice to me in three tries)

This is the output of the terminal, and there is nothing on `~/.config/lapce/lapce.log`
```
Error sending request: Broken pipe
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/khronos-egl-4.1.0/src/lib.rs:1015:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

As there is no template issue I don't know what other information you need, so feel free to ask :)

**Comment by ghishadow** [comment]
can you try latest version https://github.com/lapce/lapce/releases/tag/v0.2.0 if this is still a issue

**Comment by shinobu-uwu** [comment]
I tested a few times and no crashing so far!
