### ISSUE TITLE
Rust LSP not working

### ISSUE THREAD

**Issue by maxwell8888** [lapce/lapce#1470]
## Lapce Version

Build from source master branch 10 Oct 2022 (commit 5e507)

## System information

Ubuntu 20.04
rustc --version 1.64.0

## Describe the bug

The LSP doesn't appear to be working, I have no squiggly lines, when I press F12 nothing happens, etc

## Additional information

Nothing is printed in the terminal from which Lapce is running.
When building the v0.2.0 commit (59d55) (2 Sep 2022) from source, LSP works fine, I have squiggly lines and F12 works, so the problem has obviously been introduced since then. When I have time I might try and narrow it down further to the offending commit.

**Comment by panekj** [comment]
did you upgrade rust plugin

**Comment by maxwell8888** [comment]
Wow, that was quick! I ran rustup update yesterday, is that what you mean? Not sure if there is a standalone rust plugin for Lapce or how I would upgrade it.

**Comment by panekj** [comment]
You had to install lapce-rust plugin to get LSP features for Rust and you can upgrade it via plugin tab menu in Lapce

**Comment by maxwell8888** [comment]
Ah in the GUI, yes I've upgraded it and now it works fine, thanks so much!
