### ISSUE TITLE
ui/status-bar: Layout selector is not properly visible due to error message

### ISSUE THREAD

**Issue by schwrzstrbn** [lapce/lapce#1485]
## Lapce Version
Nightly build: 3396279

## System information

Fedora 36

## Describe the bug

When there is a long error message on the status bar, the layout selector is not properly visible because the texts are covering it.

## Additional information

All I did was, open a go file with an error long enough to cover the whole status bar.

![Screenshot from 2022-10-12 20-18-36](https://user-images.githubusercontent.com/45195351/195342399-a8ee4bf5-78b1-4c36-b388-9fb7adf35392.png)

**Comment by MinusGix** [comment]
Note: This should be truncated; however, it would be good to provide the full message when you hovered over it.

**Comment by panekj** [comment]
I think it would be better if it was a clickable area that would expand and show all LSP progress

**Comment by panekj** [comment]
We should also display only progress title on status bar and not concat it with message
