### ISSUE TITLE
newline characters shown as space

### ISSUE THREAD

**Issue by as3ii** [lapce/lapce#1488]
## Lapce Version

0.2.1

## System information

arch linux

## Describe the bug
when "Render Whitespace" is set to any other value than `none`, newline (\n) invisible characters should not be shown as spaces

## Additional informations
![2022-10-12_23-11](https://user-images.githubusercontent.com/29260716/195448794-35008ea0-bbce-4a54-b690-8ada4dc9bdfd.png)

**Comment by panekj** [comment]
duplicate of #1478

**Comment by as3ii** [comment]
oh sorry, i didn't see it
