### ISSUE TITLE
The terminal button doesn't restore the terminal pane on windows

### ISSUE THREAD

**Issue by VectorStrike** [lapce/lapce#149]
After closing the terminal using the X button clicking on the terminal icon does not restore the closed pane, search and problems does and then you can switch back to the terminal.

**Comment by SamuelMarks** [comment]
Same issue on macOS

**Comment by bugadani** [comment]
I can't reproduce this

**Comment by bugadani** [comment]
Thanks for reporting this issue. I'm not able to reproduce it, and I would like to know if the issue is still present in the current master branch. Thanks!

**Comment by panekj** [comment]
Treating as resolved
