### ISSUE TITLE
How to enable the function of code intelligent prompt in Lapce ?

### ISSUE THREAD

**Issue by kotlin2018** [lapce/lapce#1492]

**Comment by MinusGix** [comment]
If you mean like:  
![image](https://user-images.githubusercontent.com/13157904/195727017-b1e9cb04-48a0-49f5-b1b2-ed563eb6cd49.png)
That is from an language-server plugin. You can install plugins from the plugin sidebar for your specific language: 
![image](https://user-images.githubusercontent.com/13157904/195727098-dd7f977f-9334-49e0-86e3-70af3468d8fe.png)
