### ISSUE TITLE
All text is rendered as contiguous squares

### ISSUE THREAD

**Issue by carljohnesan** [lapce/lapce#1497]
## Lapce Version

I can't see the version in About Lapce window because text isn't rendered there either, it's all rectangles.
I've downloaded Lapce yesterday (October 12, 2022).

## System information

Windows 10 installed with BootCamp on MacbookAir 2011 (yeah, old stuff)

## Describe the bug
Here's the screenshot that shows the issue:
![lapce_bug](https://user-images.githubusercontent.com/47556468/195548830-73b8213f-1f56-4536-8230-17241e2c728f.PNG)

## Additional information
I'm guessing that this issue is somehow associated with that "GPU accelerated" rendering feature, because I have an old-ass Macbook from 2011 that has integrated graphics.

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/1083 and https://github.com/lapce/lapce/issues/940
