### ISSUE TITLE
Can you make this app for android

### ISSUE THREAD

**Issue by ansarimohammed422** [lapce/lapce#1499]
because android doesn't have good foss code editor at all
it would be great to see android port of lapce with native android UI

Can You Please Do It

**Comment by panekj** [comment]
there are some efforts from people using Android to package it for termux but I believe this is a non-goal for the project itself

**Comment by schwrzstrbn** [comment]
> because android doesn't have good foss code editor at all it would be great to see android port of lapce with native android UI

Try Acode from playstore, It's a really good code editor for android.
