### ISSUE TITLE
Support for Lombok (annotation preprocessing) in Java projects

### ISSUE THREAD

**Issue by ranger-ross** [lapce/lapce#1501]
## Is your feature request related to a problem? Please describe.

In Java, Lombok is a very popular library for removing boilerplate code. In Lapce, when I add the `@Data` annotation to a Java class, the editor does not take this into account and display errors and autocomplete does not work.

## Describe the solution you'd like

When the Java plugin is enabled, the editor should take into account Lombok (and any other preprocessed) annotations and provide code completion. Intellij for example, has this feature built. 

## Describe alternatives you've considered

N/A

## Additional context

Issue example

<img width="922" alt="image" src="https://user-images.githubusercontent.com/25847436/195626676-60a151ac-a495-447e-8e28-fd842ec6efe6.png">

**Comment by oknozor** [comment]
I'll take a look, soon. 
This should be straight forward by adding the correct args when launching jdtls.

This is unrelated to lapce though, you probably want to re-open your issue here: https://github.com/oknozor/lapce-java

Note to self (https://github.com/mfussenegger/nvim-jdtls/issues/28)

**Comment by oknozor** [comment]
@ranger-ross you can update the java plugin, it now support lombok annotations.
Note that you will need to enable lombok support in the plugin settings : 
 
![screenshot-2022-10-14T13:31:30](https://user-images.githubusercontent.com/24563836/195837089-452ccc1b-2d99-46ff-a6f7-08db378f149b.png)

**Comment by ranger-ross** [comment]
Thank you so much for the quick response!
