### ISSUE TITLE
"restart_to_update" action doesnt work.

### ISSUE THREAD

**Issue by cidit** [lapce/lapce#1512]
## Lapce Version

0.2

## System information

fedora 36

## Describe the bug

"restart_to_update" action doesnt work.

## Additional information

extra details: it doesnt work wither when clicking the option in the little gear menu in the top right and it doesnt work when i try to bind it to a key either

**Comment by sokorototo** [comment]
It actually does, it just doesn't tell you it's downloading the platform binary. Making the user think it's just bugging out. Just give it some time, it's just doing it in the background (silently)

**Comment by cidit** [comment]
so, i just had a conversation with someone on the discord, and according to them, the update shouldve taken just a few minutes after clicking the button. since it hasnt happened even after more than 10 mins, we concluded that its possible theres still a bug. 

heres a screenshot of the convo.
![image](https://user-images.githubusercontent.com/44065673/195723544-55b797b1-f218-44a7-8149-fee05e94da50.png)

is there an issue open to fix the lack of visual feedback yet?

**Comment by sokorototo** [comment]
I don't think so. I'm not a maintainer, but I think this issue should be escalated into a visual feedback thing

**Comment by cidit** [comment]
that would be a feature, right?

**Comment by panekj** [comment]
> is there an issue open to fix the lack of visual feedback yet?

it's already fixed in HEAD https://github.com/lapce/lapce/pull/1508

**Comment by rahulTPatil** [comment]
It is still not working for me. 
Lapce v 0.2.2
Endeavour OS

**Comment by kczx3** [comment]
Same on Windows 10
