### ISSUE TITLE
WSL proxy connection failure

### ISSUE THREAD

**Issue by ShyOnyx** [lapce/lapce#1514]
## Lapce Version

0.2.1 Portable

## System information

Windows 10 Pro 21H2

## Describe the bug

Will not properly connect to WSL. Console remains blank except for cursor, and clicking Open Folder shows empty window. No errors given.

## Additional information

After selecting Connect to WSL, this is all I get:

![LapceWSLIssue](https://user-images.githubusercontent.com/46958608/195726585-b3fdf901-63f9-46b7-9ed9-1c13cadc2f15.png)

Works fine with 0.2.0 Portable. Likely something changed in the 0.2.1 Portable is causing this. Haven't used non-portable versions, so not sure if those are affected.

Tried deleting all lapce files and folders I could find and redownloading, restarting my computer, etc. No change. Not sure what else I could try, but I'm pretty sure it's a bug.

**Comment by kiwiyou** [comment]
I had a similar issue. My log file said:
```
[2022-11-08][23:10:26][lapce_data::proxy::start_remote::first_try][DEBUG] fish: Unknown command: lapce-no-command
fish: 
lapce-no-command
^

[2022-11-08][23:10:26][lapce_data::proxy::start_remote::first_try][DEBUG] 
[2022-11-08][23:10:26][lapce_data::proxy::host_specification][DEBUG] linux x86_64
```
The proxy seemed to fail, so I removed `$HOME/.local/share/lapce` directory and lapce launched well.

**Comment by ShyOnyx** [comment]
That got it working. I'll close this since it doesn't appear to be caused by Lapce itself (and 0.2.2 is out and doesn't have the issue).

**Comment by erlantz-knbz** [comment]
Hi, Im experiencing this issue rn on nightly release for windows.
I connect to wsl but the "open folder" button does nothing.
