### ISSUE TITLE
Lapce is not indexing the project

### ISSUE THREAD

**Issue by coffee-is-power** [lapce/lapce#1539]
## Lapce Version
0.2.1

## System information

Fedora silverblue 36 (inside a toolbox)

## Describe the bug
Auto-complete doesn't work.

**Comment by coffee-is-power** [comment]
this is the time we do a git bisect

**Comment by ghishadow** [comment]
which language ?

**Comment by coffee-is-power** [comment]
rust

**Comment by oknozor** [comment]
Did you install the rust plugin ?

**Comment by coffee-is-power** [comment]
yes

**Comment by panekj** [comment]
No info to work from or reproduce
