### ISSUE TITLE
Font is not working

### ISSUE THREAD

**Issue by riley-martin** [lapce/lapce#1540]
## Lapce Version

Lapce 0.2.1

## System information

Arch Linux. Using Wayland if that makes a difference

## Describe the bug
When I use the [Iosevka](https://typeof.net/Iosevka/) font in the editor settings, it does not
work and instead falls back to a serif font

## Additional information
This is what happens when I try to use the Iosevka font. The font displayed is not correct, but seems to be a system fallback or something.
![20221016_13h48m38s_grim](https://user-images.githubusercontent.com/106552431/196050315-08cae1c9-44d1-4a96-8bff-60aa8857203d.png)

Fira Code, which I also have installed, works fine.
![20221016_13h48m49s_grim](https://user-images.githubusercontent.com/106552431/196050326-c03ceef0-aec4-4e70-b746-f744b4c90394.png)

I have tried restarting Lapce, made sure the font was installed, etc.

**Comment by panekj** [comment]
Are you sure you typed proper font family name when setting `Iosevka`?

**Comment by riley-martin** [comment]
I am pretty certain. I even tried copy and pasting it from my web browser, where it worked.  
I do not know much about fonts, but is it possible that it is a format that lapce does not support? It is a `ttf` font patched with nerd font symbols.

**Comment by henrythebuilder** [comment]
Hi, 
I had the same problem too.
The solution for me was to insert what in _FontForge_ is defined as '`Name For Humans`' (in _font information_) instead '`Family Name`', in my case for the '_Recursive_' font the '_Family Name_' field is the same for all the variants while the '_Name For Humans_' field changes for each variant: e.g. '_Recursive_' vs '_Recursive Sn Lnr St Med_'.
I hope it helps

**Comment by riley-martin** [comment]
Ok, I got it to work. The `Name for Humans` did not work, but in as I was looking for it, I noticed that in FontForge the `Family Name` was not the same as what the font was called in other applications, so I tried setting the lapce font to the font's `Family Name` and it worked.  
So thanks for the tip, but IDK why my font worked differently than yours.
