### ISSUE TITLE
Rename Code Lens

### ISSUE THREAD

**Issue by Timmmm** [lapce/lapce#1542]
It's a bit unfortunate that Lapce's Code Lens feature is completely different from VSCode's Code Lens feature. I suggest renaming it. Unfortunately Makepad doesn't really have a name for it already. Some suggestions:

* Bird's eye view
* Code overview
* Code zoom
* Selective zoom

Let the bike shedding commence! Bird's eye view is my favourite.

**Comment by oknozor** [comment]
This is a good idea, at some point we will implement LSP codelens and it will be confusing.

**Comment by panekj** [comment]
code scaleview

**Comment by LittleTasteOfHeaven** [comment]
code pov

**Comment by dehahost** [comment]
Also have some candidates: _Glance View_ and _Code (at) Glance_

**Comment by flukejones** [comment]
"code flash"?

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/3396
