### ISSUE TITLE
ui/title-bar-buttons: The window titlebar buttons disappear.

### ISSUE THREAD

**Issue by schwrzstrbn** [lapce/lapce#1563]
## Lapce Version

Nightly - e416688

## System information

Fedora 36

## Describe the bug
Window buttons disappear when the windows are resized into smaller window, and when maximized the minimized button disappears. 

## Additional information

> Lapce screenshot

![Screenshot from 2022-10-21 23-23-12](https://user-images.githubusercontent.com/45195351/197232677-f6e23d5a-c8be-4809-b60c-a58b58023903.png)

**Comment by panekj** [comment]
Fixed by #1562

**Comment by schwrzstrbn** [comment]
> Fixed by #1562

okay, thanks @panekj. I'll close this now.
