### ISSUE TITLE
Basic command line options

### ISSUE THREAD

**Issue by eshom** [lapce/lapce#157]
Currently there are no command line options.
It would be nice to have basic options like:
`lapce --version`
`lapce --help`

And a positional argument to open files from command line.
`lapce myfile.c`
Or open a directory
```
lapce .
lapce /home/user/myprojects
```

**Comment by Titaniumtown** [comment]
Yes! please do add this. I was testing lapce and found this very annoying lol

**Comment by ailyas19776** [comment]
I will work on this
