### ISSUE TITLE
Text not rendered on linux arm64

### ISSUE THREAD

**Issue by MFAshby** [lapce/lapce#1592]
## Lapce Version

Compiled from current `master` branch, c40d82b0b8b02d3c78d6565093c5e9e1e3c76622

## System information

manjaro ARM running on a pinebook pro (linux arm64)

## Describe the bug

This appears to be a recurrence of https://github.com/lapce/lapce/issues/450.

![Screenshot from 2022-10-23 17-31-53](https://user-images.githubusercontent.com/1760515/197404271-b37bc36c-d1b6-463d-a6c8-8666e4895633.png)
)

## Additional information

I haven't yet found a workaround  or have a theory why this isn't workin. Looking now!

**Comment by MinusGix** [comment]
The pinebrook pro (https://www.pine64.org/pinebook-pro/ ) documentation page says that the GPU it has is https://developer.arm.com/Processors/Mali-T860%20and%20Mali-T880  
Currently, Lapce requires OpenGL 3.3, (see #1062 and #1108, with the latter being the tracking issue sortof), but the GPU seems to only support up to 3.2.  
You can try doing `LIBGL_ALWAYS_SOFTWARE=1 lapce` to use software-rendering instead. However, the performance of that mode seems to be poor for some users but fine for others.

**Comment by MFAshby** [comment]
@MinusGix , setting that environment variable does indeed fix the text rendering, but then lapce CPU usage goes up a _lot_ (to be expected with software rendering). 

I'll follow those other issues, thanks for the pointers!
