### ISSUE TITLE
Spell checking support

### ISSUE THREAD

**Issue by LuckyTurtleDev** [lapce/lapce#1595]
## Is your feature request related to a problem? Please describe.

I am writing documents with latex and would like to use automatic spell checking.

## Describe the solution you'd like

Option to enable spellchecking, by using the system dictionary.
Maybe by using a Lapce plugin.

**Comment by msrd0** [comment]
:+1: but please don't force download a bunch of dictionaries for those that don't want it like some other text editors do.

**Comment by panekj** [comment]
Closing as this should be provided as plugin
