### ISSUE TITLE
ui/theme-color: Cannot seem to change the colors in the theme settings

### ISSUE THREAD

**Issue by schwrzstrbn** [lapce/lapce#1596]
## Lapce Version

Nightly - de965555

## System information

Fedora 36

## Describe the bug

Cannot seem to change the theme color in theme settings

## Additional Information

> Screenshot

![image](https://user-images.githubusercontent.com/45195351/198031661-c4f25766-b428-4309-9fc4-fd48f01b71cc.png)

Nothing happens after changing the lapce.border color.

**Comment by schwrzstrbn** [comment]
Is this a bug or it is intended.

**Comment by Jieiku** [comment]
I was trying to change the black base color to something a little darker and noticed the value does not save when I change it.

My thinking is that its currently displaying the values, but saving or changing them is not yet implemented.

Very excited to use Lapce full time sooner or later, once a few more things are ironed out.

**Comment by panekj** [comment]
> saving or changing them is not yet implemented.

it's implemented

**Comment by Jieiku** [comment]
What am I doing wrong? Here is a video of me trying to change the color.

You can see the value has not saved when I reopen the settings:

![lapce-save-theme-settings](https://user-images.githubusercontent.com/106644/200241951-5c842514-0e39-4fcb-b9a2-7aecd66f4263.gif)

**Comment by panekj** [comment]
As the issue says, it's not working currently...

**Comment by Jieiku** [comment]
oh sorry when you said it is implemented I took that to mean that it should be working, now I fully understand, thank you.
