### ISSUE TITLE
Basic editor functions

### ISSUE THREAD

**Issue by superiums** [lapce/lapce#1604]
after first try, found it missing some basic functions:
- multi fonts support. i use inconsolata for code, but it dose not display Chinese characters, so it's necessary to define the second font.
- find by regex, restrict supper case.
- search and replace. replace by regex.
- don't mix local file search and muti file search. there's no necessary to sync them.
- Ctrl+. not work,   Ctrl+k opens settings but not focus key-settings tab.
- Ctrl+s not save.

**Comment by hbina** [comment]
>Ctrl+s not save.

This should work. Do you have the file tab in focus?

**Comment by panekj** [comment]
> * find by regex, restrict supper case.

already implemented

**Comment by superiums** [comment]
> This should work. Do you have the file tab in focus?
of course focused.

i try it again today, and found:
1. open a dir , click a txt file, change, press Ctrl+s, it saved.
2. create a new file named aa.py, change, press Ctrl+s, it not save.

**Comment by moritzhoewer** [comment]
> try it again today, and found:
>
>    1. open a dir , click a txt file, change, press Ctrl+s, it saved.
>    2. create a new file named aa.py, change, press Ctrl+s, it not save

This is also reported in #1750

**Comment by panekj** [comment]
Closing as it should be one issue per feature/bug
