### ISSUE TITLE
Show Hover keybind

### ISSUE THREAD

**Issue by m-rutter** [lapce/lapce#1621]
## Is your feature request related to a problem? Please describe.

As a modal editor sufferer, only being able to get hover diagnostics from mouseover events is painful. 

## Describe the solution you'd like

Be able to trigger the hover tooltip with a keybinding

## Describe alternatives you've considered

Haven't considered any altnernatives

## Additional context

This is a common feature across modal editors:
* vscode vim plugin: `g h`
* helix editor: `k`
* neovim lsp suggested keybinding: `ctrl+k`
* vim coc plugin: `K`

A PR implementation: https://github.com/lapce/lapce/pull/1620

**Comment by panekj** [comment]
You don't need to create an issue if you already opened a PR

**Comment by m-rutter** [comment]
@panekj I was trying to follow the contributor guidelines which say that I should open up an issue.

> If you want to write some code, develop the documentation, or otherwise work on a certain feature or bug, let us know by replying to or creating an [issue](https://github.com/lapce/lapce/issues).

https://github.com/lapce/lapce/blob/master/CONTRIBUTING.md

**Comment by panekj** [comment]
It's more or less before you try to implement something, so others know you are working on it

**Comment by panekj** [comment]
Fixed via #1620
