### ISSUE TITLE
[Feature Request] [Documentation Enhancement] Installation from Source with `cargo`

### ISSUE THREAD

**Issue by kevinmatthes** [lapce/lapce#1623]
## Is your feature request related to a problem? Please describe.

The documentation on the installation of Lapce is incomplete.  This concerns the section on building the editor from source.  `cargo` offers a comfort feature to install Rust projects from their public repositories:

```
cargo install --git https://github.com/lapce/lapce
```

The above command is going to install the latest available repository state as a release binary into the user's home directory.  `cargo` will therefore freshly build the project.  One just needs to ensure all software requirements to be installed.

Installing Lapce this way is especially interesting for contributors in order to identify possible rough edges and / or bugs to take into account prior the next release as well as for users who always would like to use the latest version.

## Describe the solution you'd like

Please consider to expand the documentation section on building the project from source with the information given above.

## Describe alternatives you've considered

If you agree, I can also submit a Pull Request with a suggestion for an according documentation expansion.

## Additional context

This Feature Request originates from https://github.com/lapce/lapce/discussions/516.

**Comment by panekj** [comment]
> Installing Lapce this way is especially interesting for contributors in order to identify possible rough edges and / or bugs to take into account prior the next release as well as for users who always would like to use the latest version.

We have nightly releases for those who don't want to modify lapce source and others can simply git clone the repository to build locally.

**Comment by kevinmatthes** [comment]
This `cargo` feature abbreviates the local build by not demanding to manually clone the repository.

**Comment by panekj** [comment]
I'm aware but we are not a `cargo` wiki nor is that workflow particularly helpful in any way. If you are familiar with `cargo` you can continue using it that way.

**Comment by kevinmatthes** [comment]
Okay, then I will close this issue.
