### ISSUE TITLE
[Feature Suggestion] CHANGELOG Creation on Release

### ISSUE THREAD

**Issue by kevinmatthes** [lapce/lapce#1624]
## Is your feature request related to a problem? Please describe.

At the moment, the contribution guidelines ask contributors to also provide the corresponding CHANGELOG entries, if suitable.  This can lead to numerous merge conflicts as multiple Pull Requests are going to submit changes to the same file.  The first Pull Request merged will thus cause the other ones to have the resulting merge conflicts resolved.  Such situations are going to slow down the development.

For illustration, consider the following practical example.  At the time of this writing, #1619 and #1620 are Pull Requests which both edited the CHANGELOG.  Since #1619 was merged before #1620, the latter Pull Request had a merge conflict regarding the CHANGELOG which needed to be resolved.

## Describe the solution you'd like

A solution to this problem is an asynchronous CHANGELOG management, i.e. the submitted CHANGELOG entries are added on release to the CHANGELOG, staying unique files in a central storage until then.  This approach effectively prevents the merge conflicts described above.  There are free and open source software tools to fulfill this task efficiently.  I worked with [Scriv](https://github.com/nedbat/scriv) so far, so I could configure this Apache-2.0 licensed Python 3-CLI for this project, if wished.  The configuration would involve the creation of two configuration files and some minor edits to the CHANGELOG.  Contributors could then submit their CHANGELOG entries as unique files to the central storage.  The harvesting of this central storage can be perfectly combined with other automatic release mechanisms, such as incrementing the versions numbers, for instance.

## Describe alternatives you've considered

There are also other tools beside Scriv, the project itself names a few, see https://github.com/nedbat/scriv/blob/main/docs/philosophy.rst for an overview.  As I did not work with them, yet, I do not know how to set them up, if required.

## Additional context

* #1619 and #1620 as examples for Pull Requests with CHANGELOG triggered merge conflicts
* Scriv:  https://github.com/nedbat/scriv
* other tools than Scriv:  https://github.com/nedbat/scriv/blob/main/docs/philosophy.rst

If the described problem is not considered a problem at all and, hence, this suggestion is rather obsolete, feel free to close this issue as "not planned".

**Comment by panekj** [comment]
It was our decision that we don't want to generate changelog automatically due to it's nature of what we it to include.

**Comment by adam-becker** [comment]
> It was our decision that we don't want to generate changelog automatically due to its nature of what we wanted it to include.

Can't this be driven with labels? Or milestones? `foreach issue in milestone; generate changelog entry for issue`

**Comment by m-rutter** [comment]
Some other projects with high volume contributions often use something like https://github.com/changesets/changesets, which maintains a list of changes in a merge-conflict free way that then get automatically appended to the changelog when there is a "release".

The way it works is every PR has one or more randomly named "changeset" files in a `.changeset` directory that the user creates using a cli tool. A bot automatically creates and updates a "release PR" that deletes all of the changeset files in the release and appends them to the `CHANGELOG.md` file.

**Comment by panekj** [comment]
> The way it works is every PR has one or more randomly named "changeset" files in a `.changeset` directory that the user creates using a cli tool. A bot automatically creates and updates a "release PR" that deletes all of the changeset files in the release and appends them to the `CHANGELOG.md` file and increments any version numbers as required (optionally respecting semver).

That sounds like way too much noise in git repo and I'm not sure if it will fit our current release workflow

**Comment by adam-becker** [comment]
> > Can't this be driven with labels? Or milestones? `foreach issue in milestone; generate changelog entry for issue`
> 
> > we don't want to generate changelog automatically

Doesn't have to be generated automatically. The milestone would just be an association between "Issues we think are noteworthy for end-users" and the release. During the release, one could manually go through the issues in the milestone and make 1 commit to update the changelog.
