### ISSUE TITLE
Option to switch EOL sequence to CRLF

### ISSUE THREAD

**Issue by amitxv** [lapce/lapce#1627]
## Is your feature request related to a problem? Please describe.

Windows uses carrige return CRLF but the line endings are set to LF by default. As far as I am aware, there is no option to switch between them in the application settings.

- See [DOS vs. Unix Line Endings](https://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html)

## Describe the solution you'd like

An option to switch line endings in the settings page.

## Describe alternatives you've considered

N/A

## Additional context

The feature is widely available in other editors.

![image](https://user-images.githubusercontent.com/86924251/199103695-1b467c43-b689-4b52-8d79-786abd7b506a.png)

**Comment by bannert1337** [comment]
I would like to implement this feature!
