### ISSUE TITLE
Python indentation always has width of 7

### ISSUE THREAD

**Issue by Dirleye** [lapce/lapce#1637]
## Lapce Version

0.2.1

## System information

EndeavourOS Linux

## Describe the bug
Indentations with tab in Python files always have a width of seven, no matter the value in settings.
C and C++ files didn't have the same issue and would follow the value in settings.

## Additional information

This happens with and without the Python plugin installed.

**Comment by ghishadow** [comment]
looks like https://github.com/lapce/lapce/pull/1411/files#diff-d935b0f8af6b77e38d32b19067485d401a736d7af98037433583f51a85f4bcd8 has messed up many language indent values including python https://github.com/lapce/lapce/blob/master/lapce-core/src/language.rs#L624
