### ISSUE TITLE
UI unreadable if font is Inter

### ISSUE THREAD

**Issue by selfisekai** [lapce/lapce#1639]
## Lapce Version

0.2.1

## System information

Alpine Linux edge

## Describe the bug

UI font is so small that it's hard to see anything, has lots of space between the characters

## Additional information

window manager: sway (Wayland), haven't tried any other

output is using `scale 1.2` setting

![image](https://user-images.githubusercontent.com/11798442/199687925-a1d66892-c4c1-4019-a825-1ce25df0a1d2.png)

after setting font family to `JetBrains Mono` it looks fine:
![image](https://user-images.githubusercontent.com/11798442/199688321-b19ad3e8-89ed-41db-badf-dbefcc57734f.png)

**Comment by riley-martin** [comment]
I had a similar problem when lapce could not find the font name I set. Here is how I fixed it #1540, maybe it will help you.

**Comment by nekopsykose** [comment]
it does find the font- if you enter gibberish it instead correctly displays the system fallback. it's inter specifically that ends up looking like that micro jumbled mess.

**Comment by mpauper** [comment]
Same issue here. Version 1.102.

OS: Pop!_OS 22.04 LTS x86_64
DE: GNOME 42.5 
WM: Mutter

**Comment by panekj** [comment]
Should be fixed now since we overhauled whole UI
