### ISSUE TITLE
Use system dialog for "open folder"

### ISSUE THREAD

**Issue by Haroenv** [lapce/lapce#165]
The recreated open folder dialog looks pretty, but misses many features from the system (macOS) dialog I'm used to, eg. typing to jump to the folders with that name, a sidebar with frequently accessed locations, and opening up where it last was opened.

I'd recommend using the builtin system "open folder" dialog, rather than recreating.

**Comment by dzhou121** [comment]
Fixed by 0251db8011face45ce57dc5122486778d2e3cb17

**Comment by Haroenv** [comment]
What a coincidence! Thanks

**Comment by dzhou121** [comment]
They are fixed in v0.0.12
