### ISSUE TITLE
Themes not listed after install

### ISSUE THREAD

**Issue by graymind75** [lapce/lapce#1675]
## Lapce Version
0.2.2

## System information
Windows 11
Core i5 12400
16 GB Ram

## Describe the bug
After installing themes, they doesn't appear in the themes list

## Additional information
- screenshots

![lapce](https://user-images.githubusercontent.com/22690689/201030969-4e4e0eb5-c9a7-4d15-b185-1d4ce5d2e68e.png)

**Comment by panekj** [comment]
Not an issue with Lapce, themes are not updated to latest version
