### ISSUE TITLE
Indent guides seem broken for the Julia language

### ISSUE THREAD

**Issue by VarLad** [lapce/lapce#1676]
## Lapce Version

nightly-1674fff

## System information

Fedora 37 SilverBlue

## Describe the bug
Indent guides appear where they shouldn't.

## Additional information
![image](https://user-images.githubusercontent.com/51269425/201055567-fdf727c9-7bfb-4fdd-a304-fd4c2d509fc1.png)

Would be nice if someone could help me diagnose if this is an issue with Lapce, the queries or Tree-sitter julia itself

**Comment by MinusGix** [comment]
I don't see where they're appearing that they shouldn't  
If you mean at the start of the line, then that is normal in other editors. Though they perhaps should be a bit taller.

**Comment by VarLad** [comment]
@MinusGix They appear on every line, is the issue

**Comment by VarLad** [comment]
Fixed in https://github.com/lapce/lapce/pull/1862
