### ISSUE TITLE
Please add to the docs the VIM key bindings that are implemented.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [lapce/lapce#1678]
Hello,

Please consider adding to the docs the VIM key bindings that are implemented. 

This is very important for someone that is starting to use Lapse editor and is also starting to use VIM.

You could also ship Lapce with a VIM Tutor txt file for the VIM keys.

There are Open Source files that you could use.

Best regards,
João

**Comment by panekj** [comment]
Vim keybinds are available in settings
![image](https://user-images.githubusercontent.com/50457605/201124889-a19b0582-fd07-4c1a-9173-6d55e659557c.png)

**Comment by joaocarvalhoopen** [comment]
Ok I see it, and one can see that it's a VIM Mode Key if it is attributed to a mode, nice!

Best regards,
João
