### ISSUE TITLE
Please implement also horizontal window splits

### ISSUE THREAD

**Issue by joaocarvalhoopen** [lapce/lapce#1679]
Hello,

In many cases it's is beneficial to have also horizontal splits. 

What is the font that you use standard for the Linux, I'm on fedora and the font is small but very nice. Although it doesn't appear in the settings. 

On a FullHD Screen I could perfectly put 8 readable vertical splits with the small font that Lapse ships with. 

Best regards,
João

**Comment by panekj** [comment]
You can already make horizontal split by dragging the tab
![image](https://user-images.githubusercontent.com/50457605/201123984-52625aca-d5ee-4a16-a21a-9781ff9dfd6f.png)

**Comment by joaocarvalhoopen** [comment]
Thank you for explaining to me,
I didn't see that in the documentation, nor in a icon, nor in the command  palet, nor in a video about Lapce :-)

Best regards,
João
