### ISSUE TITLE
suggestion: Try to make the built in terminal little bit transparent

### ISSUE THREAD

**Issue by muzammil-85** [lapce/lapce#168]
Make the built in terminal little bit  transparent and make a option to change the background color of terminal (if multiple terminal use it help to identify the right one).

Thank you

**Comment by bugadani** [comment]
Thanks for your suggestion! How exactly would you imagine transparency here?

**Comment by muzammil-85** [comment]
It just need transparency option to adjust it.

**Comment by panekj** [comment]
Closing as it doesn't seem to suggest any proper features.
Console output can be cleared with `Ctrl`+`l`
