### ISSUE TITLE
The window maximize button doesn't work on some Linux OS

### ISSUE THREAD

**Issue by KanTakahiro** [lapce/lapce#1684]
## Lapce Version

At least form 0.2.0 to the latest 0.2.3

## System information

OS: LMDE 5
Kernel: 5.10.0-19-amd64
DE: Cinnamon 5.4.12

## Describe the bug

On LMDE5(with Cinnamon desktop environment), the window maximize button doesn't work. I clicked it but nothing happened. 

However the minimize button works well.

## Additional information

I saw [issue 1571](https://github.com/lapce/lapce/issues/1571), it seem that on KDE the window maximize works(but window is still able to be resized). I guess it may be a DE relevant issue.

I only have Cinnamon DE now, but if you need more information I will test more OS and DE.

**Comment by canadaduane** [comment]
I can confirm this is an issue on Gnome:

- Gnome 42
- Wayland
- Pop!_OS 22.04

Pressing the maximize button or double clicking the header bar (which usually has the same effect) does not maximize the window. Minimize works, as does the "restore" icon (what the "maximize" icon becomes once you toggle it).

**Comment by panekj** [comment]
Shouldn't be an issue after we switched to Floem

**Comment by canadaduane** [comment]
Confirmed that this is fixed in latest.
