### ISSUE TITLE
I think there is a bug in version 0.2.3 the theme colors don't change. 

### ISSUE THREAD

**Issue by joaocarvalhoopen** [lapce/lapce#1688]
Hello,

I have currently the DARK+ theme but I would like to change the the white color to a green one, but I cannot save what I edit in the settings, it simply doesn't change the color code that I modify.

Is that feature working correctly?

I use Linux Fedora with appimage.

Best regards,
João

**Comment by panekj** [comment]
Duplicate of #1596
