### ISSUE TITLE
download rust-plugin 

### ISSUE THREAD

**Issue by kotlin2018** [lapce/lapce#1694]
## Lapce Version
0.2.2

## System information
macOS Catalina 
10.15.7

## Describe the bug
There is no executable in the downloaded rust plugin

![image](https://user-images.githubusercontent.com/56008171/201450609-a1e69015-89a3-47d1-b444-22f62e16fa35.png)

**Comment by MinusGix** [comment]
If your network blocks the location Rust is downloaded from, then that can happen.  
What you can do is install Rust Analyzer for your system manually (using Cargo) then modify the Rust plugin's settings to the file-path of rust-analyzer.

**Comment by kotlin2018** [comment]
> If your network blocks the location Rust is downloaded from, then that can happen.
> What you can do is install Rust Analyzer for your system manually (using Cargo) then modify the Rust plugin's settings to the file-path of rust-analyzer.

Thank you very much for your help
