### ISSUE TITLE
Install plugin button not functioning

### ISSUE THREAD

**Issue by rootex-** [lapce/lapce#1699]
## Lapce Version
0.2.3

## System information
MacOS Monterey 12.6

## Describe the bug
"Install plugin" button not working for all plugins.
Unable to install plugins from the list of plugins. 
After pressing the "Install" button, nothing goes on. 
As the result, I am unable to see any of the plugins installed in the "Installed" section.

## Additional information
![Nov-13-2022 15-13-14](https://user-images.githubusercontent.com/8237030/201521269-99bca6c1-9d9d-4db8-94ec-7088edbdefc8.gif)

**Comment by panekj** [comment]
It probably doesn't work because connection to proxy failed (you can see that via red background in remote icon button)

**Comment by rootex-** [comment]
I should have "disconnected from remote ssh host". 
I actually thought that "Connect to SSH host" meant connection to a server via ssh, not a proxy. 
But how and why should it block plugin downloads?

**Comment by panekj** [comment]
> I actually thought that "Connect to SSH host" meant connection to a server via ssh, not a proxy.

It connects to lapce-proxy via SSH



> But how and why should it block plugin downloads?

Because it cannot install them in remote without a working connection

**Comment by panekj** [comment]
btw. your machine address is still visible in edits history

**Comment by rootex-** [comment]
Thank you, it's clear for now. 

> > I actually thought that "Connect to SSH host" meant connection to a server via ssh, not a proxy.
> 
> It connects to lapce-proxy via SSH
> 
> > But how and why should it block plugin downloads?
> 
> Because it cannot install them in remote without a working connection

**Comment by rootex-** [comment]
Thank you, it's clear for now

**Comment by rootex-** [comment]
@panekj thank you for the lightning fast responses 🎉
