### ISSUE TITLE
Feature request: implement ctrl+backspace to delete a entire word

### ISSUE THREAD

**Issue by SingingBush** [lapce/lapce#171]
I most editors holding ctrl while hitting backspace will allow deletion of whole words or a chunk of white space rather then just going back a single character.

**Comment by MinusGix** [comment]
This is by default bound to ctrl+w (which is an odd bound). I'll also note here that after I unbound the `delete_word_backward` (since I didn't want that keybind for that), it didn't seem to appear in the keybinding search.

**Comment by HoLLy-HaCKeR** [comment]
Other general keyboard navigation doesn't seem to be implemented either, such as ctrl+arrow keys, home/end, pageup/pagedn, etc. Which is a shame, because it makes the editor a lot less usable.

**Comment by MinusGix** [comment]
Those are *implemented*, but just aren't bound to keys. It would be good if they were added to the default keybindings, though.
