### ISSUE TITLE
Updating theme does not download new volt.toml

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#1721]
## Lapce Version

0.2.4

## System information

Linux

## Describe the bug
Updating a theme seems to not download the new volt.toml file. This causes the 'Update' notification to remain, as the version on the plugin-repository is still ''newer'' than the local version.  Uninstall and reinstalling (thus forcing volt.toml to be redownloaded) fixed the issue.  
  
(Does this affect all plugins, or just themes?)

**Comment by panekj** [comment]
@MinusGix is that still occurring?

**Comment by MinusGix** [comment]
Nope.
