### ISSUE TITLE
lapce: 2: Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by rodkrtz** [lapce/lapce#1725]
## Lapce Version

v0.2.4

## System information

Zorin OS v16.2

## Describe the bug
Message `lapce: 2: Syntax error: Unterminated quoted string` appears on console after running lapce. I build it from source.

**Comment by panekj** [comment]
this is a problem with your os and/or shell

**Comment by rodkrtz** [comment]
You're right! Tried on a fresh ubuntu vm and it worked.
My apologies.
