### ISSUE TITLE
Line numbers in modal mode are wrong

### ISSUE THREAD

**Issue by onichandame** [lapce/lapce#1728]
## Lapce Version

0.2.4

## System information

Windows 10 21H2

## Describe the bug
The line numbers above and below the cursor in modal mode is wrong.

## Additional information

![image](https://user-images.githubusercontent.com/23728505/202901089-f61eec04-2cc7-49a8-8c29-04c55b56ef40.png)

**Comment by Gerrit0** [comment]
This is expected - "Modal Mode Relative Line Numbers" is on by default.

![image](https://user-images.githubusercontent.com/19329837/202924128-a32b4f8e-04a9-421a-95f0-8e7794fc3b3c.png)

**Comment by onichandame** [comment]
oh my bad. I didn't know about this setting.
