### ISSUE TITLE
Feature request: implement multi-line editing (multi-caret)

### ISSUE THREAD

**Issue by SingingBush** [lapce/lapce#173]
I often use multi line edits to get things done. Some of the ways this is done in other editors:

VS Code (Windows): Hold <kbd>Ctrl</kbd> + <kbd>Alt</kbd> then press <kbd>Up or Down</kbd>
VS Code (Linux): Hold <kbd>Ctrl</kbd> + <kbd>Shift</kbd> then press <kbd>Up or Down</kbd>
Intellij: Double tap <kbd>Ctrl</kbd> then press <kbd>Up or Down</kbd>

With <kbd>Esc</kbd> to return to a single caret.

(no idea why VS Code behaves differently for me between Windows and Linux)

Getting multiple carets is often also possible with a mouse via alt+click or some other approach. 

I personally like either of the VS Code approaches.

**Comment by MinusGix** [comment]
Lapce already supports this through ctrl  + alt and arrow keys. It also works with alt-click.  
Though, it does not use ctrl-shift on Linux.  
Escape, however, does not return to a single caret at the moment.

**Comment by bugadani** [comment]
Escape does return into single caret mode, at least for me. The difference compared to VS Code is, that VS Code keeps the oldest cursor, while Lapce keeps the newest.

**Comment by panekj** [comment]
The requested feature has been implemented
