### ISSUE TITLE
Add syntax highlighting for HAML.

### ISSUE THREAD

**Issue by expeehaa** [lapce/lapce#1730]
## Is your feature request related to a problem? Please describe.

HAML is a markup language commonly used as a replacement for ERB in Ruby on Rails projects. To make editing `.haml` files easier, I would like to have syntax highlighting.

## Describe the solution you'd like

Implement HAML syntax highlighting in Lapce.

## Describe alternatives you've considered

* Write a plugin that adds support.

## Additional context

For the Atom editor, this is realised by a plugin: https://github.com/HarlemSquirrel/language-haml
I have not looked into how easily this can be adapted, but I suppose it could at least be a starting point. I'ld be interested in implementing this myself.

**Comment by panekj** [comment]
There doesn't seem to be any tree-sitter grammar for haml and we track syntax highlighting support in #272
