### ISSUE TITLE
Language-wise setting for indents

### ISSUE THREAD

**Issue by 1upkd** [lapce/lapce#1747]
## Is your feature request related to a problem? Please describe.

I code in multiple languages and use different indent levels for each one, e.g.: 4 for Python, 2 for HTML

## Describe the solution you'd like

Suggestions:
1. Language-wise setting for indents
2. If the first 2-3 lines of the file follow a particular indenting pattern (say 2 spaces), the editor could recognize that and use it for the rest of the file. This can override the default setting.

## Describe alternatives you've considered

None

## Additional context

None

**Comment by panekj** [comment]
> 2\. If the first 2-3 lines of the file follow a particular indenting pattern (say 2 spaces), the editor could recognize that and use it for the rest of the file. This can override the default setting.

That's how it works currently

**Comment by 1upkd** [comment]
@panekj It's not working with HTML for me. I've set the default in the settings as 4, and am trying with 2 spaces in HTML.

**Comment by 1upkd** [comment]
Will close the issue because my problem seems to be solved with the latest update.
