### ISSUE TITLE
Use current file path or workspace path when showing file dialog

### ISSUE THREAD

**Issue by marcusbritanicus** [lapce/lapce#1754]
## Is your feature request related to a problem? Please describe.

When we try to load a file when using a file dialog (open/save), it always starts with home path.

## Describe the solution you'd like

The path which the file dialog should start with should be chosen suitably, instead of always showing the home directory.
### When opening a file
1. When opening a file, check if a file is open. If yes, use the path of that file.
2. In case there is no file open, use the current workspace path.
3. In case no workspace is open, use the last used path.
4. If all the above cases fail, use home directory.

### When saving a file,
1. Use the current workspace path.
2. If no workspace is open, use the path of the file in the previous tab.
3. If there is no other tab other than the current one, use the last used path.
4. If all the above cases fail, use home directory.

It would be quite beneficial if such a mechanism was extended to new workspace dialog (open folder) as well.

**Comment by panekj** [comment]
This should be fixed
