### ISSUE TITLE
Lapce panicks when it tries to load syntax highlighting info for .sh files

### ISSUE THREAD

**Issue by TudbuT** [lapce/lapce#1762]
## Lapce Version

![image](https://user-images.githubusercontent.com/48156391/204592137-121917ba-2995-4b08-aa58-291d7f13db94.png) 
(6e4a472)

## System information

Arch Linux

## Describe the bug
Lapce panicks when it tries to load syntax highlighting for .sh files. 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError { row: 52, column: 3, offset: 702, message: "expansion_flags", kind: NodeType }': lapce-core/src/language.rs:974

## Additional information

I honestly have no idea why this is happeningm, but the original Err happens in the constructor of HighlightConfiguration or Query

**Comment by simoniz0r** [comment]
I am getting a similar error with version 0.4.0 running on openSUSE Tumbleweed using the pre-compiled tar from the releases page:

```
 syretia  ~  lapce -V
Lapce v0.4.0
 syretia  ~  lapce -w
2024-04-30T05:50:30.722961Z ERROR lapce_core::language: Encountered QueryError { row: 48, column: 3, offset: 520, message: "expansion_flags", kind: NodeType } while trying to construct HighlightConfiguration for Bash
```

Additionally, syntax highlighting doesn't seem to do anything for shell scripts; they display the same as a plain text file would.

Sorry if I should have opened a new issue for this.
