### ISSUE TITLE
Not warning about the lack of rust-analyzer

### ISSUE THREAD

**Issue by Seven0492** [lapce/lapce#1763]
## Lapce Version

0.2.4

## System information

Arch Linux kernel version: 5.15.80-1-lts

## Describe the bug

Autosuggestion not working when dealing with some crates (In Rust)

Syntax highlighting just not showing in some cases 

The problem?

I fixed it, it was that rust-analyzer was not installed.

The problem with that?

I only found out when I was trying to switch to Helix,
and had to install rust-analyzer via rustup and do a symlink to a directory in PATH from the analyzer binary.

What I suggest?

Adding a prompt warning about the lack of rust-analyzer like other mainstream IDE's instead of just being silently faulty.

Or even installing it automatically.

I had no idea what was wrong with the Rust plugin, I thought the 'sub-par' (Used lightly) performance of its highlighting was 'normal', until I added the missing part by accident and made it work like a champ!

I can now use Lapce without reservation and have had a fantastic experience so far, keep it up!
This is a wonderful project that was badly needed.

I just want other people coming to Lapce for a good Rust environment not be discouraged by its problem when it lacks rust-analyzer.

Sorry if this wasn't the place to report this, as Rust support is a plugin, after all.
Maybe this should have been a feature request, but I thought it more apt as a bug.
Since this is something that should be made aware to the user.

**Comment by TudbuT** [comment]
[lapce/lapce-rust](https://github.com/lapce/lapce-rust) would be the right place to put this issue, i think

**Comment by Seven0492** [comment]
Thanks, will do that and post another issue I had found

**Comment by Seven0492** [comment]
I will close this issue since the issue has been cloned to the relevant Rust plugin repo
