### ISSUE TITLE
cannot install on chromebook

### ISSUE THREAD

**Issue by uciharis** [lapce/lapce#1789]
## Describe the bug
i was succesfully installed lapce from snapcraft website .
the command is : sudo snap install lapce

after that, i ran that apps from terminal by typing lapce
the app didnt open but there was a log here : 

" thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /root/.cargo/git/checkouts/winit-58efae9df3f5264a/59eb01c/src/platform_impl/linux/mod.rs:626:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

**Comment by uciharis** [comment]
but i could ran lapce well from extracted downloaded file at your official website

**Comment by panekj** [comment]
Snapcraft package is outdated and it wasn't owned by us for a long time

**Comment by uciharis** [comment]
thank you sir
