### ISSUE TITLE
Lapce crashing when deleting all chars from a file.

### ISSUE THREAD

**Issue by eribol** [lapce/lapce#1790]
## Lapce Version

0.2.4 

## System information

Manjaro Linux

## Describe the bug
No mather what, when i remove all codes from a file, lapce just crashing.

**Comment by MinusGix** [comment]
Do you still experience this in 0.2.5?

**Comment by hbina** [comment]
What do you mean by deleting all chars from a file? Like deleting all the texts in any file?

**Comment by panekj** [comment]
Would be good to attach log with backtrace

**Comment by eribol** [comment]
I am sorry, my pc was broken for 2 weeks, i could not use it but i tried now and it still crashing. I started it in terminal but it does not logging.
