### ISSUE TITLE
memory leaks 

### ISSUE THREAD

**Issue by humgal** [lapce/lapce#1793]
## Lapce Version

v0.2.4

## System information

macOS 13.0.1 (22A400)

## Describe the bug
first I open lapce and open none folder,memory use 219.7MB,
and close the window and open the empty window again, memory use 374MB.
when I repeat this action ,memory also increase about 90-100MB.
and when I repeat this action about twenty times,memory increase to 2.4GB.

this muse be a memory bug.so you term use rust lang, but also has memory leaks.
or you term just use macOS api to open window but not reclaim.
please check you code ,you term must understand why you are not reclaim window resources.

so if  I run a script to open and close lapce window hundreds of times(not quite lapce) ,
I can let computer memory full about A few seconds.
this will happens.

## Additional information
<img width="624" alt="image" src="https://user-images.githubusercontent.com/26360626/206602866-cf2980de-a593-43b9-ac50-560ce6c037fa.png">
<img width="620" alt="image" src="https://user-images.githubusercontent.com/26360626/206602950-cda01d1c-4c68-454c-a47b-141e64a270a1.png">

this is my computer screenshots when lapce open none folder with only one window.

**Comment by hbina** [comment]
Does this still happen? i cannot reproduce this in master in Windows.

**Comment by humgal** [comment]
It’s still happen in macOS. I want to join you team to fix some bugs,I driect push my code ,is that ok?

On Jan 19, 2023, at 09:07, Hanif Ariffin ***@***.***> wrote:



Does this still happen? i cannot reproduce this in master in Windows.
