### ISSUE TITLE
Error building dmg target on M1 Mac

### ISSUE THREAD

**Issue by MstMoonshine** [lapce/lapce#18]
`make` error:
```
Finished release [optimized] target(s) in 1.05s
Created 'Lapce.app' in 'target/release/macos'
xattr -c target/release/macos/Lapce.app/Contents/Info.plist
xattr -c target/release/macos/Lapce.app/Contents/Resources/lapce.icns
/usr/bin/codesign -vvv --deep --strict --options=runtime --force -s FAC8FBEA99169DC1980731029648F110628D6A32 target/release/macos/Lapce.app
FAC8FBEA99169DC1980731029648F110628D6A32: no identity found
make: *** [Lapce.app-native] Error 1
```

System Info: M1 MacBook Air, macOS Monterey v12.0.1.

(`cargo build --release` works well. It is the dmg building part that failed.)

**Comment by dzhou121** [comment]
The makefile is for github actions. 

If you remove the lines that starts with ```/usr/bin/codesign```, it should work.

**Comment by MstMoonshine** [comment]
Thanks! I have just worked around the issue.

Solution:
1. run `security find-identity`
2. copy the identity to replace the hard-coded identity in the Makefile (4 places)
3. `make` again.
