### ISSUE TITLE
Can't debug application (development)

### ISSUE THREAD

**Issue by FancyBanana** [lapce/lapce#1804]
## Lapce Version

Git main trunk version

## System information
Ubuntu 22.04

## Describe the bug
When trying to debug the application the debugger stops as if the application had closed, but the Lapce window remains visible.
## Additional information

Development environment: Ubuntu 22.04, vscode, rust-analyzed extension. CodeLLDB extension.   
I've started the debugging session with a breakpoint on `app::launch()`, and it followed just until the 
> small hack to unblock terminal if launched from it

section, after which the application returned (exited).

**Comment by panekj** [comment]
I don't see how that's a lapce issue

**Comment by FancyBanana** [comment]
Well it's definetly a Lapce issue because I am trying to debug Lapce, but it's the 'editor' bug.

**Comment by TudbuT** [comment]
try using the -w command line argument, it won't detach that way.

**Comment by FancyBanana** [comment]
With the `-w` the application does not detach.
