### ISSUE TITLE
About menu pointer bug on windows

### ISSUE THREAD

**Issue by HJX-001** [lapce/lapce#1806]
## System information
Windows 10 64bit

## Describe the bug
When clicking 'About Lapce' in Settings, Hand pointer stays even after moving from button, becomes arrow pointer only after moving pointer out of lapce.

## Additional information
In Lapce UI

**Comment by hbina** [comment]
Hmmm I think I fixed this issue before here https://github.com/lapce/lapce/pull/1565

**Comment by hbina** [comment]
Here's some discovery. There seems to be a bug with the default cursor when opening the modal for the second time. Make the following changes:

```
hbina@akarin ~/g/lapce (master)> git diff
diff --git a/lapce-ui/src/about.rs b/lapce-ui/src/about.rs
index ed576956..d76a114b 100644
--- a/lapce-ui/src/about.rs
+++ b/lapce-ui/src/about.rs
@@ -192,7 +192,7 @@ fn event(
                 if self.icon_hit_test(mouse_event) {
                     ctx.set_cursor(&druid::Cursor::Pointer);
                 } else {
-                    ctx.clear_cursor();
+                    ctx.set_cursor(&druid::Cursor::NotAllowed);
                 }
                 ctx.set_handled();
             }
```

And observe this issue https://youtu.be/_eL8c3qpe48. Notice that one the second opening of the modal, the cursor is set to Pointer while its hovering outside the modal.
