### ISSUE TITLE
Matching search substrings and SSH icon foreground colors same as background's

### ISSUE THREAD

**Issue by ayhon** [lapce/lapce#1819]
## Lapce Version

Version 0.2.5

## System information

Fedora Workstation 37

## Describe the bug

I'm trying to build a theme, but I'm having trouble fixing a couple of visual bugs. 
 1. When using the command palette, the substring from the query that a result matches is colored like the background, so it makes it hard to see what's written. This color doesn't seem to be addressable from the `THEME.toml` file, or at least I wasn't able to find such an option in `defaults/dark-theme.toml`
 2. The "Connect with SSH" logo seems to also be colored like the background, which makes it impossible to see.

After asking in the Discord, I was told to file it as a bug

<details>
<summary>
Images
</summary>
<img src='https://user-images.githubusercontent.com/43295942/208243484-65bf8d14-e2b3-44c8-971b-6cac795d8094.png'/>
<img src='https://user-images.githubusercontent.com/43295942/208243494-a7da31f8-507c-4f34-8add-ecef0e6b8d5d.png'/>
</details>
## Additional information

I assume some kind of value is being read incorrectly, and defaults are being used instead. I don't know how to change this, since this doesn't seem to be a problem other color themes are facing.

The TOML files are:
 - Light variant: https://gist.github.com/ayhon/f8fe1aeebb67a2f4d1c6c08a4a52f90a
 - Dark variant: https://gist.github.com/ayhon/12ae7fe1ca04c3c183874d31a923d7ae

**Comment by ayhon** [comment]
This is no bug, solved both issues
 1. Solved by tweaking `editor.focus`
 2. Solved by tweaking `lapce.remote.local`, which fills the background.

**Comment by panekj** [comment]
This will be fixed via #1820
