### ISSUE TITLE
Some characters (such as ⏺ U+23FA) make the line invisible

### ISSUE THREAD

**Issue by shoebe** [lapce/lapce#1849]
## Lapce Version

0.2.5

## System information

Artix Linux (wayland, KDE)

## Describe the bug
Some characters (such as ⏺ U+23FA) make the line invisible

## Additional information

See line 702
with `cat -n`
![image](https://user-images.githubusercontent.com/59572972/208757166-5e3380c1-dec4-4ae4-b9dd-4ff430689e59.png)
with lapce
![image](https://user-images.githubusercontent.com/59572972/208757318-221812ef-7cb6-48da-9ef1-004149020173.png)

**Comment by LuckyTurtleDev** [comment]
I notify similar behaviors with emojis, if no fonts for this emojis is installed. If I install an emoji font everything lines with emojis work fine again.

**Comment by shoebe** [comment]
Seems to be fixed now
