### ISSUE TITLE
Confusion between uppercase and lowercase keyboard modifiers

### ISSUE THREAD

**Issue by rbran** [lapce/lapce#185]
Some keymaps don't work out of the box on Arch Linux. Such the `goto_definition` with keymap `ctrl+n`.

To fix this problem I had to add the following config:
```
# Remove the invalid key
[[keymaps]]
command = "-goto_definition"
mode = "n"
key = "Ctrl+n"

[[keymaps]]
command = "goto_definition"
mode = "n"
key = "ctrl+n"
```

I think this happen because lapce compare `Ctrl` and `ctrl` case-sensitive in some place.

**Comment by bugadani** [comment]
Your "Ctrl+n" command is `command = "-goto_definition"` (note the extra -). Is this intentional?

**Comment by rbran** [comment]
@bugadani Yes, the first one remove the uppercase `Ctrl` , with is invalid.

**Comment by bugadani** [comment]
Thanks! So far, I didn't see anything obviously wrong with the code but I'll keep checking. Keypress parts are converted to lowercase strings internally, so I'm not sure if this is the issue. What happens if you unbind and re-bind the same key combination, with capical `C`?

**Comment by rbran** [comment]
It works. The config seems to be case insensitive, and doesn't matter the Ctrl upper or lower case.

But if you only add
```
[[keymaps]]
command = "goto_definition"
mode = "n"
key = "Ctrl+n"
```
The `settings` window will show the config as duplicated.
