### ISSUE TITLE
Can not open the editor.

### ISSUE THREAD

**Issue by goldwind-ting** [lapce/lapce#1860]
## Lapce Version
v0.2.5

## System information

Windows 11 Pro, 22H2

## Describe the bug
Can not open editor, and getting:
![screen](https://user-images.githubusercontent.com/63939636/209467314-f3bbec85-7063-48b6-bfab-65360af794a2.png)

**Comment by panekj** [comment]
You need to install Visual C++ Redistributable

**Comment by goldwind-ting** [comment]
> You need to install Visual C++ Redistributable

Okay, will check.
