### ISSUE TITLE
Ocaml is listed twice in the "Set file syntax" dropdown

### ISSUE THREAD

**Issue by datawater** [lapce/lapce#1861]
## Lapce Version

0.2.5

## System information

Windows 10 x86_64

## Describe the bug

Ocaml is listed twice in the language syntax dropdown

## Additional information

![image](https://user-images.githubusercontent.com/86855332/209470356-bd341b56-2d58-4867-9e6b-2fafa3fa7447.png)

**Comment by panekj** [comment]
This is fixed now
