### ISSUE TITLE
Lapce on KDE Wayland has both server side decorations and client side decorations

### ISSUE THREAD

**Issue by ColonelPhantom** [lapce/lapce#1864]
## Lapce Version

Lapce 0.2.5

## System information

Fedora 37 + KDE Plasma 5.26.4 on Wayland

## Describe the bug
I see both the titlebar from KDE and Lapce's built in titlebar. KDE's top bar should be hidden, similarly to VSCode in "custom" window decoration mode or any GTK3 headerbar-based software. Alternatively, making Lapce's top bar not have the window buttons would also be usable.

## Additional information
![Screenshot_20221226_152657](https://user-images.githubusercontent.com/7569492/209558823-4c3949b0-a1c5-4047-83d5-ca0b567c2f7e.png)

**Comment by panekj** [comment]
You can disable our window management in settings via Custom titlebar option

**Comment by ColonelPhantom** [comment]
I see, thanks! Might still be nice to leave this issue open to get CSD working properly, though.

KDE also does not pick up the program icon, but that's maybe because all I did is drop the binary in `~/.local/bin`, so there's no .desktop file it can get the proper icon from.

**Comment by panekj** [comment]
> KDE also does not pick up the program icon, but that's maybe because all I did is drop the binary in `~/.local/bin`, so there's no .desktop file it can get the proper icon from.

That is up to your distribution package maintainer to deal with.

**Comment by ColonelPhantom** [comment]
For anyone else who runs into this: it's possible to set a window rule in Plasma that hides the titlebar for Lapce. While this issue should still be fixed at some point, it makes the CSD at least usable.

**Comment by stalkerg** [comment]
As I understand, to solve it, lapce should be ported to GTK4, which supports Wayland CSD/SSD protocol switch.

**Comment by sombriks** [comment]
so this is why vscode can hide kde window bar but not lapce? a gtk thing?

**Comment by ColonelPhantom** [comment]
The current nightly version uses winit and does not have this issue anymore.
