### ISSUE TITLE
Lapce.exe - System error

### ISSUE THREAD

**Issue by seokkuuu** [lapce/lapce#1869]
## Lapce Version

0.2.5

## System information

Windows 10 64 bit
CPU: Pentium (r) Dual Core 2.6GHz
GPU: Nvidia GeForce 9800 1GB
RAM: 4GB

## Describe the bug
"The code execution cannot continue because VCRUNTIME1.40_1.dll was not found. This problem may solve reinstalling the program."

## Additional information

I have a clear installation of Lapce, when It was installed, I tried to open and it shows me this error.

- screenshots

![image](https://user-images.githubusercontent.com/114446163/209737746-4407ae1b-db54-43cc-8b61-4b7e8b14bccb.png)

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/1860
