### ISSUE TITLE
`go to definition` command opens an empty `mod.rs`

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#187]
Title says all, the command just does not work for me. The `Rust` plugin is installed.

**Comment by MinusGix** [comment]
Does it still not work?

**Comment by bugadani** [comment]
Go to definition is not working for me on master. In the video below, all I'm doing is pressing F12, and letting the recording go long enough to show that it's not just slow loading.

https://user-images.githubusercontent.com/977627/159878903-5d147207-50a7-40cd-9855-8dc29a459478.mp4

**Comment by bugadani** [comment]
I suspect this has something to do with the command opening a new tab, and the copy-on-write nature of Lapce. But I haven't even tried to debug this yet.

**Comment by MinusGix** [comment]
There might also be weirdness because it is opening the same file in a new tab. Though, I've had lapce do that without any issue.

**Comment by bugadani** [comment]
Some progress on this front: Somewhere, some piece of code creates a path that starts with `/`, which makes it relative. Problem is, those paths look like `/c:/...`. This makes `url` bail out and crash the proxy thread.
