### ISSUE TITLE
Method for choosing syntax coloring of a file (.txt files do not render with CMake syntax color)

### ISSUE THREAD

**Issue by sdbbs** [lapce/lapce#1873]
## Lapce Version

0.2.5

## System information

Microsoft Windows 10, Build 19045

## Describe the bug

I was not sure whether to file this as a bug, or as feature request, however:

I have seen there is CMake syntax coloring support: https://github.com/lapce/lapce/pull/1767 - that page shows the syntax color working, but with a `temp.cmake` file.

So I opened my `CMakeListst.txt` file - and there is no syntax color.

## Additional information

My guess is, this happens because the syntax color is decided strictly from the file extension.

Since one could have all kinds of content in `.txt` files, it will be impossible to enumerate all such uses (in order to have automatic handling via file extension) -- so, I would suggest the approach the Scite ( https://www.scintilla.org/SciTE.html ) text editor has: there is a "Language" menu item, that lists all of the supported syntax color languages; then, if you open say a `.c.` file, by default the syntax color applied is "C / C++" - however, you can then click "Language" and choose any other language; so if you want, you can display a `.c` file with syntax coloring for Python, if you choose so (even if that example has a limited utility).

Anyways, if there was such a feature, then I would not have to bother developers to include handling of say `.txt` file as a CMake file - I could just simply open the file, then choose "Language"/"Cmake" - and then the CMakeLists.txt would have been displayed with CMake syntax color, even though it has `.txt` extension.

**Comment by sdbbs** [comment]
Oh, there is a method for this, though a bit unobvious for me:

* Click the Settings cogwheel icon upper right of the Lapce window / titlebar
* Click "Command Palette"
* Find and click on "Change current file language"
* You will get a bunch of options - just find CMake and click it

There, it works! 

So, this works, and can be closed, but I'm leaving it open until devs close it just for exposure (as I was not able to find how to do this in my searches before I posted this)

**Comment by panekj** [comment]
> * Click the Settings cogwheel icon upper right of the Lapce window / titlebar

This is unnecessary

> * Click "Command Palette"
> * Find and click on "Change current file language"

That or you can just click bottom right corner where it says `Plain text`

**Comment by MinusGix** [comment]
> So, this works, and can be closed, but I'm leaving it open until devs close it just for exposure (as I was not able to find how to do this in my searches before I posted this)

I think it would be useful to autohighlight a very common file like `CMakeLists.txt`, so I'll leave this issue open for tracking that.

**Comment by Stanislav-Lapata** [comment]
I think Lapce has similar problem in ruby projects that has `Gemfile` file. I also know `Jenkinsfile` that need for Jenkins CI/CD.

**Comment by panekj** [comment]
That's because we match only on file extensions, but it will be fixed soon

**Comment by AlexisTM** [comment]
I was looking exactly at this, trying to use `extensions: &["cmake", "cmakelists.txt", "cmake.in"],`, but this only works without points
