### ISSUE TITLE
Folder picker ergonomics are bad

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [lapce/lapce#188]
Trying out Lapce for the first time, I noticed a few issues with the folder picker. As it's the first thing a new user uses, it may be worth it trying to improve its UX.

1. **The text input is case sensitive on Windows, which has case insensitive paths.** This means that `d:/projects` does not show anything if your projects folder is `d:/Projects`.
2. **Selected text does not show as selected**. [Here is a small clip](https://streamable.com/m544lz) that shows me selecting text using the shift key and overwriting it by typing
3. **Arrow keys cannot be used to select folders.** The mouse can be used to open/collapse folders, but I would prefer to use arrow keys. It seems that the text input is always selected to this isn't possible.
4. **Any invalid folder name will show an empty folder list.** Ideally, it would show the current folder, similar to [VS Code's behavior](https://streamable.com/ekfvs3).
5. **Lacking keyboard controls in any textbox.** See issue #178.

**Comment by bugadani** [comment]
https://github.com/lapce/lapce/commit/0251db8011face45ce57dc5122486778d2e3cb17 changed the open folder dialog to use the OS's native dialog.

**Comment by HoLLy-HaCKeR** [comment]
That's a shame, a custom color picker like the one in VS Code would be really nice.
