### ISSUE TITLE
Lapce v0.0.2 installation failure on Windows 10

### ISSUE THREAD

**Issue by Chaz6** [lapce/lapce#19]
When trying to install Laplace v0.0.2 on Windows 10, the following error is displayed:-

![image](https://user-images.githubusercontent.com/12680/146007056-4928c152-5f61-4067-8406-da1c10546e67.png)

```
---------------------------
lapce.exe - System Error
---------------------------
The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

**Comment by Chaz6** [comment]
Sorry, I meant when running, not installing.

**Comment by Jack-Works** [comment]
https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

Download it from this address

**Comment by Chaz6** [comment]
Thank you!

**Comment by RoyiAvital** [comment]
Could it be supplied with the portable version?
