### ISSUE TITLE
Introduce a better way to define the UI

### ISSUE THREAD

**Issue by x70b1** [lapce/lapce#1909]
## Is your feature request related to a problem? Please describe.

A common question is how to customize the UI to your own needs. Sometimes some options already exist such as `show-bread-crumbs`.

## Describe the solution you'd like

I have thought of templating for the UI.
Each element can be placed in a desired position or hidden. Additionally, a set of options can be defined for each element:

- Background
- Font
- Height
- Width
- ...

Maybe it's not the best idea. But I think offering config options for everything is also rather not a good idea as it fragments the configuration and there is little consistency.

## Additional context

What is the background of my idea?

vscode does not have a very comfortable interface. Happily, there is a plugin that allows extensive customization [customize-ui](https://github.com/iocave/customize-ui). Microsoft broke it. And it seems like they dont want to rollback the change. There are many PRs for the customizations to support them natively but they have not been worked on for several years now. The extension was installed over 140.000 times. The disappointment is huge: https://github.com/iocave/customize-ui/issues/156

Don't be like Microsoft. Give the user the possibilities from the beginning.

**Comment by panekj** [comment]
What is currently not possible what you listed?

**Comment by x70b1** [comment]
Line height works for editor, but not for UI.
I would also like to hide the titlebar.

But to be honest: That is not my point here. 

I followed the discussion at vscode and customize-ui and I have seen the big interesst in personal customization and the fact that its to much to define it in a traditional config file.

As lapce is very young with a great community I just wanted to share this observation.

**Comment by panekj** [comment]
Most of the list issues are already opened for tracking or fixed
