### ISSUE TITLE
Spaces in path break definition lookup

### ISSUE THREAD

**Issue by SkaneroOo** [lapce/lapce#1910]
## Lapce Version

0.2.5

## System information

Windows 11

## Describe the bug
If path to file containing definition contains spaces, lapce replaces them with %20 and tries to open file in location, that doesn't exist

## Additional information

While trying to access definition of EntityPosition struct, instead of moving cursor few lines higher, lapce opened new tab with file, that doesn't exist. Original file path is in terminal, opened path is at the top of right tab. 
When I've removed space in directory name, everything worked fine.

![Screenshot (5)](https://user-images.githubusercontent.com/40175161/210282856-8f07dfad-f7ba-43aa-8ee8-0c60d0ed2537.png)

**Comment by TheIronBorn** [comment]
Is anyone else working on this? I think I could manage this if not. I welcome any tips though

**Comment by panekj** [comment]
Fixed via f2355aa0b8839aacc5fa684db2c8b75b5258e251
