### ISSUE TITLE
Somehow untag nightly as being a 'release' on github?

### ISSUE THREAD

**Issue by jgarvin** [lapce/lapce#1914]
Usually when I want to be notified of how a project is progress without getting spammed too much. I set the "Releases only" watch option. However, lapce appears to have a nightly release every day which defeats the point :P I do like getting notified when real releases happen, and I don't see how anybody could be getting any information from a notification that happens at the same time everyday, so wondering if this is just a box that could be unchecked somewhere?

**Comment by MinusGix** [comment]
Based on  
- https://github.com/community/community/discussions/10776
- https://github.com/orgs/community/discussions/4993
- https://github.com/community/community/discussions/29192
It doesn't seem to be possible to just ignore pre-releases, even with custom notification settings (though, *if it was implemented*, it should preferably be configurable on the repo side too, to avoid requiring every watcher to manually untick pre-releases).  
So, unfortunately, this seems to be blocked on github doing something about it.

**Comment by MinusGix** [comment]
Hm, actually a hacky method would be to watch https://github.com/flathub/dev.lapce.lapce PRs since they only update for the full releases and not the nightlys (you'll get some minor noise, but obviously far less than the nightlys cause).

**Comment by jgarvin** [comment]
Thanks, I'll give that a try!
