### ISSUE TITLE
Ansible langage server support

### ISSUE THREAD

**Issue by yodatak** [lapce/lapce#1926]
## Is your feature request related to a problem? Please describe.

Hi i want to migrate to vscode to lapce but the lack of yaml language server and Ansible support i cannot migrate on it

## Describe the solution you'd like

Make the language server installation easy and support ansible language server and maybe yaml

**Comment by panekj** [comment]
Ansible language support should be done via plugin.

**Comment by lxwulf** [comment]
Is there any new information to that plugin? I have the same thoughts and situation as @yodatak. I know that Ansible has already its own [LSP server,](https://github.com/ansible/ansible-language-server) could this not be integrated?

**Comment by panekj** [comment]
> I know that Ansible has already its own [LSP server,](https://github.com/ansible/ansible-language-server) could this not be integrated?

That integration would be done via plugin and unless someone makes one, there is no information.

**Comment by lxwulf** [comment]
Okay, thanks for the answer. I hope someone can do this, unfortunately I am not able to help at the moment because I lack the knowledge to do so, except testing it at the end.

Nonetheless, I look further to this project, I really like it though.

Greets LxWulf :penguin: :wolf:
