### ISSUE TITLE
Failed "Go to definition" breaks file reading

### ISSUE THREAD

**Issue by ponei** [lapce/lapce#1942]
## Lapce Version

Latest (0.2.5) 08/01/2023

## System information

Windows 10 22H2 (Build 19045.2364)

## Describe the bug
Clicking "Go to definition" sometimes fails, making it show a file with a blank name & content.
This behaviour snowballs into the whole application and breaks any file manager read.

## Additional information

Using the TS/JS server in a medium sized project.

https://user-images.githubusercontent.com/28790957/211215796-b4e8763b-e86d-451f-bde9-78b823acfa3f.mp4

```
[2023-01-08][16:41:41][panic][ERROR] thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()': lapce-proxy\src\plugin\mod.rs:909
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: git_filter_source_repo
   4: git_filter_source_repo
   5: git_filter_source_repo
   6: git_filter_source_repo
   7: git_filter_source_repo
   8: tree_sitter_bash
   9: tree_sitter_bash
  10: git_filter_source_repo
  11: git_filter_source_repo
  12: git_filter_source_repo
  13: git_filter_source_repo
  14: BaseThreadInitThunk
  15: RtlUserThreadStart
```

**Comment by Pczinho** [comment]
Could you pass your discord? I wanted to talk to you
