### ISSUE TITLE
Rename symbol in right click menu

### ISSUE THREAD

**Issue by ArniDagur** [lapce/lapce#1949]
Currently, you can rename a symbol using the `F2` keybinding. However, I want to be able to right click a symbol to rename it.

I briefly looked into implementing this myself. I see that there is a `Rename` member inside of `FocusCommand`. However, I don't know why it is not displayed when I right click, as "Go to Type Definition" is.

**Comment by tk103331** [comment]
try add MenuItem like this:

https://github.com/lapce/lapce/blob/242fa766d0904f8048845ad3284a8514404d5bb8/lapce-ui/src/editor.rs#L310-L320
