### ISSUE TITLE
Arrow keys don't recall command history in terminal on windows

### ISSUE THREAD

**Issue by VectorStrike** [lapce/lapce#195]
Pressing any of the arrow keys has no effect, the up arrow doesn't recall the last command and the left and right arrows don't move the cursor.

**Comment by Kyllingene** [comment]
I am unable to even move my cursor along the current line in the terminal, so it would seem that arrow keystrokes aren't being sent to the shell.

**Comment by MinusGix** [comment]
I'll note that this is a more general issue and also does not work on Linux.
