### ISSUE TITLE
circumflex character doesn't not appear

### ISSUE THREAD

**Issue by Cyrix126** [lapce/lapce#1957]
## Lapce Version

0.2.5

## System information

Artix Linux
AZERTY keyboard layout

## Describe the bug
the character circumflex "^" does not appear when I press the key. 
Only a white space appear. 

## Additional information
I can copy/paste the character from another application.
If I try to use the circumflex key in a keyboard shortcut, It shows "DEAD".

**Comment by panekj** [comment]
Duplicate of #1094
