### ISSUE TITLE
Creating a new file with the same path as an already opened file displays the content for the opened file

### ISSUE THREAD

**Issue by ajbdev** [lapce/lapce#1959]
## Lapce Version

nightly-a49e354

## System information

Macbook Pro M1 (2021)
macOS 13.1 (22C65)

## Describe the bug
1) Open a file in a subfolder of the opened folder
2) Rename that folder to something else
3) Create a new folder with the same name as the original folder name from step 2
4) Create a new file with the same name as the file you opened in step 1

Observed behavior:  The new file contains the code as the file opened in step 1
Expected behavior:  File is blank

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/1559
