### ISSUE TITLE
Identation only works in one direction, Cutting does not work

### ISSUE THREAD

**Issue by L3P3** [lapce/lapce#1961]
## Lapce Version

0.2.5

## System information

Debian testing, German

## Describe the bug

When I select text and press TAB, the selection is moved to the right by adding tabs to the begin of lines.
When I select text and press SHIFT+TAB, nothing happens.

I use this feature all the time and it is very annoying that I need to delete every TAB manually in order to move a block to the left.

Also, when I select text and press CTRL+X, it does not cut the text. Copy and insert does work.

**Comment by jossensei** [comment]
Same here, I've been apple to mitigate the shift+tab problem (https://github.com/lapce/lapce/issues/589) but the ctrl+x does not seems to be recognized (nor the ctrl+k, if that can help). 

Using the 0.2.5 version on Kubuntu 22.04

**Comment by ousado** [comment]
Same issues here. Is there some way to prioritize bugs? This is important, basic functionality that has been broken for some time now. 

There's a new [commit](https://github.com/lapce/lapce/commit/3c2e6e83105367e179af769f6ae7c60d9a1f88cc) that removed the shift+delete shortcut, it's unclear if that has anything to do with this bug, it's not mentioned in the [pull request](https://github.com/lapce/lapce/pull/2246)

**Comment by panekj** [comment]
Both deindent and cutting works fine for all versions

**Comment by ousado** [comment]
It usually works when you (re-)start Lapce, and then it stops working after some (often relatively short) time, as also described here: https://github.com/lapce/lapce/issues/1652#issuecomment-1321863468

Unfortunately I haven't noticed any specific action that triggers it, so far.

I'm currently working full time in lapce on several projects, and I encounter this bug at least 10 times a day.

**Comment by ousado** [comment]
And BTW @panekj, telling people that the issues they are reporting don't exist, especially when it's about absolutely basic, crucial functionality, is probably the worst thing you can do on a software project - let alone a code editor before it's fit for everyday use.

**Comment by panekj** [comment]
I never said the issue doesn't exist, I stated that both of those keybinds work fine since I tested it myself on multiple versions.
If you want to argue and be angry, go to twitter or something.

**Comment by L3P3** [comment]
@panekj I double-checked and your comment missed "for me" at its end, I see both your points guys. ;) Would have been helpful to also share your platform.

```js
msg.append(' for me on ', platform);
```

**Comment by panekj** [comment]
> What platforms have you tested and what exactly did work for you? ctrl+c, ctrl+x and ctrl+v?

macOS 13, Windows 10 and Fedora 37. Both deindent (`Ctrl`+`[`) and cutting (`Ctrl`+`x`) work fine

With German keyboard layout you probably have to rebind `Outdent line` action since `Ctrl`+`[` is `Ctrl`+`ü`
![image](https://user-images.githubusercontent.com/50457605/230764697-4f5ff4b0-94a1-4d77-86b9-34f6313b4b09.png)

**Comment by L3P3** [comment]
I still think that for consistency reasons, there should be a default key binding for shift+tab to outdent...

**Comment by hakro** [comment]
> I still think that for consistency reasons, there should be a default key binding for shift+tab to outdent...

I Agree. All other editors out there have `shift`+`tab` mapped out of the box : Gedit, Kate, VSCode, Eclipse ...

It has been so common for decades, that one assumes it should be there by default, and not have to think about changing a keybinding or choose a different.
I initially thought it was a bug and that outdent was not working, until I found, not one, but several issues mentioning it.

**Comment by L3P3** [comment]
Exactly. If you first have to setup something that is expected to be set by default and then create issues for it, it is not your fault as a user!

**Comment by RichardFevrier** [comment]
I was becoming crazy myself until I found your issue. Thanks mate!
