### ISSUE TITLE
"Delete line" command

### ISSUE THREAD

**Issue by phw** [lapce/lapce#1966]
## Is your feature request related to a problem? Please describe.

When removing code I often want to remove lines completely with a quick keyboard shortcut.

## Describe the solution you'd like

Add a "Delete line" command that completely removes the current line (similar to Vim's "dd" command) or currently selected lines.

## Describe alternatives you've considered

Using the existing "Delete line and insert" command. But it leaves the line itself and on the last line it even leaves the last character (this might be a bug, not sure).

**Comment by lnicola** [comment]
Shift-Delete used to exist (it cut to clipboard), but it got broken in #2071. Now it cuts the selection, then deletes an extra line, because there are two commands for the same binding.
