### ISSUE TITLE
Appimage file in Releases

### ISSUE THREAD

**Issue by iloveclang** [lapce/lapce#1974]
## Describe the solution you'd like

.AppData version of the program

## Describe alternatives you've considered

Making my own

## Additional context

You say the program is in pre-alpha, but it already has everything I need, so I want to be able to carry it around and save it for the future.

**Comment by panekj** [comment]
Hi, AppImage has it's own issues and limitations but also most maintainers don't use Linux so we would like to not provide something that doesn't work and isn't tested.

**Comment by iloveclang** [comment]
It's ok. I managed to make my own, and it works. Good luck with the project. It's really cool.

**Comment by Samueru-sama** [comment]
> AppImage has it's own issues and limitations

You already release a portable binary, not sure why that isn't used to make the appimage instead.

Something I did notice is that this application does not work when the binary is mounted with FUSE, that's interesting [but not something impossible to fix](https://github.com/Portable-Linux-Apps/lapce-AppImage/blob/main/lapce-appimage.sh#L37-L41) lol.
