### ISSUE TITLE
Nothing happens when running lapce on Linux (Kali). 

### ISSUE THREAD

**Issue by sivadasrajan** [lapce/lapce#1975]
## Lapce Version 
0.2.5
## System information

Kali rolling

## Description
Nothing happens when running lapse.
- starting from command line outputs nothing
- double clicking nothing

**Comment by panekj** [comment]
run `lapce -w` from terminal

**Comment by sivadasrajan** [comment]
> run `lapce -w` from terminal

Still nothing.

**Comment by panekj** [comment]
and `RUST_LOG=off,lapce_ui=debug lapce -w`?

**Comment by sivadasrajan** [comment]
> and `RUST_LOG=off,lapce_ui=debug lapce -w`?

running `RUST_LOG=off,lapce_ui=debug lapce -w`? yielded nothing
but and `RUST_LOG=info,lapce_ui=debug lapce -w`? gave the error away

`[2023-01-12][21:57:00][panic][ERROR] thread 'main' panicked at '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, and 1.00 ES
`

Found that more info is available at issue #1108

**Comment by panekj** [comment]
Closing since it's OpenGL 3 is required for Lapce

**Comment by Kuratius** [comment]
MESA_LOADER_DRIVER_OVERRIDE=zink ./lapce  seems to work on raspberry pi 4, though I'm unsure if it has better performance than software rendering.
