### ISSUE TITLE
32-bit Linux support

### ISSUE THREAD

**Issue by RedDeadAlice** [lapce/lapce#1977]
Compiling on 32-bit GNU/Linux fails because dependency "wasmtime-runtime" does not support 32-bit Linux arch and raises "Unsupported Architecture" error

**Comment by panekj** [comment]
Wasmtime doesn't have interest in 32-bit x86 so it's impossible for us to provide Lapce for that architecture
https://github.com/bytecodealliance/wasmtime/issues/1980
