### ISSUE TITLE
Unbearably slow Python autocomplete (sometimes)

### ISSUE THREAD

**Issue by Sciancisco** [lapce/lapce#1982]
## Lapce Version
nightly-acf1de5

## System information
Debian 11

python3.9.2
lapce-python plugin
python-lsp-server 1.7.0
pyflakes 2.2.0
pycodestyle 2.6.0
mccabe 0.6.1

## Describe the bug
Autocompletion sometimes takes many seconds to complete.

## Additional information
I don't know (yet at least) how to force this behavior.
The file is ~1000 lines of pytest tests.
The variables I write are declared globally at the top of the file.
The same thing happens for class names imported from another module (`from module import ClassName`), and for some variables _declared in the signature_ of a function (but not all of them).
However, the weird part is that `pytest`, imported at the top, autocompletes __instantly__.
I can write `pytest.mark.parametrize` using three completions without any problem...

https://user-images.githubusercontent.com/66979306/212218846-49be2394-5477-4b78-a2aa-5cdbfe181927.mp4

The video shows the delay.
The first time, I write press <enter> and wait for the completion.
The second time, I wait until the messages in the bottom-left corner stop and then hit <enter> to complete instantly.
Also the second time, you can see the red squiggle progress from character to character between each cycle of messages.
From my tests, it seems that the more I manually complete the variable name, the longer it takes for autocomplete to work.

The messages cycle:
lint: pyflakes -> lint: pycodestyle -> lint: mccabe

Both times, my CPU jumps to ~40%.

That's all I've got

**Comment by Sciancisco** [comment]
After some more usage and refactor, it seems the slow down was due to a deep json-like structure of nested dicts.

**Comment by panekj** [comment]
This should be opened against Python plugin issue tracker
