### ISSUE TITLE
Modal mode indicator in statusbar is low contrast

### ISSUE THREAD

**Issue by jtbx** [lapce/lapce#1983]
## Lapce Version

0.2.5

## System information

Arch Linux (rolling) w/ Plasma 5.26 & Wayland 1.21

## Describe the bug

When modal mode is enabled, the mode indicator in the status bar has low contrast which bothers me a little bit.

![Screenshot](https://i.ibb.co/J3ChJk4/Screenshot-20230113-161504.png)

**Comment by panekj** [comment]
![image](https://user-images.githubusercontent.com/50457605/212368140-9f38c9d0-20fa-4316-b0f3-d38ca70d8da9.png)
Can't reproduce, did you change background colour of status?

**Comment by jtbx** [comment]
Yes, I only changed the base colours.

**Comment by panekj** [comment]
You need to change the modal status colour then
