### ISSUE TITLE
Terminal titles don't appear with Bash

### ISSUE THREAD

**Issue by Insprill** [lapce/lapce#1984]
## Lapce Version
0.2.5

## System information
Garuda Linux
Kernel: 6.1.4-zen
Shell: Bash 5.1.16

## Describe the bug
When using Bash as your terminal shell, the terminal titles don't show, leaving a blank space. Setting the shell to ZSH properly shows the titles.

## Additional information
![image](https://user-images.githubusercontent.com/52843537/212252049-1f0e664f-3270-4af0-831a-19d61a906b8f.png)

**Comment by panekj** [comment]
Works fine for me
![image](https://user-images.githubusercontent.com/50457605/212267565-d0336a95-840a-4fa8-b882-62f46fc9b22c.png)

**Comment by Insprill** [comment]
I see, setting it manually does work. I'm assuming in that case that Bash just doesn't set it by default. If there's no title, perhaps Lapce could make one so the button isn't just empty?
