### ISSUE TITLE
Remote SSH connections are slow to setup on Windows

### ISSUE THREAD

**Issue by peterjc123** [lapce/lapce#1993]
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 
0.2.5

## System information

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04
Host: Windows 10 21H2
Remote: Debian sid

## Describe the bug

It takes nearly one minute to connect to a pre-configured remote SSH server on the same LAN.

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

Log:
```bash
[2023-01-14][12:41:48][lapce_data::proxy::start_remote::first_try][DEBUG] bash: Line 1: lapce-no-command: Not found

[2023-01-14][12:41:48][lapce_data::proxy::start_remote::first_try][DEBUG] 
[2023-01-14][12:42:04][lapce_data::proxy::host_specification][DEBUG] linux x86_64
[2023-01-14][12:42:19][lapce_data::proxy::upload_file][DEBUG] 
[2023-01-14][12:42:19][lapce_data::proxy::upload_file][DEBUG] 
[2023-01-14][12:42:34][lapce_data::proxy::upload_file][DEBUG] 
[2023-01-14][12:42:34][lapce_data::proxy::upload_file][DEBUG] 
[2023-01-14][12:42:50][lapce_data::proxy::upload_file][DEBUG] + _TMP=/tmp
+ _VER=v0.2.5
+ eval _DIR='/home/peter/.local/share/lapce-stable/proxy'
+ _DIR=/home/peter/.local/share/lapce-stable/proxy
+ [ -e /home/peter/.local/share/lapce-stable/proxy/lapce ]
+ chmod +x /home/peter/.local/share/lapce-stable/proxy/lapce
+ /home/peter/.local/share/lapce-stable/proxy/lapce --version
+ cut -dv -f2
+ _ver=Lapce 0.2.5
+ printf [DEBUG]: %s = %s Lapce 0.2.5 v0.2.5
+ [ Lapce 0.2.5 = v0.2.5 ]
+ printf Proxy already exists\n
+ exit 0

[2023-01-14][12:42:50][lapce_data::proxy::upload_file][DEBUG] [DEBUG]: Lapce 0.2.5 = v0.2.5Proxy already exists
```

I guess what is wrong is that it takes too long to communicate via SSH and SCP.

**Comment by peterjc123** [comment]
It seems that https://github.com/lapce/lapce/blob/master/lapce-data/src/proxy.rs#L799 is the culprit.
```rust
use std::process::Command;
use std::time::Instant;
use std::thread;

fn main() {
    let t = thread::spawn(|| {
        let now = Instant::now();
        let cmd = Command::new("ssh").arg("-o").arg("ConnectTimeout=15").arg("peter@192.168.50.214").arg("echo yes").output().unwrap();
        println!("elpased: {} ms", now.elapsed().as_millis());
        println!("stderr: {}", String::from_utf8_lossy(&cmd.stderr));
        println!("elpased: {} ms", now.elapsed().as_millis());
        println!("stdout: {}", String::from_utf8_lossy(&cmd.stdout));
        println!("elpased: {} ms", now.elapsed().as_millis());
    });

    t.join().ok();

}
```
This prints out `elapsed: 15251 ms`, if the options are removed, it prints out `elapsed: 251 ms`.

**Comment by peterjc123** [comment]
It seems that https://github.com/lapce/lapce/blob/master/lapce-data/src/proxy.rs#L799 is the culprit.
```rust
use std::process::Command;
use std::time::Instant;
use std::thread;

fn main() {
    let t = thread::spawn(|| {
        let now = Instant::now();
        let cmd = Command::new("ssh").arg("-o").arg("ConnectTimeout=15").arg("peter@MY_IP").arg("echo yes").output().unwrap();
        println!("elpased: {} ms", now.elapsed().as_millis());
        println!("stderr: {}", String::from_utf8_lossy(&cmd.stderr));
        println!("elpased: {} ms", now.elapsed().as_millis());
        println!("stdout: {}", String::from_utf8_lossy(&cmd.stdout));
        println!("elpased: {} ms", now.elapsed().as_millis());
    });

    t.join().ok();

}
```
This prints out `elapsed: 15251 ms`, if the options are removed, it prints out `elapsed: 251 ms`.

**Comment by peterjc123** [comment]
Upstream issue: https://github.com/PowerShell/Win32-OpenSSH/issues/1352
The ssh version on my host OS: `OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2`

**Comment by peterjc123** [comment]
So, the workaround is listed below.
1. Uninstall the built-in OpenSSH client via Settings-Optional features
2. Reboot
3. Install the latest version according to https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH or using installers listed in https://github.com/PowerShell/Win32-OpenSSH/releases

After applying those changes, the button turns green from yellow within 2 seconds.

**Comment by qaqland** [comment]
And should **NOT** use password :)

> Remote development only works with key based SSH authentication at the moment. So it doesn't connect if you normally put a password for connecting to the SSH host.
