### ISSUE TITLE
could not download plugin

### ISSUE THREAD

**Issue by itzhoujun** [lapce/lapce#1999]
## Lapce Version

0.2.5

## System information

macos 13.1 m1 pro

## Describe the bug
<img width="271" alt="image" src="https://user-images.githubusercontent.com/6897671/212529218-5975a852-1639-46e7-85e7-3e76d3468a08.png">

**Comment by itzhoujun** [comment]
cause by my network. Installed successful when in my office

**Comment by WeebNetsu** [comment]
I have this same issue, but see no issue with my network

Lapce: 0.2.5

System: Arch Linux

**Comment by panekj** [comment]
This is different issue, plugin server currently doesn't work properly.
