### ISSUE TITLE
DPI/display scaling

### ISSUE THREAD

**Issue by jansol** [lapce/lapce#20]
Seems like Lapce isn't handling a different display scale than 1.0 very well (at least on macOS):

1) Resizing the window leaves only a small viewport in the corner, the rest of the window does not get redrawn at all.
2) Line spacing is off, especially noticeable with box drawing characters like what nushell uses to draw its tables.

**Comment by dzhou121** [comment]
Hi, can you share a screenshot of the issue?

I thought macOS always scale at 2.0 for HiDPI.

**Comment by jansol** [comment]
1.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/2588851/146012767-c2147456-4886-47cd-a0de-d93b34d5ed41.png">

2.
<img width="481" alt="image" src="https://user-images.githubusercontent.com/2588851/146012874-b179d4f9-88da-41c7-be02-d8d403dbf09d.png">

**Comment by dzhou121** [comment]
Thanks for the screenshot.

Maybe can you let me know your OS version and which hardware?

**Comment by hkjels** [comment]
<img width="698" alt="display_err" src="https://user-images.githubusercontent.com/339547/146014413-ef3257fa-bfea-4779-9ad9-7d226f8856e9.png">
The same happens for me

**Comment by jansol** [comment]
macOS Big Sur 11.6.1
Intel HD Graphics 530 / Radeon Pro 460
(it's a MacBook Pro 2016, 15-inch model)

Lapce seems to be using the Intel integrated GPU here.

**Comment by DanielBelmes** [comment]
Have this issue as well:
macOS Big Sur 11.6
AMD Radeon Pro 5300M 4 GB
2.6 GHz 6-Core Intel Core i7
MacBook Pro (16-inch, 2019)

**Comment by dzhou121** [comment]
Can you also let me know the display settings?

**Comment by jansol** [comment]
2880x1800 Retina, and alacritty (which uses winit) reports a device pixel ratio of 2.0

**Comment by PaulPorthouse** [comment]
Similar/same issue on Windows where different monitors have different scaling applied

100% scaling
![image](https://user-images.githubusercontent.com/8049270/146019043-de851ad1-2534-4e39-ada8-edb5807618fe.png)

125% scaling
![image](https://user-images.githubusercontent.com/8049270/146019211-9e26ad88-62d3-48e6-8833-94168205afe4.png)

**Comment by bjorn3** [comment]
I got the same issue as OP, but only when compiling lapce in debug mode. In release mode it is fine.

**Comment by virtualritz** [comment]
Same issue with 0.0.2 on macOS 10.15.7.

**Comment by bruno-anjos** [comment]
Same behaviour as OP. Intel MacBook Pro 16" with macOS 12.0.1 installed from .dmg

**Comment by Yevgnen** [comment]
```
                    'c.          User@macOS.local 
                 ,xNMM.          ------------------- 
               .OMMMMo           OS: macOS 12.1 21C52 x86_64 
               OMMM0,            Host: MacBookPro15,1 
     .;loddo:' loolloddol;.      Kernel: 21.2.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 23 hours, 26 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 283 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: bash 5.1.12 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1200@2x 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: kitty 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Intel i7-9750H (12) @ 2.60GHz 
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Intel UHD Graphics 630, Radeon Pro 560X 
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 16793MiB / 32768MiB 
       .cooc,.    .,coo:.
```

**Comment by maks** [comment]
I actually seem to get something simliar with scaling turned on in Ubuntu 21.10 (using wayland).
This is what it looks like with scaling at 100%:
![image](https://user-images.githubusercontent.com/71999/146114963-eb763041-5b38-4af4-b76a-bcf2ac4f8548.png)

and this the very same running instances window dragged over to a second monitor with scaling enabled (at 200%):
![image](https://user-images.githubusercontent.com/71999/146115045-9fedc8da-ab2c-4b00-9f1c-22cec78c13b1.png)

lapse debug build of main branch at 93737031

**Comment by dzhou121** [comment]
Should be fixed by the latest release. https://github.com/lapce/lapce/releases/tag/v0.0.3

**Comment by PaulPorthouse** [comment]
Yeah,, fixes the problem for me with Windows. 

Many thanks

**Comment by maks** [comment]
Thank you for working on this so quickly! On Linux I can now see the expected UI but unfortunately this doesn't yet fix the issue on Linux wayland for scaled displays or resizing on a non scaled display.

Here is what it looks like (correct) on a 100% scaled display:
![Screenshot from 2021-12-16 12-17-16](https://user-images.githubusercontent.com/71999/146290578-079d82e9-0021-4dca-a363-05392b31de1a.png)

But as soon as I try to resize the window I get:
![Screenshot from 2021-12-16 12-17-46](https://user-images.githubusercontent.com/71999/146290682-37e70b46-8cd2-40c0-b248-e8daad4f4893.png)

And when I move the window over onto a scaled monitor display (at 200%) I get:
![Screenshot from 2021-12-16 12-18-35](https://user-images.githubusercontent.com/71999/146290763-35109786-f3d8-4195-bdb1-f706192c67a2.png)

This is all with Ubuntu 21.20 Gnome (wayland) and happens with using both "standard" scaling and the experimental fractional scaling.

**Comment by dzhou121** [comment]
@maks which commit is it running on?

**Comment by maks** [comment]
its:
```
>git log --oneline
a61d3b2 Updte piet-wgpu
```

**Comment by osa1** [comment]
I'm trying lapce 176fbd8 (current master branch) on Linux with Xorg. With "XFCE settings -> appearance -> settings -> window scaling" set to 2x, lapce GUI is rendered very small. 

Changing the setting after running lapce also doesn't make any difference. It seems like the setting is ignored.

**Comment by LyesSaadi** [comment]
On latest release, this is what I have on GNOME 42/Wayland:
![image](https://user-images.githubusercontent.com/33597258/156550130-eddf2127-8974-4142-b9b9-4c2e7d10d5a4.png)

My screen is 2880/1800 at 200% zoom.

**Comment by LyesSaadi** [comment]
Ah, it actually works on master! My bad!
