### ISSUE TITLE
Druid development discontinued

### ISSUE THREAD

**Issue by reckel-jm** [lapce/lapce#2011]
Acoording to its [README](https://github.com/linebender/druid/blob/master/README.md), the development of druid is discontinued. That means, it would be good to start a roadmap on migrating to an other UI toolkit such as [xilem](https://github.com/linebender/xilem) in the future.

**Comment by nheuillet** [comment]
The plan is to migrate to xilem once it has reached a "complete" / working enough state. As of right now, the migration roadmap has not been created at all because xilem is not ready but the core team is really excited for it's development!

**Comment by panekj** [comment]
We're using our own fork of druid so there isn't any issue of it being deprecated, its development has been been slow for quite a while now.

**Comment by reckel-jm** [comment]
Thanks for letting me know! Great that you have this on spot and I share the excitement :+1:

**Comment by milahu** [comment]
lapce is now based on [floem](https://github.com/lapce/floem)

**Comment by bergus** [comment]
@milahu you may want to update https://docs.lapce.dev/development/architecture#frontend accordingly

**Comment by panekj** [comment]
> you may want to update [docs.lapce.dev/development/architecture#frontend](https://docs.lapce.dev/development/architecture#frontend) accordingly

it's in progress
