### ISSUE TITLE
Cannot select the current line on Linux (on X11)

### ISSUE THREAD

**Issue by salvoc81** [lapce/lapce#2025]
## Lapce Version

0.2.5

## System information

Arch linux (Manjaro GNOME); Kernel 6.1.1 on X11

## Describe the bug
The keybinding to select the current line `Ctrl + L` does nothing.

### Other info
Lapce was installed using the package in the Arch repositories (e.g., not using Flatpak)

**Comment by PeepoFrog** [comment]
not only x11
in wayland same problem ubuntu 22.04
