### ISSUE TITLE
Cannot type "~"

### ISSUE THREAD

**Issue by frafra** [lapce/lapce#2027]
## Lapce Version

0.2.5

## System information

Ubuntu 20.04

## Describe the bug
I cannot type `~`. I usually type `~` followed by a space to make the `~` character appear on the screen when using my keyboard.

## Additional information

I am using Ubuntu inside a remote desktop application. Other editors and software work as usual. Cannot reproduce on Windows.

**Comment by jpdarricarrere** [comment]
Related to #1798 ?

**Comment by frafra** [comment]
Yes, I think so. I am using a Norwegian keyboard.
I will close this issue.

**Comment by hbina** [comment]
I think you should keep this open. It's a legitimate issue for a text editor to not work with some locales?

**Comment by panekj** [comment]
> I think you should keep this open. It's a legitimate issue for a text editor to not work with some locales? BTW do you know of the specific unicode value that doesn't work here?

We already have issue opened for dead keys

**Comment by frafra** [comment]
> BTW do you know of the specific unicode value that doesn't work here?

nb_NO

**Comment by panekj** [comment]
> nb_NO

That's keyboard layout.

> That's keyboard layout.

Go to keyboard settings in Lapce and try to map the key that doesn't work, if it shows as `DEAD` it's a dead keys issue #1094

**Comment by frafra** [comment]
It is a dead key indeed.
