### ISSUE TITLE
User configurable diff context lines

### ISSUE THREAD

**Issue by lukaslihotzki** [lapce/lapce#2029]
Currently, the number of diff context lines is hardcoded to 3 in [lapce-core/src/buffer/mod.rs](https://github.com/lapce/lapce/blob/e686e6f999c593aadde3dd37b1dafcfd739095d9/lapce-core/src/buffer/mod.rs#L1205-L1246). This should be user-configurable. Also, it should be configurable to disable line skipping at all (like infinite context lines) by skipping the whole `if !changes.is_empty()` block.

**Comment by tk103331** [comment]
This issue should be closed.
