### ISSUE TITLE
Copy pasting folder path does not work on Windows

### ISSUE THREAD

**Issue by gerroon** [lapce/lapce#203]
Hi

I am using it on Windows 10. Opening a folder does not work when I paste the full path to my folder in the "open folder" dialog. It seems counter intuitive to browse the folders only via its own internal browser.

There is no information about the version of this app so I cant tell what version it is. I downloaded it today and using it on Windows 10 x64

**Comment by bugadani** [comment]
Hi and thanks for reporting this issue!

The most recent release should use Windows' own file picker, thich should solve this issue, so I'm closing this. However, feel free to reopen if you still experience it with the newest release. Thanks!
