### ISSUE TITLE
No syntax highlighting with Python

### ISSUE THREAD

**Issue by gerroon** [lapce/lapce#204]
Here is an `__init__.py` open in the editor and no color coding or syntax highlighting is visible. Plus, see those weird spaces? There are no indents or spaces in the beginning of those lines but rendered with such errors.

I am using the portable version on windows 10

![lapce_7oN19btV6X](https://user-images.githubusercontent.com/8519469/159192956-639efa06-cf32-4fc9-ba1a-3038c19bef69.jpg)

**Comment by ghishadow** [comment]
https://github.com/lapce/lapce/commit/bf2e4959fd10688fc24fbd1c7fb44ca5f80026ee it is available in master after this commit
![image](https://user-images.githubusercontent.com/9583775/159389332-f67db051-464f-4663-bc1e-10d2f35f1dd0.png)

**Comment by bugadani** [comment]
Thanks for opening this issue!

As bf2e4959fd10688fc24fbd1c7fb44ca5f80026ee added python syntax highlighting, I'm closing this issue.
