### ISSUE TITLE
Only default Cascadia Code is being recognized

### ISSUE THREAD

**Issue by jbrodriguez** [lapce/lapce#2041]
First of all, this is an awesome editor, i really like it, may even compete with vscode, let's see how this goes

## Lapce Version

0.2.5

## System information

macOS Ventura 13.1

## Describe the bug
Can't set any font other than the default (Cascadia Code)

I tried with SF Mono, Fira Code and none work (both are installed)

![Screenshot 2023-01-20 at 08 51 18](https://user-images.githubusercontent.com/1305422/213713090-5e79196c-8157-4953-be80-3924d9507b62.png)

it seems to default back to the system font (variable)

## Additional information

supposedly rendering with fira code
![Screenshot 2023-01-20 at 08 48 52](https://user-images.githubusercontent.com/1305422/213712954-e04b67f5-25ac-41fa-b7fd-71404454aff8.png)

cascadia code renders fine
![Screenshot 2023-01-20 at 08 52 48](https://user-images.githubusercontent.com/1305422/213713442-e6803f3d-6380-4601-9937-2d0fdc1e048d.png)

**Comment by panekj** [comment]
Only one font can be set, setting multiple fonts will fallback to default

**Comment by jbrodriguez** [comment]
ohhhh i see, awesome ! 

yes it works now with fira code
![Screenshot 2023-01-20 at 09 15 27](https://user-images.githubusercontent.com/1305422/213719438-0cb7bcb7-40c4-407e-b764-bc1fd2fae875.png)

but doesn't like sf mono
![Screenshot 2023-01-20 at 09 15 39](https://user-images.githubusercontent.com/1305422/213719571-21fc1f57-5810-443a-8423-6fd7a4397bd2.png)

i can live with that at the moment, thanks a lot for the reply!

**Comment by panekj** [comment]
`SF Mono` looks like #1639
