### ISSUE TITLE
Text overflows when to long

### ISSUE THREAD

**Issue by lucalewin** [lapce/lapce#2043]
## Lapce Version

0.2.5

## System information

Windows 11

## Describe the bug

In the git tab the filename overflows when it is to long.

Possible solution: add three dots (...) at the end and ignore the rest of the filename when the filename would overflow

## Additional information

![image](https://user-images.githubusercontent.com/66569227/213883224-7b7df0f4-0479-4c5a-a15b-ce3e5ba3402e.png)

**Comment by nick-1666** [comment]
ima work on this

**Comment by panekj** [comment]
> ima work on this

@nick-1666 you can start looking at plugin implementation
https://github.com/lapce/lapce/blob/4fb921c7d4ce4c3b38b8879c7d9f17da5a3c64ee/lapce-ui/src/plugin.rs#L246

and code for source panel should be here
https://github.com/lapce/lapce/blob/4fb921c7d4ce4c3b38b8879c7d9f17da5a3c64ee/lapce-ui/src/source_control.rs#L430

**Comment by nick-1666** [comment]
New problem, the folder name (displayed in gray) can overflow too
![image](https://user-images.githubusercontent.com/67550680/213887208-a58f4b48-b60a-4eb5-bd29-2bf8fde39664.png)
I think we have to add the widths of the filename and the folder (plus the padding) and then truncate

**Comment by nick-1666** [comment]
Idk if this is intended behaviour 
![image](https://user-images.githubusercontent.com/67550680/213887257-bfdc1578-d845-4226-a481-38c43736a6b0.png)
but if we are truncating in one panel we should truncate here aswell for consistency maybe?

**Comment by panekj** [comment]
Bonus points if you make generalized option so we can re-use it in multiple places 😺

**Comment by nick-1666** [comment]
> Bonus points if you make generalized option so we can re-use it in multiple places 😺 

relates to my newest issue too. Maybe a wrapper class for the text and you can just call `.truncate()` and it mutates itself and returns the text but truncated

**Comment by hbina** [comment]
It should be a new Widget with its own implementation I think. It can determine how much text it can display in `layout`. Then we can reuse it wherever truncation makes sense. This is what VSCode does for example.
![Screenshot from 2023-01-22 07-22-58](https://user-images.githubusercontent.com/6733660/213893933-cede30fb-2922-40c9-815d-21af0a43f2d0.png)

**Comment by panekj** [comment]
This is fixed
