### ISSUE TITLE
Feature Request: Add a localization system

### ISSUE THREAD

**Issue by Baumfinder** [lapce/lapce#2053]
It would be very nice if you could set the language of the app to anything different than English. 
Crates that could be used:
* [Gettext](https://crates.io/crates/gettext)
* [Fluent](https://crates.io/crates/fluent)

I could contribute to a German translation if this gets implemented.

**Comment by panekj** [comment]
Druid already provides a system for localisation but we don't use it and we're most likely won't implement localisation until after migration to Xilem.

**Comment by Baumfinder** [comment]
Ah ok, thanks for clarifying!

**Comment by Initsnow** [comment]
> Druid already provides a system for localisation but we don't use it and we most likely won't implement localisation until after migration to Xilem.

Uh, any progress at all?

**Comment by panekj** [comment]
> > Druid already provides a system for localisation but we don't use it and we most likely won't implement localisation until after migration to Xilem.
> 
> Uh, any progress at all?

There will ve a status update if anything changes. Currently there are no plans to implement this.
