### ISSUE TITLE
Add regexp search mode

### ISSUE THREAD

**Issue by vlanse** [lapce/lapce#2058]
## Is your feature request related to a problem? Please describe.

Most editors/IDEs usually support various search modes, including search by regexp

## Describe the solution you'd like

Add regexp mode to search box

## Describe alternatives you've considered

N/A

**Comment by panekj** [comment]
search is already regex

**Comment by vlanse** [comment]
Sorry, but it is completely not obvious how it works

For example, on the picture below I am trying to find "numbers" by searching like `\d+` - as you can see, nothing is actually highlighted

Meanwhile I expect to have all lines highlighted (considering any JB IDE as a reference)

<img width="376" alt="Screenshot 2023-01-25 at 11 20 50" src="https://user-images.githubusercontent.com/17192647/214513351-eeca4a68-66b5-4f03-8add-3a03ff32f52c.png">
