### ISSUE TITLE
Branch filter not updating

### ISSUE THREAD

**Issue by runiorr** [lapce/lapce#2079]
## Lapce Version

0.2.5

## System information

6.1.6-200.fc37.x86_64

## Describe the bug

There's a bug when we write in the filter input, close it and open again.

If I write "terminal", it shows only one branch. Then I click away to minimize and click on the branches icon again, "terminal" is still there, but now all branches have appeared, ignoring the filter.

I don't know which should be the normal behavior, keep the filter on or clean the input field.

## Additional information

All branches

![without_filter](https://user-images.githubusercontent.com/69124149/215306645-a7a6b795-0c51-46b1-879c-2ef286ff8a04.png)

Filtering by "terminal"

![filtered](https://user-images.githubusercontent.com/69124149/215306651-71dffc7f-68be-4478-9162-3dcb21cb2bdf.png)

After clicking away and branches again

![after_clicking_away](https://user-images.githubusercontent.com/69124149/215306653-cd60eea4-e211-4697-a9b1-9e4a6447563f.png)

**Comment by hbina** [comment]
>I don't know which should be the normal behavior, keep the filter on or clean the input field.

I think for now it should at least be consistent then we can bikeshed how it _should_ work. That is the filter should be applied the second time you open it if the text is there.

**Comment by runiorr** [comment]
I fixed the issue with the filter refreshing but I don't know the process to make a PR. 
Is there a doc for it? Didn't find any about it

**Comment by hbina** [comment]
There's no set guidelines for a PR if its a fix. Just:

1. Fork the project
2. Push your changes to your fork
3. Create the PR from your branch
