### ISSUE TITLE
Scroll speed setting

### ISSUE THREAD

**Issue by expenses** [lapce/lapce#2085]
## Is your feature request related to a problem? Please describe.

Hi! I'm enjoying Lapce a lot but one issue I have is that the scroll speed is a little too fast on my trackpad. I've love the ability to bump it down to 2/3rds or 1/2th of what it is now.

## Describe the solution you'd like

A scroll speed setting would be the deal solution to this.

## Describe alternatives you've considered

I guess the only alternative would be to change what the default speed is.

## Additional context

Lapce version: 0.2.5

**Comment by Netroxen** [comment]
This can usually be configured on your laptop with the appropriate touchpad driver. This is not a problem for Lapce to resolve in my opinion, and would add unnecessary bulk to the code-base.

**Comment by expenses** [comment]
> This can usually be configured on your laptop with the appropriate touchpad driver. This is not a problem for Lapce to resolve in my opinion, and would add unnecessary bulk to the code-base.

The scroll speed of every other program I use is fine, it's just that Lapce is too fast. I'm not sure if it's possible for me to change scroll speed on a per-program setting.

I'm also not sure I buy the bloat argument 😉 how many lines of code could a change like this possibly add?

**Comment by hbina** [comment]
I can try take a look at it.
