### ISSUE TITLE
Could not download Plugin

### ISSUE THREAD

**Issue by MicroBlueee** [lapce/lapce#2103]
## Lapce Version

Lapce 0.2.5

## System information

Mac OS 13.2 (22D49)

## Describe the bug
I cannot either upgrade plugins or download new plugins.

## Additional information

<img width="441" alt="image" src="https://user-images.githubusercontent.com/49147382/216652234-9a27186f-a445-4bf5-bc61-0ea3943c57ca.png">

I tried to change the network environment, but the problem occurred still.

**Comment by panekj** [comment]
Seems like DB de-synced again and our API is borked.

**Comment by MicroBlueee** [comment]
Sorry to add to your troubles, this is not urgent and I can continue to use the old version. 

So I don't need to do anything else now, just wait for you to fix the API?

**Comment by panekj** [comment]
It's fixed now but the problem will happen again until I figure out what's the actual problem.
Will need to ask @dzhou121 how it was configured/works since I did not deploy [plugins.lapce.dev](https://plugins.lapce.dev).

**Comment by MicroBlueee** [comment]
Many thanks for your fixing, I just checked thee function which can work properly now. And I upgraded my needed plugins successfully. Sorry for adding your troubles and thanks again.

**Comment by angelthorns** [comment]
still this same issue on all versions of lapce, nightly, built from source and the packaged Arch Linux version.

distro is Arch for all, using NetworkManager

i've also tested it on a NixOS vm and it has the same issue 

on the nightly version all plugins change to say "Installing" but stay that way forever and never install, on the packaged Arch Linux version it does the same as in OP's image

had to clone plugins to the folder and build them myself to get any plugins installed.

couldn't find any output showing any errors unfortunately

**Comment by angelthorns** [comment]
been messing with the api and it appears the download from cloudflare storage returns Unauthorized

e.g: https://plugins.lapce.dev/api/v1/plugins/dzhou121/lapce-rust/0.2.4/download 
the cloudflare cdn storage link this api request returns gives a 401 with an XML error 'Unauthorized'

I inserted some log prints, and confirmed that 401 is what it is.
so it fails here, and this error message is never propagated to any sort of logging mechanism, or the ui resulting in an infinite "Installing" message:
https://github.com/lapce/lapce/blob/980b025886bb52c151cd8954c7547fd94be35c73/lapce-proxy/src/plugin/mod.rs#L1278C27-L1278C27
