### ISSUE TITLE
Open a non-existing file at command line

### ISSUE THREAD

**Issue by sgon00** [lapce/lapce#2109]
OS: Debian 11.4

## Is your feature request related to a problem? Please describe.

When I try to create a file with lapce, I tried to execute the following commands in a terminal:

```
$ lapce newfile.sh

$ lapce -n newfile.sh
```

None of the above methods will work. This looks a bug to me, but I select a feature label in github issue to be kind.

## Describe the solution you'd like

Just make it the same behavior as all other editors such as vim, vscode etc..

**Comment by hbina** [comment]
I prefer this behavior:

1. non-existent file/folder -> error
2. non-existent file but -n specified -> create the file
3. file/folder exists -> open them

**Comment by sgon00** [comment]
@hbina Thanks for the reply, but I prefer the standard way. I don't know if you are a Linux user or not. I am a Linux user. I never see any editors have the first behavior you described. You can try any editors, such as `vim`, `gvim`, `nano`, `kwrite`, `kate`, `gedit`, `emacs`, `vscode` etc.. The first behavior you described is just weird to me.

**Comment by sgon00** [comment]
> We're not going to error on non-existing path, it should and will create required directories and file.

Thanks a lot. Yeah, The new file should be created on SAVE.
