### ISSUE TITLE
Ability to customize terminal

### ISSUE THREAD

**Issue by Kyllingene** [lapce/lapce#211]
It would be great to be able to at least set a custom startup command, to be able to run a custom shell (such as nu or zsh) instead of the default. On Windows the default is Powershell, which is much worse than modern shells.

**Comment by ghishadow** [comment]
looks like new setting has been added in this commit
https://github.com/lapce/lapce/commit/fc7a3b0824bf007345fd6fa04fe0f957d07ba898
![image](https://user-images.githubusercontent.com/9583775/159389607-c98563c7-c4a4-42f8-a693-e262aaa39572.png)
I tried changing to nu and wsl it worked

**Comment by Kyllingene** [comment]
Ok, it's great to see a performant editor get updates so rapidly!
