### ISSUE TITLE
[Feature]: Please provide downloads for Linux aarch64

### ISSUE THREAD

**Issue by babaric-dev** [lapce/lapce#2110]
Please build for aarch64-unknown-linux-gnu triplet in future GitHub CI and releases. RISC architectures are getting more common these days.

Although I don't use arm (I use 64 bit aarch64), it would be cool to add it too because others may have, say, a Raspberry Pi.

**Comment by Titaniumtown** [comment]
you can just compile it yourself

**Comment by panekj** [comment]
Fixed via #2989
