### ISSUE TITLE
Saving to a symlinked file overwrites the link

### ISSUE THREAD

**Issue by detjensrobert** [lapce/lapce#2122]
## Lapce Version

nightly-eaa1b57 (`lapce-nightly-bin` AUR package)

## System information

Arch Linux, x64

## Describe the bug

Saving a file that is a symlink to a different file overwrites the file and removes the symlink (and thus does not update the linked-to file).

Intended behaviour is to preserve/follow the link and update the original file.

## Additional information

- Created test files:
![image](https://user-images.githubusercontent.com/12376078/217686404-f2f07977-7cf9-4682-8563-5d5df3157804.png)

- Edited in Lapce:
![image](https://user-images.githubusercontent.com/12376078/217686523-d9004317-e43c-44e5-b258-0ae77fcd068b.png)

- `bar` is no longer a link:
![image](https://user-images.githubusercontent.com/12376078/217686673-ee08e717-3e77-4f58-a567-3f64d3c646e1.png)

**Comment by hbina** [comment]
`lapce-proxy` should probably only accept canonicalized strings. Think its possible with a little bit of newtype. Can be extended to be an URN later.
