### ISSUE TITLE
File icons showing on the left panel do not match the corresponding file type and language

### ISSUE THREAD

**Issue by hakro** [lapce/lapce#2142]
## Lapce Version

0.2.5

## System information

PopOS 22.04

## Describe the bug
The file icons showing on the left panel do not match the corresponding file type (py, go, cpp ...)
Only generic icons are shown (basic directory, basic files)

## Additional information

![2023-02-13_14-50](https://user-images.githubusercontent.com/3624853/218475939-7e68e914-1b6d-4567-85c5-2842d8a596d7.png)

**Comment by panekj** [comment]
These are the icons that Lapce ships with

**Comment by panekj** [comment]
To get icons for each file type you can install any icon theme in plugins tab and enable it in settings

**Comment by hakro** [comment]
Thank you @panekj.
It's the name of the default icons that put me off in the settings: Lapce Codicons
Sounded like this theme includes coding icons already :) 

I managed to use the material icons plugin. For any one stumbling upon this issue and is interested, here are the steps : 
- Install and enable Material Icon Theme plugin (this seems to be the only one currently available)
![2023-02-13_15-37](https://user-images.githubusercontent.com/3624853/218487311-8bc4c838-4960-4328-8e41-52ed1e905608.png)

- In the core settings, set the Icon Theme property to `Material Icons`. This needs to be typed in the text field. This values comes from the config file that get downloaded with the pluging 

![2023-02-13_15-38](https://user-images.githubusercontent.com/3624853/218487935-7cf59821-429a-44a0-9f1e-7cc8c640834b.png)

- Happy coding.

**Comment by MinusGix** [comment]
> In the core settings, set the Icon Theme property to Material Icons. This needs to be typed in the text field. This values comes from the config file that get downloaded with the plugin  
  
(In the next release of Lapce, there's a dropdown for changing the themes so you don't have to manually type it anymore)
