### ISSUE TITLE
Lapce not starting in Windows 10 (VMware virtual machine)

### ISSUE THREAD

**Issue by fnicolini** [lapce/lapce#2143]
## Lapce Version

0.2.5

## System information

Windows 10 (Inside a VMware virtual machine)

## Describe the bug
Lapce does not open. I tried double clicking the executable as well as running lapce from command line. Either way nothing happens and no information is displayed.

## Additional information

I found the following error in the Windows Event Viewer:

>   Faulting application name: lapce.exe, version: 0.2.5.0, timestamp: 0x639a2d18
>   Faulting module name: ucrtbase.dll, version: 10.0.19041.789, timestamp: 0x2bd748bf
>   Exception code: 0xc0000409
>   Error offset 0x000000000007286e
>   Process ID that generated the error: 0x2ec4
>   Start time of the application that generated the error: 0x01d93fb47634ac38
>   Faulting application path: C:\Program Files\Lapce\lapce.exe
>   Path to the module that generated the error: C:\Windows\System32\ucrtbase.dll
>   Report ID: 663267a9-4981-4d4a-abb9-5344b49edda9
>   Full package name that generated the error:
>   Application ID of the package that generated the error:

I have looked up the ucrtbase.dll and it seems something related to the Microsoft Visual C++ Redistributable, which i made sure that i have installed (i even re-installed it just to make sure).

**Comment by panekj** [comment]
Lapce requires OpenGL3 to run

**Comment by fnicolini** [comment]
I don't know if this is of any interest or not, but it seems that i am running OpenGL version 3.3:
![immagine](https://user-images.githubusercontent.com/19589757/218499783-cd93cc17-46c6-49e1-ab2e-6b1ca06eeed6.png)

**Comment by panekj** [comment]
Try running lapce with `RUST_LOG=debug`

**Comment by fnicolini** [comment]
I don't have much experience with environment variables in Windows, so i hope this is the right way to do it:
![immagine](https://user-images.githubusercontent.com/19589757/218510285-11c7598b-15c9-4ad8-92ae-76dc3c0a3c95.png)

Nothing changed, and the same error appears in the event log.

**Comment by rbharathkumar** [comment]
just wanted to add that I am facing similar issues in a Azure Virtual Desktop environment.
Lapce portable just wouldn't start...

**Comment by MinusGix** [comment]
> just wanted to add that I am facing similar issues in an Azure Virtual Desktop environment. Lapce portable just wouldn't start...
> 
> **Update Edit:** Tried version 0.2.4 on the same system - same results - not opening - no error - nothing... Tried version 0.2.4 on a **similar but different remote system**, getting the below error. Note - I have cut out part of the error which basically shows the path to the lapce executable. ![image](https://user-images.githubusercontent.com/38585383/219075679-9f0bbb83-a75a-48c5-a63b-9dd116528d23.png)

I think the second system is #1137 / #132, which is due to us requiring a minimum windows version at this time.  
At a glance, I don't think the minimum-windows version is the cause of the issue author's problem. Though, that it failed to start for one of your systems (without even that error) might be the same as the issue author's problem.

**Comment by panekj** [comment]
> just wanted to add that I am facing similar issues in an Azure Virtual Desktop environment.

You need an actual GPU available in machine to run lapce

**Comment by panekj** [comment]
> I don't have much experience with environment variables in Windows, so i hope this is the right way to do it: ![immagine](https://user-images.githubusercontent.com/19589757/218510285-11c7598b-15c9-4ad8-92ae-76dc3c0a3c95.png)
> 
> Nothing changed, and the same error appears in the event log.

I keep forgetting that Windows builds are slightly different, you need to build lapce from source to see any output or you can try looking in `AppData\Local\lapce\lapce-stable\data\logs` and attach it here

**Comment by rbharathkumar** [comment]
> > just wanted to add that I am facing similar issues in an Azure Virtual Desktop environment.
> 
> You need an actual GPU available in machine to run lapce

Oh so Virtual Desktops do not have GPU allocated to them ? Just asking - I do not know...
I also checked out the logs as you suggested in a different comment. I could not copy the content directly - so manually typing the content or atleast part of it. My Apologies...

**Error 01:** Failed to load from keymaps.toml - no keymaps
**Error 02:** thread 'main' panicked from at called `Result::unwrap()` on an `Err` value: Other(no avaible pixel format)': <path>\.cargo\git\checkouts\druid-<>\<>\druid-shell\src\backend\windows\window.rs

**Comment by rbharathkumar** [comment]
> > just wanted to add that I am facing similar issues in an Azure Virtual Desktop environment. Lapce portable just wouldn't start...
> > **Update Edit:** Tried version 0.2.4 on the same system - same results - not opening - no error - nothing... Tried version 0.2.4 on a **similar but different remote system**, getting the below error. Note - I have cut out part of the error which basically shows the path to the lapce executable. ![image](https://user-images.githubusercontent.com/38585383/219075679-9f0bbb83-a75a-48c5-a63b-9dd116528d23.png)
> 
> The second system's issue is #1137 / #132, which is due to us requiring a minimum windows version at this time. At a glance, I don't think the minimum-windows version is the cause of the issue author's problem. Though, that it failed to start for one of your systems (without even that error) might be the same as the issue author's problem.

So the other system I had mentioned was a Windows Server 2016 - So I am guessing - it will not be possible to run lapce here ?

**Comment by panekj** [comment]
> So the other system I had mentioned was a Windows Server 2016 - So I am guessing - it will not be possible to run lapce here ?

Create new issue.

**Comment by panekj** [comment]
@fnicolini could you provide your host and guest specs (CPU, CPU, OS)?

**Comment by panekj** [comment]
Also do you have vmware-tools installed, is the GPU acceleration enabled and how much memory is provided to guest?

**Comment by starchyunderscore** [comment]
Same issue, thought it might have something to do with visual studio c++ (that was a problem for me on other systems), so I tried without it installed and just the proper DLL files as well, though the video you see has vsc++ installed. https://youtu.be/YxkWSginSdg this is the latest (portable) version.

**Comment by starchyunderscore** [comment]
Note that it does create the lapce-data folder on first run (not in video), so the program is executing, it just stops before a GUI is displayed.

**Comment by panekj** [comment]
We use wgpu now
