### ISSUE TITLE
No code completion & plugin settings unclickable

### ISSUE THREAD

**Issue by realzhujunhao** [lapce/lapce#2148]
I am new to both rust and github, so this issue might not be a valid one.
I'm currently using MacOS m1, the version is
[Lapce-macos.dmg](https://github.com/lapce/lapce/releases/download/v0.2.5/Lapce-macos.dmg)
Highlight is OK but completion is not working. It seems lsp is not correctly configured.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/63294481/218731239-5a4b2a3e-f0cc-4aa9-81d0-6a89a40c8758.png">
<img width="728" alt="image" src="https://user-images.githubusercontent.com/63294481/218731380-0a7964f5-4bb6-4e57-8b16-24fe05f05418.png">
(and terminal looks weird)

**Comment by panekj** [comment]
> <img alt="image" width="728" src="https://user-images.githubusercontent.com/63294481/218731380-0a7964f5-4bb6-4e57-8b16-24fe05f05418.png">

It's your shell not setting terminal title

**Comment by realzhujunhao** [comment]
> > <img alt="image" width="728" src="https://user-images.githubusercontent.com/63294481/218731380-0a7964f5-4bb6-4e57-8b16-24fe05f05418.png">
> 
> It's your shell not setting terminal title

Thank you.
May I also get help on code completion? I appreciate that. : )

**Comment by panekj** [comment]
Did you install rust plugin?

**Comment by realzhujunhao** [comment]
> Did you install rust plugin?

No I did not. But as I said, I cannot access the plugin settings
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/63294481/218733418-31ebbcc4-b1e9-4c78-9c64-f0788f10b049.png">
It does not respond when I click it, while other setting tags works fine.

**Comment by panekj** [comment]
There is no plugin settings if you don't have any plugin installed

**Comment by realzhujunhao** [comment]
> There is no plugin settings if you don't have any plugin installed

Oh I see, I found one https://github.com/lapce/lapce-rust
But I don't know how I am able to install that.
Would you send a link for me to refer?

**Comment by panekj** [comment]
![image](https://user-images.githubusercontent.com/50457605/218734736-64f34928-6a82-4f10-af74-642180e9559e.png)

**Comment by realzhujunhao** [comment]
That solves all my problem. Thank you so much and you may close this issue. : )
