### ISSUE TITLE
Add ability to hide files in the sidebar

### ISSUE THREAD

**Issue by AstroOrbis** [lapce/lapce#2164]
Would it be possible to not have specific file/folder names show up in the sidebar?
ex: node_modules, .DS_Store, Cargo.lock, package-lock.json, etc etc etc

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/811

**Comment by AstroOrbis** [comment]
Thanks - searched "hide" and didn't find anything, guess I didn't look hard enough
