### ISSUE TITLE
GoToDefinition not working for Go (but working for Rust)

### ISSUE THREAD

**Issue by amcooper** [lapce/lapce#2168]
## Lapce Version

0.2.5

## System information

Arch Linux

## Describe the bug
`F12`/`Go To Definition` has no apparent effect in a Go project. I have the Go plugin installed (and `gopls` installed on my machine). The command works as expected in a Rust project.

**Comment by hbina** [comment]
Do you have the server path set in the plugin setting?

**Comment by amcooper** [comment]
That did it, @hbina . Thank you!
