### ISSUE TITLE
Add keybinding to swiching between source and header files

### ISSUE THREAD

**Issue by Aukstkalnis** [lapce/lapce#2174]
## Is your feature request related to a problem? Please describe.

I am trying Lapce for C development and started to miss VSCoce feature to easily switch between header and source files with Alt+o keybinding. This is helpful feature.  I think clangd has this feature but I am not sure.

## Describe the solution you'd like

So the feature should work as in VSCode. Alt+o opens header file with the same name as current source file. Pressing Alt+o again will jump back to source file. The header file can be in different folder then source file. The feature should work with C++ as well.

**Comment by panekj** [comment]
That can be only done by plugin.

**Comment by Aukstkalnis** [comment]
Ok, so I should register this issue to Clang plugin? Where I can find github page fro this plugin? In plugin's description there is no web page for bug tracking.
