### ISSUE TITLE
clangd plugin fails to load

### ISSUE THREAD

**Issue by liam-clink** [lapce/lapce#2181]
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 

0.2.5

## System information
the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04

Ubuntu 22.04LTS

## Describe the bug

After installing the C/C++ (clangd) plugin, it will not load, with a popup at the top right corner saying:

Plugin: C/C++ (clangd)
failed to find a pre-opened file descriptor through which "clangd-linux-15.0.6.zip" could be opened

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

The log entry corresponding to this is:
[2023-02-24][12:05:47][lapce_data::proxy][ERROR] failed to find a pre-opened file descriptor through which "clangd-linux-15.0.6.zip" could be opened

**Comment by hbina** [comment]
Environment variables are currently broken in WASM so the automatic download is not working. Can you try specifying the path to the LSP directly in the plugin settings?

**Comment by VladRico** [comment]
@liam-clink 
I've added this:
```
File: /home/user/.config/lapce-stable/settings.toml
[...]
[lapce-cpp-clangd.volt]
clangdVersion = "15.0.7" # git tag from https://github.com/clangd/clangd
serverPath = "/usr/bin/clangd"
serverArgs = [
    #custom args
]
```

and in the plugin settings:
```
File: /home/user/.local/share/lapce-stable/plugins/panekj.lapce-cpp-clangd/volt.toml

[...]
[config."volt.serverPath"]
default = "/usr/bin/clangd"
description = "Path to clangd"
[...]

```
and it works

**Comment by panekj** [comment]
That's wrong, there is no point in setting default path and overriding it in settings
Also setting tag is doing nothing when you set path to clangd
