### ISSUE TITLE
The title bar does not display properly at startup

### ISSUE THREAD

**Issue by EdenHell** [lapce/lapce#2187]
## Lapce Version
v0.2.5
## System information
windows 11

## Describe the bug
The title bar does not display properly at startup

## Additional information

![image](https://user-images.githubusercontent.com/5779655/221887848-5e8e43b8-cbd0-4be5-bdfc-a1dd675b5516.png)

**Comment by superlou** [comment]
Does this seem similar to https://github.com/lapce/lapce/issues/1014?

**Comment by EdenHell** [comment]
> 

Yes, it is the same one
