### ISSUE TITLE
0.2.6 doesn't run on Ubuntu Linux

### ISSUE THREAD

**Issue by dflock** [lapce/lapce#2196]
## Lapce Version

0.2.6

## System information

Ubuntu 22.04.2 LTS

## Describe the bug

If I run `~/bin/lapce --help` I get this:

```console
./lapce --help
Lapce 0.2.6

USAGE:
    lapce [OPTIONS] [PATHS]...

ARGS:
    <PATHS>...    

OPTIONS:
    -h, --help       Print help information
    -p, --proxy      
    -V, --version    Print version information
```

if I run `~/bin/lapce` I get nothing at all - no processes start, no windows open.

**Comment by panekj** [comment]
`RUST_LOG=debug ./lapce -w`

**Comment by dflock** [comment]
Crap, sorry, yes I was trying to run the proxy by mistake!
