### ISSUE TITLE
Lapce is missing icon in a lot of places for Gnome/Wayland

### ISSUE THREAD

**Issue by Porkepix** [lapce/lapce#2199]
## Lapce Version

0.2.6

## System information

ArchLinux, running Gnome & Wayland

## Describe the bug

Lapce icon is missing in activies view, application switcher, activities "dock" or top-side bar when lapce is on foreground.
It seems to be missing from everywhere excepted application list when pressing super key.

## Additional information

Screenshot of some of the affected cases:

![Screenshot from 2023-03-01 19-14-31](https://user-images.githubusercontent.com/709500/222227246-b28175a0-9edf-4cb8-b076-b9146d078f6b.png)
![Screenshot from 2023-03-01 19-14-44](https://user-images.githubusercontent.com/709500/222227249-6a043969-83d6-4cb1-b292-662c7866606b.png)

**Comment by kojq** [comment]
An interrelated issue is that new instances of the application can only be created from the original icon and not from a preexisting instance. In addition, these instances are treated as individual applications, so the multiple Lapce instances are shown individually on the application bar rather than once under the Lapce application icon.

**Comment by heftig** [comment]
The issue is that the app identifies itself to the compositor as `lapce` but the desktop entry is named `dev.lapce.lapce`.

```
> WAYLAND_DEBUG=1 lapce --wait |& grep app_id
[1675469.343]  -> xdg_toplevel@36.set_app_id("lapce")
```

**Comment by inglor** [comment]
Maybe it could help to add `StartupWMClass` ?

**Comment by Porkepix** [comment]
(For context, I reported it to the distro on https://bugs.archlinux.org/task/77772 as requested by @panekj on Matrix)

**Comment by panekj** [comment]
Fixed via #2228

**Comment by panekj** [comment]
![image](https://user-images.githubusercontent.com/50457605/224478477-00bb5da9-9d0c-4488-ae2e-02af3ce80012.png)

**Comment by heftig** [comment]
There's no set_app_id happening at all anymore.

**Comment by heftig** [comment]
Floem needs to use winit's `WindowAttributesExtWayland` and `WindowAttributesExtX11` to set the application name on its windows.

https://docs.rs/winit/latest/winit/platform/wayland/trait.WindowAttributesExtWayland.html#tymethod.with_name

https://docs.rs/winit/latest/winit/platform/x11/trait.WindowAttributesExtX11.html#tymethod.with_name

**Comment by ElSamhaa** [comment]
Same here.

**Comment by prisvrax** [comment]
Same
