### ISSUE TITLE
虽然BUG很多，但还是star+fork了

### ISSUE THREAD

**Issue by darvintang** [lapce/lapce#22]
不能调整窗口大小，全屏后只能强制退出

**Comment by dzhou121** [comment]
Thanks for the star.

Can you please let me know what's your OS/version etc?

感谢star+fork
请问你是什么操作系统，什么版本？

**Comment by darvintang** [comment]
![image](http://img.tcoding.cn/2021/12/14/4d3aacd93135e.png)

**Comment by dzhou121** [comment]
Are you running on the latest release v0.0.2 https://github.com/lapce/lapce/releases/tag/v0.0.2?

是运行的v0.0.2版本吗 https://github.com/lapce/lapce/releases/tag/v0.0.2

**Comment by darvintang** [comment]
嗯 0.0.2版本，窗口调整大小内容就乱了，黑色的缩到左上角去了，全屏后菜单栏出不来

**Comment by DawnMagnet** [comment]
同0.0.2 M1的MBA，也是同样的问题

**Comment by dzhou121** [comment]
试一下v0.0.4 https://github.com/lapce/lapce/releases/tag/v0.0.4

Can you please try the latest release. https://github.com/lapce/lapce/releases/tag/v0.0.4

**Comment by bugadani** [comment]
Hi and thank you for reporting this issue!

Could you please check if this issue has been fixed?
Thank you!
