### ISSUE TITLE
Crash when opening a folder

### ISSUE THREAD

**Issue by Jeyhey** [lapce/lapce#2200]
## Lapce Version
0.2.6

## System information
MacOS 13.2.1
Intel processor

## Describe the bug
Lapce crashes as soon as I chose a folder to open (File -> open folder -> ...)

## Additional information

Extract of the crash report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               lapce [17593]
Path:                  /Applications/Lapce.app/Contents/MacOS/lapce
Identifier:            io.lapce
Version:               0.2.6 (1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-03-01 20:37
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Bridge OS Version:     7.2 (20P3045)

Time Awake Since Boot: 57000 seconds
Time Since Wake:       106 seconds

System Integrity Protection: enabled

Crashed Thread:        12

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00001fc552740070
Exception Codes:       0x0000000000000001, 0x00001fc552740070

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [17593]

VM Region Info: 0x1fc552740070 is not in any region.  Bytes after previous region: 34927584063601  Bytes before following region: 70620763914128
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      VM_ALLOCATE (reserved)      11c345000-11c365000    [  128K] rw-/rwx SM=NUL  ...(unallocated)
--->  GAP OF 0x5ffee3c9b000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0:: main Dispatch queue: com.apple.main-thread
0   lapce                         	       0x103197dfa druid::contexts::LifeCycleCtx::register_child::h4385bbdf716ee2b7 + 714
1   lapce                         	       0x103a36ea0 druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h5114a9cf928cd5bb + 1984
2   lapce                         	       0x103a33235 druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h66f9b41a06872a64 + 949
3   lapce                         	       0x103a31533 _$LT$lapce_ui..editor..view..LapceEditorView$u20$as$u20$druid..widget..widget..Widget$LT$lapce_data..data..LapceTabData$GT$$GT$::lifecycle::h195999c42b121571 + 2675
4   lapce                         	       0x103a4c159 druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h998dc30492c88f0c + 905
5   lapce                         	       0x103a071ed _$LT$druid..widget..padding..Padding$LT$T$C$W$GT$$u20$as$u20$druid..widget..widget..Widget$LT$T$GT$$GT$::lifecycle::h8afd829cc5dcefa6 + 13
6   lapce                         	       0x10397e50e druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h839bc5aca0559c0b + 910
7   lapce                         	       0x103a6daf5 _$LT$lapce_ui..split..LapceSplit$u20$as$u20$druid..widget..widget..Widget$LT$lapce_data..data..LapceTabData$GT$$GT$::lifecycle::h4df51e0aa57732c0 + 85
8   lapce                         	       0x10397e50e druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h839bc5aca0559c0b + 910
9   lapce                         	       0x103b68a7a druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h464d6508a631663a + 1722
10  lapce                         	       0x10397e50e druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h839bc5aca0559c0b + 910
11  lapce                         	       0x103b5f5a6 druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h2a35c91d59e50847 + 966
12  lapce                         	       0x10397e50e druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h839bc5aca0559c0b + 910
13  lapce                         	       0x10398e655 druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::hb273e6eb6e08f68b + 1141
14  lapce                         	       0x10393dc44 _$LT$druid..widget..lens_wrap..LensWrap$LT$T$C$U$C$L$C$W$GT$$u20$as$u20$druid..widget..widget..Widget$LT$T$GT$$GT$::lifecycle::hef34d3b74fec7784 + 676
15  lapce                         	       0x103c35611 druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h6bc0bc52bf71346b + 1441
16  lapce                         	       0x103c3510c druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h6bc0bc52bf71346b + 156
17  lapce                         	       0x103c2c7a5 _$LT$druid..widget..lens_wrap..LensWrap$LT$T$C$U$C$L$C$W$GT$$u20$as$u20$druid..widget..widget..Widget$LT$T$GT$$GT$::lifecycle::hd866743d096ae1d8 + 341
18  lapce                         	       0x103c1891d druid::core::WidgetPod$LT$T$C$W$GT$::lifecycle::h61d99373cdff2134 + 1149
19  lapce                         	       0x103c18000 druid::window::Window$LT$T$GT$::lifecycle::hbfbe23d2d5dd4a95 + 704
20  lapce                         	       0x103c162c2 druid::window::Window$LT$T$GT$::post_event_processing::hfd96d0821472b18c + 274
21  lapce                         	       0x103c1d084 druid::window::Window$LT$T$GT$::event::h9923c710b03e00b7 + 10372
22  lapce                         	       0x103c1a061 druid::win_handler::InnerAppState$LT$T$GT$::dispatch_cmd::hfbfb66b6b882dbb6 + 1777
23  lapce                         	       0x103c0fc3b druid::win_handler::AppState$LT$T$GT$::handle_cmd::hf6360620b372c563 + 3819
24  lapce                         	       0x103c28d4c druid::win_handler::AppState$LT$T$GT$::handle_dialog_response::hfdbe8cd43dab657a + 1340
25  lapce                         	       0x103c2607c _$LT$druid..win_handler..DruidHandler$LT$T$GT$$u20$as$u20$druid_shell..window..WinHandler$GT$::save_as::hf5a0637e2b437a37 + 76
26  lapce                         	       0x1031b9699 _$LT$X$u20$as$u20$block..IntoConcreteBlock$LT$$LP$A$C$$RP$$GT$$GT$::into_concrete_block::concrete_block_invoke_args1::h0288c606f6dc47de + 1497
27  AppKit                        	    0x7ff812740838 -[NSSavePanel didEndPanelWithReturnCode:] + 114
28  AppKit                        	    0x7ff812740160 -[NSSavePanel completeModeless:] + 23
29  AppKit                        	    0x7ff81274047a -[NSSavePanel completeWithReturnCode:url:urls:] + 640
30  AppKit                        	    0x7ff81273e130 -[NSSavePanel observeMostRecentCompletion:] + 451
31  AppKit                        	    0x7ff81273db74 -[NSSavePanel observeValueForKeyPath:ofObject:change:context:] + 460
32  Foundation                    	    0x7ff80f929320 NSKeyValueNotifyObserver + 306
33  Foundation                    	    0x7ff80f9e44a1 NSKeyValueDidChange + 431
34  Foundation                    	    0x7ff80feced92 NSKeyValueDidChangeWithPerThreadPendingNotifications + 146
35  ViewBridge                    	    0x7ff816ab3a4d __47-[NSViewBridge setObject:forKey:withKVO:local:]_block_invoke + 360
36  ViewBridge                    	    0x7ff816b3ca3f withHintInProgress + 198
37  ViewBridge                    	    0x7ff816ab3711 -[NSViewBridge setObject:forKey:withKVO:local:] + 652
38  ViewBridge                    	    0x7ff816b1a97e -[NSRemoteViewMarshal setHostObject:forKey:] + 291
39  CoreFoundation                	    0x7ff80eaddb0c __invoking___ + 140
40  CoreFoundation                	    0x7ff80eadd9a9 -[NSInvocation invoke] + 305
41  ViewBridge                    	    0x7ff816aaab92 __deferNSXPCInvocationOntoMainThread_block_invoke + 164
42  ViewBridge                    	    0x7ff816a9f17b __wrapBlockWithVoucher_block_invoke + 37
43  ViewBridge                    	    0x7ff816b3b5f9 kNotRunningOnAppKitCompatibleThread_block_invoke + 323
44  CoreFoundation                	    0x7ff80eaf97cc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
45  CoreFoundation                	    0x7ff80eaf9702 __CFRunLoopDoBlocks + 406
46  CoreFoundation                	    0x7ff80eaf8a62 __CFRunLoopRun + 2184
47  CoreFoundation                	    0x7ff80eaf7b60 CFRunLoopRunSpecific + 560
48  HIToolbox                     	    0x7ff818445766 RunCurrentEventLoopInMode + 292
49  HIToolbox                     	    0x7ff818445576 ReceiveNextEventCommon + 679
50  HIToolbox                     	    0x7ff8184452b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
51  AppKit                        	    0x7ff811c482f3 _DPSNextEvent + 909
52  AppKit                        	    0x7ff811c47174 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
53  AppKit                        	    0x7ff811c397b7 -[NSApplication run] + 586
54  lapce                         	       0x103c08f92 lapce_ui::app::launch::h3c7b1f5a6d174775 + 17266
55  lapce                         	       0x102f80346 std::sys_common::backtrace::__rust_begin_short_backtrace::ha9ee8fe6cc287d9a + 6
56  lapce                         	       0x102f805fc main + 668
57  dyld                          	    0x7ff80e6eb310 start + 2432

**Comment by sid3r** [comment]
Have the same issue, first install and first launch. when trying to open folder from top menu.
'''
Process:               lapce [76755]
Path:                  /Applications/Lapce.app/Contents/MacOS/lapce
Identifier:            io.lapce
Version:               0.2.6 (1)
Code Type:             X86-64 (Native)
'''

MacOS: 11.6.5

**Comment by thelibrarian** [comment]
This seems to be fixed in the latest nightly release.

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/2209
