### ISSUE TITLE
Remote proxy keeps re-installing

### ISSUE THREAD

**Issue by peterjc123** [lapce/lapce#2202]
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 
0.2.6

## System information
Host: OSX
Remote: Linux

## Describe the bug
It keeps reinstalling `lapce-proxy` if the Lapce is reopened

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

```
[2023-03-02][15:26:15][lapce_data::proxy::upload_file][DEBUG] [DEBUG]: Current proxy version: Lapce 0.2.6
[DEBUG]: New proxy version: v0.2.6
Proxy outdated. Replacing proxy
```

**Comment by peterjc123** [comment]
Workaround:
Open Lapce and establish the remote connection. Open a separate terminal and connect to the remote machine using SSH, and make the following changes to `/tmp/lapce-proxy.sh`.
```diff
-  lapce_installed_ver=$("${lapce_dir}/lapce" --version | cut -d'v' -f2)
+  lapce_installed_ver=$("${lapce_dir}/lapce" --version | cut -d' ' -f2)

-   if [ "${lapce_installed_ver}" = "${lapce_new_ver}" ]; then
+   if [ "v${lapce_installed_ver}" = "${lapce_new_ver}" ]; then 
```
And then use `chattr +i /tmp/lapce-proxy.sh` to make the file readonly.

**Comment by non-descriptive** [comment]
I think the reason why it keeps reinstalling - it fails to recognize where is current version of lapce installed. On windows it downloads installer and install Lapce into default program location - "C:\Program Files\Lapce\". If lapce was build from source or installed via `cargo` and exists in `PATH` it will launch outdated version, and since it's binary wasn't affected - will try to suggest to install newer version.

**Comment by peterjc123** [comment]
> I think the reason why it keeps reinstalling - it fails to recognize where is current version of lapce installed. On windows it downloads installer and install Lapce into default program location - "C:\Program Files\Lapce". If lapce was build from source or installed via `cargo` and exists in `PATH` it will launch outdated version, and since it's binary wasn't affected - will try to suggest to install newer version. Similar behaviour must be on the linux.

Nope, it is different here. As you can see in the log, the version is correctly detected, just the format doesn't match.

**Comment by peterjc123** [comment]
@panekj It seems this issue is still here. I have Lapce 0.3.0.

**Comment by peterjc123** [comment]
Log:
```bash
+ lapce_new_ver=v0.3.0
+ eval 'lapce_dir='\''/home/admin/.local/share/lapce-stable/proxy'\'''
++ lapce_dir=/home/admin/.local/share/lapce-stable/proxy
+ case "${lapce_new_ver}" in
++ echo v0.3.0
++ cut -dv -f2
+ lapce_new_version=0.3.0
+ lapce_new_ver_tag=v0.3.0
+ '[' -e /home/admin/.local/share/lapce-stable/proxy/lapce ']'
++ /home/admin/.local/share/lapce-stable/proxy/lapce --version
++ cut '-d ' -f2
+ lapce_installed_ver=v0.3.0
+ printf '[DEBUG]: Current proxy version: %s\n' v0.3.0
[DEBUG]: Current proxy version: v0.3.0
+ printf '[DEBUG]: New proxy version: %s\n' 0.3.0
[DEBUG]: New proxy version: 0.3.0
+ '[' v0.3.0 = 0.3.0 ']'
+ printf 'Proxy outdated. Replacing proxy\n'
Proxy outdated. Replacing proxy
```

**Comment by peterjc123** [comment]
New workaround for 0.3.0:
Open Lapce, establish the remote connection and wait for the button to become green. Open a separate terminal and connect to the remote machine using SSH, and then:
```bash
cd ~/.local/share/lapce-stable/proxy
mv lapce lapce.real
cat > lapce << EOF
#!/bin/bash

if [[ "$@" == "--version" ]]; then
  ~/.local/share/lapce-stable/proxy/lapce.real $@ | tr -d 'v'
else
  ~/.local/share/lapce-stable/proxy/lapce.real $@
fi
EOF
chmod +x lapce
```
And then you may restart Lapce.
