### ISSUE TITLE
In terminal, backspace deletes a whole word instead of a character

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#221]

**Comment by MinusGix** [comment]
I'll note that I don't see this issue on Linux, so it is perhaps Windows-specific

**Comment by keeslinp** [comment]
On macos hitting backspace does nothing at all for me. I can enter characters just fine but I can't backspace to delete them.

**Comment by keeslinp** [comment]
This was on a freshly compiled version yesterday.

**Comment by justinfarrelldev** [comment]
Everything including backspace is working flawlessly in my terminal. I am also on MacOS (Monterey 12.2.1 on a Macbook Pro 2015), but I am using Fish as my shell. Maybe it's an issue with bash/zsh?

**Comment by bugadani** [comment]
Eh, usually I'm the one asking for this information, but now I failed to provide it: this issue happens on Windows, using PowerShell.

**Comment by hasali19** [comment]
I have the same issue using wsl with zsh, where I have `bindkey '^H' backward-kill-word` set in my .zshrc to delete a word on `ctrl+backspace`. This works as expected when using windows terminal, with normal backspace only deleting a single character, but with lapce it always deletes a word. If I disable the keybind then it works normally, so I guess lapce is sending the wrong command for backspace?
