### ISSUE TITLE
New file created in Lapce does not save

### ISSUE THREAD

**Issue by kojq** [lapce/lapce#2210]
### Bug description
1) Create a new file in Lapce with `CTRL + n`
1) Write to the file
1) Save the file
1) The file does not save

Preexisting files on disk can be saved in Lapce just fine.

### Lapce Version

`0.2.6`

### System information

`Arch Linux` (a vanilla install that is up to date at the time of posting)

Time of posting:
```
5:45 PM
Sunday, March 5, 2023
Coordinated Universal Time (UTC)
```

Notable packages installed:
- `gnome`
- `vulkan-radeon`
- `nvidia`

**Comment by kristianpennacchia** [comment]
I'm experiencing the same issue on macOS 13.2.1

**Comment by millsapjohn** [comment]
experiencing the same on Windows 11.

**Comment by PhysicsDan** [comment]
Also experiencing this on 0.2.6 on MacOS 13.2.1

Note, that it is only an issue when using `ctrl + n` or `File -> New File`.  When you create a new file using the "file browser" within Lapce (`right click -> New File`) the file will save without any issues.

Keep up the great work.

**Comment by hbina** [comment]
Should be fixed by https://github.com/lapce/lapce/pull/2225
Regression from https://github.com/lapce/lapce/pull/2131
