### ISSUE TITLE
Highlight all occurrences of the selected variable / text in the current document

### ISSUE THREAD

**Issue by hakro** [lapce/lapce#2212]
It would be really useful to have all occurrences of the selected text highlighted.

![2023-03-05_23-01](https://user-images.githubusercontent.com/3624853/222988464-22779fce-0547-48bd-aff1-6432dc4c8b01.png)

This helps spot where the variable is used in the document.

Thank you !

**Comment by tk103331** [comment]
@hakro  hello hakro，I just implemented this feature.

see https://github.com/lapce/lapce/pull/2222

**Comment by hakro** [comment]
It's Christmas everyday. Thank you very much :)
I'll give it a test today.
