### ISSUE TITLE
Add code folding

### ISSUE THREAD

**Issue by hakro** [lapce/lapce#2214]
Hi !

It would be great to be able to fold function, methods, classes ..., to simplify code readability in the main editor : 

![2023-03-05_23-21](https://user-images.githubusercontent.com/3624853/222989236-e61cb9d6-7a62-435c-82f4-5866a8d90bd6.png)

Thx !

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/749

**Comment by hakro** [comment]
Sorry for the noise, I did do a search of the open issues, but somehow I missed 749
Thank you :)
