### ISSUE TITLE
Select theme from settings menu

### ISSUE THREAD

**Issue by eirnym** [lapce/lapce#2220]
## Is your feature request related to a problem? Please describe.

I have installed a few theme plugins, I can't switch themes in settings (cmd-,). Currently, the only way is to use "command pallete".

## Describe the solution you'd like

Settings contain `Theme settings` and `UI Settings`. I'd like to have a dropdown menu to select a theme which will be applied after selection

## Describe alternatives you've considered

`Command pallete` is nice, but too hacky way to set UI theme

**Comment by panekj** [comment]
There is already a dropdown menu for themes
![image](https://user-images.githubusercontent.com/50457605/223836779-47ffc629-2071-4401-bc98-ebb67360fc5c.png)

**Comment by eirnym** [comment]
Ok, it's in a place I'd never search. It belongs to UI or theme settings, not to Core settings!
