### ISSUE TITLE
Theme in settings doesn't represent selected one

### ISSUE THREAD

**Issue by eirnym** [lapce/lapce#2221]
## Lapce Version

0.2.6

## System information

macOS Monterey M2

## Describe the bug

Select theme, using command palette, settings won't represent selected theme

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

**Comment by hbina** [comment]
I can't reproduce this. Perhaps the theme that you are trying to change into is corrupted or badly formatted? AFAIK, there are no visual feedback to this kind of issues.

**Comment by eirnym** [comment]
yep, I've downloaded plugins and switching between them. I can reproduce the issue 100% of time.

Ayu
Aleph
Aura Theme
Catppuccin
Alabaster
Material Icon theme
Visual Studio Code Themes
Tokio Night
Rust
Python (python-lsp-server)

**Comment by eirnym** [comment]
Please, have in mind, that it's need to be switched using command palette, not using settings

**Comment by eirnym** [comment]
if os is important, my is macOS Monterey on M2

**Comment by panekj** [comment]
Can't reproduce
