### ISSUE TITLE
Immediate crash on Asahi Linux with no debug output

### ISSUE THREAD

**Issue by AmateurECE** [lapce/lapce#2230]
## Lapce Version

HEAD of master, also present on 0.2.5

## System information

Asahi Linux (Arch Linux ARM) on Apple M1 Macbook Pro

## Describe the bug
At some point, it looks like lapce stopped being able to run on Asahi Linux. Issue #976 (closed) indicates that it did work at one point, but neither the latest release, nor the HEAD of master are able to run.

Executing `cargo run` from the root of the repository completes successfully, but the lapce window does not appear, and no debug output is produced. The same behavior is produced when running the 0.2.5 version installed from the community repository.

I've also tried switching from Sway to Plasma, and the behavior was the same for both environments.

## Additional information

I have not been able to determine a workaround, and not been able to exhume any log files. I have been able to get Lapce working on x86_64 with Arch Linux and Sway, so I believe it must be something related to specifically the M1 platform. If there are any suggestions to produce a debug log, I'd be happy to do so and provide it for further investigation!

**Comment by panekj** [comment]
Does Asahi have OpenGL 3 with hardware acceleration?

**Comment by AmateurECE** [comment]
Ah, sure enough, `glxinfo` shows that OpenGL only up to 2.0 is supported using the gpu driver. How silly of me! Thanks very much for your quick reply. I look forward to the day that I can run lapce with hardware acceleration.

**Comment by cal97g** [comment]
Is there a way to run lapce without hardware acceleration?

**Comment by cal97g** [comment]
There is a way to run lapce in software only mode.

`LIBGL_ALWAYS_SOFTWARE=1 lapce`

https://discord.com/channels/946858761413328946/946858761413328949/1089305707150590003

**Comment by Kuratius** [comment]
MESA_LOADER_DRIVER_OVERRIDE=zink ./lapce seems to work on raspberry pi 4, though I'm unsure if it has better performance than software rendering.

**Comment by rlueder** [comment]
Quick update in case it saves someone else some time.

As the OP I'm trying to run Lapce on Asahi Linux M1 Macbook Pro (2021) and neither the [Flatpak version](https://flathub.org/apps/dev.lapce.lapce) or the [pre-built releases](https://github.com/lapce/lapce/releases) worked. The solution was to [compile from source following the steps here](https://github.com/lapce/lapce/blob/master/docs/building-from-source.md) and it worked without any other tweaks needed.

Also be aware that updating through the in-app notification `Restart to update (nightly-xxxxxxx)` will not work as it'll download a pre-built release.

For reference, the error message when trying to run the pre-built release on Asahi is below:

```
qemu-x86_64-static: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```
