### ISSUE TITLE
No javascript and typescript support

### ISSUE THREAD

**Issue by elo1lson** [lapce/lapce#2233]
I like the editor, it's wonderful, but it still lacks many features, including support for typescript and javascript, there's no way to program in an editor without auto-complete or anything (better to use a note editor lol), there's even a plugin, but I've tried everything, it doesn't work

**Comment by hbina** [comment]
Do you use `nvm` to manage your node versions?

**Comment by elo1lson** [comment]
@hbina No,I don't use it, why? Oh, and I know where the node, typescript and typescript-language-server are installed, it doesn't matter how I configure the server, it can be the relative path like $PATH, it doesn't work

**Comment by panekj** [comment]
It's responsibility of a plugin to provide language capabilities
