### ISSUE TITLE
It's responsibility of a plugin to provide language capabilities

### ISSUE THREAD

**Issue by elo1lson** [lapce/lapce#2237]
It's responsibility of a plugin to provide language capabilities

_Originally posted by @panekj in https://github.com/lapce/lapce/issues/2233#issuecomment-1465392406_

        But I installed the plugin, a plugin that's up to you, TS/JS

**Comment by elo1lson** [comment]
I installed the plugin, in the plugin description it says how to configure it (in a rude way), it doesn't say where the configuration file has to be in the workspace, but I managed to find this file in ~/.config/lapce-stable (I found that also in the settings), I did it the way I asked, and it doesn't work

**Comment by panekj** [comment]
If it doesn't work, issue should be opened in [`lapce-typescrip`](https://github.com/panekj/lapce-typescript) bug tracker. Also you don't have to create new issue to talk about the problem.

> But I installed the plugin, a plugin that's up to you, TS/JS

The plugin is not maintained by Lapce devs.
