### ISSUE TITLE
Add promo image for GitHub.

### ISSUE THREAD

**Issue by Alex313031** [lapce/lapce#2249]
## Lapce Version

0.2.6

## System information

Ubuntu 23.04

## Describe the bug
We should add a promo image, i.e. in Settings under "Social Preview". I have made one that I am using in my fork.
I didn't make a pull request because I have made some other changes in my repo that you guys wouldn't want (compiling with AVX via rustflags)

Here it is > https://github.com/Alex313031/lapce-ng/blob/master/icons/promo.png

**Comment by dzhou121** [comment]
It would be best if you could send a PR in? We can’t just grab stuff you’ve made.
