### ISSUE TITLE
Build warnings on Kubuntu 20.04 -- but lapce runs after build

### ISSUE THREAD

**Issue by rajames429** [lapce/lapce#225]
I am running  Kubuntu 20.04 in a guest Virtual Machine in VBox on a Windows 10 Pro x64 host: 

$ uname -a
        Linux LWKFF001 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

I am running Rust version: 
$ rustc --version
        rustc 1.59.0 (9d1b2106e 2022-02-23)

I followed the instructions to Build lapce from source:  
Install the Rust compiler with rustup
        Install rustup.rs.
I installed the dependencies for Ubuntu: 
        sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev

Then I built the project with 
        cargo build --release

The output from the build process is below -- It produced multiple warnings.  

Then I changed my directory to .../target/release 
Then I run the executable 
        ./lapce 

This is the output I receive 
        Projects/git/lapce/target/release$ ./lapce
        libEGL warning: DRI2: failed to authenticate
        WARNING: lavapipe is not a conformant vulkan implementation, testing use only.

There were no errors prior to the following truncated output  
This is the output from the build process....

      Downloaded crossbeam-utils v0.8.5
      Downloaded crossbeam-utils v0.6.6
      Downloaded clicolors-control v0.2.0
      Downloaded crc32fast v1.2.1
      Downloaded const_fn v0.4.8
      Downloaded 467 crates (41.1 MB) in 4.57s (largest was `openssl-src` at 5.1 MB)
       Compiling libc v0.2.101
       Compiling proc-macro2 v1.0.36
       Compiling unicode-xid v0.2.2
       Compiling cfg-if v1.0.0
       Compiling autocfg v1.0.1
       Compiling syn v1.0.86
       Compiling version_check v0.9.3
       Compiling once_cell v1.8.0
       Compiling memchr v2.4.1
       Compiling bitflags v1.2.1
       Compiling lazy_static v1.4.0
       Compiling pkg-config v0.3.19
       Compiling serde_derive v1.0.130
       Compiling log v0.4.14
       Compiling serde v1.0.130
       Compiling smallvec v1.6.1
       Compiling stable_deref_trait v1.2.0
       Compiling fallible-iterator v0.2.0
       Compiling adler v1.0.2
       Compiling rustc-demangle v0.1.21
       Compiling scopeguard v1.1.0
       Compiling xml-rs v0.8.4
       Compiling regex-syntax v0.6.25
       Compiling proc-macro-hack v0.5.19
       Compiling pin-project-lite v0.2.7
       Compiling cfg-if v0.1.10
       Compiling slab v0.4.4
       Compiling parking_lot_core v0.8.5
       Compiling rustc-hash v1.1.0
       Compiling fixedbitset v0.2.0
       Compiling rand_core v0.4.2
       Compiling bytecheck v0.6.7
       Compiling ident_case v1.0.1
       Compiling strsim v0.10.0
       Compiling futures-core v0.3.17
       Compiling unicode-width v0.1.8
       Compiling rustversion v1.0.6
       Compiling fnv v1.0.7
       Compiling rend v0.3.6
       Compiling matches v0.1.9
       Compiling crossbeam-utils v0.8.5
       Compiling crc32fast v1.2.1
       Compiling rkyv v0.7.28
       Compiling arrayvec v0.5.2
       Compiling itoa v0.4.8
       Compiling minimal-lexical v0.1.2
       Compiling maybe-uninit v2.0.0
       Compiling proc-macro-nested v0.1.7
       Compiling seahash v4.1.0
       Compiling downcast-rs v1.2.0
       Compiling futures-channel v0.3.17
       Compiling target-lexicon v0.12.2
       Compiling futures-task v0.3.17
       Compiling scoped-tls v1.0.0
       Compiling ryu v1.0.5
       Compiling futures-sink v0.3.17
       Compiling ucd-trie v0.1.3
       Compiling either v1.6.1
       Compiling typenum v1.13.0
       Compiling byteorder v1.4.3
       Compiling futures-io v0.3.17
       Compiling pin-utils v0.1.0
       Compiling anyhow v1.0.43
       Compiling percent-encoding v2.1.0
       Compiling crossbeam-epoch v0.9.5
       Compiling unicode-bidi v0.3.6
       Compiling same-file v1.0.6
       Compiling bytes v1.1.0
       Compiling more-asserts v0.2.2
       Compiling autocfg v0.1.7
       Compiling cranelift-entity v0.76.0
       Compiling wasmparser v0.78.2
       Compiling serde_json v1.0.67
       Compiling linked-hash-map v0.5.4
       Compiling semver-parser v0.7.0
       Compiling cranelift-codegen-shared v0.76.0
       Compiling tinyvec_macros v0.1.0
       Compiling scopeguard v0.3.3
       Compiling fixedbitset v0.4.0
       Compiling const_fn v0.4.8
       Compiling ahash v0.4.7
       Compiling arrayvec v0.4.12
       Compiling khronos-egl v4.1.0
       Compiling rayon-core v1.9.1
       Compiling base64 v0.13.0
       Compiling termcolor v1.1.2
       Compiling bit-vec v0.6.3
       Compiling ash v0.34.0+1.2.203
       Compiling cty v0.2.2
       Compiling nodrop v0.1.14
       Compiling cfg_aliases v0.1.1
       Compiling unic-char-range v0.9.0
       Compiling openssl v0.10.38
       Compiling tinystr v0.3.4
       Compiling hexf-parse v0.2.1
       Compiling unic-common v0.9.0
       Compiling unicode-general-category v0.2.0
       Compiling foreign-types-shared v0.1.1
       Compiling leb128 v0.2.5
       Compiling glow v0.11.2
       Compiling httparse v1.5.1
       Compiling memoffset v0.2.1
       Compiling native-tls v0.2.8
       Compiling openssl-probe v0.1.4
       Compiling encoding_rs v0.8.30
       Compiling arrayvec v0.7.1
       Compiling profiling v1.0.3
       Compiling inplace_it v0.3.3
       Compiling renderdoc-sys v0.7.1
       Compiling lazycell v1.3.0
       Compiling xmlparser v0.13.3
       Compiling ttf-parser v0.12.3
       Compiling unicode-script v0.5.3
       Compiling float-cmp v0.5.3
       Compiling signal-hook v0.3.13
       Compiling remove_dir_all v0.5.3
       Compiling wasmer-compiler-cranelift v2.1.1
       Compiling unicode-ccc v0.1.2
       Compiling siphasher v0.2.3
       Compiling crossbeam-utils v0.5.0
       Compiling copyless v0.1.5
       Compiling ttf-parser v0.9.0
       Compiling fastrand v1.7.0
       Compiling unicode-bidi-mirroring v0.1.0
       Compiling try-lock v0.2.3
       Compiling pico-args v0.4.2
       Compiling httpdate v1.0.2
       Compiling lexical-core v0.7.6
       Compiling matrixmultiply v0.1.15
       Compiling xmlwriter v0.1.0
       Compiling glob v0.3.0
       Compiling utf8parse v0.2.0
       Compiling cpufeatures v0.2.1
       Compiling unicode-vo v0.1.0
       Compiling dtoa v0.4.8
       Compiling opaque-debug v0.3.0
       Compiling Inflector v0.11.4
       Compiling rctree v0.3.3
       Compiling unicode-segmentation v1.8.0
       Compiling bytecount v0.6.2
       Compiling tower-service v0.3.1
       Compiling float-ord v0.2.0
       Compiling lazy_static v0.2.11
       Compiling ndarray v0.11.2
       Compiling rand_core v0.5.1
       Compiling druid-shell v0.7.0 (https://github.com/lapce/druid#ce620508)
       Compiling rawpointer v0.1.0
       Compiling static_assertions v1.1.0
       Compiling nameof v1.2.2
       Compiling ansi_term v0.12.1
       Compiling serde v0.8.23
       Compiling vec_map v0.8.2
       Compiling ansi_term v0.11.0
       Compiling ipnet v2.3.1
       Compiling strsim v0.8.0
       Compiling mime v0.3.16
       Compiling rust-ini v0.13.0
       Compiling xi-unicode v0.3.0
       Compiling bit-vec v0.5.1
       Compiling home v0.5.3
       Compiling diff v0.1.12
       Compiling strum v0.19.5
       Compiling libloading v0.7.0
       Compiling instant v0.1.10
       Compiling indexmap v1.7.0
       Compiling miniz_oxide v0.4.4
       Compiling memoffset v0.6.4
       Compiling num-traits v0.2.14
       Compiling futures-macro v0.3.17
       Compiling futures-util v0.3.17
       Compiling rayon v1.5.1
       Compiling num-integer v0.1.44
       Compiling ahash v0.7.6
       Compiling nom v7.0.0
       Compiling proc-macro-error-attr v1.0.4
       Compiling proc-macro-error v1.0.4
       Compiling standback v0.2.17
       Compiling generic-array v0.14.4
       Compiling time v0.2.27
       Compiling glam v0.10.2
       Compiling nom v5.1.2
       Compiling im v15.0.0
       Compiling thread_local v1.1.3
       Compiling tracing-core v0.1.19
       Compiling sharded-slab v0.1.3
       Compiling wayland-sys v0.28.6
       Compiling wayland-sys v0.29.4
       Compiling servo-fontconfig-sys v5.1.0
       Compiling x11-dl v2.18.5
       Compiling smithay-client-toolkit v0.15.3
       Compiling owning_ref v0.4.1
       Compiling lock_api v0.4.5
       Compiling regex-automata v0.1.10
       Compiling crossbeam-utils v0.6.6
       Compiling generational-arena v0.2.8
       Compiling type-map v0.4.0
       Compiling rand_core v0.3.1
       Compiling rand_jitter v0.1.4
       Compiling textwrap v0.11.0
       Compiling data-url v0.1.0
       Compiling pest v2.1.3
       Compiling itertools v0.7.11
       Compiling itertools v0.10.3
       Compiling fxhash v0.2.1
       Compiling form_urlencoded v1.0.1
       Compiling walkdir v2.3.2
       Compiling rand_pcg v0.1.2
       Compiling rand_chacha v0.1.1
       Compiling rand v0.6.5
       Compiling http v0.2.5
       Compiling yaml-rust v0.4.5
       Compiling semver v0.9.0
       Compiling cranelift-codegen-meta v0.76.0
       Compiling tinyvec v1.3.1
       Compiling hashbrown v0.9.1
       Compiling codespan-reporting v0.11.1
       Compiling bit-set v0.5.2
       Compiling raw-window-handle v0.4.2
       Compiling cranelift-bforest v0.76.0
       Compiling wgpu-core v0.12.1
       Compiling unic-char-property v0.9.0
       Compiling unic-langid-impl v0.9.0
       Compiling unic-ucd-version v0.9.0
       Compiling foreign-types v0.3.2
       Compiling wast v38.0.1
       Compiling roxmltree v0.14.1
       Compiling svgtypes v0.5.0
       Compiling rand_xoshiro v0.4.0
       Compiling heck v0.3.3
       Compiling dlib v0.5.0
       Compiling fuzzy-matcher v0.3.7
       Compiling tracing-subscriber v0.2.20
       Compiling lock_api v0.1.5
       Compiling rand_xorshift v0.1.1
       Compiling rand_isaac v0.1.1
       Compiling rand_hc v0.1.0
       Compiling semver-parser v0.10.2
       Compiling http-body v0.4.4
       Compiling rustc_version v0.2.3
       Compiling cranelift-codegen v0.76.0
       Compiling unicode-normalization v0.1.19
       Compiling unic-langid v0.9.0
       Compiling unic-ucd-bidi v0.9.0
       Compiling wat v1.0.40
       Compiling getrandom v0.2.3
       Compiling thread-id v4.0.0
       Compiling num_cpus v1.13.1
       Compiling net2 v0.2.37
       Compiling iovec v0.1.4
       Compiling memmap2 v0.2.3
       Compiling signal-hook-registry v1.4.0
       Compiling memmap2 v0.3.1
       Compiling inotify-sys v0.1.5
       Compiling memmap2 v0.5.0
       Compiling dirs-sys v0.3.6
       Compiling rand v0.5.6
       Compiling dirs-sys-next v0.1.2
       Compiling tempfile v3.3.0
       Compiling socket2 v0.4.2
       Compiling which v4.2.2
       Compiling filetime v0.2.15
       Compiling atty v0.2.14
       Compiling rand_os v0.1.3
       Compiling termios v0.3.3
       Compiling clicolors-control v0.2.0
       Compiling fs2 v0.4.3
       Compiling time v0.1.44
       Compiling quote v1.0.15
       Compiling jobserver v0.1.24
       Compiling xcb v0.9.0
       Compiling object v0.26.2
       Compiling aho-corasick v0.7.18
       Compiling bstr v0.2.17
       Compiling grep-matcher v0.1.5
       Compiling region v3.0.0
       Compiling nix v0.20.0
       Compiling gpu-alloc-types v0.2.0
       Compiling gpu-descriptor-types v0.1.1
       Compiling wgpu-types v0.12.0
       Compiling keyboard-types v0.5.0
       Compiling mio v0.7.13
       Compiling regalloc v0.0.31
       Compiling simplecss v0.2.1
       Compiling want v0.3.0
       Compiling mio v0.8.0
       Compiling fern v0.6.0
       Compiling crossbeam-channel v0.5.1
       Compiling smallvec v0.6.14
       Compiling semver v0.11.0
       Compiling bitmaps v2.1.0
       Compiling parking_lot_core v0.3.1
       Compiling idna v0.2.3
       Compiling crossbeam-epoch v0.5.2
       Compiling crossbeam-epoch v0.6.1
       Compiling fluent-langneg v0.13.0
       Compiling intl_pluralrules v7.0.1
       Compiling intl-memoizer v0.5.1
       Compiling unic-bidi v0.9.0
       Compiling encoding_rs_io v0.1.7
       Compiling mio v0.6.23
       Compiling fontdb v0.5.4
       Compiling inotify v0.7.1
       Compiling inotify v0.9.6
       Compiling dirs v3.0.2
       Compiling directories v4.0.1
       Compiling dirs-next v2.0.0
       Compiling clap v2.33.3
       Compiling wayland-scanner v0.28.6
       Compiling wayland-scanner v0.29.4
       Compiling vte_generate_state_changes v0.1.1
       Compiling flate2 v1.0.22
       Compiling nix v0.22.2
       Compiling euclid v0.22.6
       Compiling spirv v0.2.0+1.5.4
       Compiling sid v0.6.1
       Compiling float_next_after v0.1.5
       Compiling num-traits v0.1.43
       Compiling num-complex v0.1.43
       Compiling cc v1.0.69
       Compiling regex v1.5.4
       Compiling gpu-alloc v0.5.0
       Compiling gpu-descriptor v0.2.1
       Compiling wayland-commons v0.28.6
       Compiling tokio v1.15.0
       Compiling xcursor v0.3.4
       Compiling xkbcommon-dl v0.1.0 (https://github.com/maroider/xkbcommon-dl?rev=900832888ad6f11011d1369befb344a9aa8a9610#90083288)
       Compiling rustc_version v0.3.3
       Compiling block-buffer v0.9.0
       Compiling digest v0.9.0
       Compiling sized-chunks v0.6.5
       Compiling crossbeam-deque v0.5.2
       Compiling grep-searcher v0.1.8
       Compiling hashbrown v0.11.2
       Compiling mio-extras v2.0.6
       Compiling mio-uds v0.6.8
       Compiling signal-hook v0.1.17
       Compiling notify v5.0.0-pre.13
       Compiling darling_core v0.13.1
       Compiling thiserror-impl v1.0.28
       Compiling ptr_meta_derive v0.1.4
       Compiling bytecheck_derive v0.6.7
       Compiling loupe-derive v0.1.3
       Compiling tracing-attributes v0.1.15
       Compiling rkyv_derive v0.7.28
       Compiling time-macros-impl v0.1.2
       Compiling bytemuck_derive v1.0.1
       Compiling include_dir_impl v0.6.1
       Compiling alacritty_config_derive v0.1.0
       Compiling serde_repr v0.1.7
       Compiling druid-derive v0.4.0 (https://github.com/lapce/druid#ce620508)
       Compiling strum_macros v0.19.4
       Compiling wayland-client v0.28.6
       Compiling wayland-protocols v0.28.6
       Compiling wayland-client v0.29.4
       Compiling wayland-protocols v0.29.4
       Compiling vte v0.10.1
       Compiling wayland-commons v0.29.4
       Compiling calloop v0.9.3
       Compiling crossbeam-deque v0.8.1
       Compiling lyon_geom v0.17.5
       Compiling chrono v0.4.19
       Compiling openssl-src v111.16.0+1.1.1l
       Compiling cmake v0.1.45
       Compiling backtrace v0.3.61
       Compiling wasmer-vm v2.1.1
       Compiling libz-sys v1.1.3
       Compiling tree-sitter v0.20.6
       Compiling libssh2-sys v0.2.21
       Compiling libgit2-sys v0.12.24+1.3.0
       Compiling tree-sitter-javascript v0.20.0
       Compiling tree-sitter-go v0.19.1
       Compiling tree-sitter-rust v0.20.0
       Compiling tinyfiledialogs v3.8.3
       Compiling globset v0.4.8
       Compiling locale_config v0.3.0
       Compiling serde-hjson v0.9.1
       Compiling grep-regex v0.1.9
       Compiling tokio-util v0.6.9
       Compiling pathfinder_simd v0.5.1
       Compiling sha2 v0.9.8
       Compiling uuid v0.7.4
       Compiling notify v4.0.17
       Compiling signal-hook-mio v0.2.1
       Compiling darling_macro v0.13.1
       Compiling thiserror v1.0.28
       Compiling ptr_meta v0.1.4
       Compiling tracing v0.1.26
       Compiling time-macros v0.1.1
       Compiling bytemuck v1.7.2
       Compiling include_dir v0.6.1
       Compiling wasmer-derive v2.1.1
       Compiling ouroboros_macro v0.9.5
       Compiling lyon_path v0.17.6
       Compiling openssl-sys v0.9.72
       Compiling freetype-sys v0.13.1
       Compiling expat-sys v2.1.6
       Compiling x11-clipboard v0.5.2
       Compiling ignore v0.4.18
       Compiling parking_lot v0.6.4
       Compiling hotwatch v0.4.6
       Compiling darling v0.13.1
       Compiling serde_bytes v0.11.5
       Compiling kurbo v0.8.1
       Compiling url v2.2.2
       Compiling xi-rope v0.3.0 (https://github.com/lapce/xi-editor#5578c725)
       Compiling serde_urlencoded v0.7.0
       Compiling fluent-syntax v0.11.0
       Compiling wasmer-vfs v2.1.1
       Compiling futures-executor v0.3.17
       Compiling rustybuzz v0.3.0
       Compiling ouroboros v0.9.5
       Compiling lyon_tessellation v0.17.9
       Compiling lyon_algorithms v0.17.5
       Compiling crossbeam-channel v0.2.6
       Compiling enumset_derive v0.5.5
       Compiling structdesc v0.1.0 (https://github.com/lapce/structdesc#a6a2b8ab)
       Compiling gimli v0.25.0
       Compiling petgraph v0.5.1
       Compiling loupe v0.1.3
       Compiling petgraph v0.6.0
       Compiling object v0.27.1
       Compiling h2 v0.3.9
       Compiling serde_yaml v0.8.21
       Compiling toml v0.5.8
       Compiling jsonrpc-lite v0.5.0
       Compiling piet v0.4.0
       Compiling lsp-types v0.89.2
       Compiling futures v0.3.17
       Compiling usvg v0.14.1
       Compiling wayland-cursor v0.28.6
       Compiling wayland-cursor v0.29.4
       Compiling fluent-bundle v0.15.1
       Compiling lyon v0.17.5
       Compiling tree-sitter-highlight v0.20.1
       Compiling pathfinder_geometry v0.5.1
       Compiling crossbeam v0.4.1
       Compiling enumset v1.0.8
       Compiling addr2line v0.16.0
       Compiling naga v0.8.1
       Compiling hyper v0.14.16
       Compiling config v0.11.0
       Compiling smithay-client-toolkit v0.14.0
       Compiling freetype v0.7.0
       Compiling cranelift-frontend v0.76.0
       Compiling wasmer-types v2.1.1
       Compiling smithay-clipboard v0.6.4
       Compiling servo-fontconfig v0.5.1
       Compiling wasmer-wasi-types v2.1.1
       Compiling copypasta v0.7.1
       Compiling tokio-native-tls v0.3.0
       Compiling font-kit v0.10.1
       Compiling parking_lot v0.11.2
       Compiling wasmer-compiler v2.1.1
       Compiling hyper-tls v0.5.0
       Compiling wgpu-hal v0.12.1
       Compiling winit v0.26.1 (https://github.com/lapce/winit?branch=new-keyboard-all#75e95695)
       Compiling alacritty_terminal v0.16.0-rc2
       Compiling console v0.6.2
       Compiling lapce-rpc v0.0.1 (/home/rajames429/Projects/git/lapce/lapce-rpc)
       Compiling alacritty_terminal v0.15.0
       Compiling sled v0.34.7
       Compiling wasmer-engine v2.1.1
       Compiling wasmer-object v2.1.1
       Compiling reqwest v0.11.8
       Compiling fzyr v0.1.2
       Compiling wasmer-engine-universal v2.1.1
       Compiling wasmer-engine-dylib v2.1.1
       Compiling wgpu v0.12.0
       Compiling wasmer v2.1.1
       Compiling piet-wgpu v0.1.0 (https://github.com/lapce/piet-wgpu#c82d19a4)
       Compiling wasmer-wasi v2.1.1
       Compiling druid v0.7.0 (https://github.com/lapce/druid#ce620508)
       Compiling lapce-core v0.0.10 (/home/rajames429/Projects/git/lapce/lapce-core)
    warning: unused import: `QueryCursor`
     --> lapce-core/src/syntax.rs:9:41
      |
    9 | use tree_sitter::{Parser, Point, Query, QueryCursor, Tree};
      |                                         ^^^^^^^^^^^
      |
      = note: `#[warn(unused_imports)]` on by default
    
    warning: unused import: `borrow::BorrowMut`
     --> lapce-core/src/syntax.rs:2:5
      |
    2 |     borrow::BorrowMut,
      |     ^^^^^^^^^^^^^^^^^
    
    warning: unused variable: `l`
       --> lapce-core/src/lens.rs:202:20
        |
    202 |     fn is_boundary(l: &LensLeaf, offset: usize) -> bool {
        |                    ^ help: if this is intentional, prefix it with an underscore: `_l`
        |
        = note: `#[warn(unused_variables)]` on by default
    
    warning: unused variable: `offset`
       --> lapce-core/src/lens.rs:202:34
        |
    202 |     fn is_boundary(l: &LensLeaf, offset: usize) -> bool {
        |                                  ^^^^^^ help: if this is intentional, prefix it with an underscore: `_offset`
    
    warning: unused variable: `l`
       --> lapce-core/src/lens.rs:206:13
        |
    206 |     fn prev(l: &LensLeaf, offset: usize) -> Option<usize> {
        |             ^ help: if this is intentional, prefix it with an underscore: `_l`
    
    warning: unused variable: `cancellation_flag`
       --> lapce-core/src/style.rs:339:9
        |
    339 |         cancellation_flag: Option<&'a AtomicUsize>,
        |         ^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_cancellation_flag`
    
    warning: unused variable: `tree`
       --> lapce-core/src/syntax.rs:143:21
        |
    143 |         if let Some(tree) = new_tree.as_ref() {
        |                     ^^^^ help: if this is intentional, prefix it with an underscore: `_tree`
    
    warning: associated function is never used: `new_highlight_query`
      --> lapce-core/src/language.rs:55:19
       |
    55 |     pub(crate) fn new_highlight_query(&self) -> Query {
       |                   ^^^^^^^^^^^^^^^^^^^
       |
       = note: `#[warn(dead_code)]` on by default
    
    warning: field is never read: `ix`
      --> lapce-core/src/lens.rs:35:5
       |
    35 |     ix: usize,
       |     ^^^^^^^^^
    
    warning: `lapce-core` (lib) generated 9 warnings
       Compiling git2 v0.13.23
       Compiling lapce-proxy v0.0.10 (/home/rajames429/Projects/git/lapce/lapce-proxy)
       Compiling lapce-data v0.0.10 (/home/rajames429/Projects/git/lapce/lapce-data)
    warning: unused import: `PietText`
     --> lapce-data/src/buffer.rs:4:12
      |
    4 |     piet::{PietText, Text, TextAttribute, TextLayoutBuilder},
      |            ^^^^^^^^
      |
      = note: `#[warn(unused_imports)]` on by default
    
    warning: unused import: `Point`
     --> lapce-data/src/buffer.rs:7:23
      |
    7 | use druid::{PaintCtx, Point};
      |                       ^^^^^
    
    warning: unused import: `interval::IntervalBounds`
      --> lapce-data/src/buffer.rs:30:5
       |
    30 |     interval::IntervalBounds,
       |     ^^^^^^^^^^^^^^^^^^^^^^^^
    
    warning: unused import: `LinePosition`
      --> lapce-data/src/editor.rs:20:29
       |
    20 |     movement::{ColPosition, LinePosition, Movement, SelRegion, Selection},
       |                             ^^^^^^^^^^^^
    
    warning: unused import: `TextLayout`
      --> lapce-data/src/editor.rs:40:57
       |
    40 |     PaintCtx, Point, Rect, RenderContext, Size, Target, TextLayout, Vec2, WidgetId,
       |                                                         ^^^^^^^^^^
    
    warning: unused import: `lapce_core::lens::Lens`
      --> lapce-data/src/editor.rs:43:5
       |
    43 | use lapce_core::lens::Lens;
       |     ^^^^^^^^^^^^^^^^^^^^^^
    
    warning: unused import: `druid::piet::PietText`
     --> lapce-data/src/movement.rs:1:5
      |
    1 | use druid::piet::PietText;
      |     ^^^^^^^^^^^^^^^^^^^^^
    
    warning: unreachable pattern
        --> lapce-data/src/editor.rs:4246:13
         |
    4246 |             LapceCommand::MoveLineUp => {}
         |             ^^^^^^^^^^^^^^^^^^^^^^^^
         |
         = note: `#[warn(unreachable_patterns)]` on by default
    
    warning: unused variable: `gutter_width`
        --> lapce-data/src/editor.rs:1672:58
         |
    1672 |     fn paint_gutter_code_lens(&self, ctx: &mut PaintCtx, gutter_width: f64) {
         |                                                          ^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_gutter_width`
         |
         = note: `#[warn(unused_variables)]` on by default
    
    warning: associated function is never used: `paint_code_lens_line`
        --> lapce-data/src/editor.rs:1936:8
         |
    1936 |     fn paint_code_lens_line(
         |        ^^^^^^^^^^^^^^^^^^^^
         |
         = note: `#[warn(dead_code)]` on by default
    
    warning: function is never used: `get_workspace_edit_changes_edits`
        --> lapce-data/src/editor.rs:4841:4
         |
    4841 | fn get_workspace_edit_changes_edits<'a>(
         |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    warning: function is never used: `get_workspace_edit_document_changes_edits`
        --> lapce-data/src/editor.rs:4849:4
         |
    4849 | fn get_workspace_edit_document_changes_edits<'a>(
         |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    warning: unused `std::result::Result` that must be used
       --> lapce-data/src/data.rs:917:29
        |
    917 | / ...                   event_sink.submit_command(
    918 | | ...                       LAPCE_UI_COMMAND,
    919 | | ...                       LapceUICommand::SetWorkspace(workspace),
    920 | | ...                       Target::Auto,
    921 | | ...                   );
        | |________________________^
        |
        = note: `#[warn(unused_must_use)]` on by default
        = note: this `Result` may be an `Err` variant, which should be handled
    
    warning: `lapce-data` (lib) generated 13 warnings
       Compiling lapce-ui v0.0.10 (/home/rajames429/Projects/git/lapce/lapce-ui)
       Compiling lapce v0.0.10 (/home/rajames429/Projects/git/lapce)
        Finished release [optimized] target(s) in 31m 43s
    rajames429@LWKFF001:~/Projects/git/lapce$ ls
    Cargo.lock  Cargo.toml  defaults  docs  extra  icons  lapce-core  lapce-data  lapce-proxy  lapce-rpc  lapce-ui  LICENSE  Makefile  README.md  target
    rajames429@LWKFF001:~/Projects/git/lapce$ cd target/
    rajames429@LWKFF001:~/Projects/git/lapce/target$ l
    CACHEDIR.TAG  release/
    rajames429@LWKFF001:~/Projects/git/lapce/target$ cd release/
    rajames429@LWKFF001:~/Projects/git/lapce/target/release$ ls
    build  deps  examples  incremental  lapce  lapce.d  lapce-proxy  lapce-proxy.d
    rajames429@LWKFF001:~/Projects/git/lapce/target/release$ ./lapce
    libEGL warning: DRI2: failed to authenticate
    WARNING: lavapipe is not a conformant vulkan implementation, testing use only.

**Comment by Kyllingene** [comment]
I don't see any errors in that output, just warnings.

**Comment by rajames429** [comment]
You are correct.  I should watch the words I use more carefully.

**Comment by Kyllingene** [comment]
Warnings in rust just indicate unnecessary or potentially problematic code, such as unused enum variants. They don't actually indicate a serious issue, and can usually be ignored.

**Comment by bugadani** [comment]
Hi and thanks for reporting!

As Kyllingene said, warnings are not necessarily mistakes, but they do indicate potentially problematic code. I think there was some progress on this front in the last few days/weeks.

I'm going to close this issue for now, because I don't think tracking warnings is something we want to do, and we don't currently have any warnings in Lapce itself. Having said that, I admit that we might want to make improvements with regards to code style/quality.

Some relevant changes:
 - #267
 - 955f99df11a292c200821700f9242e39155e0143
