### ISSUE TITLE
Git branch dropdown clips branch names

### ISSUE THREAD

**Issue by tranquanghuy0801** [lapce/lapce#2251]
## Lapce Version

Version 0.2.6

## System information

MacOS Monterey 12.3

## Describe the bug

The git branch dropdown is hiding the branch name. See the attached screenshot below. 

## Additional information

Screenshot

<img width="294" alt="image" src="https://user-images.githubusercontent.com/29462498/225606250-4f5066d9-ea2d-4ddc-9b72-8f7cf8e5d759.png">

**Comment by panekj** [comment]
What is hidden here?

**Comment by tranquanghuy0801** [comment]
> What is hidden here?

Some branches are not showing full name. Is this dropdown a fixed width?

**Comment by panekj** [comment]
Yes, that's expected, as we don't have many dynamic UI components

**Comment by panekj** [comment]
Fixed since we outsourced branch selection to palette
