### ISSUE TITLE
Cannot type "`" and "~"

### ISSUE THREAD

**Issue by habi** [lapce/lapce#2274]
## Lapce Version

Versioin 0.2.7

## System information

Ubuntu 20.04.5 LTS

## Describe the bug

I wanted to type `PNG` in a Markdown file, which does not work in `lapce` on my Microsoft Natural Ergonomic Keyboard 4000.
I'm using a [Swiss German keyboard layout](https://i.pinimg.com/474x/ec/e1/b8/ece1b821dfd44dffdd663bff4f04aaf0--keyboard-swiss.jpg) and the \` is on the left of the backspace, usually typed with `Shift + ^`.
Typing \` works nicely in all other software I use, also here for submitting this issue.

Typing ~ and ' also does not work in lapce, they are reachable with `Alt Gr + ^` or `Alt Gr + '`.

**Comment by panekj** [comment]
Most likely a duplicate of #1094

**Comment by habi** [comment]
Sorry, I haven't searched well enough through all the issues.
This seems is exactly the same problem.
As I'm also writing German and sometimes need to type capital Umlaut letters (Ä, Ö, Ü, which don't work in lapce), this makes it not very usable for me unfortunately...
