### ISSUE TITLE
Open multiple workspaces / projects

### ISSUE THREAD

**Issue by hanckmann** [lapce/lapce#2275]
## Is your feature request related to a problem? Please describe.

My work is often separated into multiple projects.
I would like to be able to open multiple projects (workspaces) and work on them.
Currently I can open only 1 lapce editor at a time, and in the editor I can only open 1 workspace at a time.

## Describe the solution you'd like

I would like to be able to open multiple lapce editors simultaneously and/or open multiple workspaces simultaneously.

## Describe alternatives you've considered

There are two alternatives as I see them:
1. open the first folder which is parent to both/all projects
2. use a different editor :-(

## Additional context
```bash
lapce --version
$ Lapce 0.2.5
```

**Comment by panekj** [comment]
You can create new window tabs that can open different workspace via palette

**Comment by fcolecumberri** [comment]
May I suggest to put a little tab with the `+` symbol just next to the last window tab to add a new tab, that would make clear that you can add more tabs

**Comment by polx** [comment]
I just discovered lapce today (through AlternativeTo while on intellij) and was really enchanted.

Wouldn't simply the command "open folder" always open a new window? It seems like we have enough performance under the hood for this! Adding a keyboard shortcut to close the window after the last editor is closed (again cmd/ctrl-W?) would complete the perfect usability.

**Comment by bartmika** [comment]
+1
