### ISSUE TITLE
Lapce asks for update even if installed via package manager

### ISSUE THREAD

**Issue by VaiTon** [lapce/lapce#2284]
## Lapce Version

0.2.6

## System information

openSUSE Tumbleweed (20230318)

## Describe the bug
Even when installed with the package manager, Lapce displays an "update available" notification. 
When clicked, it remains stuck on "Updating..." and then, after a while, returns to "Update available".

## Possible solution

Provide a build config to disable in-app update.

I don't really know if it is a packaging issue or a problem with lapce itself. 
Either ways, if you can point me in the right direction I would be grateful. 

If it's a packaging problem please tell me how to enable this "flag" so that I can do that in the build script.

For reference:
https://build.opensuse.org/package/view_file/editors/lapce/lapce.spec

**Comment by panekj** [comment]
> Provide a build config to disable in-app update.


https://github.com/lapce/lapce/blob/0ded46c988d72b563bd78b29cc11107d4e2248bc/lapce-ui/Cargo.toml#L48
