### ISSUE TITLE
line number as distance to current line 

### ISSUE THREAD

**Issue by sergey-sign** [lapce/lapce#23]
<img width="501" alt="Screen Shot 2021-12-14 at 16 22 56" src="https://user-images.githubusercontent.com/681721/146017208-55d5ec75-66e6-487a-bae7-b02cdd667fc0.png">
macOS 12.0.1 m1 2020

**Comment by dzhou121** [comment]
Can you try the latest release? https://github.com/lapce/lapce/releases/tag/v0.0.4

**Comment by sergey-sign** [comment]
@dzhou121 yes, thanks)
