### ISSUE TITLE
Lapce [Nightly] - Homebrew Cask (versions)

### ISSUE THREAD

**Issue by dalisoft** [lapce/lapce#2314]
## Is your feature request related to a problem? Please describe.

I now using stable version of lapce installed via Homebrew, but i'd like to use `nightly` version via Homebrew Cask versions

## Describe the solution you'd like

Add Lapce Nightly to `homebrew/cask-versions` tap

## Describe alternatives you've considered

Downloading from releases every time can be automatized via Homebrew as i'm using Homebrew for apps installing, updating, managing and deleting on macOS

**Comment by panekj** [comment]
We have own tap https://github.com/lapce/homebrew-lapce

**Comment by dalisoft** [comment]
@panekj Very cool, thank you.
