### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by foxlldev** [lapce/lapce#2329]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I have to use VSCode as well as Lapce because I can't have multiple Lapce windows.

## Describe the solution you'd like
The ability to have multiple Lapce windows concurrently.

## Describe alternatives you've considered
Plugins: I do not know enough Rust to make one myself and I cannot find an existing plugin for it.
My friend managed to open another window via the command line, but I think this is unnecessarily complicated. Maybe add an option to add another instance to the system tray or right click on taskbar.

## Additional context
Windows 11, Lapce 0.2.7

**Comment by panekj** [comment]
F1 > `New window`

**Comment by weykon** [comment]
In VSCode, my custom is passing `Shift + CMD + N` to create New Window, and now I have set the keybinding for this "New window" command is good.

but a simple issue is when in MacOS, some customer not really conveniently to pass F1, and the Menu there is no this command item expose. 

shall we add "New Window" at Menu in file nav ?

**Comment by ElDiddi** [comment]
As a new Windows Lapce user, I was very surprised not to be able to open a second window when I run lapce.exe again. When trying to start Lapce a second time, two window frames appear briefly and it looks like the process for the second instance crashes without an error message. It took me a little while to find the solution in the form of this post (thx panekj). The onboarding for a new user could be simplified a bit in my opinion.
