### ISSUE TITLE
Add instructions about running on systems that don't support openGL to the documentation

### ISSUE THREAD

**Issue by Kuratius** [lapce/lapce#2333]
## Is your feature request related to a problem? Please describe.

Lapce doesn't run out of the box on systems that only support outdated versions of openGL in their driver.

## Describe the solution you'd like

Add information to the documentation/installation guide (maybe also the compilation instructions?) about possible workarounds, such as zink and software rendering 
such as
LIBGL_ALWAYS_SOFTWARE=1 lapce
MESA_LOADER_DRIVER_OVERRIDE=zink ./lapce
(the latter is useful on raspberry pi 4, as it supports Vulkan 1.2 and Zink, but not new versions of openGL).

## Describe alternatives you've considered

Automatically integrate these workarounds (detect supported graphics apis, then choose launch options automatically?)
Add alternative graphics backends directly and choose automatically or in a way that is configurable with a setting.

**Comment by Dirleye** [comment]
MESA_LOADER_DRIVER_OVERRIDE=zink ./lapce doesn't seem to work on the Pi 4.

**Comment by Kuratius** [comment]
@Dirleye Update your drivers
![2023-05-14-144457_1600x900_scrot](https://github.com/lapce/lapce/assets/47481645/607eb7a1-f8b3-4dd3-b769-30b7292078e1)

**Comment by Dirleye** [comment]
I'll try compiling from source later. Otherwise could be a difference with how Arch Mesa is built.

**Comment by Dirleye** [comment]
@Kuratius yup, I get `WARNING: Some incorrect rendering might occur because the selected Vulkan device (V3D 4.2) doesn't support base Zink requirements` and a segfault.
Did you add any other build flags? Or just cargo build --release?

**Comment by Kuratius** [comment]
> @Kuratius yup, I get `WARNING: Some incorrect rendering might occur because the selected Vulkan device (V3D 4.2) doesn't support base Zink requirements` and a segfault. Did you add any other build flags? Or just cargo build --release?

Was cargo build --release I think.
I can check what mesa version I'm running, one sec.

**Comment by Kuratius** [comment]
pi@raspberrypi:~ $ glxinfo | grep Mesa
client glx vendor string: Mesa Project and SGI
OpenGL version string: 2.1 Mesa 20.3.5
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.3.5

If you have time, probably see if it runs on raspberryPiOS, the addition of Vulkan 1.2 conformance (which is needed for Zink) was relatively recent:
https://www.raspberrypi.com/news/vulkan-update-version-1-2-conformance-for-raspberry-pi-4/

Rust target triple (but this is chosen by default, I didnt pass it):
pi@raspberrypi:~ $ rustc -vV | sed -n 's|host: ||p'
aarch64-unknown-linux-gnu

The lapce version is 0.2.7.

**Comment by Kuratius** [comment]
https://docs.mesa3d.org/drivers/zink.html
`We also require either the [VK_EXT_scalar_block_layout](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_scalar_block_layout.html) extension or Vulkan 1.2, with the [scalarBlockLayout](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#features-scalarBlockLayout) feature.`

**Comment by Dirleye** [comment]
@Kuratius Thanks for the info, and the binary would be great if you don't mind.
According to a comment on the linked pi news blog, all necessary changes should have been upstreamed by Mesa 22.2. Arch ARM looks to be shippng 23.0.3 currently and vulkaninfo confirms conformanceVersion is 1.2.7.
My rustc target reports as the same as yours so I'm a tad confused.
If nothing else works I'll ask around in the forums and see if anything in Arch's Mesa build is configured differently for some reason.
Thanks for the help.

**Comment by Kuratius** [comment]
I'm not sure how to check the zink version directly, if I can figure it out I'll do that.
Binary is here:
https://drive.google.com/file/d/1jj_1KapUBc0CxmDdE031GxmFJKbIWxfi/view?usp=share_link

**Comment by Kuratius** [comment]
I'm starting to wonder if this is some kind of software fallback in mesa
pi@raspberrypi:~/lapce $ MESA_LOADER_DRIVER_OVERRIDE=zink glxgears
libGL error: failed to create dri screen
libGL error: failed to load driver: zink
libGL error: failed to create dri screen
libGL error: failed to load driver: zink
1810 frames in 5.0 seconds = 361.979 FPS
1957 frames in 5.0 seconds = 391.382 FPS

(this does produce a working 3D animation on my screen, so it's a bit weird that it claims the driver failed).

**Comment by Kuratius** [comment]
pi@raspberrypi:~ $ MESA_LOADER_DRIVER_OVERRIDE=zink glxgears -info
libGL error: failed to create dri screen
libGL error: failed to load driver: zink
libGL error: failed to create dri screen
libGL error: failed to load driver: zink
GL_RENDERER   = llvmpipe (LLVM 11.0.1, 128 bits)
GL_VERSION    = 3.1 Mesa 20.3.5
GL_VENDOR     = Mesa/X.org

might be that libGL is set up to fallback to llvmpipe if it fails

**Comment by Dirleye** [comment]
@Kuratius Oddly, glxgears is working almost perfectly with Zink for me. It complains that VK_EXT_depth_clip_enable isn't supported, but I can confirm the GL_RENDERER is Zink. My GL_VERSION defaults to 2.1 instead of 3.1 which could explain why Zink made seemingly no difference to Lapce running or not.

Forcing OpenGL 3.1 with `MESA_GL_VERSION_OVERRIDE=3.1` does indeed make glxgears report 3.1 and Lapce gets a bit further.

Running `MESA_LOADER_DRIVER_OVERRIDE=zink MESA_GL_VERSION_OVERRIDE=3.1 RUST_LOG=info,lapce_ui=debug ./lapce -w` now panics on main with `error: output location 0 >= GL_MAX_DUAL_SOURCE_DRAW_BUFFERS with index 1 for o_frag_alpha`.
It shows its trace followed by the final line: `scalarBlockLayout OR EXT_scalar_block_layout`. I'm not sure what it's trying to say by just stating that.

**Comment by Kuratius** [comment]
What I think is happening is that in my case zink is defaulting to software rendering, while for you it isn't.


MESA_LOADER_DRIVER_OVERRIDE=zink RUST_LOG=info,lapce_ui=debug ./lapce -w
Parsing RUST_LOG
level='info' for all modules
module='lapce_ui', level='debug'
[2023-05-15][23:28:12][lapce_data::keypress][ERROR] Failed to load from "/home/pi/.config/lapce-stable/keymaps.toml": no keymaps
libGL error: failed to create dri screen
libGL error: failed to load driver: zink
libGL error: failed to create dri screen
libGL error: failed to load driver: zink


https://blogs.igalia.com/itoral/2023/02/20/supertuxkart-vulkan-vs-opengl-and-zink-status-on-raspberry-pi-4/
This blog post seems to imply that this feature can't be supported in hardware but will be worked around eventually(?).

`Also, I have been talking to zmike about one of the features we could not support natively: scalarBlockLayout. Particularly, the issue with this is that we can’t make it work with vectors in all cases and the only alternative for us would be to scalarize everything through a lowering, which would probably have a performance impact. However, zmike confirmed that Zink is already doing this, so in practice we would not see vector load/stores from Zink, in which case it should work fine .

`
Probably should report it to the zink developer zmike.

**Comment by Kuratius** [comment]
Does anything change if you force openGL 3.3?

**Comment by Dirleye** [comment]
I get the same with 3.3. The only difference is that anything above 3.1 shows the GL_VERSION in glxgears as running with a compatibility profile.

**Comment by panekj** [comment]
We use wgpu now
