### ISSUE TITLE
Wrong search result enumeration 

### ISSUE THREAD

**Issue by embeddedc** [lapce/lapce#2348]
## Lapce Version
0.2.7

## Describe the bug
Precondition:
- File search with results in multiple files 
- Collapse multiple search results

Expected behavior:
- Clicked search result collapses
Actual behavior: 
- Preceding result expands

https://user-images.githubusercontent.com/4259379/232326336-336fe6e2-170d-4be2-aeb9-28365ef1ac1e.mp4

**Comment by hakro** [comment]
This is likely fixed by https://github.com/lapce/lapce/pull/2272
@embeddedc, you can try to download the nightly build and confirm that it's fixed.
This will probably get shipped in the next version.
Cheers !

**Comment by embeddedc** [comment]
> This is likely fixed by #2272 @embeddedc, you can try to download the nightly build and confirm that it's fixed. 

Already done 2 min ago.  Sorry, should have checked before creating the issue...

**Comment by embeddedc** [comment]
Duplicate of #2272
