### ISSUE TITLE
Displays: unknown option --wait

### ISSUE THREAD

**Issue by akhildevelops** [lapce/lapce#2349]
## Lapce Version
v0.2.7

## System information
Ubuntu

## Describe the bug
Running `lapce --wait` spins up the IDE, but shows `Unknown option --wait` in the terminal, even though it's a right flag.

## Additional information

Ouput log:
``` rust
❯ target/release/lapce --wait
[lapce-data/src/proxy.rs:843] format!("{}:{remote}", self.ssh.user_host()) = "vscode@172.17.0.2:/tmp/lapce-proxy.sh"
Unknown option --wait
```

**Comment by akhildevelops** [comment]
I've cloned the master branch and built a release `cargo build --release` on this commit https://github.com/lapce/lapce/commit/3767221f7d049102f54c86700f862def73f9eebf

Launched by running `./target/release/lapce`

OS: Ubuntu 22.04

**Comment by panekj** [comment]
can't reproduce
