### ISSUE TITLE
Open folder window is empty

### ISSUE THREAD

**Issue by Jellyfrog** [lapce/lapce#235]
When pressing "Open Folder" I only see a white box;
![image](https://user-images.githubusercontent.com/759887/159758686-384926d9-035c-4539-a525-0b5eda1db9be.png)

I'm suspecting I'm missing some dependency for a file manager

Lapce: ab817e435c723f6dab1bd32c6625da9f295e20f5
OS: Arch linux
Window manager: sway

**Comment by marchersimon** [comment]
Same happens with EndeavourOS (KDE). The popup just contains an `Ok` and `Cancel` button.

**Comment by matthis-k** [comment]
Same for me.
I am using `sway` and have `yad` installed (which should be sufficient according to terminal messages)

**Comment by kk6mrp** [comment]
I also have sway and yad running on Alpine Linux and see an empty window.

**Comment by 3355715293** [comment]
Installing the "zenity" package on Arch Linux solves this issue for me.

**Comment by marchersimon** [comment]
Can confirm. Thanks for the fix.

**Comment by lucamanga** [comment]
Confirmed, on a Fedora KDE system.
