### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by IUB2010** [lapce/lapce#2352]
Lapce is very slow when connecting to wsl, in comparison connecting to wsl in vscode is faster

**Comment by IUB2010** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/110409936/234576670-6ebb3706-1421-43c9-9cba-be3b778abc2d.png">
 
It just won't load.

**Comment by wildwestrom** [comment]
I started using lapce on MacOS and I found it to be extremely slow. It's damn near unresponsive to clicks.

**Comment by Kuratius** [comment]
@wildwestrom What version? I think there has been a performance regression due to backend changes between 0.2.7 and now, so you may want to try that version instead.

**Comment by wildwestrom** [comment]
I downloaded 0.2.8 to try it out again. It's very slow. I'm experiencing the same thing all the way back to 0.2.5.
