### ISSUE TITLE
Builtin fuzzy finder

### ISSUE THREAD

**Issue by lbirkert** [lapce/lapce#2353]
## Is your feature request related to a problem? Please describe.

-

## Describe the solution you'd like

A command that can be mapped to a shortcut opening a find files menu for fast switching inspired by fzf and telescope.

This would allow users good with their keyboards to switch between files faster than switching to their mouse to click around in the file explorer.

## Describe alternatives you've considered

-

## Additional context

![image](https://user-images.githubusercontent.com/88548934/234689843-d710505e-dbe5-4ee6-baba-630335e7837f.png)
![image](https://user-images.githubusercontent.com/88548934/234689926-a012c3f2-bb9c-439d-86ae-20a9db7cc5a0.png)

**Comment by panekj** [comment]
Palette already does fuzzy matching for paths
