### ISSUE TITLE
Rhai syntax highlighting

### ISSUE THREAD

**Issue by superlou** [lapce/lapce#2354]
## Is your feature request related to a problem? Please describe.

Syntax highlighting for [Rhai](https://rhai.rs/) would be helpful, especially as it's a scripting language easily integrated into Rust applications.

## Describe the solution you'd like

Syntax highlighting support built into Lapce.

## Describe alternatives you've considered

A plugin could be made using the [Rhai LSP](https://github.com/rhaiscript/lsp), and while this is probably a more robust approach, the LSP is relatively incomplete. Still, this is probably a candidate for better-as-a-plugin.

**Comment by panekj** [comment]
Syntax highlighting is provided via tree-sitter grammar.

> Syntax highlighting support built into Rust.

what does that mean

**Comment by panekj** [comment]
Added to #272
