### ISSUE TITLE
Removing tabulation in the code editor.

### ISSUE THREAD

**Issue by DmitryNX** [lapce/lapce#2359]
## Is your feature request related to a problem? Please describe.

There is an action "Insert Tab" on pressing on `Tab` button, but there is no a reverse action "Remove Tab" on pressing on `Shift + Tab` keyboard shortcut.

## Describe the solution you'd like

To make the action "Remove Tab" on pressing on `Shift + Tab` keyboard shortcut.

**Comment by panekj** [comment]
You can outdent lines with `Ctrl` + `[` or `Cmd` + `[`

**Comment by DmitryNX** [comment]
Thanks 😊
