### ISSUE TITLE
Homebrew Support

### ISSUE THREAD

**Issue by FlorianWendelborn** [lapce/lapce#236]
As a macOS user, I’m used to installing tools through [Homebrew](https://brew.sh/). Given that lapce already has a lot of stars, I think it should be possible to get its formula merged into homebrew without any issues

**Comment by ghishadow** [comment]
you can `brew install --cask lapce` https://formulae.brew.sh/cask/lapce.

**Comment by kraemi** [comment]
@ghishadow Any chance to install lapce on Ubuntu using homebrew?

**Comment by abitrolly** [comment]
@kraemi perhaps it is better to open another issue.
