### ISSUE TITLE
can‘t start?

### ISSUE THREAD

**Issue by ritchie2000** [lapce/lapce#2369]
## Lapce Version
Lasted version msi, can't be started on my win10

**Comment by MinusGix** [comment]
Currently Lapce requires a minimum of OpenGl 3.3, which might be the issue? Information on your graphics card/opengl-version and potentially windows version would be helpful.

**Comment by ritchie2000** [comment]
Oh, okay

**Comment by ritchie2000** [comment]
Oh, okay
