### ISSUE TITLE
Text rendering messed up in open folder dialog

### ISSUE THREAD

**Issue by davidak** [lapce/lapce#238]
![Screenshot from 2022-03-23 20-50-43](https://user-images.githubusercontent.com/91113/159784223-c9282126-fcc8-4557-b23c-00c3a58c60d2.png)

It did crash shortly after rendering this (https://github.com/lapce/lapce/issues/237).

It should look like this. It did work at another try.

![Screenshot from 2022-03-23 20-52-51](https://user-images.githubusercontent.com/91113/159784520-63a7b93c-5e64-463f-ab57-9c7821a1d527.png)

---

lapce 0.0.10 from [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=lapce&from=0&size=50&sort=relevance&type=packages&query=Lapce)
NixOS 21.11.336538.64fc73bd74f

**Comment by bugadani** [comment]
Lapce no longer uses this dialog, so this issue won't be present in the future.

**Comment by davidak** [comment]
This also happens in other places where text is rendered.

![Screenshot from 2022-03-23 22-10-18](https://user-images.githubusercontent.com/91113/159949979-d5f67285-45db-4b0e-8fa9-e132f864f94e.png)
![Screenshot from 2022-03-23 22-08-05](https://user-images.githubusercontent.com/91113/159950136-81423287-7316-468e-a32c-cb7f65f741bb.png)

**Comment by davidak** [comment]
This: https://codeberg.org/davidak/webseite/src/commit/1113feb5034de12bbc5fb7ffde36fd2dab62ede0/pages/uses.md#workstation

**Comment by panekj** [comment]
Whew, that's an old lapce, we currently regressed and don't even have that UI anymore but it should not appear that way anyway since we replaced lots of UI code
