### ISSUE TITLE
Going a little bit more specific when building on Windows

### ISSUE THREAD

**Issue by badolsmito** [lapce/lapce#239]
The instructions on building on windows are a little bit confusing, and should be as clear as possible. It is pretty simple, essentially, you just add the steps where you unzip the file downloaded, go the the folder where all the files are and copy the path for it. Then, simply open Powershell, change the directory using `cd [path]` and then build it.

Also, if there was a significantly better way to suggest this, please let me know, I'm new to GitHub.

**Comment by bugadani** [comment]
> The instructions on building on windows are a little bit confusing
There are instructions on how to build on windows? :) 

Anyway, as far as I know, the simplest set of steps are:
 - you install Rust, if you don't have it already
 - you clone the repository (or donwload the zip as you did)
 - you open a terminal (be it powershell, cmd, windows terminal...) in the folder where you cloned/extracted the source
 - and you run `cargo run --bin lapce`

**Comment by bugadani** [comment]
I'm closing this in favour of #3. Thank you for reporting! 💖
