### ISSUE TITLE
Even when building with the --no-default-features option, all tree-sitters are downloaded (~1.8 Gb)

### ISSUE THREAD

**Issue by Gliese852** [lapce/lapce#2396]
## Lapce Version
0.2.7

## System information
GNU/Linux x86_64 (ALT Sisyphus)

## Describe the bug
I expected that when some features are disabled, the corresponding repositories will not be downloaded, but it's downloaded. This happens even if I comment out the appropriate lines from `lapce-ui/Cargo.toml` - in the log below, all mentions of the word `bash` in this file are commented out.
Only if I also remove this from `lapce-core/Cargo.toml` it doesn't load.
Given some limitation on internet traffic, this is a problem for me.

## Additional information

my attempt log: (cleared the db between attempts)
```
$ cargo build --release
    Updating git repository `https://github.com/lapce/druid`
    Updating git repository `https://github.com/tree-sitter/tree-sitter-bash`
^C     Fetch [===>                     ]  19.17%, 3.77MiB/s
$ cargo build --release --no-default-features
    Updating git repository `https://github.com/lapce/druid`
    Updating git repository `https://github.com/tree-sitter/tree-sitter-bash`
^C     Fetch [==>                      ]  15.96%, 393.25KiB/s
$ cargo build --release -p lapce-ui --no-default-features
    Updating git repository `https://github.com/lapce/druid`
    Updating git repository `https://github.com/tree-sitter/tree-sitter-bash`
^C     Fetch [====>                    ]  20.21%, 3.66MiB/s
$ cargo build --release --no-default-features -p lapce-ui
    Updating git repository `https://github.com/lapce/druid`
    Updating git repository `https://github.com/tree-sitter/tree-sitter-bash`
^C     Fetch [=========>               ]  41.28%, (57/734) resolving deltas
$
```

**Comment by panekj** [comment]
This is working as intended since lockfile is the source of truth for dependencies download

**Comment by Gliese852** [comment]
@panekj Are you saying that `cargo` can't do better?

**Comment by panekj** [comment]
It is currently not possible with cargo to have selective lockfile
