### ISSUE TITLE
The rust-analyzer plugin shouldn't blindly execute `build.rs` without user confirmation

### ISSUE THREAD

**Issue by KSXGitHub** [lapce/lapce#2398]
## Lapce Version

0.2.7

## System information

OS: Linux

### Steps to reproduce

**Step 1:** Use `cargo init` to create an empty Rust project.

**Step 2:** Write a `build.rs` file with the following content:

```rust
use std::process::Command;

fn main() {
    Command::new("notify-send").arg("hello from build.rs").output().expect("send notification");
}
```

**Step 3:** Press <kbd>Ctrl+S</kbd> to Save.

### Expected behavior

Lapce should ask user whether to execute `build.rs` first.

### Actual behavior

Lapce executes `build.rs` and cause a notification to appear. This could make Lapce users vulnerable to supply chain attack.

## Additional information

I have proposed an idea in this comment: https://github.com/lapce/lapce/issues/558#issuecomment-1151067738

**Comment by panekj** [comment]
If you don't want to run build scripts, you should disable them in rust-analyzer.

**Comment by KSXGitHub** [comment]
I think you missed the point, @panekj.

What if I want to run `build.rs` for trusted repos but I also want the ability to check out arbitrary repos without worry?

Besides, this problem is not about me. The default behavior of Lapce is to run build script if it detects one. Meaning, Lapce is vulnerable out-of-the-box. Curious, unaware users may become cyberattack target just by innocently checking out a random git repo that was cloned from the net.

This is pretty much a security issue. You cannot just ignore it.

**Comment by panekj** [comment]
> I think you missed the point, @panekj.

I didn't. You missed the final message in the issue about plugins: https://github.com/lapce/lapce/issues/558#issuecomment-1245436002

> The default behavior of Lapce is to run build script if it detects one

This is not a "Lapce behaviour", it's a behaviour of rust-analyzer.
You should read https://rust-analyzer.github.io/manual.html#security
There isn't any way to block RA from running build scripts other than implementing Code Trust as vscode did, which will take time as we're working on many things.
