### ISSUE TITLE
Proportional width fonts are treated as monospaced

### ISSUE THREAD

**Issue by PhilipDaniels** [lapce/lapce#240]
Running on KDE Neon (Linux), font set to "DejaVu Sans", which is a proportional width font. DIsplay renders as follows:

![image](https://user-images.githubusercontent.com/1809220/159804359-2ee3b10b-5d38-4f9e-8b89-4e2293b69d0d.png)

Equivalent screenshot from VS Code:

![image](https://user-images.githubusercontent.com/1809220/159804393-897cf6b8-a6ac-4402-8a76-063a69eb717e.png)

Programming in proportional width fonts is the best thing so it would be good if we could fix this :-)

I don't know if the underlying display technology that lapce is using supports display of proportional fonts. If it does, if someone could point me in the direction of where the problem lies I would take a shot at making this work. I think it is primarily a rendering issue, as movement with the cursor keys and mouse through the document seems to work ok, although I would expect the mouse integration to need some patching if we get the rendering to work with variable width characters.

**Comment by PhilipDaniels** [comment]
The culprit here appears to be the `char_width` function in config.rs, and the places from which it is used:

https://github.com/lapce/lapce/blob/7b3f6a389de43c37d7bde3f507bbedf35f850699/lapce-data/src/config.rs#L426-L451

Note however the interesting functions which follow it, we have the ability to measure text widths and the sizes of blocks of text.

**Comment by dzhou121** [comment]
This should be fixed now by the latest v0.1.0 release.

**Comment by PhilipDaniels** [comment]
Wow, I'm amazed @dzhou121 This appears to be working great! I logged this issue because I was going to tackle it myself (eventually) since I expected nobody else to care :-) Was it a big change? Appreciate it if you could point me to the PR.

There is one thing I noticed/anticipated: the font rendering in the terminal is still 'broken': things just look weird with a proportional font. I think we need two font settings: if a separate font is set for the terminal then it should override the default Editor font. Requires a slight change to the configuration. I am happy to take a look at that.

**Comment by dzhou121** [comment]
It's part of the OpenGL rewrite. With that, I've also added proper text layout support with Swash, which makes the rich text in Hover works.

I think it makes sense to have font settings(font family, size, etc) for different parts of the UI. I'll leave it to you then. :)
