### ISSUE TITLE
Allow Window Installer Without Admin

### ISSUE THREAD

**Issue by chuongmep** [lapce/lapce#2402]
## Is your feature request related to a problem? Please describe.

My problem is I want to install don't need admin, it is similar with Visual Studio Code .
![image](https://github.com/lapce/lapce/assets/31106432/3c765f4e-d029-436b-9ae1-0d8c2b7664cf)

## Describe the solution you'd like

Can continue to install no need admin confirm

## Describe alternatives you've considered
 
- Allow option install for all user or separate user.

**Comment by panekj** [comment]
Duplicate of #498
