### ISSUE TITLE
character  ^  not working

### ISSUE THREAD

**Issue by pdenapo** [lapce/lapce#2413]
## Lapce Version

0.2.7

## System information

Ubuntu 22.04.2

## Describe the bug

It is not possible to enter the ^ character in Lapce by pressing shift and the `/^ key in the spanish key work.

Set your keyboard to spanish with before running Lapce to test it with setxkbmap like

$setxkbmap -v es
Warning! Multiple definitions of keyboard layout
         Using command line, ignoring X server
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+es+inet(evdev)
geometry:   pc(pc105)

**Comment by panekj** [comment]
Duplicate of #1094
