### ISSUE TITLE
Editor gets confused with CRLF line endings

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#242]
https://user-images.githubusercontent.com/977627/159858576-5d54e5c6-ef9b-4ba4-a47e-a40711b0a11f.mp4

**Comment by bugadani** [comment]
Relevant PRs:
 - #293

**Comment by hbina** [comment]
Is this on Windows?

**Comment by bugadani** [comment]
Yes, although I can no longer reproduce it. I don't know what fixed it or if my uncaffeinated brain just can't follow my own video properly. At any rate, since I can't repro, I'm closing this. Thanks for the ping

**Comment by hbina** [comment]
I tried reproducing this myself but I am on Ubuntu so IDK if its something to do with Windows CRLF. I did clearly remember that it was reproducible couple of weeks ago.
