### ISSUE TITLE
High Latency

### ISSUE THREAD

**Issue by michael-swan** [lapce/lapce#2423]
The latency of each keystroke is about 27ms on average on my machine which is actually significantly slower than VS Code at 20ms of input lag. It may be worth investigating ways of improving this. The tool I used is called Typometer: https://pavelfatin.com/typometer/

For reference, Emacs is between 1/5th and 1/10th the latency of this program. I'm not trying to be overly critical but "lightning-fast" isn't a good descriptor for this program if you have almost two whole frames of input lag. I get that different environments will mean different latencies and it could even be related to things like device drivers and whatnot, but with an empty text file, VS Code is significantly faster in my environment, about 35% less latency on average with the same sized window.

**Comment by panekj** [comment]
Please include required information from bug template that you omitted
