### ISSUE TITLE
Lapce keeps bugging me to save a file (infinite loop-style)

### ISSUE THREAD

**Issue by kylegoetz** [lapce/lapce#2427]
## Lapce Version

0.2.1

## System information

macOS 12.0.1 (Monterrey)

## Describe the bug

Open a new file. Type anything. Get prompted to save the file. I don't want to save the file. I just want a scratch file to see some syntax highlighting before closing this file w/o ever saving. I just keep getting prompted to save it over and over, no matter how many times I hit cancel instead of save, keeps prompting for save. The only escape is to force quit Lapce.

**Comment by MinusGix** [comment]
This sounds like #1703, but I thought that got fixed. Do you have autosave on?

**Comment by panekj** [comment]
> 0.2.1

This is very old version, please upgrade

**Comment by kylegoetz** [comment]
OK will do, thanks. My IDE has the "restart to upgrade" so I figured I had a pretty recent version if it auto-upgrades when I restart (which I have done about a dozen times in the past couple days). I'll upgrade right now and see if it changes.

**Comment by kylegoetz** [comment]
Yes, problem is resolved.
