### ISSUE TITLE
Request to add Vala syntax highlighting support

### ISSUE THREAD

**Issue by phase1geo** [lapce/lapce#2430]
## Describe the solution you'd like

I would like to see Vala syntax highlighting be supported by Lapce.

**Comment by MinusGix** [comment]
#272 is the tracking issue for syntax highlighting (using tree-sitter). I've added it to that list.  
https://github.com/vala-lang/tree-sitter-vala is probably what you're looking for, but I think it will need the Rust bindings generated for it (like how other tree-sitters have them).
