### ISSUE TITLE
Terminal not rendering

### ISSUE THREAD

**Issue by Banyc** [lapce/lapce#2437]
## Lapce Version

0.2.8

## System information

macOS 13.4

## Describe the bug

Newly created terminal panels are not rendered. They are only rendered when you switch tabs.

The initial terminal tab did get rendered on the APP startup.

## Additional information

![lapce_terminal_not_rendering](https://github.com/lapce/lapce/assets/36535895/8c820cce-491c-4e22-b0c3-dc61a67e7ec4)

**Comment by arnaudsm** [comment]
Exact same bug. Fedora 0.2.7

**Comment by panekj** [comment]
duplicate of https://github.com/lapce/lapce/issues/2156
