### ISSUE TITLE
Show Help Information in Palette

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#2445]
## Is your feature request related to a problem? Please describe.

It would be useful to have a quick way of getting the possible palette kinds (by prefix) while in the editor.  

## Describe the solution you'd like

When you enter `?` into the palette, VSCode (for example) shows the various prefixes that can be used.

## Describe alternatives you've considered

We could do something like showing it on the side of the palette, like as extra buttons, when the palette is empty. I think the separate `?` menu is simpler, though.

**Comment by weykon** [comment]
@MinusGix Hi, I want to know what is palette in editor.

do you mean color palette?

**Comment by panekj** [comment]
> Hi, I want to know what is palette in editor.
> 
> do you mean color palette?

https://docs.lapce.dev/get-started/command-palette
