### ISSUE TITLE
Code completion doesn't work on Mac OS M1

### ISSUE THREAD

**Issue by MassonNN** [lapce/lapce#2469]
## Lapce Version

0.2.8

## System information

Mac OS Ventura 13.4 (Apple M1)

## Describe the bug
Any code completion doesn't work. Errors/Warnings highlighting also. I tried it in a Rust, Python, and Dart projects. The hints didn't work anywhere. I installed several plugins (e.g., Rust, Lapce-python), but it made no difference. 

## Additional information

<img width="1280" alt="Снимок экрана 2023-06-19 в 00 58 47" src="https://github.com/lapce/lapce/assets/35528949/fe2e3007-6d42-48d6-8dbf-97781f6e15bb">

**Comment by panekj** [comment]
It should be reported to each plugin bug tracker, since each plugin defines how and which LSP to use.

**Comment by MassonNN** [comment]
Completions also don't work without any plugins

**Comment by panekj** [comment]
There isn't any completion without plugins.
