### ISSUE TITLE
Add appimage or flatpak for linux

### ISSUE THREAD

**Issue by JakeDevs** [lapce/lapce#247]
This would be really cool to see.

**Comment by ghishadow** [comment]
https://flathub.org/apps/details/dev.lapce.lapce Flatpak is released yesterday, thanks to @sebastian-de

**Comment by JakeDevs** [comment]
> https://flathub.org/apps/details/dev.lapce.lapce Flatpak is released yesterday, thanks to @sebastian-de

finally thank you @sebastian-de
