### ISSUE TITLE
Editor tab close button on the left side

### ISSUE THREAD

**Issue by jim-ec** [lapce/lapce#2472]
## Is your feature request related to a problem? Please describe.

I personally find it annoying to close multiple adjacent editor tabs.
Because they have differing widths, I constantly have to move the cursor.

## Describe the solution you'd like

It would be much nicer if there would be an option to have the tab close button on the left side instead of on the right side.

## Describe alternatives you've considered

Enforce a uniform tab width. But in that case, long editor tab title would have to be truncated.

**Comment by panekj** [comment]
It will be better to implement closing tabs on mouse middle click

**Comment by jim-ec** [comment]
This leaves out track-pad users who don't have a middle mouse button. Still, this seems like a good additional option.

**Comment by panekj** [comment]
They can use keyboard shortcut, allowing unnecessary over-customisation of UI is not a good idea.
