### ISSUE TITLE
Feature request: Config to enable auto-saving files after a short period of inactivity, or loss of focus

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#248]
Similar to how settings are saved, we could also save files if the user is done typing. The delay may or may not be configurable.

Auto-save should disable the "file changed" UI hint, to avoid distracting flashing.

**Comment by Chaphasilor** [comment]
The "loss of focus" part of this request isn't present yet, should I create a new issue for that? Really love that feature :)

**Comment by panekj** [comment]
Issue #1884
