### ISSUE TITLE
QHD Manjaro Linux Can't zoom into Editor

### ISSUE THREAD

**Issue by elibroftw** [lapce/lapce#2481]
## Lapce Version

0.2.7

## System information

<details><summary>Manjaro</summary>

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 5.15.114-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620
Manufacturer: Razer
Product Name: Blade Stealth
System Version: 2.04

</details>

## Describe the bug

Can't zoom the UI

## Additional information

QHD, 12.5" display

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

![image](https://github.com/lapce/lapce/assets/21298211/5f9319ce-74e5-443d-a310-39e0dd5b192b)

**Comment by panekj** [comment]
What do you mean by "can't zoom"

**Comment by elibroftw** [comment]
Ctrl + "+" does not make the UI bigger as it does in VS Code, so the UI is not big enough

**Comment by panekj** [comment]
You need to change font size in settings

**Comment by elibroftw** [comment]
The splitscreen icon is still tiny

**Comment by panekj** [comment]
![image](https://github.com/lapce/lapce/assets/50457605/6a875ef4-fc09-4fdf-87b2-3619a0e912d1)
You can change icon size right next to font size

**Comment by elibroftw** [comment]
![image](https://github.com/lapce/lapce/assets/21298211/21a6685a-b235-4076-a9f7-82fda0a93cd6)
It doesn't work

**Comment by elibroftw** [comment]
And there's clipping of the settings text

**Comment by panekj** [comment]
Icon size in status bar should scale with status bar height

**Comment by elibroftw** [comment]
![image](https://github.com/lapce/lapce/assets/21298211/be156d96-2dcd-4cd1-8f73-ed97950eef43)
But it doesn't

**Comment by panekj** [comment]
It might be bugged, unfortunately can't fix it now since whole UI code was replaced so the bug doesn't exists in lapce anymore.
