### ISSUE TITLE
Add an option to disable auto-update

### ISSUE THREAD

**Issue by CaseOf** [lapce/lapce#2483]
## Is your feature request related to a problem? Please describe.

When packaged on a Linux distribution, it would be appreciated that lapce do not auto-update by itself but via package manager instead.

## Describe the solution you'd like

A good way to do this would be via a configuration option at build time.

## Describe alternatives you've considered

Another option would be to add an option in GUI settings.

## Additional context

I’ve opened a bug report about this on Gentoo bug tracker: https://bugs.gentoo.org/909102

**Comment by panekj** [comment]
This is already implemented https://github.com/lapce/lapce/blob/6c85e94e1d21ad2dfc42b9756f2806b5e67d6160/lapce-ui/Cargo.toml#L51
