### ISSUE TITLE
Some errors when installing in windows 10

### ISSUE THREAD

**Issue by br14n-sol** [lapce/lapce#2486]
## Lapce Version

Latest version available from the website.

## System information

Windows 10 Version 22H2 (OS build 19045.3086)

## Describe the bug

The installation executable seems to fail after getting permission to make changes to the device.

## Additional information

![image](https://github.com/lapce/lapce/assets/60621046/e6d1d388-2f8d-4d40-84a0-71afa4a7957a)
![image](https://github.com/lapce/lapce/assets/60621046/93def0f3-e904-42da-a47c-69d176b9e947)
![image](https://github.com/lapce/lapce/assets/60621046/5759a70e-5423-4d7f-af29-61b68f6afde2)

**Comment by panekj** [comment]
Error code 2502/2503 means there is an issue installer service on your machine.

**Comment by br14n-sol** [comment]
> Error code 2502/2503 means there is an issue with installer service on your machine.

The strange thing is that it only happens to me with lapce 🤨

**Comment by br14n-sol** [comment]
I tried the installation again, this time with the nightly version, and it installs without problems, the problem now is that when I want to open the editor the tab remains blank:

![image](https://github.com/lapce/lapce/assets/60621046/b1b571ed-d3cc-45ac-8acf-1a48045f7ae3)

But that I think that would already be for another issue.
