### ISSUE TITLE
"About" window doesn't appear on nightly

### ISSUE THREAD

**Issue by lcotux** [lapce/lapce#2487]
## Lapce Version

Nightly release (June 25, 2023)

## System information

  Kernel: 5.19.0-45-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.6.8 tk: GTK 3.24.33
    wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

## Describe the bug
When I click on the gear wheel on the right corner, no window appears to display a menu (update, about Lapce, ...).

## Additional information

There is no issue on release 0.2.8 and has appeared in nightly a few weeks ago

**Comment by panekj** [comment]
Tracked in #2417
