### ISSUE TITLE
Unwelcome behavior in GNOME

### ISSUE THREAD

**Issue by kojq** [lapce/lapce#2493]
## Lapce Version

`5c15d8489275e7b229cf7615d7a8a06aa75fd996` on master.

## System information

Arch Linux with GNOME.

## Describe the bug

As much as I want to call it a feature request, the interference makes it more of an unintended behavior and should thus be considered a bug.

Here are the situations I notice where Lapce should not be mentioned:

Plugging in a USB drive into the computer port results in asking if you want to open with Lapce.

If you do not have a calendar application installed on GNOME, you will notice the default calendar application is Lapce in GNOME's settings.

**Comment by dmig** [comment]
feel free to fix this: https://github.com/lapce/lapce/blob/master/extra/linux/dev.lapce.lapce.desktop

**Comment by panekj** [comment]
Sorry, but we can't solve GNOME bugs, it's their responsibility to make proper UX. Uninstalling Calendar replaces it with whatever application available on your system.
As for USB, that's also configurable in GNOME Settings.
