### ISSUE TITLE
Show Lapce as an option when doing "Open With..."

### ISSUE THREAD

**Issue by kojq** [lapce/lapce#2494]
## Lapce Version

`v0.2.8`

## System information

Arch Linux with GNOME.

## Describe

Show Lapce as an option when doing "Open With..." using the right click context menu in a file manager such as Nautilus.

**Comment by EErbium** [comment]
Alright working on it

**Comment by SuperSamus** [comment]
That's weird, [the desktop file](https://github.com/lapce/lapce/blob/master/extra/linux/dev.lapce.lapce.desktop) does have:
```
MimeType=text/plain;inode/directory;
```
