### ISSUE TITLE
Rendering issues with Lapce on Ubuntu

### ISSUE THREAD

**Issue by cutoken** [lapce/lapce#2495]
## Lapce Version
Latest (compiled from main) - unfortunately nothing happens when I click on settings

## System information
Ubuntu 22.04 with KDE Plasma Breeze Light theme

## Describe the bug
1) I have compiled the latest lapce from source as per instructions and ran with cargo run --release
2) Lapce launches but doesn't show anything under file explorer. Only the terminal is fully functional. Even clicking settings icon doesn't do much

## Additional information
The plugins tab partially displays the plugins. I'm able to install them but left side of the pane is weirdly cut off/not rendering
![Screenshot from 2023-06-30 18-49-42](https://github.com/lapce/lapce/assets/31798395/9b6d017e-248e-47aa-95b8-9c824cdd0674)
![Screenshot from 2023-06-30 19-02-23](https://github.com/lapce/lapce/assets/31798395/d701a6e8-152c-4d9f-b30f-39e40ba277d6)

**Comment by panekj** [comment]
This is expected due to #2417

**Comment by cutoken** [comment]
hi @panekj ,
    Is Ubuntu not in supported platform list ? Sorry if this is a known bug. Do older releases work ?

**Comment by panekj** [comment]
Stable release should work fine
