### ISSUE TITLE
UI error on win11

### ISSUE THREAD

**Issue by xietao1233** [lapce/lapce#2500]
## Lapce Version

UI error at software startup on win11 

v0.2.8

## System information

Windows 11 Pro 22H2

## Describe the bug

![屏幕截图 2023-07-06 175555](https://github.com/lapce/lapce/assets/16441171/1482a452-540a-4474-a237-28a0d8a23c99)

**Comment by xietao1233** [comment]
And this app has no drag-and-drop operation

**Comment by xietao1233** [comment]
@superlou yes, top bar fixed when resize window

**Comment by xietao1233** [comment]
@superlou my graphics
![屏幕截图 2023-07-08 103829](https://github.com/lapce/lapce/assets/16441171/bf1dd303-b80b-4e28-be7f-266d3fe92f43)

**Comment by superlou** [comment]
Ah, Intel Xe. Looks like the same as #1014.

**Comment by dsweb19778** [comment]
same problem lapce is not working at all in windows

**Comment by dsweb19778** [comment]
@superlou 
![Screenshot 2023-07-13 235327](https://github.com/lapce/lapce/assets/40462602/62357235-54d4-4573-85df-df1afd011fa6)
UI is messy
