### ISSUE TITLE
Integration with Nix-Shell/NixOS

### ISSUE THREAD

**Issue by thopri** [lapce/lapce#2504]
## Is your feature request related to a problem? Please describe.
Kinda? I am starting to use NixPkgs to maintain my dev environments but Lapce cannot see my dependencies installed by Nix (Nix-shell)

## A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
When using Nix-Shell to setup an environment to build my rust apps, Lapce cannot see the dependancies. 
Main issue is the rust-analyzer package. I can set this globally but then its not in lockstep with project e.g. (my global config is nix unstable but projects use current stable).
I can put the rust-analyzer binary path in the settings in Lapce but need to change it each time I load a different project.

## Describe the solution you'd like
A way to tell lapce paths of things like rust analyser on a workspace basis e.g. .env file of somekind

Integration with Nix-Shell environments

## Describe alternatives you've considered
Vscode has a plugin (but what doesn't it have a plug in for....)

**Comment by panekj** [comment]
You can configure all settings via `.lapce/settings.toml` the same way as settings page in lapce

**Comment by thopri** [comment]
but this is still a global reference not a project level one?

**Comment by thopri** [comment]
ah yeah that would be project specific, :) thank you!
