### ISSUE TITLE
Winget installation fails: hash does not match

### ISSUE THREAD

**Issue by vittoriocandolo** [lapce/lapce#2510]
## Lapce Version

0.2.7

## System information

W11

## Describe the bug

Winget installation fails because of hash mismatch.

Also, shouldn't Winget point to 0.2.8?

I think the issue is that the link points at 0.2.8 while some Winget metadata may still refer to 0.2.7.

## Additional information

```powershell
PS C:\Users\dell> winget install lapce
Found Lapce [Lapce.Lapce] Version 0.2.7
This application is licensed by the owner.
Microsoft is not responsible for or grants any license to any third party packages.
Downloading https://github.com/lapce/lapce/releases/latest/download/Lapce-windows.msi

██████████████████████████████ 17.9 MB / 17.9 MB

The installer hash does not match.
```

**Comment by panekj** [comment]
It's a problem with winget, not lapce. You should open issue in https://github.com/microsoft/winget-pkgs

**Comment by vittoriocandolo** [comment]
Committing a new manifest should solve the issue:

https://github.com/microsoft/winget-pkgs/tree/master/manifests/l/Lapce/Lapce

0.2.7 is the last one and is pointing to latest.

It was not clear to me that it was manual effort to update the manifest, so I do apologize for opening the issue in the wrong place.

**Comment by panekj** [comment]
Seems that https://github.com/microsoft/winget-pkgs/pull/112921 fixed it
