### ISSUE TITLE
Unable to navigate remote host

### ISSUE THREAD

**Issue by tirohia** [lapce/lapce#2518]
## Lapce Version
Nightly

## System information
Linux Mint 21.1 (local)
Ubuntu 20.04 (remote)

## Describe the bug
I am able to connect to the remote host using SSH, but am unable to open a directory. 
When I attempt to open a folder, none of the directories in my home directory are visible. Any attempt to change directory results in the SSH status icon dropping from green to orange. 

## Additional information
No additional information. There are no error messages. Navigation works fine on the local machine, but selecting any folder using the Open Folder Dialogue on the remote machine results in the Open Folder dialogue closing and the remote connection getting reset. Happy to post logs if someone tells me where they might be found.

**Comment by panekj** [comment]
This is expected due to #2417
