### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by justinfarrelldev** [lapce/lapce#252]
Adding a contributing file would greatly improve the starting-time for new contributors in this repo. 
Benefits: 

- New contributors would be able to know how to test, run the development build, etc. (seems we have a lot of new Rust devs here, myself included) 
- Code style could be defined more effectively 
- Pull Request style could be specified 

Overall, I love how this is coming along though and I look forward to contributing myself!

**Comment by dzhou121** [comment]
https://github.com/lapce/lapce/blob/master/CONTRIBUTING.md Added now.

Please let me know if it's missing anything.

**Comment by justinfarrelldev** [comment]
Looks good to me!
