### ISSUE TITLE
Add mode for GPU acceleration using OpenGL < 3.3

### ISSUE THREAD

**Issue by hmpthcs** [lapce/lapce#2528]
I have really enjoyed lapce on my laptop and would like to use it on a tablet. In fact, the interface being touch-friendly gives lapce a huge leg up over other newer rust editors (e.g. helix) for use on tablets.

Unfortunately, the tablet has a Mali G52 GPU--no support for OpenGL 3.3. I am left with helix (command line, no touchy) or other standard apps like gedit (not nearly as nice to work on).

I tested lapce using both software rendering and zink as described here: #2333 . On my device (rockchip 3566 CPU), the performance drop was substantial. With these options, I did not feel any of the snappyness that makes lapce such a pleasure to work on.

## Describe the Solution You'd Like to See
Given that GPU acceleration is such a selling point for lapce, and given that many devices are and will continue to be used out there which lack OpenGL 3.3 support I would like to see an option to disable backend features that necessitate OpenGL 3.3. #2333 specifically introduces the idea of "alternative graphics backends." I think this is a great idea; for me, it is unfortunately no GPU = no lapce. Can we somehow replace dual source blending and any other items that need opengl 3.3. with an alternative that works with OpenGL 3.2 (or lower). 

Happy to begin working on a pull request if anyone can add insights and guidance on which _currently-existing_ features of lapce use opengl 3.3. There is some info on the switch to OpenGL here: #1108 , #1062 and #1592 , but I am unsure of the current status of lapce's OpenGL dependencies.

## Additional Context
I am running lapce on a pinenote: rockchip 3566 + mali g52; it has an e-ink screen, and sub-optimal graphics rendering (software rendering, for example) is instantly noticeable.

**Comment by panekj** [comment]
There is alternative renderer in floem now
