### ISSUE TITLE
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x2 but is 0x7fbe4fedc8cb'

### ISSUE THREAD

**Issue by planetoryd** [lapce/lapce#2529]
## System information

EndeavourOS 6.4.7-arch1-1

## Describe the bug

In the middle of developing https://github.com/planetoryd/netns-proxy , `lapce-stable 0.2.8` crashed. 

And when I tried to restart `v0.2.8`. (of lapce-stabe, and then lapce-debug compiled by cargo, both are 0.2.8)

```log
$ lapce /space/netns-proxy
(totally nothing was printed. it crashed)
(happens consistently)
```

the one that crashed in the middle, which is the first occurrence. [lapce.log](https://github.com/lapce/lapce/files/12238151/20230802-003018.log)

`strace -o ./strace.log -f ./target/debug/lapce /space/netns-proxy`, [strace.log](https://github.com/lapce/lapce/files/12238116/strace.log)

`./target/debug/lapce /space/netns-proxy` [lapce-debug.log](https://github.com/lapce/lapce/files/12238101/20230802-161933.log)

**Comment by MinusGix** [comment]
This is: #2463  
As my comment says there,
> This is due to a bug in Swash  
> However, we've fixed this in latest master - but of course latest master is missing various pieces of functionality due to the UI rewrite.

> I believe the answer, since we've changed the UI backend and so we aren't doing new releases with the druid backend, is that you should build that old commit using 1.69/1.68.
