### ISSUE TITLE
Performance regression between 0.2.7 and Nightly

### ISSUE THREAD

**Issue by Kuratius** [lapce/lapce#2538]
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 

lapce --version gives 0.2.7  (no idea what the commit was)

and for lapce nightly the commit is 7682fdb
## System information
Raspberry pi 400
the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04
Raspberry Pi OS, newest version
`Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux`
## Describe the bug

Performance of typing on the built in console is massively reduced.
Characters take a much longer time to appear after being typed. Menu is unresponsive.
## Additional information
This was with software rendering,
LIBGL_ALWAYS_SOFTWARE=1 ./lapce

I can provide the executables I compiled if necessary.

**Comment by panekj** [comment]
That's expected, since we replaced druid with floem (#2417) and we don't use GTK backend anymore

**Comment by Kuratius** [comment]
Is floem a worse backend?

**Comment by dzhou121** [comment]
The release version is a OpenGL backend, and the new nightly is a Wgpu backend. The real solution is a CPU renderer which is planned in Floem.

**Comment by panekj** [comment]
There is now a tiny skia backend
