### ISSUE TITLE
"Unsaved" indicator dot shows up even if you undo the changes

### ISSUE THREAD

**Issue by Sheyne** [lapce/lapce#254]
If you make a change in the editor then hit undo back to the original file, I expect the "unsaved" indicator dot that shows up in the tab bar to disappear.

**Comment by justinfarrelldev** [comment]
It's also happening with me

**Comment by justinfarrelldev** [comment]
Appears to be a duplicate of #245

**Comment by Sheyne** [comment]
Closing in favor of #245
