### ISSUE TITLE
Mirror CTRL + TAB vscode behavior

### ISSUE THREAD

**Issue by AlvinKuruvilla** [lapce/lapce#2543]
## Is your feature request related to a problem? Please describe.

I think it would be a nice quality of life improvement if there were a keybinding to cycle through all open files. Vscode has similar behavior through CTRL + TAB
## Describe the solution you'd like
We should add a keybinding that will cycle through all currently open files. 

## Describe alternatives you've considered

We could use a different keybinding, but if we want to stick with a style similar to vscode, then it would be CTRL + TAB

**Comment by panekj** [comment]
You can bind shortcuts locally in settings
