### ISSUE TITLE
executable size

### ISSUE THREAD

**Issue by 1268** [lapce/lapce#2550]
I am interested in Lapce, especially when I noticed the small build size. for example this is 17.5 MB:

https://github.com/lapce/lapce/releases/download/v0.2.8/Lapce-windows-portable.zip

and this is 20.1 MB:

<https://github.com/vim/vim-win32-installer/releases/download/v9.0.1712/gvim_9.0.1712_x64.zip>

however it seems Lapce is heavily compressed. if you extract, the executable is actually 78.3 MB, whereas the 2,356 files in the Vim distribution add up to 51.8 MB. is the Lapce team interested in reducing this footprint?

**Comment by panekj** [comment]
> is the Lapce team interested in reducing this footprint?

Obviously the answer is yes, it's always nice to reduce distribution size but your comparison is unfair to us.
You can't compare a C codebase distribution which tends to be much leaner to Rust codebase distribution where bundled runtime is much bigger.

> the executable is actually 78.3 MB, whereas the 2,356 files in the Vim distribution add up to 51.8 MB

As of right now, Lapce built from master takes 47MB.

**Comment by 1268** [comment]
> As of right now, Lapce built from master takes 47MB.

ooh thats nice. do you have Windows instructions? I checked here:

https://github.com/lapce/lapce/blob/master/docs/building-from-source.md

or is it just `cargo build`?

**Comment by panekj** [comment]
> or is it just `cargo build`?

It is but the current HEAD version is not as usable as 0.2.8 is due to rewriting/switching GUI library.

**Comment by 1268** [comment]
> not as usable

can you elaborate? I can wait for next release if need be, but if the HEAD is decent then I am OK with it. is it buggy or just missing some features or what? I am coming from gVim, so I dont need anything too fancy

**Comment by panekj** [comment]
#2417

**Comment by MinusGix** [comment]
> or is it just `cargo build`?

(Specifically `cargo build --release`, otherwise it will include a bunch of debug info and not be optimized by the compiler as much)

**Comment by panekj** [comment]
I believe the question has been answered. As for reducing size, it was already done (by me, #2478) and more changes to our dependency tree are planned but it's a long hard work of dealing with `Cargo.lock` file and dependency versions.
