### ISSUE TITLE
Single registry for all commands

### ISSUE THREAD

**Issue by andreytkachenko** [lapce/lapce#256]
- create a registry of all commands where each command will be a struct with **name** and **args** and other (group, plugin etc.). 
- allow run all commands from **:** command (similar to vim command model) with auto-completions taken from **args** description
- share this commands with plugins (`download_file` and `start_lsp` should be a `lapce` command not `lapce-proxy`)

It would be great if some part of **lapce** code will migrate into plugins:
- Language Integrations (syntax, preferences etc.)
- Themes

**Comment by panekj** [comment]
Some of these features have been implemented
