### ISSUE TITLE
Allow binding mouse buttons to commands

### ISSUE THREAD

**Issue by riverbl** [lapce/lapce#2572]
I'd like to bind the side buttons on my mouse to navigate forward and backward. This behaviour is the default in web browsers and VS Code.

Currently Lapce doesn't allow binding mouse buttons to commands, so this is not possible.

**Comment by panekj** [comment]
It's already implemented

**Comment by riverbl** [comment]
Ah OK - how do I bind `mouseback` and `mouseforward` to navigate backward and forward? The following does not work for me on `master`:

```
[[keymaps]]
command = "jump_location_forward"
mode = "i"
key = "mouseforward"

[[keymaps]]
command = "jump_location_backward"
mode = "i"
key = "mousebackward"
```

**Comment by panekj** [comment]
It's implemented in latest release, if it doesn't while building from source, it should be mentioned in https://github.com/lapce/lapce/issues/2417

**Comment by riverbl** [comment]
I don't see it mentioned in #2417. I'm building the latest `master` from source.

**Comment by MinusGix** [comment]
(The idea is/was that features that were implemented in release but were missing from master would be added to #2417 to make it easier to track that we need to reimplement them)
I added it and also linked your PR. Thanks for reimplementing it, I was missing that feature.
