### ISSUE TITLE
Intellicense doesn't work. lsp plugin javascript/typescript not connect.

### ISSUE THREAD

**Issue by 1uri-silva** [lapce/lapce#2586]
Lapce nightly

Ubuntu mint 20.3 x86_64

I installed the javascript/typescript plugin but it gives this error, I also have node installed by nvm

![Captura_de_tela_de_2023-08-31_15-16-13](https://github.com/lapce/lapce/assets/78041884/c05dae3b-0f0b-4aac-932d-e09aa4f5383d)

**Comment by panekj** [comment]
`node` executable wasn't found, proably due to some custom things that `nvm` does, `node` needs to be in one of the paths availabl in `PATH`
