### ISSUE TITLE
Current nightly makes gnome-shell crash

### ISSUE THREAD

**Issue by FlixCoder** [lapce/lapce#2592]
## Lapce Version

master/8d7a1f1b7f56b973720ac6c7ba18cf1578cd5006

## System information

Fedora Linux 38 (Workstation Edition)
Kernel 6.4.13-200.fc38.x86_64
Gnome 44.4
Wayland

## Describe the bug
Running lapce makes gnome-shell crash and either send me back to login or crash the OS.

Obviously this might be a bug in the OS/Gnome-shell too, but it might still make sense to track that here.

## Additional information

None, I just built and run. No logs are being put out.

**Comment by flukejones** [comment]
I don't think this is due to lapce at all. You might want to check the tail end of `journal -b`

**Comment by FlixCoder** [comment]
You might be right, it somehow works now? Not sure why, sorry
