### ISSUE TITLE
Can't close window using the window close button

### ISSUE THREAD

**Issue by bjorn3** [lapce/lapce#26]

**Comment by Artofaj** [comment]
I can reproduce this on manjaro (gnome, if it makes any difference). I can only close the application by killing it.

**Comment by ghishadow** [comment]
latest update fixed this for me, also remote development is working now

**Comment by bugadani** [comment]
@bjorn3 could you please see if this issue still stands? Thanks!

**Comment by bjorn3** [comment]
It works now for me.
