### ISSUE TITLE
How do I add auto completion for languages other than rust?

### ISSUE THREAD

**Issue by IUB2010** [lapce/lapce#2600]

**Comment by MinusGix** [comment]
Typically you need a language server for your language. You can then have a plugin start that LSP.  
There's a template for writing plugins at https://github.com/lapce-community/lapce-volt-template which has some of the setup you might want for a language server plugin.  
There are several plugins for other languages which you could take a look at: https://github.com/lapce/lapce-rust or https://github.com/lapce-community/lapce-go
