### ISSUE TITLE
`Dockerfile` files syntax highlight

### ISSUE THREAD

**Issue by banditopazzo** [lapce/lapce#2613]
## Lapce Version

0.28

## System information

Arch Linux

## Describe the bug

No automatic syntax highlight for files named `Dockerfile` without any extension

## Additional information

workaround: manually specify the language with the language selector

**Comment by panekj** [comment]
Already mentioned in https://github.com/lapce/lapce/issues/272 and it's available in 0.2.8

**Comment by volkertb** [comment]
@panekj If it's already available, does it need to be enabled some way? Because Dockerfiles are still not being highlighted "out of the box". Shall I open a separate issue for this?
