### ISSUE TITLE
proC macro entry not expanded: Proc-macro dylib Loading failed: unsupported metadata version 7

### ISSUE THREAD

**Issue by Springrass** [lapce/lapce#2615]
![截屏2023-09-15 20 31 45](https://github.com/lapce/lapce/assets/65485088/6581a0bb-8239-49fd-91d2-f5d8ffbfcad8)
Is it not supported for kernel calls?

**Comment by panekj** [comment]
Not an issue with lapce
https://github.com/lapce/lapce-rust/issues/33
