### ISSUE TITLE
Multiple cursor keybinds modification

### ISSUE THREAD

**Issue by Bykow** [lapce/lapce#2623]
Hello !

In the [docs](https://docs.lapce.dev/features/multiple-cursor) for multiple cursor, it specifies Ctrl + Alt. It would be super usefull to be able to change that to Ctrl + Shift.

The reason behind that is that I'm using Alt as my main swaywm (or i3) modifier. I'm sure I'm not alone in this !

Repost from https://github.com/lapce/lapce/discussions/2433 for tracking

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/2442
