### ISSUE TITLE
Terminal does not allow to select text

### ISSUE THREAD

**Issue by FlixCoder** [lapce/lapce#2627]
## Lapce Version

Nightly `c539f7a205ec056b6bceed963b61165e9f430353`

## System information

Fedora 38, Wayland

## Describe the bug

Whatever I do, when I click and drag in the terminal, nothing happens. I would expect text to be selected and highlighted up for copying.

## Additional information

None

**Comment by panekj** [comment]
This is a regression due to https://github.com/lapce/lapce/issues/2417

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/3106
