### ISSUE TITLE
Julia highlighting used in another project - request to do so under MIT

### ISSUE THREAD

**Issue by ShalokShalom** [lapce/lapce#2640]
Hi there :)

I used some of your code, and the project I am using it with, is licensed under the MIT. 
Do you give us the permission, to relicense it under MIT?

https://github.com/TorchedSammy/Evergreen.lxl/pull/47

Thanks a lot

**Comment by panekj** [comment]
It's not our code so we cannot do that

**Comment by MinusGix** [comment]
As the comment on the original file says on the bottom, it is from https://github.com/helix-editor/helix/blob/master/runtime/queries/julia/highlights.scm which is MPL-2.0  
Other files we have from them have  
```
; source: https://github.com/helix-editor/helix/blob/master/runtime/queries/javascript/highlights.scm
; license: https://github.com/helix-editor/helix/blob/master/LICENSE
; spdx: MPL-2.0
```
at the top, but it seems like it was forgotten to add to this file.  
Or the more standard way is probably to just add the text here https://github.com/helix-editor/helix/blob/master/LICENSE#L358-L360 to the top of the scm file in Evergreen.

**Comment by ShalokShalom** [comment]
Thanks a lot
