### ISSUE TITLE
Build dependencies for openSUSE

### ISSUE THREAD

**Issue by MatusModder** [lapce/lapce#265]
Hello there. I have a question. Will there be a tutorial how to build Lapce on openSUSE?

**Comment by justinfarrelldev** [comment]
I would also love to see more build instructions for various platforms. I think ideally we should have the instructions added to both Contributing.md as well as the top of [this page](https://docs.lapce.dev/get-started/setup).

**Comment by bugadani** [comment]
Hi and thanks for reporting!

We already have an issue for missing build instructions (#3) so I'm closing this as a duplicate.
