### ISSUE TITLE
Weird clipboard crash

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#2676]
## Lapce Version

Almost latest master

## System information

Linux, Wayland

## Describe the bug
I was spamming typing in my editor to test my screen lines cache and it crashed with
```
Maximum number of clients reached
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConn(Connection)', lapce-app/src/doc.rs:79:43
```

## Additional information

Which is
```rust
impl SystemClipboard {
    pub fn new() -> Self {
        SystemClipboard {
            ctx: ClipboardProvider::new().unwrap(),
        }
    }
}
```
and it is constructed every time an edit is done.  
Presumably it is either getting constructed too often while other clipboard connections are open, or it isn't getting cleaned up at all.  
Possibly we should just have a general shared instance on `common` or something?

**Comment by lukaslihotzki** [comment]
I can trigger this reliably by holding down `Ctrl+V`.
