### ISSUE TITLE
Drag and drop in the left panel

### ISSUE THREAD

**Issue by trignomtry** [lapce/lapce#2692]
## Is your feature request related to a problem? Please describe.

In visual studio there is a drag and drop in the left panel where you can put a file in a directory by just dragging it into.
## Describe the solution you'd like

I would like for you to be able to Drag a file into the folder to move it. 
## Describe alternatives you've considered

I'vs used the reveal directory and dragged the file but it is more hassle.

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/1460
