### ISSUE TITLE
Does not compile on Linux (cause: tree-sitter-highlight dependency)

### ISSUE THREAD

**Issue by flosse** [lapce/lapce#27]
![Bildschirmfoto_2021-12-14_17-30-47](https://user-images.githubusercontent.com/276043/146039320-17d34003-8b05-49ae-a1ac-dfe4f0f43b51.png)

- rustc 1.57.0
- target: x86_64-unknown-linux-gnu
- commit: 93737031e7ce6dfafefd60df3503c039c2df90eb

**Comment by channelbeta** [comment]
This happened to me when I ran `cargo update`. Is your `Cargo.lock` modified (should be if you ran the update command) or the same as the git repository?

**Comment by flosse** [comment]
I'm sorry, I forgot to add `--locked` to `cargo install` :see_no_evil:
