### ISSUE TITLE
why i cann't ssh remote Linux Server in Windows11

### ISSUE THREAD

**Issue by songqing0353036** [lapce/lapce#2726]
## Lapce Version
v0.2.8

## System information
Windows 11  22H2

## Describe the bug
![Uploading image.png…]()
I cann't ssh a remote Linux Server in Windows11 env,  are there something wrong in my setting of OS or Lapce?

**Comment by MinusGix** [comment]
The image appears broken for me.

**Comment by songqing0353036** [comment]
can this image be

**Comment by SashaPetrovska** [comment]
why is this closed? it doesn't work for me either. I can ssh from windows terminal, but I can't ssh from the ide. Actually running a local vmware environment. but it worts fine with other ides.
