### ISSUE TITLE
Lapce became File Manager on Manjaro

### ISSUE THREAD

**Issue by 8ullyMaguire** [lapce/lapce#2727]
## Lapce Version

```
❯ lapce -V
Lapce-Stable 0.2.8
```

## System information

Manjaro Cinnamon

```
❯ uname -r
6.5.9-1-MANJARO

~
❯ cat /etc/lsb-release
DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="23.1.0"
DISTRIB_CODENAME="Vulcan"
DISTRIB_DESCRIPTION="Manjaro Linux"
```

## Describe the bug

Lapce became the File Manager even though I had Nemo installed.

I tried to select it from the Source Code dropdown but it didn't appear in Recommended, Related or Other Applications. In Other Applications there are many programs, but Lapce isn't there.

## Additional information

This has happened to me before with vscodium.

**Comment by paricbat** [comment]
`xdg-mime default nemo.desktop inode/directory` should set Nemo as the default when opening folders

**Comment by MinusGix** [comment]
Unsure if there's a nice immediate way to fix this, but I haven't looked closely. Like you, I've had this with VSCodium/VSCode and other apps like Firefox taking priority for files/folders which they really shouldn't, and if VSCode hasn't fixed it then it may just be an annoyance we have to live with.  
(Though if someone has a solution that still allows us to have 'open this folder with Lapce' then that'd be great)

**Comment by BoxFoxCode** [comment]
Speaking of VSCodium, here's the issue of them discussing that and updating early docs for the time. - https://github.com/VSCodium/vscodium/issues/409

I don't think I've had this before, but it seems the hypothesis was that it ended up mostly being defaults not being set or not set correct such that order of precedence fell all the way to `mimeinfo.cache` which is not ordered/weighted; may be sorted for binary sort, as the spec says for the cache. Which would mean occurrence is only possible between applications that would get sorted in that order -- "codium" or "dev.lapce" is sorted before "org.gnome" (Gnome) or "nemo"/"org.nemo" (Cinnamon) but after "caja" (MATE).
Whether that is the full picture or not, I don't know.

`xdg-mime` should fix that, likely with a restart/relog needed. If not, checking the local user and system locations for the list files for mime file default like that VSCodium discussion may be a first step.
Ex. Their(VSCodium) resolution was assuring `~/.config/mimeapps.list` for local user defaults; referencing the Arch wiki - [XDG_MIME_Applications](https://wiki.archlinux.org/title/XDG_MIME_Applications#Non-default_application).

Another way that this could happen is if an application only supports some, it's own, or depreciated locations for default lists such that those locations aren't updated by whatever application is used to set defaults.

---
"Open this folder with..." should probably work normally, if you don't accidentally set the default application from the option to do so being set to true by default.
It'd be interesting if a file manager kept it's own config list of folders to do something different with, but I don't think I've seen that before. Similarly, as far as I know, it's not actually possible to create a new mime subtype of `inode/directory` like `inode/mount-point`. That makes sense for non-extensions in that `inode/mount-point` exists to add functionally, not to operate differently, for what it is and not really a setting you can change. Directory extensions aren't a thing like I think maybe macOS does.
But I think you maybe mean being listed as an "Open with..." option in the context menu, which should also be fine just the same as the dialog for further selection.

**Comment by panekj** [comment]
Issue exists outside of Lapce scope
