### ISSUE TITLE
UI issues in v0.3.0

### ISSUE THREAD

**Issue by dpcat237** [lapce/lapce#2732]
## Lapce Version

v0.3.0

## System information

Ubuntu 22.04.03

## Describe the bug
After updating to v0.3.0, the UI interface is gigantic. When I try to move the Lapce's window, the app jumps to the left, almost totally outside of the desktop.

PS. I had to roll back to v0.2.8.

## Additional information

v0.2.8
![Screenshot from 2023-11-01 00-13-06](https://github.com/lapce/lapce/assets/388031/953219a1-d6d3-4d16-9cea-ef6f0a7a3656)

v0.3.0
![Screenshot from 2023-11-01 00-13-32](https://github.com/lapce/lapce/assets/388031/b5eb699b-3552-4954-8f51-a70d4db6e403)

v0.3.0 - after trying to move the window
![Screenshot from 2023-11-01 00-14-18](https://github.com/lapce/lapce/assets/388031/e16f7838-d840-432c-801d-1d81a0a711fd)

**Comment by john01dav** [comment]
I encountered a similar problem on Debian 12. Sometimes it crashes completely as I try to move it (stops showing up in ps aux).

**Comment by burrbull** [comment]
The same. Collapses window width or height to 1px when trying to move or change window size.

**Comment by LSchuepbach** [comment]
Also affected . Here's what comes when launching:
```
Nov 01 09:58:21 lsc-sepp /usr/libexec/gdm-x-session[7022]: (II) modeset(0): EDID vendor "LGD", prod id 1667
Nov 01 09:58:21 lsc-sepp /usr/libexec/gdm-x-session[7022]: (II) modeset(0): Printing DDC gathered Modelines:
Nov 01 09:58:21 lsc-sepp /usr/libexec/gdm-x-session[7022]: (II) modeset(0): Modeline "1920x1080"x0.0  138.70  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync (66.7 kHz eP)
Nov 01 09:58:21 lsc-sepp /usr/libexec/gdm-x-session[7022]: (II) modeset(0): Modeline "1920x1080"x0.0  110.96  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync (53.3 kHz e)
Nov 01 09:58:21 lsc-sepp /usr/libexec/gdm-x-session[7022]: (--) modeset(0): HDMI max TMDS frequency 300000KHz
```
Here when resizing:
```
Nov 01 09:58:27 lsc-sepp gnome-shell[7324]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5593e5ec2320] is on because it needs an allocation.
Nov 01 09:58:27 lsc-sepp gnome-shell[7324]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5593e8146b10] is on because it needs an allocation.
Nov 01 09:58:27 lsc-sepp gnome-shell[7324]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5593e626c360] is on because it needs an allocation.
```

uname -a (in case it helps)
```
Linux lsc-sepp 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Willy19921992** [comment]
Same issue here with gigantic UI, but moving the window works differently for me. I can maximize and minimze the window normally, but if I try to move it, the entire graphic environment freezes. I can still move the mouse, but I can't interact with anything. Only solution I found was to change to a different tty (for whatever reason the keyboard shortcut also takes like 20 seconds to switch me to another tty) and kill lapce manually, which makes the graphical environment responsive again.

I'm using Arch Linux with KDE Plasma in a X session. Lapce doesn't print anything usefull in the terminal when I run it with -w.

Could also be related, but maybe requires a different issue. I use a laptop with dual graphics, AMD iGPU and NVIDIA dGPU. Normally I would use prime-run to run stuff with the dGPU, but since I upgraded to v0.3.0, Lapce switched to use the dGPU by default. Checked for environment variables and all, but all of my other programs behave normally, only Lapce uses dGPU by default.

**Comment by computermouth** [comment]
```
When I try to move the Lapce's window, the app jumps to the left, almost totally outside of the desktop.
```

Weird, mine jumps to the right.

(Debian 11, xorg, openbox)

**Comment by ElmeriVincent** [comment]
Yup. Can replicate with Pop!_OS. 

The window can be moved on Pop with Super+left_click and drag, but only with that and not with keyboard shortcuts like the default (super+enter and arrows). Even when the move is possible, there seems to be a frame drop

**Comment by jay-j** [comment]
Can also replicate here with v0.3.0 and the current nightly (https://github.com/lapce/lapce/commit/bbe431a162e95685d2a334caa7e33bc8f3b2c255).

Linux Mint 21.1 Xfce, Linux 5.15.0-88-generic, XDG_SESSION_TYPE=x11, NVIDIA driver version 535.129.03.

**Comment by ethereumdegen** [comment]
i can replicate as well with linux mint 21.

**Comment by Kulasko** [comment]
@ethereumdegen "lapce -w" doesn't detach from your terminal session and gives you debug outputs.

**Comment by pwouik** [comment]
caused by https://github.com/rust-windowing/winit/issues/3245

**Comment by pwouik** [comment]
likely fixed by [048c510](https://github.com/lapce/lapce/commit/048c5103e27f62a5605f841d2915af14cd183565)

**Comment by burrbull** [comment]
Yes. Does not crashes now. Thanks.

Although still some issues after changing editor zoom. With popup menu positioning and cursor.

**Comment by pwouik** [comment]
this should be separate issues if they do not exist already

**Comment by ethereumdegen** [comment]
> @ethereumdegen "lapce -w" doesn't detach from your terminal session and gives you debug outputs.

nope i just tried that. i did -w and it says Uknown Option -w.  then it does seem like it would give me outputs BUT when i write code, 30 seconds later it crashes and no terminal output.   Only fix is to restart PC then i get another good 30 mins out of lapce.

**Comment by Viciouss** [comment]
For me, using the snapshot solved the problem as well.

Is there anyone still having issues with the latest snapshot or is this fixed by https://github.com/lapce/lapce/commit/048c5103e27f62a5605f841d2915af14cd183565 as mentioned above? If so, the issue could be closed.

**Comment by LSchuepbach** [comment]
Yes, the nigthly build doesn't have this issue anymore. I agree with closing the issue.

**Comment by as3ii** [comment]
I tried building 45951733ee and I still see the bad UI, really huge compared to other programs.
Lapce has its default settings, 1080p display, lapce and vscode (default font size) side by side:
![screenshot](https://github.com/lapce/lapce/assets/29260716/6bc9236e-50c4-4861-bcb3-82bfeb4dbeb6)

**Comment by Viciouss** [comment]
@as3ii there is already !2737 for the issue with menus and UI scaling, I think it's better to have separate issues as they don't seem to have a common root cause.

**Comment by LSchuepbach** [comment]
Resizing and moving window works now reliably. Unfortunately, the minimize window doesn't do anything. The maximize button makes everything go black. This feels like a bigger issue than just !2737.

**Comment by oleole39** [comment]
> Yes, the nigthly build doesn't have this issue anymore. I agree with closing the issue.

Not sure which nightly build you are referring to, but it is at least not fixed (gigantic UI & window's jumping behavior) in 0.3.1 (Flatpak) on Linux Mint 21 Cinnamon

**Comment by dpcat237** [comment]
After updating to v0.4.0 I see adjusting the font size of the UI all gets smaller :) So, I'll close this issue.
What is left is a commented [issue](https://github.com/lapce/lapce/issues/2737) with too large Menus.
