### ISSUE TITLE
v0.3.0 crash maybe due to failed to create initial log file

### ISSUE THREAD

**Issue by hgkamath** [lapce/lapce#2734]
## Lapce Version
v0.3.0
problem did not exist before upgrade from 0.2.8

There are two distinct bugs here
BugA) one that shows up while trying to run as unprivileged user <- workaround=give-write-permission-to-logdir
BugB) one that shows up while trying to run as privileged user. <- more **serious** one

## System information
HP laptop, Intel haswell i7-4700mq with intel HD4600 graphics with NVidia gt740m hybrid graphics

The operating system used, including its version, 
```win11 22H2 22621.2506```
lapce is installed by admin user as a non-private global app using scoop installer: ```scoop install -g lapce```  
```
PS C:\Users\admin> $env:SCOOP_GLOBAL
C:\vol\scoop_01\scoopg
PS C:\Users\admin> echo $env:SCOOP
C:\vol\scoop_01\scoop
```
```
PS C:\Users\gana> echo $env:SCOOP_GLOBAL
C:\vol\scoop_01\scoopg
```
```C:\vol\scoop_01\scoopg\shims``` is in the ```PATH``` 

## Describe the bug

**BugA**: can't find logfile error followed by crash, on start by unprivileged user
```
PS C:\Users\gana> $env:RUST_BACKTRACE="full"
PS C:\Users\gana> lapce
thread 'main' panicked at lapce-app\src\app.rs:3341:10:
Couldn't create rolling appender: InitError { context: "failed to create initial log file", source: Os { code: 5, kind: PermissionDenied, message: "Access is denied." } }
stack backtrace:
   0:     0x7ff7dbac59df - git_tag_tagger
   1:     0x7ff7d9f8197b - git_odb_object_data
   2:     0x7ff7dbaa4392 - git_tag_tagger
   3:     0x7ff7dbac7d1a - git_tag_tagger
   4:     0x7ff7dbac790e - git_tag_tagger
   5:     0x7ff7dbac8905 - git_tag_tagger
   6:     0x7ff7dbac8385 - git_tag_tagger
   7:     0x7ff7dbac82d9 - git_tag_tagger
   8:     0x7ff7dbac82c4 - git_tag_tagger
   9:     0x7ff7dc5a6985 - tree_sitter_bash
  10:     0x7ff7dc5a6df4 - tree_sitter_bash
  11:     0x7ff7db1f860b - git_tag_tagger
  12:     0x7ff7d9ea13e6 - <unknown>
  13:     0x7ff7d9ea14b0 - <unknown>
  14:     0x7ff7dc5a199c - tree_sitter_bash
  15:     0x7fffe72e257d - BaseThreadInitThunk
  16:     0x7fffe89caa58 - RtlUserThreadStart
```

**BugB** GUI crash on start by privileged user  
But, when running in admin privileged powershell windows terminal, the log crash does not happen
Instead a different bug, GUI crash like, but no useful messages. 
- A blank white main GUI window, with title ```winit window``` shows up for a while, its title bar is outside view above top of display.
- then the below happens twice ( second time around, the main GUI window resizes to a little bit smaller, bringing the titlebar into view)
   - a dialog-box with title ```lapce.exe has stopped working```, and description : _"Hangon while windows reports the problem to microsoft"_
   - which becomes a message-box with close button with the same mbox-title but with description : _"A problem caused program to stop working correctly, Windows will close the program and notify you if a solution is available"_
- followed by silent termination
```
PowerShell 7.3.9
Loading personal and system profiles took 947ms.
PS C:\Users\admin> $env:RUST_BACKTRACE="full"
PS C:\Users\admin> lapce
PS C:\Users\admin> lapce
PS C:\Users\admin>
```

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- this might be because i run the user as a unprivileged user powershell windows-terminal
- but, then I also ran this in an admin privileged admin powershell windows-terminal
- lapce is installed via 'scoop', As scoop is for shared portable use, its ```persist``` directory needs to be have write permissions which I need to check.

So
Q1) where is it trying to create the log file?

**Comment by panekj** [comment]
Lapce uses standard AppData location for storing data.

**Comment by hgkamath** [comment]
rgd BugA:  
When running as admin the 'unable to log file does not happen' because the admin user can write to 
So one part of this bug is that 
when doing portable install in scoop the data directory 
```C:\vol\scoop_01\scoopg\``` **```apps```** ```\lapce\current\lapce-data```
should be a Junction-Link to
```C:\vol\scoop_01\scoopg\``` **```persist```** ```\lapce\lapce-data```
A scoop user is expected to have/give write permissions here, so that scoop apps can persist configuration data between upgrades.  
The apps folder ```C:\vol\scoop_01\scoopg\apps\lapce\current``` folder which is a junction to ```C:\vol\scoop_01\scoopg\apps\lapce\0.3.0``` is managed by scoop and gets completely deleted on each upgrade. 

```
PS C:\Users\admin> (Get-ChildItem -Recurse -Directory C:\vol\scoop_01\scoopg\apps\lapce\current\)| %{ $_.FullName}
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data\config
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data\data
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data\config\lapce.db
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data\config\lapce.db\blobs
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data\data\cache
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data\data\grammars
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data\data\logs
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data\data\plugins
C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data\data\themes
```
```
PS C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data> cmd /c "dir "
 Volume in drive C is WinOS_2112A
 Volume Serial Number is 6910-34FB

 Directory of C:\vol\scoop_01\scoopg\apps\lapce\current\lapce-data

11/01/2023  10:16 AM    <DIR>          .
11/01/2023  10:16 AM    <DIR>          ..
11/01/2023  10:16 AM    <DIR>          config
11/01/2023  10:16 AM    <DIR>          data
               0 File(s)              0 bytes
               4 Dir(s)  81,413,398,528 bytes free
```
```
PS C:\vol\scoop_01\scoopg\apps\lapce> cmd /c "dir "
 Volume in drive C is WinOS_2112A
 Volume Serial Number is 6910-34FB

 Directory of C:\vol\scoop_01\scoopg\apps\lapce

11/01/2023  09:07 AM    <DIR>          .
10/22/2023  05:07 PM    <DIR>          ..
11/01/2023  10:16 AM    <DIR>          0.3.0
11/01/2023  09:06 AM    <JUNCTION>     current [\??\C:\vol\scoop_01\scoopg\apps\lapce\0.3.0]
               0 File(s)              0 bytes
               4 Dir(s)  81,413,398,528 bytes free
```

**Comment by hgkamath** [comment]
This is the last line in the log file 
```
2023-11-01T04:58:41.920942Z ERROR lapce_app::keypress: Failed to load from "C:\\vol\\scoop_01\\scoopg\\apps\\lapce\\current\\lapce-data\\config\\keymaps.toml": no keymaps
```

**Comment by panekj** [comment]
> rgd BugB:
> 
> This is the last line in the log file
> 
> ```
> 2023-11-01T04:58:41.920942Z ERROR lapce_app::keypress: Failed to load from "C:\\vol\\scoop_01\\scoopg\\apps\\lapce\\current\\lapce-data\\config\\keymaps.toml": no keymaps
> ```
> 
> Attachment `lapce.2023-11-01.log` : Uploading lapce.2023-11-01.log…

This is not a bug, that's correct behaviour

**Comment by hgkamath** [comment]
So do you have enough information for actionability on both bug-A an bug-B?  
or do you need me to any more troubleshooting, are u able to replicate it ?

**Comment by vova616** [comment]
Also does not open for me windows 11, even after removing all files and settings and reinstalling

**Comment by vova616** [comment]
Direct installer, and also the portable versions, both of them not working at all and not opening

[lapce.2023-11-01.log](https://github.com/lapce/lapce/files/13230043/lapce.2023-11-01.log)

**Comment by panekj** [comment]
The problem exists because scoop is using portable build instead of standard build, portable puts all the data next to the executable which is correct behaviour for portable scenarios
