### ISSUE TITLE
I don't have exe file

### ISSUE THREAD

**Issue by lorypelli** [lapce/lapce#2738]
After installing .msi latest 0.30.0 doesn't have .exe file

**Comment by lorypelli** [comment]
Ok, now I have it, but the window is called `winit window`

**Comment by panekj** [comment]
> the window is called `winit window`

That's expected behaviour

**Comment by lorypelli** [comment]
> > the window is called `winit window`
> 
> That's expected behaviour

why?

**Comment by panekj** [comment]
because there is currently no way to set the window title

**Comment by lorypelli** [comment]
> because there is currently no way to set the window title

There was a title with 0.28

**Comment by panekj** [comment]
Yes but since then whole UI has changed

**Comment by lukaslihotzki** [comment]
There must be a way to set the title because it gets set on the old window when you open a new window.
