### ISSUE TITLE
File & Folder open functions and other dialoges broken in v0.3.0

### ISSUE THREAD

**Issue by alerque** [lapce/lapce#2740]
I just gave a test drive to v0.3.0 via Arch Linux packages running Wayland (Hyprland). The result is barely usable. I first noticed the file open / folder open functions would not pull up. I was able to open a project by launching it externally with a file parameter, but nothing in-app would allow me to open a file.

While reporting this bug, I realized even the "about lapce" dialogue won't come up. I suspect something very fundamental about launching dialogue boxes is broken, likely Wayland specific.

**Comment by shivshankardayal** [comment]
I confirm this even for X11 on Manjaro. Though, "About Lapce" is working for me. However, I cannot open a file/folder.

**Comment by gnuchanos** [comment]
arch linux same problem not just folder ui not responsive very well

**Comment by RenjiSann** [comment]
I had the same issue with the version 0.3.0. on Arch Linux.
I fixed it by downgrading the version of the `xdg-desktop-portal` from 1.18 to 1.16.

I was able to replicate the same issue with the `rfd` (rust file dialog) crate, so I guess this is an upstream bug.

**Comment by alerque** [comment]
Thanks for the research @RenjiSann. Did you file an upstream bug we can track here? If it gets a fix I could potentially even patch the Arch Linux package, although a patch release to this project would be much better.

**Comment by RenjiSann** [comment]
I haven't filed any issue yet, I will do it now

**Comment by RenjiSann** [comment]
Here is the issue on the rfd repo: https://github.com/PolyMeilex/rfd/issues/157

Also, I just realized that this bug also affects firefox. When setting the file dialog to the xdg-portal in Firefox, no dialog will appear with xdg-desktop-portal v1.18, but it will work with version 1.16. So it might be an even bigger problem than I originally thought

**Comment by RinLovesYou** [comment]
xdg-desktop-portal downgrade did not solve this for me

**Comment by shivshankardayal** [comment]
It has started working for me in v0.3.1.

**Comment by johndo100** [comment]
Still not working flatpak 0.3.1 - on Void Linux

**Comment by panekj** [comment]
Should be fixed in master since updated `rfd`
