### ISSUE TITLE
lapce 0.3.0 need to be executed with WAYLAND_DISPLAY="" on gnome 45 wayland session.

### ISSUE THREAD

**Issue by M0Rf30** [lapce/lapce#2742]
## Lapce Version

0.3.0

## System information

Arch Linux with Gnome 45 (wayland session)

## Describe the bug
Launching lapce with the deskop entry or using the command from terminal don't work.
No window appear at all.

## Additional information
I solved using
`
Exec=env WAYLAND_DISPLAY="" lapce %F
`
in `/usr/share/applications/dev.lapce.lapce.desktop`

**Comment by sfzhu93** [comment]
I tried `WAYLAND_DISPLAY="" ./lapce` but window still doens't show up on my main display. I can alt-tab and find lapce is started. The menu bar on top of the gnome desktop also shows lapce is running.

**Comment by MedLabs** [comment]
with WAYLAND_DISPLAY="" it starts with black window on the top left corner, then it freezes... on arch linux

**Comment by M0Rf30** [comment]
Fixed in 0.4.0 on gnome 46
