### ISSUE TITLE
v0.3.0 Can't save New File on Windows 10

### ISSUE THREAD

**Issue by wHoIsDReAmer** [lapce/lapce#2753]
## Windows 10

I tried save the file named any, but I can't. it doesn't show any format on save window.

![image](https://github.com/lapce/lapce/assets/100464827/6c28d131-c199-47c3-b6bd-241cfafb98db)

**Comment by TitanNano** [comment]
Also not possible on macOS

**Comment by Mforcen** [comment]
Not possible either in Linux, although you can create them in the terminal and they are immediately recognized.

**Comment by wHoIsDReAmer** [comment]
I know that it can be created by terminal command but it's so uncomfortable. too slow
