### ISSUE TITLE
Broken editor window behavior in KDE

### ISSUE THREAD

**Issue by Khvalin** [lapce/lapce#2758]
## Lapce Version
0.3.0, also nightly

## System information
Manjaro Linux 23.0.4, Plasma 

## Describe the bug
Attempts to drag or resize the editor window makes it disappear or positioned incorrectly. 

## Additional information
- dragging is more flawed.
- there is a way to  bring it back by "Maximizing" the window from the task bar context menu.
- the window seems to be positioned outside of viewport. 

Attaching a video of this issue:

<video src='https://github.com/lapce/lapce/assets/1132781/8ac16b4a-4a10-4ef4-8037-923c53855c7d'  />

**Comment by ElmeriVincent** [comment]
#2732

**Comment by hollispotter** [comment]
A workaround appears to be to disable "enable customized titlebar" - window now behaves acceptably. (I also prefer my native Irix-themed titlebar :-))

Pop!_OS 22.04 LTS, XFCE 4.16, Lapce 0.3.0

**Comment by Khvalin** [comment]
> A workaround appears to be to disable "enable customized titlebar" - window now behaves acceptably. (I also prefer my native Irix-themed titlebar :-))
> 
> Pop!_OS 22.04 LTS, XFCE 4.16, Lapce 0.3.0

nice, thanks for sharing! that workaround worked for me.

**Comment by Khvalin** [comment]
This bug appears to be fixed now indeed.
