### ISSUE TITLE
[Bug Report] Settings page navigation exceptions

### ISSUE THREAD

**Issue by Curious-r** [lapce/lapce#2759]
## Lapce Version

0.3.0 

## System information

Windows 11

## Describe the bug
Sometimes, when we click on the navigation on the left side of the settings page, the settings do not jump to the specified position correctly. Especially the ones that are lower down. This is episodic, and the pattern of its appearance is not yet known.
## Additional information

For example, click the tab of "Terminal Settings", it wont jump to the settings about terminal. 
![image](https://github.com/lapce/lapce/assets/19733878/1ce618f0-5fd1-4611-a97d-30d57ce687f4)

**Comment by RivenSkaye** [comment]
As I noted in #2808 the pattern of appearance seems to be fresh loads/renders of the settings page, when content below a certain point has not yet come into view. Maybe this'll make it easier to find the cause
