### ISSUE TITLE
self-Compiled release version acts like nightly

### ISSUE THREAD

**Issue by Schievel1** [lapce/lapce#2760]
## Lapce Version

0.3.0

## System information

Gentoo

## Describe the bug
When Lapce is compiled using the tarball of the repository that is downloadable from a release page (e.g. https://github.com/lapce/lapce/archive/v0.3.0.tar.gz) Lapce still says it is a nightly version on the 'About Lapce' window. It therefore also tries to update itself to the next nightly version.

I can set up the build myself to end in a released version if you tell me how to do it.

**Comment by panekj** [comment]
That is correct behaviour. Version and release type is baked in during compilation.

**Comment by Schievel1** [comment]
> That is correct behaviour. Version and release type is baked in during compilation.

Yes, how do you bake it in?
On gentoo packages are usually compiled on the users computer. Of course a versioned release should act for users like a versioned release from your GitHub. 
I just need to know how you do it to make sure I do the same during the packages compilation

**Comment by panekj** [comment]
https://github.com/lapce/lapce/blob/07040dab7f22025f069bb95d1f3dcc6fbc0201df/lapce-core/build.rs#L10-L21
