### ISSUE TITLE
Remote Development broken on v0.30.0

### ISSUE THREAD

**Issue by vietvudanh** [lapce/lapce#2766]
## Lapce Version

0.30.0

## System information

MacOS 14.0

## Describe the bug
When open ssh connection to remote server:
1. Terminal connected successfully, open a ssh shell on remote
2. title bar empty, not showing `Open folder on [ssh ....]` as in prev versions (e.g: 0.28.0)
3. when tried to `open folder`, nothing happens

## Additional information

Not sure, I don't know how to check log of Lapce, where is it? It does not show on MacOS's Console logs.

**Comment by panekj** [comment]
That's intended, remote file picker is not re-implemented yet, tracking issue: #2417

**Comment by dzhou121** [comment]
You can use the terminal ```lapce folder``` to open the folder for now.

**Comment by vietvudanh** [comment]
Thank you the for information.
