### ISSUE TITLE
Crash when pressing enter or backspace in editor

### ISSUE THREAD

**Issue by lukaslihotzki** [lapce/lapce#2768]
## Lapce Version

0.3.0

## System information

Arch Linux, Wayland, sway, XWayland disabled (start sway with `xwayland disable` in the config).

## Describe the bug
When XWayland is disabled, pressing Enter or Backspace in the Editor crashes lapce:
```
thread 'main' panicked at lapce-app/src/doc.rs:75:43:
called `Result::unwrap()` on an `Err` value: XcbConn(ClosedParseErr)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Panic is at https://github.com/lapce/lapce/blob/master/lapce-app/src/doc.rs#L75.

## Additional information

This crash is caused by an Xcb connection fail because the Clipboard is X11-only. This issue can be fixed in multiple ways:
- Add native Wayland support for the clipboard.
- Use the clipboard API only if the user does a clipboard-related action.
- Handle the error gracefully, so just copy and paste does not work if the clipboard API errors.

Also, when this code needs a redesign, the ClipboardProvider should be kept after creation. This may fix #2676.

**Comment by panekj** [comment]
Wayland is not supported

**Comment by Kulasko** [comment]
Can confirm this error using Arch/GNOME/X11.
