### ISSUE TITLE
Ctrl + D multicursor selection is case insensitive

### ISSUE THREAD

**Issue by mmstick** [lapce/lapce#277]
If for example I'm trying to refactor a type declaration `Type`, any variable named `type` will also get selected for being edited. As well as vice versa. I know that this is the default behavior in VS Code (which I'd argue is a terrible default), but it should be configurable with case-sensitive searches the default.

**Comment by DanielCohenHillel** [comment]
### 🌟 Yes! 🌟

Also,`ctrl+d` should be a whole-word search, see the following example in Lapce:

![image](https://user-images.githubusercontent.com/19638053/174832665-0c9a1a4f-327b-44b5-9b1d-71257cec14e3.png)

It shouldn't have selected "gates" and "gate".

Here is the same example but in Sublime Text 4 (no setting changes)

![image](https://user-images.githubusercontent.com/19638053/174833390-02f1b953-57b3-4ec3-b6ff-d7a544244736.png)

And I'm not sure what @mmstick refers to regarding VSCode, I tried it there and it seems to have the same behavior (maybe I'm unaware of a configuration of some configuration in my installation of VSCode?)

![image](https://user-images.githubusercontent.com/19638053/174833893-8fa17ba1-39d3-4c78-bdfe-425b108fe243.png)

These should be the defaults and make the current behavior as a settings option.



Also, unrelated, but I noticed both Sublime and VSCode highlight the next words to be selected (as you images above), so the user is able to know what would be selected the next time he presses `ctrl+d`, probably would be nice to add this feature here.

**Comment by cauebs** [comment]
I know this project doesn't intend to be a VSCode clone, but I really like how this works there. The search widget has three toggles: whole-word (alt-w by default), case sensitive (alt-c) and regex matching (alt+r). This applies to the full project search (ctrl-shift-f), in-editor search (ctrl-f), and also ctrl-d.

**Comment by Chaphasilor** [comment]
I agree with @cauebs, these settings should be configurable on-the-fly. There are cases when I want it to be case-sensitive and select whole words, but there are also many cases where I want the opposite. the two toggles (alt-w for whole word and alt-c for case-sensitivity) are super useful in this regard (the regex setting doesn't really apply to multi cursors, so I left it out).

The new setting `toggle_case_sensitive_search` from #1441 is already global (it works even when the search modal is closed), so this setting should ideally be re-used for this (along with some visual feedback)
