### ISSUE TITLE
UI too large in 0.3.0

### ISSUE THREAD

**Issue by BillyDM** [lapce/lapce#2773]
## Lapce Version

0.3.0

## System information

EndeavourOS Linux with the XFCE desktop environment
Running on a small netbook with a 1366x768p display

## Describe the bug

The entire UI is too large after updating to version 0.3.0. It was fine on version 0.2.8, but for some reason the scaling seems to be the wrong value or something. I'm not using any scaling on my system (it's a netbook with a small 1366x768p screen).

I don't have this problem when running version 0.3.0 on my desktop computer running KDE on a 2560x1440p display, it's only on this netbook running XFCE where I have this problem.

This may be similar to https://github.com/lapce/lapce/issues/2737, but my problem is with the entire UI, not just the menus, so it could be a separate problem.

## Additional information

Here are some screenshots, the first is the UI in 0.2.8, and the second is the UI in 0.3.0.

![Screenshot_2023-11-09_14-04-31](https://github.com/lapce/lapce/assets/60663878/b3cd04a4-88f8-4499-8a55-0bda99b7b1b2)
![Screenshot_2023-11-09_14-05-45](https://github.com/lapce/lapce/assets/60663878/7eed2e37-df9a-493e-887d-36179f24491f)

Nothing about UI scaling appears in the logs. All I see is some debug info about keymaps.

**Comment by ElmeriVincent** [comment]
Large UI mentioned in #2732

**Comment by BillyDM** [comment]
Ah, somehow I missed that when looking to see if someone had already posted this issue.
