### ISSUE TITLE
Ctrl+Z and Ctrl+Y inverted on German keyboard

### ISSUE THREAD

**Issue by Aloso** [lapce/lapce#2775]
## Lapce Version

0.3.0

## System information

<details>

<summary>Manjaro Linux, KDE</summary>

```
 ██████████████████  ████████     ludwig@lu
 ██████████████████  ████████     OS: Manjaro 23.0.4 Uranos
 ██████████████████  ████████     Kernel: x86_64 Linux 6.5.5-1-MANJARO
 ██████████████████  ████████     Uptime: 1d 16h 31m
 ████████            ████████     Packages: 1955
 ████████  ████████  ████████     Shell: fish 3.6.1
 ████████  ████████  ████████     Resolution: 3440x1440
 ████████  ████████  ████████     DE: KDE 5.110.0 / Plasma 5.27.8
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breeze [GTK2/3]
 ████████  ████████  ████████     Icon Theme: breeze-dark
 ████████  ████████  ████████     Disk: 207G / 367G (60%)
 ████████  ████████  ████████     CPU: AMD Ryzen 5 5500U with Radeon Graphics @ 12x 4.056GHz
 ████████  ████████  ████████     GPU: AMD Radeon Graphics (renoir, LLVM 16.0.6, DRM 3.54, 6.5.5-1-MANJARO)
                                  RAM: 6690MiB / 7279MiB
```

</details>

## Describe the bug
On my German (QWERTZ) keyboard, Ctrl+Z and Ctrl+Y are inverted: Pressing Ctrl+Y undoes the last change, Ctrl+Z redoes it. The keyboard shortcuts are configured correctly, and the keys work correctly when typing: When I press the <kbd>Z</kbd> key, a 'z' is printed. However, Lapce seems to assume an American (QWERTY) keyboard layout when handling keyboard shortcuts.

## Additional information
n/a

**Comment by ElmeriVincent** [comment]
It's known  that  there are layout problems. Similar #2731 #2244.

**Comment by Aloso** [comment]
@panekj is it not planned to support non-American keyboards?

**Comment by panekj** [comment]
> @panekj is it not planned to support non-American keyboards?

there are other issues opened for same problem
