### ISSUE TITLE
Build and deploy your Flatpak application using the official GitHub Actions

### ISSUE THREAD

**Issue by pauloxnet** [lapce/lapce#2777]
## Problem

The latest versions of Lapce are not quickly available as flatpack (e.g. Lapce 0.3.0 was released 2 weeks ago and is not available on Flathub)

## Solution

Build and deploy your Flatpak application using the official GitHub Actions

## Note

Instructions from Flathub documentation:
https://docs.flathub.org/docs/for-app-authors/github-actions

**Comment by panekj** [comment]
Not interested in doing that since I'm maintainer of the flathub package

**Comment by pauloxnet** [comment]
> Not interested in doing that since I'm maintainer of the flathub package

I can't find the Flathub package after 2 weeks of the v0.3.0
https://flathub.org/apps/dev.lapce.lapce

I know is not simple to find the time to release a new package quickly, so the GitHub action can help you to reduce the time to do that.

But is just a suggestion.

**Comment by panekj** [comment]
> > Not interested in doing that since I'm maintainer of the flathub package
> 
> I can't find the Flathub package after 2 weeks of the v0.3.0 [flathub.org/apps/dev.lapce.lapce](https://flathub.org/apps/dev.lapce.lapce)
> 
> I know is not simple to find the time to release a new package quickly, so the GitHub action can help you to reduce the time to do that.
> 
> But is just a suggestion.

This is not a problem of time or something that can be fixed using some different CI/CD.

**Comment by pauloxnet** [comment]
> > > Not interested in doing that since I'm maintainer of the flathub package
> > 
> > I can't find the Flathub package after 2 weeks of the v0.3.0 [flathub.org/apps/dev.lapce.lapce](https://flathub.org/apps/dev.lapce.lapce)
> > 
> > I know is not simple to find the time to release a new package quickly, so the GitHub action can help you to reduce the time to do that.
> > 
> > But is just a suggestion.
> 
> This is not a problem of time or something that can be fixed using some different CI/CD.

Ok. Thanks for your work.
I'll wait to use Lapce 0.3.0 when it will be available on Flathub.
