### ISSUE TITLE
Fresh Git Repos are not recognized by Source Control

### ISSUE THREAD

**Issue by ajoklar** [lapce/lapce#2779]
## Lapce Version

v0.3.0

## System information

macOS 14, Manjaro Linux

## Describe the bug

When opening folders that are Git repos (the .git folder is in the project root), but have no commit yet, changes are not visible in the commit pane. Also in the bottom left there is no button with the current branch name. Those features only start working after the first commit.

**Comment by mrtryhard** [comment]
Is this fine if I work on this ?
