### ISSUE TITLE
XWayland key lags one character behind in integrated terminal & flicker

### ISSUE THREAD

**Issue by DuckDuckWhale** [lapce/lapce#278]
Using workaround for #55 and using XWayland: `env -u WAYLAND_DISPLAY target/release/lapce`

When typing in the integrated terminal, the second to last key shows up but the most recently typed key does not, and the cursor sometimes flicker to the previous character (or is the whole frame flickering?). When using `echo` the whole prompt doesn't show up until I type another character.

Using Ubuntu 21.10 Wayland Nivida 510 Gnome rustc 1.59.0 commit 1baaa041581e4a514033b50b91624860c5b97096

**Comment by flukejones** [comment]
This is highly likely to be related to Ubuntu version never really being up-to-date enough. Much changes in Gnome/Mutter and the entire graphics stack between their stable releases. I used to get a similar issue with electron apps before update to fedora 36.

**Comment by DuckDuckWhale** [comment]
Can't reproduce in 2.0
