### ISSUE TITLE
On Windows a console is shown on startup

### ISSUE THREAD

**Issue by timendum** [lapce/lapce#2813]
## Lapce Version

v3.0
## System information

Windows 10

## Describe the bug

When I launch the portable version of Lapce, a Console is briefly shown and than disappars.

## Additional information

I am not a rust expert, but specifying the [https://doc.rust-lang.org/reference/runtime.html](runtime) should solve the issue.

In particular the code should be:

`#![windows_subsystem = "windows"]`

**Comment by oberrich** [comment]
Any updates on this?
