### ISSUE TITLE
macOS Menu Bar support 

### ISSUE THREAD

**Issue by girlbossceo** [lapce/lapce#2818]
## Is your feature request related to a problem? Please describe.

Currently the menu bar in macOS is basically blank. I am trying this editor out and coming from VS Code I am constantly instinctively going to my menu bar to open a new project, open settings, close just one window, etc.

<img width="276" alt="image" src="https://github.com/lapce/lapce/assets/112147643/9b9453ac-9a4d-4c3e-af53-2496b84374e8">

## Describe the solution you'd like

I found [this issue](https://github.com/lapce/lapce/issues/270) which asks for the same thing, but I don't really understand why it was closed because I can think of even just a few things to add to the menu bar that VS Code has. Maybe it wasn't applicable at the time it was opened?

This is VS Code's menu bar:
<img width="595" alt="image" src="https://github.com/lapce/lapce/assets/112147643/d153c3ea-9c06-4f84-8745-9bcc2bcf1e2a">

<img width="581" alt="image" src="https://github.com/lapce/lapce/assets/112147643/4e476438-8551-4cf2-9aad-9eddea252c54">

Lapce could certainly add Settings, Check for Updates, Create New File, Create New Folder, Open Folder/Project, Open File Connect to Remote host, Close Window, Close Tab, Close Folder/Project, Save File, Save All Files, etc.

Plenty of useful things that could be added.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by panekj** [comment]
This is due to #2417

**Comment by WeetHet** [comment]
> This is due to #2417

Why not keep this open then? I thought that issue was a compilation of the issues that have arisen from the transition to floem?
