### ISSUE TITLE
built-in terminal /alacritty/ seems to ignore config file 

### ISSUE THREAD

**Issue by Unisa-Merni-392** [lapce/lapce#2821]
## Lapce Version
nightly

## System information
Gentoo, with sway+wayland+kitty VT

## Describe the bug
built-in terminal uses alacritty crate (I use kitty and have no alacritty on the system ATM), but it seems to run with default config settings.
It ignored alacritty config file that I've had from previous alacritty installation, which makes running Midnight Commander in such window dreadful experience (screaming, "washed" colors).

my config file location was IIRC in ~/.config/alacritty/alacritty.yml

## Additional information
My default TERM=xterm-kitty, if that is of any significance.

**Comment by panekj** [comment]
We don't and will not use alacritty config file since our terminal is not alacritty but only its backend

**Comment by panekj** [comment]
All terminal configuration is available in settings tab.
