### ISSUE TITLE
When executing the binary, the session crashes

### ISSUE THREAD

**Issue by prohtmlcoder** [lapce/lapce#2828]
## Lapce Version
v0.3.0

## System information
OS: Pop!_OS 22.04 LTS x86_64 
 Kernel: 6.5.4-76060504-generic 
 Shell: fish 3.3.1 
 Resolution: 1600x900 
 DE: Plasma 5.24.7 
 WM: KWin 
 WM Theme: Utterly-Round 
 Theme: [Plasma], Breeze [GTK2/3]  
 Terminal: konsole 
 Terminal Font: CaskaydiaCove Nerd Font Propo 13 
 CPU: Intel i5-4670 (4) @ 3.800GHz 
 GPU: Intel HD Graphics 
 
## Describe the bug
Whenever I executes the binary the whole session is getting crashed(login screen appears)

## Additional information

I think may be it is because of the system font ?

**Comment by nunotexbsd** [comment]
Could you take a look at https://github.com/lapce/lapce/issues/2748 and see if it is related?

**Comment by prohtmlcoder** [comment]
Hi there thank you for your reply...

I went to the #2748 thread.


Just a bit of additional info:
I was able to see the welcome screen, when I try to move the screen on the desktop the session crashes. 

Thank you once again.....
