### ISSUE TITLE
Resizing panel mouse position bug

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#2832]
## Lapce Version

HEAD

## System information

Linux. Gnome (Wayland) + PaperWM
No alternative display scaling

## Describe the bug
When resizing the panel with the mouse, the coloration when the mouse hovers over the left panel works fine. However upon clicking, it jumps and is noticeably to the left as you drag.

## Additional information
![image](https://github.com/lapce/lapce/assets/13157904/814b19a5-d3bd-4c92-9ef1-d19d74b4cae4)
(taken while dragging)

**Comment by RustoMCSpit** [comment]
i can confirm. Using LTS Linux Mint Gnome Jammy Jellyfish

**Comment by RustoMCSpit** [comment]
@MinusGix are you also using flatpak?

**Comment by MinusGix** [comment]
Nope, I'm running Lapce directly.

**Comment by RustoMCSpit** [comment]
THABNK YOU

**Comment by panekj** [comment]
Thanks a lot
