### ISSUE TITLE
Update Flatpak

### ISSUE THREAD

**Issue by RustoMCSpit** [lapce/lapce#2833]
Linux Flatpak still on 2.8 for some reason

**Comment by panekj** [comment]
Unrelated to this repository

**Comment by RustoMCSpit** [comment]
> Unrelated to this repository

Which repo then

**Comment by panekj** [comment]
Issues regarding flatpak should be opened in https://github.com/flathub/dev.lapce.lapce but don't create an issue for update since I'm already aware it's outdated

**Comment by RustoMCSpit** [comment]
> Issues regarding flatpak should be opened in https://github.com/flathub/dev.lapce.lapce but don't create an issue for update since I'm already aware it's outdated

thank you for the info and fast reply! okay hope you update it soon i love the app!! also is there a way to run current script as a keybinding like f5 or do you have to use the terminal every time?

**Comment by panekj** [comment]
I don't think there is current script runnable action but it's possible to add run tasks since lapce 0.3.0 after clicking `Run` button
![image](https://github.com/lapce/lapce/assets/50457605/9bc996e7-d5bc-4dd4-8ce7-4d5b067e0237)

**Comment by RustoMCSpit** [comment]
> I don't think there is current script runnable action but it's possible to add run tasks since lapce 0.3.0 after clicking `Run` button ![image](https://private-user-images.githubusercontent.com/50457605/288511163-9bc996e7-d5bc-4dd4-8ce7-4d5b067e0237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4OTA2MjUsIm5iZiI6MTcwMTg5MDMyNSwicGF0aCI6Ii81MDQ1NzYwNS8yODg1MTExNjMtOWJjOTk2ZTctZDViYy00ZGQ0LThjZTctNGQ1YjA2N2UwMjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE5MTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMGY3YWY4YmI1MDAxZjMxN2E0ODViNWIwNDE3MzJjODJjMWE3MjdjMTM2MzQ3OGQ0NDQxYjJlNzVhYzNhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UZxoMc2Mxc4A-Ppi5ZYQ_x6ncNjcz6yPBRbEOf2WnE0)

cant access it though cause 2.8, do you know who manages flatpaks?
