### ISSUE TITLE
KDE Plasma: Desktop env crash when moving the window

### ISSUE THREAD

**Issue by valentimarco** [lapce/lapce#2854]
## Lapce Version
lapce 0.3.1-1 

## System information
![Screenshot_20231216_173721](https://github.com/lapce/lapce/assets/26926690/4cd62cd8-3ad5-4548-b7ea-a0b620318173)

## Describe the bug
1. The windows always spawn in the top left of the monitor
2. When i try to move it, the desktop env crash and i need to reboot

## Additional information
I am a noob in share infos in linux, my transition from windows 10 is slow xd
In backgroud i have only:
1. discord
2. firefox
3. Okular

**Comment by RustoMCSpit** [comment]
occurs on linux mint lts jammy jellyfish 21.2 as well. using super key and arrow keys let me resize the program into one of the corners but any size adjustment spawns lapce off the screen to the left

**Comment by RustoMCSpit** [comment]
has only started occuring from latest update

**Comment by RustoMCSpit** [comment]
> lapce 0.3.1-1
flatpak?

**Comment by RustoMCSpit** [comment]
> 1. discord

get webcord instead, foss frontend

**Comment by valentimarco** [comment]
> > lapce 0.3.1-1
> 
> flatpak?
Nop

**Comment by pwouik** [comment]
this should be fixed on master

**Comment by RustoMCSpit** [comment]
> this should be fixed on master

can you link the pr that fixed?

**Comment by pwouik** [comment]
https://github.com/lapce/lapce/issues/2651
it was a bug fixed in winit
it was updated with floem https://github.com/lapce/lapce/commit/048c5103e27f62a5605f841d2915af14cd183565

**Comment by RustoMCSpit** [comment]
> #2651 it was a bug fixed in winit it was updated with floem [048c510](https://github.com/lapce/lapce/commit/048c5103e27f62a5605f841d2915af14cd183565)

can a new flatpak drop asap cause lapce is unusable

**Comment by pwouik** [comment]
for now you can enable kde borders in settings

**Comment by RustoMCSpit** [comment]
> for now you can enable kde borders in settings

whens next patch?

**Comment by RustoMCSpit** [comment]
https://github.com/lapce/lapce/issues/2832

is this a duplicate?

**Comment by pwouik** [comment]
no it is about an offset of border position when resizing it
it is duplicate of https://github.com/lapce/lapce/issues/2651 and https://github.com/lapce/lapce/issues/2758

**Comment by RustoMCSpit** [comment]
> no it is about an offset of border position when resizing it it is duplicate of #2651 and #2758

any idea when #2832 will be fixed?

**Comment by poelzi** [comment]
I'm not sure if it is related, but moving lapce on KDE X11 from primary to secondary monitor causes the window to disappear completely. It does not crash anything, but the window is just gone, while the app is still running in showing the taskbar entry.

**Comment by panekj** [comment]
@valentimarco could you confirm if the issue is fixed for you with latest release?

**Comment by valentimarco** [comment]
> @valentimarco could you confirm if the issue is fixed for you with latest release?

I need to update it, i will try

**Comment by valentimarco** [comment]
I confirm that works with 0.4.0
