### ISSUE TITLE
Icon-only UI buttons should have tooltips

### ISSUE THREAD

**Issue by lostmsu** [lapce/lapce#2866]
## Is your feature request related to a problem? Please describe.

It is hard to get started with Lapce because the icon buttons do not have tooltips

## Describe the solution you'd like

Add tooltips and/or add text to all/most icon buttons.

## Additional context

After clicking it I know, but _before_ clicking it - how do I know what is this button? Hovering over it does nothing.

![image](https://github.com/lapce/lapce/assets/239520/9ff0f61e-f611-41d5-8321-6a94e5c8fb0b)

Same for tool panel icons. The Open Editors/File Explorer container has an icon that looks like copy icon from cut/copy/paste.

**Comment by lostmsu** [comment]
For tool panel it may make sense to show text next to the currently active panel icon. E.g.
![image](https://github.com/lapce/lapce/assets/239520/581c5c5e-5e83-47d4-9709-c1366446459a)

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/2866

**Comment by lostmsu** [comment]
@panekj it is funny, that an issue can be made a duplicate of itself 🥴

**Comment by panekj** [comment]
@lostmsu fixed
