### ISSUE TITLE
Translate the program

### ISSUE THREAD

**Issue by saihaze** [lapce/lapce#2868]
## Is your feature request related to a problem? Please describe.

The editor is English only.

## Describe the solution you'd like

Take advantage of `i18n-embed` and `fluent` to translate the program. I can help with Chinese translations.

## Describe alternatives you've considered

`gettext` crates will also do, but I think `fluent` is more advanced.

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/2236
