### ISSUE TITLE
Code Action Context Menu: Cannot select actions

### ISSUE THREAD

**Issue by Cody-Duncan** [lapce/lapce#287]
Platform: Windows
Lapce Version: commit https://github.com/lapce/lapce/commit/d9b0492267c786af8314bfce8b87673a130bf86c, built from latest on master

1, Open the code action context menu. (@see #286 about why that's difficult)
2. Note that "inline variable" is highlighted

Expected-1: Pressing enter should select "inline variable" and trigger the code action
Expected-2: Clicking on "inline variable" in the code action context menu should trigger the code action
Expected-3: ⬆ (up) or ⬇️ (down) arrow keys should change the code action that is highlighted. 
Actual: No inputs can change the selection or trigger a code action.

https://user-images.githubusercontent.com/1480323/160232151-cbbc99c9-ab26-4c2f-9e88-3211af7d445d.mp4

Sample Source:
```rust
let index = std::cmp::min(0, 15);
		
// timing mea timing measures for Frames-Per-Second
use std::time::Instant;
let now = Instant::now();
let mut time_fence = index; // the previous second that has been printed.
let mut count = index; // count of frames
```

**Comment by bugadani** [comment]
There are a few merged related PRs that fixes different issues in your video:
- #269
- #275
- #284

Unfortunately, the code action still probably doesn't get applied as expected.

**Comment by panekj** [comment]
This should've been closed long time ago as we did multiple major changes to lapce, with the original issue being fixed
