### ISSUE TITLE
No menu in the file explorer.

### ISSUE THREAD

**Issue by ZeerDonker** [lapce/lapce#2873]
## Lapce Version
0.3.1

## System information

Windows 10 

## Describe the bug

There is no menu opened with a way to make new files, if you right click in the File Explorer

## Additional information

I did not even know there was a menu, until I searched if someone requested such a menu as a feature. And saw a different bug about the menu. 

This makes this editor unusable for me.

**Comment by leorsousa05** [comment]
You found a way to navigate on the File Explorer and create file? This editor is literally unusable without that, no one answer and they don't update anything...

**Comment by ZeerDonker** [comment]
Nope. 

Even looked at the yesterdays nightly, in case something changed. 
Some menu items got added, but create file item and other items don't show. 
(On v.3.1 those didn't show either.) 

![2024-02-09 09_25_29-hello_world - Lapce](https://github.com/lapce/lapce/assets/4290287/99b44e91-4520-48eb-971b-8d1ed3845b6b)

**Comment by roberfu** [comment]
Some update here?

**Comment by panekj** [comment]
> Some update here?

no

**Comment by disturb16** [comment]
Is this a general bug or does it affect just some unlucky users like us?
This is a major bug and seems like nobody is working on it.

**Comment by panekj** [comment]
It's been fixed 2 days ago

**Comment by disturb16** [comment]
> It's been fixed 2 days ago

Thanks for letting me know, I can't wait for the next release then 😁.
