### ISSUE TITLE
Settings won't sync

### ISSUE THREAD

**Issue by AVDiv** [lapce/lapce#2875]
## Lapce Version

Lapce v0.3.1 (on AppImage)

## System information

Kali Linux 2023.4 (Debian)

## Describe the bug
The settings won't sync in the lapce Appimage. For example, I changed the UI Font Size, didn't work. When I just downloaded it worked, now it doesn't anymore.

`Ctrl` + `-`  works btw.

**Comment by panekj** [comment]
We don't distribute AppImage of lapce, you should ask whoever made it
