### ISSUE TITLE
Code Action Context Menu: Menu stays after losing cursor or losing window focus

### ISSUE THREAD

**Issue by Cody-Duncan** [lapce/lapce#288]
Platform: Windows
Lapce Version: commit https://github.com/lapce/lapce/commit/d9b0492267c786af8314bfce8b87673a130bf86c, built from latest on master

1, Leave the cursor on an actionable symbol, 
2. Open the code action context menu. (@see https://github.com/lapce/lapce/issues/286 about why that's difficult)
3. Move cursor off the symbol.
4. Click outside the windows
5. Scroll up and down.
6. Change text editor tabs.

Expected: Any of the actions that lose focus on the symbol, i.e. steps 3-6, close the code action context menu.
Actual: The context menu never closes.

https://user-images.githubusercontent.com/1480323/160232375-45025cab-9d50-4f00-b7df-97bde1ba9e3e.mp4

**Comment by Cody-Duncan** [comment]
This appears to have been resolved in commit 367dcd27 as part of PR https://github.com/lapce/lapce/pull/294.

https://user-images.githubusercontent.com/1480323/160262224-ca1ed787-c45b-4bd7-82d4-b10d1b7fc04d.mp4

**Comment by bugadani** [comment]
I've closed this issue because you said it's resolved. Feel free to reopen if you'd like to keep it open, but please explain it if you do.
