### ISSUE TITLE
Resizing the window on macOS breaks the window size

### ISSUE THREAD

**Issue by domesticmouse** [lapce/lapce#29]
On initial load:

<img width="912" alt="Screen Shot 2021-12-15 at 8 38 13 am" src="https://user-images.githubusercontent.com/30503/146083498-6edd8111-9f4c-4503-b06a-388395e48d3d.png">

After screen resize:

<img width="936" alt="Screen Shot 2021-12-15 at 8 38 22 am" src="https://user-images.githubusercontent.com/30503/146083523-450a847c-9535-42f5-9631-846df998dd58.png">

**Comment by lazyoracle** [comment]
+1 Just tried it on 2021 M1 Macbook Pro and resizing broke the window rendering.

**Comment by bruno-anjos** [comment]
+1 on Intel MacBook Pro

**Comment by domesticmouse** [comment]
Closing as duplicate of #20
