### ISSUE TITLE
Unusable last drop-down list (at the bottom of a settings list) as it goes offscreen

### ISSUE THREAD

**Issue by eugenesvk** [lapce/lapce#2904]
## Lapce Version

nightly-8312021

## System information

Windows 10

## Describe the bug

If you scroll down to the last drop-down element in the settings (`Terminal: Default Profile`) and click it, the resulting drop-down list is unusable since it goes offscreen. Also none of the regular keybinds work (like arrow down/up), so you also can't select the profiles with a keyboard

## Additional information

<img width="554" alt="CaptureDropDown" src="https://github.com/lapce/lapce/assets/12956286/1025695e-b7d1-43e4-bcc9-df26a7acf0e5">

**Comment by Dave-van-der-Meer** [comment]
The same is happening in the Linux version under Manjaro using Wayland with Hyprland. I use version 0.3.1 of Lapce.

**Comment by craigz** [comment]
this is also present in the MacOS version:
<img width="462" alt="lapceTermProfileCut" src="https://github.com/lapce/lapce/assets/1929275/049c65b3-b3d5-4d31-b3a2-838a7f956c92">

**Comment by panekj** [comment]
We don't need more information about the issue, currently the only required action is to fix it.
