### ISSUE TITLE
Mixing of CRLF and LF causing rendering issues

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#291]
When CRLF and LF characters are mixed in a single file (which can easily currently occur due to newline inserting a LF character in a CRLF file, #290 , or due to backspacing breaking it #289 , but could also occur due to simply opening a mixed-case file), the rendering appears to break in certain ways. See:

(Video showcasing the issue)
https://user-images.githubusercontent.com/13157904/160234251-aee2f517-6da5-480e-a04f-bff5d3c94d44.mp4

**Comment by Cody-Duncan** [comment]
I tested PR #293. This seems to have resolved this issue.
