### ISSUE TITLE
Cannot build lapce git version from source 

### ISSUE THREAD

**Issue by 0xDEAD-C0DE** [lapce/lapce#2919]
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 
latest git version

## System information

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04
ArchLinux on Wayland kernel 6.6.9
## Describe the bug
Can't compile due to a cargo compilation error about a returning Impl on Floem

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:
cargo -v 1.74.0
rustc -v 1.74.0
![20240113_15h19m52s_grim](https://github.com/lapce/lapce/assets/155328330/57405b8d-e166-4d71-8739-ba4372b5b9b2)
- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

**Comment by panekj** [comment]
You need Rust 1.75
