### ISSUE TITLE
Unicode path handling not working on Windows

### ISSUE THREAD

**Issue by thistle-witch** [lapce/lapce#2920]
## Lapce Version

nightly-9bddebd

## System information

Windows 11

## Describe the bug
Error paths reported through the LSP have escaped HTML characters if the original path has non-ascii characters. This causes incorrect error navigation.

## Additional information

Path reported in error should be C:/Users/þistle/bincode/src

![image](https://github.com/lapce/lapce/assets/129108882/386f9e05-23a5-441e-8b1c-02885dadbb29)

My best guess is that the LSP requires HTML escaping of paths and lapce needs to unescape them.

**Comment by thistle-witch** [comment]
Error is on this line https://github.com/lapce/lapce/blob/9bddebda161d65c27c74a892bae40afe82972c9f/lapce-app/src/proxy.rs#L151
`path()` returns the percent-encoded ascii path, not the unescaped path.

**Comment by panekj** [comment]
Fixed via f2355aa0b8839aacc5fa684db2c8b75b5258e251
