### ISSUE TITLE
Direnv support

### ISSUE THREAD

**Issue by cmargiotta** [lapce/lapce#2923]
## Is your feature request related to a problem? Please describe.
In my projects I always use a flake.nix defined development environment, which provides fixed versions of compiler, debugger and clangd too. In vscode I can preload this environment using the direnv plugin, but I don't know if this is actually possible in lapce.

## Describe the solution you'd like
Automatically load direnv environment if a .direnv file is found in the project's root.

**Comment by numfin** [comment]
Want to have this functionality too. 
Lets start discussion! Lets go by small steps.
Any ideas how we can implement this? 

I'll start:
- We have plugins like lapce-rust that searching for rust-analyzer. I believe plugin is here https://github.com/lapce/lapce-rust . It uses `serverPath` config to execute it or downloads its own rust-analyzer if cant find it. 
- So if we want to "override" this setting what we suppose to do?
- There are crates that work with direnv:
  - https://crates.io/crates/quickenv
  - https://crates.io/crates/direnv

**Comment by panekj** [comment]
> * So if we want to "override" this setting what we suppose to do?

You can just configure it in settings, there is no need for overriding

**Comment by numfin** [comment]
@panekj it is dynamic. Per project this path will be different. So we need ability to change it "on fly".
One way of doing it is env variables. What if we had ability to use env variables in settings?

**Comment by numfin** [comment]
Is there a way to manipulate Lapce env variables so extensions can search binaries from that variable?
Also is there a way to set extension load order

**Comment by panekj** [comment]
> Per project this path will be different.

project can have settings defined in `${PROJECT_DIR}/.lapce/settings.toml`, just like standard settings

**Comment by cmargiotta** [comment]
> project can have settings defined in `${PROJECT_DIR}/.lapce/settings.toml`, just like standard settings

But this feature cannot be used to dynamically load a direnv environment.

**Comment by panekj** [comment]
> > project can have settings defined in `${PROJECT_DIR}/.lapce/settings.toml`, just like standard settings
> 
> But this feature cannot be used to dynamically load a direnv environment.

I did not say that it can be used in such way
