### ISSUE TITLE
fedora linux, no longer a way to install and call from cli?

### ISSUE THREAD

**Issue by lineality** [lapce/lapce#2925]
## Is your feature request related to a problem? Please describe.
A way to actually install Lapce for Fedora linux (rpm linux in general?) is needed.

In the past there was a way to install Lapce (from an odd  nonstandard package source) but now with Fedora, I cannot find any instructions for actually installing Lapce at all. Since for dev work I would need to call it from the command line for files...I'm not sure how I can use it as a badly needed replacement for the dreaded vsCode. 

## Describe the solution you'd like
the flat-pack somehow does not install so that lapce is recognized by the OS.
having a version in RPM or 3rd-party RPM would be useful I think

**Comment by panekj** [comment]
There is already an unofficial build of lapce, https://copr.fedorainfracloud.org/coprs/titaniumtown/lapce/packages/
