### ISSUE TITLE
Go To Definition does not work on windows 11

### ISSUE THREAD

**Issue by rimantasrickus** [lapce/lapce#2954]
## Lapce Version
nightly build

## System information
Windows 11 23H2

## Describe the bug
Both in JS and PHP when selecting "Go To Definition" from the right-click menu, the file path gets messed up and the language server stops working. I don't know if this error is in the editor or the PHP and TS / JS plugins.
![image](https://github.com/lapce/lapce/assets/28595949/6b6405de-e2d5-4729-a262-e33877f202e7)
![image](https://github.com/lapce/lapce/assets/28595949/1f95c2f8-ca9d-4ec7-aa11-ef65a3fb417b)

With the newest nightly build, now error is thrown:
![image](https://github.com/lapce/lapce/assets/28595949/33e4e94e-44e9-4b7c-b1be-9ffad3106fc9)

**Comment by Mirsario** [comment]
Also occurs for me on Win10 with [Zig](https://github.com/syntacti/lapce-zig), so it's not your PHP/JS plugins.
