### ISSUE TITLE
Open Folder not working for SSH session

### ISSUE THREAD

**Issue by keeb** [lapce/lapce#2985]
## Lapce Version

0.3.1

## System information

Windows 10

## Describe the bug

1. Connect to SSH successfully
2. Terminal appears correctly with connected session
3. Attempt to open folder. 
4. No preview available. Providing absolute path doesn't load folder.

## Additional information
![image](https://github.com/lapce/lapce/assets/107596234/814bee77-8c55-4f05-9453-f2885496d9f8)
![image](https://github.com/lapce/lapce/assets/107596234/0f7f70bf-b33f-4fe6-bfef-95d7d87b3642)
![image](https://github.com/lapce/lapce/assets/107596234/c433899e-30c9-4129-ac60-514429153b52)

**Comment by tofraa** [comment]
Same issue with macOS connecting to Linux.

**Comment by panekj** [comment]
Duplicate of #2417
Remote file picker has not been yet reimplemented after switching to Floem
You can open a directory with `lapce <path>` in terminal

**Comment by abal1000x** [comment]
> Duplicate of [#2417](https://github.com/lapce/lapce/issues/2417) Remote file picker has not been yet reimplemented after switching to Floem You can open a directory with `lapce <path>` in terminal

How? Can you give an example?
I try call lapce user@host:/path/to/workspace
Doesnt work

**Comment by panekj** [comment]
<img width="962" height="145" alt="Image" src="https://github.com/user-attachments/assets/80f2311d-70d3-4276-a767-b9363188b004" />

**Comment by abal1000x** [comment]
> <img alt="Image" width="962" height="145" src="https://private-user-images.githubusercontent.com/50457605/473789084-80f2311d-70d3-4276-a767-b9363188b004.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzMDE2MDcsIm5iZiI6MTc1NDMwMTMwNywicGF0aCI6Ii81MDQ1NzYwNS80NzM3ODkwODQtODBmMjMxMWQtNzBkMy00Mjc2LWE3NjctYjkzNjMxODhiMDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA0VDA5NTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNzQ0MWIwZTcyYjgwZjg0NjRmMzQ5YjBjMDljNWJhZTYzNzU2ZjU2YzQ2NzBkNmQ0Y2Q0ZGFkN2VjY2VkMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XX9avho1ic71Pc7LpA4g0DZql4qbDJ9axoiN8HHpZYQ">

Thank you for the response.
Turns out i need to use the proxy lapce installed by the lapce when i connect it remotely.
At first i manually download and install on the remote host, and when i open the workspace nothing happened.

**Comment by slowkow** [comment]
I have exactly the same issue. The ssh connection seems ok, but there is no way to browse files and folders.

When I try to run `lapce` on the remote server in the Lapce terminal window (as shown in panekj's comment above), I get `lapce: command not found`.

I'm following along here: https://docs.lapce.dev/get-started/remote-development

It seems like I am not missing any steps. Am I supposed to install lapce myself on the remote server? The docs seem to suggest that this happens automatically?

**Comment by panekj** [comment]
If you are connected (green status icon) then Lapce is already "installed" (present in your user profile). If it's not available in shell `PATH`, you can try running it manually via `~/.local/share/lapce-*/proxy/lapce -h`

**Comment by slowkow** [comment]
That worked!

In the Lapce terminal on the remote server, I ran:

```
~/.local/share/lapce-stable/proxy/lapce MY_DIR
```

And then a new window popped up on my local machine where I could browse and edit files in `MY_DIR`.

Thank you 😊
