### ISSUE TITLE
Need OS-specific build instructions

### ISSUE THREAD

**Issue by ralyodio** [lapce/lapce#3]
linux/arch

**Comment by denisgolius** [comment]
I think you need rust + cargo and then run the following commands:
```
git clone git@github.com:lapce/lapce.git
cd lapce
cargo build
```

**Comment by sikmir** [comment]
Failed to build:
```
lapce> error: failed to sync
lapce> Caused by:
lapce>   found duplicate version of package `xi-rope v0.3.0` vendored from two sources:
lapce>          source 1: registry `crates-io`
lapce>          source 2: https://github.com/lapce/xi-editor#5578c725
lapce> Traceback (most recent call last):
lapce>   File "/nix/store/qcr9904iv7flbkd9g56rk5fc11lyn7df-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
lapce>     main()
lapce>   File "/nix/store/qcr9904iv7flbkd9g56rk5fc11lyn7df-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
lapce>     assert list(data.keys()) == ["source"]
lapce> AssertionError
```

**Comment by gigatexal** [comment]
clone and run make help it'll give you targets to try out

**Comment by gavinlaking** [comment]
You'll need to install `cmake` and freetype2 (`libfreetype6-dev`) on Ubuntu 21.10 if they are not already present, plus also install packages to fix the inevitable linker errors (https://github.com/lapce/lapce/issues/11)

```bash
sudo apt install cmake libfreetype6-dev libxkbcommon-dev libxcb-xfixes0-dev libxcb-shape0-dev
```

**Comment by bjorn3** [comment]
> Failed to build:
> 
> ```
> lapce> error: failed to sync
> lapce> Caused by:
> lapce>   found duplicate version of package `xi-rope v0.3.0` vendored from two sources:
> lapce>          source 1: registry `crates-io`
> lapce>          source 2: https://github.com/lapce/xi-editor#5578c725
> lapce> Traceback (most recent call last):
> lapce>   File "/nix/store/qcr9904iv7flbkd9g56rk5fc11lyn7df-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
> lapce>     main()
> lapce>   File "/nix/store/qcr9904iv7flbkd9g56rk5fc11lyn7df-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
> lapce>     assert list(data.keys()) == ["source"]
> lapce> AssertionError
> ```

Seems like nix can't handle multiple versions of the same crate with the same version string. Try building using cargo directly instead of nix.

**Comment by sikmir** [comment]
> Seems like nix can't handle multiple versions of the same crate with the same version string. Try building using cargo directly instead of nix.

I've tried, the same problem.

**Comment by qarmin** [comment]
This one liner will build lapce from git without to clone anything(of course dependences needs to be installed manually)
```
cargo install --git https://github.com/lapce/lapce lapce --locked
```

**Comment by KaranAhlawat** [comment]
> This one liner will build lapce from git without to clone anything(of course dependences needs to be installed manually)
> 
> ```
> cargo install --git https://github.com/lapce/lapce lapce --locked
> ```

Would you happen to know what all deps are needed? Would like to verify i have everything setup before i try again.

**Comment by transtrike** [comment]
I'm using Arch and everything I needed to build was `cmake` and `rust`.

```
sudo pacman -S rust cmake
git clone git@github.com:lapce/lapce.git
cd lapse
make install
```

**Comment by DeadMozay** [comment]
> > Failed to build:
> > ```
> > lapce> error: failed to sync
> > lapce> Caused by:
> > lapce>   found duplicate version of package `xi-rope v0.3.0` vendored from two sources:
> > lapce>          source 1: registry `crates-io`
> > lapce>          source 2: https://github.com/lapce/xi-editor#5578c725
> > lapce> Traceback (most recent call last):
> > lapce>   File "/nix/store/qcr9904iv7flbkd9g56rk5fc11lyn7df-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
> > lapce>     main()
> > lapce>   File "/nix/store/qcr9904iv7flbkd9g56rk5fc11lyn7df-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
> > lapce>     assert list(data.keys()) == ["source"]
> > lapce> AssertionError
> > ```
> 
> Seems like nix can't handle multiple versions of the same crate with the same version string. Try building using cargo directly instead of nix.

The problem is not nix, the error is thrown by `cargo`, the error comes out even before the build starts while getting `vendor` dependencies.
cargo can process any number of the same crate from both different versions and from different sources, provided that the code is written correctly in the target application, more than once I've met such applications where one crate had different sources and versions.

If we run `cargo vendor` to get vendored sources we get the same error
```
❯ cargo vendor --manifest-path Cargo.toml  
error: failed to sync

Caused by:
  found duplicate version of package `xi-rope v0.3.0` vendored from two sources:

  	source 1: registry `crates-io`
  	source 2: https://github.com/lapce/xi-editor#5578c725
```
This shouldn't be
Rust 1.57.0

**Comment by bjorn3** [comment]
I see. `cargo build` accepts it just fine. It only breaks `cargo vendor`, which isn't too surprising as `cargo vendor` produces a single (directory) registry and within a single registry there can't be duplicate versions.

**Comment by ymolists** [comment]
This is what i did on this regolith (based on ubuntu) distribution

```
apt install libfreetype6-dev libexpat1-dev libx11-xcb-dev
```

yet i am still getting this error

```
...
nux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib" "-Wl,--end-group" "/home/ymo/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-5c77a3b4d3711371.rlib" "-Wl,-Bdynamic" "-lz" "-ldl" "-lxcb" "-lxcb-render" "-lxcb-shape" "-lxcb-xfixes" "-lxkbcommon" "-ldl" "-lexpat" "-lfreetype" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/ymo/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/ymo/3rdp/github/lapce/lapce-src/lapce-master/target/debug/deps/lapce-40bd144e32277fd2" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
          /usr/bin/ld: cannot find -lxkbcommon
          collect2: error: ld returned 1 exit status
```

I would really appreciate if someone can put the required libraries in a Readme
