### ISSUE TITLE
Installer prematurely closes without installing

### ISSUE THREAD

**Issue by kamva9697** [lapce/lapce#30]
The wizard installer on my Windows machine exists with "A newer version has already installed" and then aborts without instaling

**Comment by kohlerm** [comment]
Same for me

**Comment by dzhou121** [comment]
Can you try the latest release?

https://github.com/lapce/lapce/releases/tag/v0.0.4

**Comment by bugadani** [comment]
@kamva9697 @kohlerm thanks for reporting this issue! Could you please check if this still happens for you?

**Comment by kohlerm** [comment]
v0.0.12 works for me!

**Comment by bugadani** [comment]
Great, thanks!
