### ISSUE TITLE
Lapce not starting

### ISSUE THREAD

**Issue by r3nor** [lapce/lapce#3011]
## Lapce Version

Latest Nightly (2024_02_03)

## System information

Fedora Linux 39

## Describe the bug

When I try opening the binary, I get:

```
lapce-linux-amd64/Lapce  ❯ ./lapce
./lapce: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by r3nor** [comment]
Solved with `sudo dnf install openssl1.1`

**Comment by LSchuepbach** [comment]
Same issue on ubuntu jammy (22.04 LTS). But libssl.1.1 isn't available anymore there. I'd appreciate if libssl3 was used. Openssl website mentions 1.1 isn't supported anymore.
