### ISSUE TITLE
Feature request: Some settings items would be better as dropdown selectors

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#302]
A good example is the theme selector - right now I have to type in the file name exactly, or I'll get the light theme, which is not an ideal user experience, when the set of themes is known in advance.

**Comment by PhilipDaniels** [comment]
Seconded. I was just about to raise an issue saying exactly this.

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/1938
