### ISSUE TITLE
Feature Request: File Explorer File Watching

### ISSUE THREAD

**Issue by undersquire** [lapce/lapce#304]
I am assuming that this is already a planned feature for when Lapce adds file creation/deletion, but I thought it might be worth opening an issue for just to make sure it is not forgotten. Lapce should watch for local file changes in the currently opened directory, that way if a file is created or deleted it will show this in the file explorer.

Example: If I run `touch test.txt`, it should pop up in the file explorer. If I then were to `rm test.txt`, it should disappear.

**Comment by dzhou121** [comment]
This should be fixed by the latest v0.1.0 release

**Comment by undersquire** [comment]
Yep just tried the latest build, working good here!
