### ISSUE TITLE
When window closed with (X) on MacOS you can't reopen the editor

### ISSUE THREAD

**Issue by rehoehle** [lapce/lapce#3043]
## Lapce Version

0.3.1 and Nightly tested

## System information

MacOS 14.3.1 (M2)

## Describe the bug

When you close the Window over the X then you can't reopen the editor over the icon in the dock. Then nothing happen. Then you have to right click and close completely.

**Comment by Allespro** [comment]
Same bug
MacOS 12.6.8
Lapce v0.3.1

**Comment by rehoehle** [comment]
Is here something happen? The editor is not usable under MacOS. Is the Project dead?

**Comment by luochuan2008** [comment]
is this question still don't have solve ? i look forward to try your system

**Comment by rehoehle** [comment]
@luochuan2008 nope it's unusable under OSX. Nothing is working. Drag and Drop is broken. You can't open txt files... the UI when you close it won't open. So i don't think that only me has that problem.
