### ISSUE TITLE
Windows & chrome complain that the latest nightly is a virus. (2024-03-07)

### ISSUE THREAD

**Issue by ZeerDonker** [lapce/lapce#3045]
## Lapce Version

2024-03-07 nightly. Issue does not happen for 0.31.0 (And did not happen for a previous nightly.)

## System information

Windows 10

## Describe the bug

If downloading with Chrome, it will complain about a virus. For both portable and msi versions.
And not download.

If downloaded with Firefox, it will say the file is not correct. (Zip file will also say something about a virus)

(I could not scroll in the file explorer of a previous nightly version, wanted to check  a newer nightly version if that was still the case.)  

## Additional information

I suspect the build system is failing. Or code was introduced that is seen as a virus.

**Comment by panekj** [comment]
It's something about your system (probably anti-virus) that doesn't like it. Nothing we can do about it.
