### ISSUE TITLE
Please fix Find/Replace function that freezes

### ISSUE THREAD

**Issue by lineality** [lapce/lapce#3057]
## Lapce Version

"About Lapce" says lapce nightly.

## System information

fedora 39

## Describe the bug
Find/Replace function that freezes

## Additional information
maybe the fedora repo is not being updated?
```bash
$ sudo dnf copr enable titaniumtown/lapce 
$ sudo dnf install lapce
```

**Comment by MinusGix** [comment]
This should be fixed on nightly, are you on the latest nightly?
