### ISSUE TITLE
lapce compile time error

### ISSUE THREAD

**Issue by IntelligenceInside** [lapce/lapce#3059]
## Lapce Version

0.3.1

## System information

Alpine linux  6.1.72-0-lts

## Describe the bug

>>> lapce: Checking sha512sums...
lapce-0.3.1.tar.gz: OK
use-system-libs.patch: OK
cargo.lock.patch: OK
>>> lapce: Unpacking /var/cache/distfiles/lapce-0.3.1.tar.gz...
>>> lapce: use-system-libs.patch
patching file lapce-proxy/Cargo.toml
>>> lapce: cargo.lock.patch
patching file Cargo.lock
Hunk #1 succeeded at 3684 (offset 12 lines).
Hunk #2 succeeded at 3692 (offset 12 lines).
Hunk #3 succeeded at 7469 (offset 19 lines).
error: package `floem v0.1.0 (https://github.com/lapce/floem?rev=0694f9672a10a49290af223cac3dc2ab53b1b1dd#0694f967)` cannot be built because it requires rustc 1.73 or newer, while the currently active rustc version is 1.71.1
Either upgrade to rustc 1.73 or newer, or use
cargo update -p floem@0.1.0 --precise ver
where `ver` is the latest version of `floem` supporting rustc 1.71.1
>>> ERROR: lapce: build failed

## Additional information

none.

**Comment by panekj** [comment]
As the error suggests, you need newer rust

**Comment by IntelligenceInside** [comment]
added note: rust 1.73 is not available for alpine.
