### ISSUE TITLE
recomendations of objects and code stay after moving line. 

### ISSUE THREAD

**Issue by Attackly** [lapce/lapce#3073]
## Lapce Version
v0.3.1

## System information
Windows 11 Home 23H2
## Describe the bug
The recomendations stay after moving curser to another line and the Box Scrolls with the File.
 

## Additional information
![grafik](https://github.com/lapce/lapce/assets/91603506/676d3a8a-d5d6-4dec-86ea-71c545fb8506)

Also when scrolling it moves infront of the Terminal
![grafik](https://github.com/lapce/lapce/assets/91603506/918632a4-fb35-419f-bf57-530d1416f32d)

It does work if you move to another line and type or delte something there.

**Comment by dzhou121** [comment]
should be fixed in 0.4.0 https://github.com/lapce/lapce/releases/tag/v0.4.0

**Comment by Attackly** [comment]
Just updated. I at least did not encounter it anymore. Thanks.
