### ISSUE TITLE
Key not found: tooltip.foreground

### ISSUE THREAD

**Issue by lexika979** [lapce/lapce#3075]
Not sure if this is known yet, so might aswell:

## Lapce Version

Nightly

## System information

Windows 10

## Describe the bug
Trying to open the settings, the about window, or a folder, will cause lapce to panic

## Additional information

panicked at lapce-app\src\config.rs:323:32:
Key not found: tooltip.foreground

**Comment by Long0x0** [comment]
`tooltip.background` and `tooltip.foreground` are missing in the default theme https://github.com/lapce/lapce/pull/3053 @MinusGix
