### ISSUE TITLE
Enter causes multiple newlines to be passed to cosmic-text

### ISSUE THREAD

**Issue by zhouxs1023** [lapce/lapce#3079]
## Lapce Version
Lapce-windows-portable  2ea1c8a

## System information
windows 10

## Describe the bug
Using druid samples/hello, I want to add a line into the code, then using enter, but an error occurred as below:
![error](https://github.com/lapce/lapce/assets/905931/b09a4463-f28c-4376-ac59-d5f7309cd9ff)

## Additional information
 I feel that using the Druid library is more stable than the Floem library,
Same code, same operation, no problem with lapce-0.28

[lapce.2024-03-15.log](https://github.com/lapce/lapce/files/14617189/lapce.2024-03-15.log)

**Comment by MinusGix** [comment]
I'm not able to reproduce consistently, but I have seen this crash in similar situations. (It is due to including more than one line when shaping the text)

(Also stability issues like this are due to "rewrote frontend and also bunch of editor code", rather than due to floem itself.)
