### ISSUE TITLE
ssh not connecting 

### ISSUE THREAD

**Issue by harrydevnull** [lapce/lapce#308]
I was trying out the editor with remote code editing on my mac.
when I try to access the remote server it says disconnected. ( I can connect to remote host via my iterm without any issues)

where can I see logs ? my gut feeling says that editor is not picking up the keys on my ssh-agent

The only error I see on the terminal is 
```
/root/.lapce/lapce-proxy-0.0.12: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /root/.lapce/lapce-proxy-0.0.12)
```

which is kind of odd as I was trying this on my mac

**Comment by ghishadow** [comment]
can you tell more about remote server ?

**Comment by dzhou121** [comment]
@harrydevnull The remote server will run something to talk with Lapce local ui. The binary on the server was compiled with GLIBC_2.28 so that's why it didn't run. It means it's running on a slightly old Linux OS.

**Comment by harrydevnull** [comment]
it's running bionic 
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by harrydevnull** [comment]
would it be possible to stream the logs while connecting to server? 
something akin to 
```
ssh -vvv username@serverip
```

**Comment by clach04** [comment]
I think I'm having a similar issue from Windows (with https://github.com/lapce/lapce/releases/tag/v0.0.12 portable version) to an older Linux server that ssh/putty can connect to without any problem.

**Comment by clach04** [comment]
actually Lapce hangs under windows :( Quiting and restarting does NOT resolve it, on re-open Lapce attempts to ssh connect again. Can open previous work space which appears to cancel the ssh attempt

**Comment by DahShahar** [comment]
I'm having this issue as well. Is there any way to debug what might be going on for myself?

**Comment by SamuelPoulin** [comment]
> actually Lapce hangs under windows :(

Can confirm. I have two PCs with Lapce installed on them and a homeserver. I configured the two PCs with the same .ssh/config and copied both of their public keys to the authorized_keys file of my homeserver. When I use the "Connect to ssh host" dialog in Lapce with _username@homeserver_ it connects instantly on the PC running arch and takes about 30s on the PC running windows.
