### ISSUE TITLE
Lapce crashes on start

### ISSUE THREAD

**Issue by LambdaAlpha** [lapce/lapce#3081]
## Lapce Version

Lapce v0.3.1

## System information

OS: Arch Linux x86_64
Kernel: 6.7.9-arch1-1

## Describe the bug
Lapce crashes on start, 100%.

## Additional information

<details>
<summary>Backtrace</summary>

```
❯ RUST_BACKTRACE=full lapce -w
2024-03-16T08:33:46.056142Z ERROR lapce_app::keypress: Failed to load from "/home/lqh/.config/lapce-stable/keymaps.toml": no keymaps
thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.18.0/src/backend/direct.rs:778:18:
Error in Surface::configure: Validation Error

Caused by:
    Not enough memory left.

stack backtrace:
   0:     0x5ec1e632a71f - <unknown>
   1:     0x5ec1e4d6aeac - <unknown>
   2:     0x5ec1e62f103c - <unknown>
   3:     0x5ec1e632ceaf - <unknown>
   4:     0x5ec1e632ca93 - <unknown>
   5:     0x5ec1e632da59 - <unknown>
   6:     0x5ec1e632d57c - <unknown>
   7:     0x5ec1e632d4d6 - <unknown>
   8:     0x5ec1e632d4c1 - <unknown>
   9:     0x5ec1e4b91634 - <unknown>
  10:     0x5ec1e6873442 - <unknown>
  11:     0x5ec1e691fe68 - <unknown>
  12:     0x5ec1e697c821 - <unknown>
  13:     0x5ec1e4fe4737 - <unknown>
  14:     0x5ec1e4fca7c0 - <unknown>
  15:     0x5ec1e5ae8b77 - <unknown>
  16:     0x5ec1e4c747b3 - <unknown>
  17:     0x5ec1e4c74c25 - <unknown>
  18:     0x7cc417157cd0 - <unknown>
  19:     0x7cc417157d8a - __libc_start_main
  20:     0x5ec1e4c742a5 - <unknown>
  21:                0x0 - <unknown>
```

</details>

This bug seems to be reported before (#237)

**Comment by caedmon-kitty** [comment]
Same behavior on Fedora 39 using flatpak or downloading the app from github releases.

**Comment by afarinetti** [comment]
Same behavior on Pop!_OS 22.04 LTS.

**Comment by LambdaAlpha** [comment]
After updating system two days ago, Lapce doesn't crash any more.
Lapce version is still v0.3.1
Kernel: 6.8.1-arch1-1

**Comment by glademiller** [comment]
I'm not sure if this is the same issue my backtrace is different but as of two nightly releases ago downloaded from github I have the following backtrace. 

Linux fedora 6.7.9-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar  6 19:31:16 UTC 2024 x86_64 GNU/Linux

RUST_BACKTRACE=full lapce -w
2024-03-28T16:01:59.680201Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//cargo/git/checkouts/sled-4d0409c39405d50a/005c023/src/pagecache/snapshot.rs:131:70
   0: lapce_app::app::panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:785:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:659:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
   5: core::panicking::panic_fmt
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/result.rs:1649:5
   7: sled::db::Db::start_inner
   8: lapce_app::db::LapceDb::new
   9: lapce_app::app::launch
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: main
  12: __libc_start_call_main
  13: __libc_start_main_alias_2
  14: _start

**Comment by Aviksaikat** [comment]
Same error in `kali linux`

**Comment by panekj** [comment]
@LambdaAlpha could you provide more details on what kind of GPU/CPU are you using? What are the specs of your machine?

**Comment by panekj** [comment]
@glademiller your backtrace seems to point at `sled` which is no longer used in Lapce. If you can try updating to latest nightly and create a new issue if it's still a problem.

**Comment by glademiller** [comment]
@panekj I should have given an update a few days after this initial for me an updated nightly took care of the problem.

**Comment by Aviksaikat** [comment]
@glademiller I tried the Niglty build version & the issue still persists & here is my backtrace

```sh
2024-04-23T16:19:02.250189Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:724:18
   0: lapce_app::app::panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:785:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:659:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   5: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   6: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_fatal
   7: <T as wgpu::context::DynContext>::surface_configure
   8: wgpu::Surface::configure
   9: floem::app_handle::ApplicationHandle::new_window
  10: lapce_app::app::launch
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: main
  13: <unknown>
  14: __libc_start_main
  15: _start
```

**Comment by LambdaAlpha** [comment]
> @LambdaAlpha could you provide more details on what kind of GPU/CPU are you using? What are the specs of your machine?

I'm not familiar with cpu/gpu things.
My device is mibook 15 pro with os arch linux.
cpu: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
gpu: 00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: Xiaomi Device 1701
	Flags: bus master, fast devsel, latency 0, IRQ 142
	Memory at b2000000 (64-bit, non-prefetchable) [size=16M]
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 4000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

And, lapce hasn't crashed recent weeks, I have checked some(< 10) times in the past.

**Comment by panekj** [comment]
> And, lapce hasn't crashed recent weeks, I have checked some(< 10) times in the past.

That's good to hear :)

**Comment by Aviksaikat** [comment]
Still I'm seeing the issue
