### ISSUE TITLE
Look and feel on my mac 

### ISSUE THREAD

**Issue by harrydevnull** [lapce/lapce#309]
I have a rather odd issue the look and feel of the editor on my extended monitor is rather hazy. on my mac screen it looks good.
![Screen Shot 2022-03-27 at 12 00 36 PM](https://user-images.githubusercontent.com/13472925/160290138-a1eb5ac2-3cba-42b5-bc2c-6b52c6cf9d0f.jpg)

This is on my extended screen; though not pretty clear on the image it looks blurry on my extended screen

![Screen Shot 2022-03-27 at 12 00 47 PM](https://user-images.githubusercontent.com/13472925/160290139-9c6256ce-6e1a-4346-b3fb-fb510480a5c4.jpg)

**Comment by bugadani** [comment]
Hi and thanks for reporting this issue!

Do your monitors use different UI scaling values?

**Comment by kedare** [comment]
I confirm the issue, all clear on the main laptop screen, completely blurry on external monitors
Laptop screen is high DPI (3024x1964, 14")
External monitors are not (1920x1080, 27")

**Comment by dzhou121** [comment]
This should be fixed now by the latest v0.1.0 release.
