### ISSUE TITLE
Not Working On Linux Mint!

### ISSUE THREAD

**Issue by csubrahmanyam** [lapce/lapce#3102]
## Lapce Version

0.3.1

## System information

Linux Mint 21.1 Cinnamon

## Describe the bug
I cloned the lapce repo as mentioned in the docs and compiled it.
But when I run the lapce binary:
    - Only terminal works
    - settings button not working
    - menu not working
    - connect to SSH not working
It is just a ui window opened having no functionality!

**Comment by Long0x0** [comment]
Same problem on the latest commit.
Looks like [this PR](https://github.com/lapce/floem/pull/379) changed something causing the popout_menu to not work.

**Comment by csubrahmanyam** [comment]
Can you suggest how to go back to a working version before that PR.

**Comment by Long0x0** [comment]
You can temporarily downgrade floem by reverting commit https://github.com/lapce/lapce/commit/987bfb8b28a632df2536a1fe82a83f2cdd232a0c.

**Comment by csubrahmanyam** [comment]
Thank you @Long0x0 for the suggesstion and thank you @panekj for the fix!
Now lapce is working.
But another small issue with file explorer!
It is closed and not opening.

**Comment by csubrahmanyam** [comment]
![lapce-file-explorer-error](https://github.com/lapce/lapce/assets/112937168/5e162e81-e599-4ed2-9315-43df38b5cd10)

**Comment by csubrahmanyam** [comment]
![lapce-file-explorer-error](https://github.com/lapce/lapce/assets/112937168/e1b4a104-ac48-45fa-95f5-69caba33920d)

**Comment by csubrahmanyam** [comment]
OK, the explorer opened with the keyboard shortcut, but the tooltip saying "File Explorer" stays even after it is closed.
