### ISSUE TITLE
Lapce crashes on startup (Windows 11)

### ISSUE THREAD

**Issue by lpaulino07** [lapce/lapce#3114]
## Lapce Version

v0.3.1

## System information

Windows 11
AMD GPU, Adrenaline v24.3.1

## Describe the bug

Application crashes during startup. A white rectangle shows up for a few seconds, then closes without any errors.

## Additional information

Also tried with latest nightly, same issue. Attached GBD and didn't get any helpful information.

GDB log:
```
Starting program: C:\Program Files\Lapce\lapce.exe
[New Thread 12816.0x5540]
[New Thread 12816.0x59c8]
[New Thread 12816.0x2d40]
[New Thread 12816.0x538]
[Thread 12816.0x538 exited with code 0]
[Thread 12816.0x2d40 exited with code 0]
[Thread 12816.0x59c8 exited with code 0]
[Thread 12816.0x5540 exited with code 0]
[Inferior 1 (process 12816) exited normally]
```

Screenshot of behavior (White rectangle on top left of screen):
![image](https://github.com/lapce/lapce/assets/31266959/055623d0-884b-435a-95a3-6302757e832d)

**Comment by lpaulino07** [comment]
Seems to be fixed. I still get the white rectangle for like a second, but Lapce opens afterwards. I recently had to reinstall graphics drivers, so that might've been the issue. Latest nightly (nightly-39ef70d) works fine as well.

Will leave the issue open for now since somebody else seems to have the same issue in the comments.

**Comment by lpaulino07** [comment]
The issue is back, but I still think it might be a driver issue. Also, just found out that I need to run Lapce with "-w" if I want to keep in running in the terminal. Therefore, the previous log is not correct. A relevant portion of the new log is:
```
Thread 108 received signal SIGSEGV, Segmentation fault.
0x00007ffa38a25dcc in vk_icdGetInstanceProcAddrSG ()
   from C:\Windows\System32\DriverStore\FileRepository\u0401413.inf_amd64_997830838cb299a9\B401180\amdvlk64.dll
```
@SeleDreams would you be willing to post a log to see if we're having similar issues? Since you're using NVIDIA, it won't be an amdvlk64.dll problem, but it might help devs figure this out. Thanks!

**Comment by lpaulino07** [comment]
In my case, it can be fixed by setting WGPU_BACKEND=`dx12` or `gl`, so it's definitely a Vulkan issue. Unless SeleDreams's crash is also Vulkan related, I will close this issue.

**Comment by asik** [comment]
I get this:

```
2024-04-05T02:57:06.441305Z ERROR lapce_app::keypress: Failed to load from "C:\\Users\\******\\AppData\\Roaming\\lapce\\Lapce-Stable\\config\\keymaps.toml": no keymaps
2024-04-05T02:57:09.654119Z ERROR wgpu_hal::auxil::dxgi::result: Buffer creation failed: 0x887A0005
2024-04-05T02:57:09.654363Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.18.0\src\backend\direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer
    Parent device is lost


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lpaulino07** [comment]
Could you post the backtrace? Or if you have a gdb log could you post the relevant portion? Also please try the different WGPU_BACKEND options to see if it's actually a Vulkan issue. If not you might need to create a separate issue.

**Comment by lpaulino07** [comment]
I see. At least in my case it helped me identify it as a Vulkan problem. Thanks for the input!
