### ISSUE TITLE
`Open Folder` does not open file dialog on GNU/Linux.

### ISSUE THREAD

**Issue by JamesClarke7283** [lapce/lapce#3116]
## Lapce Version

I am using the latest nightly which is commit 16e0775

## System information

Arch: x86_64
OS: archlinux (GNU/Linux)

## Describe the bug
When i click the `Open Folder` button, it does not open a file dialog. 

## Additional information

I am pretty sure its a regression, i am currently now using the version just before this commit as a workaround: 70cee3b

**Comment by panekj** [comment]
Duplicate of #3102
