### ISSUE TITLE
Ability to open files with Lapce

### ISSUE THREAD

**Issue by Kyllingene** [lapce/lapce#312]
It's nice to be able to double-click a file and have it open in a text editor, instead of having to navigate to the folder in the editor, then open it. On a related (but less important) note, being able to drag files onto the editor to open them is handy; but definitely of lower priority.

**Comment by Tiggilyboo** [comment]
If I understand correctly you wish for your OS to open the file in lapce directly without using workspaces (the folder view in the side)?

If so, this can be done with Ctrl + O: then select the file regardless of the workspace already opened.

**Comment by Kyllingene** [comment]
That is helpful; however, I meant opening a file in Lapce from a file explorer when lapce isn't open. For example, I could associate .json with lapce, then I could open the file (double-click, maybe), and when lapce opens, it would automatically open the file. I don't know how operating systems handle things like that, but I believe it probably just passes the file in as a command line argument, so handling those would probably be sufficient.

**Comment by Evrey** [comment]
Yes, unless otherwise specified in e.g. `.desktop` files on Linux, double-click handling is performed by appending *all* given file/directory (right click, open with) paths as positional args. Note that i’m saying »all«, for you can attempt to open multiple files at once.

**Comment by cindRoberta** [comment]
it can be solved as I suggested to multiple folders, but instead to open a new folder, open a file
https://github.com/lapce/lapce/issues/533

**Comment by panekj** [comment]
`lapce` and proxy now accept file as argument
