### ISSUE TITLE
Concerning resource usage increase since the floem port

### ISSUE THREAD

**Issue by Samuel-B-D** [lapce/lapce#3159]
## Lapce Version
0.3.1

## System information
Windows 10

## Describe the bug
The memory usage seems to have increased quite a lot since the floem port. The GPU memory usage (VRAM) in particular looks pretty alarming to me.

## Additional information
Here is a screenshot illustrating the resource usage of both Lapce 0.2.8 (Druid) and 0.3.1 (floem), both in a blank state, without any file or folder open and no LSP running. I've highlighted the two metrics that I find a bit concerning:
![image](https://github.com/lapce/lapce/assets/3065425/e9f7a9c4-00e7-4fa5-9865-06200f9734f3)

**Comment by dzhou121** [comment]
We've fixed some GPU memory issues in the latest 0.4.0.

Can you please try it out? https://github.com/lapce/lapce/releases/tag/v0.4.0

**Comment by Samuel-B-D** [comment]
@dzhou121 It indeed seems resolved!
![image](https://github.com/lapce/lapce/assets/3065425/48d088bc-34e3-49bb-9fc8-0cdf491d0c2b)
It's now much more reasonable, nice improvements =)
