### ISSUE TITLE
Can't use settings combo box in bottom of settings

### ISSUE THREAD

**Issue by justanotheranonymoususer** [lapce/lapce#3182]
## Lapce Version

v0.3.1

## System information

Windows 11

## Describe the bug
Go to settings, search for "terminal", scroll to bottom, try to change default profile

## Additional information

https://github.com/lapce/lapce/assets/5781692/7f5eaecc-1438-4ebd-902a-653b65895913

**Comment by justanotheranonymoususer** [comment]
Also I can't use the keyboard to select as a workaround :(

**Comment by justanotheranonymoususer** [comment]
Also searching for "terminal default" doesn't find it. But "terminal: default" works. Maybe implement fuzzy search?

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/2904
