### ISSUE TITLE
Click on the tab on the lapce settings interface to switch to the wrong position

### ISSUE THREAD

**Issue by rootber** [lapce/lapce#3196]
## Lapce Version

v0.3.1

## System information

Windows11

## Describe the bug

Click on the tab on the lapce settings interface to switch to the wrong position

## Additional information

![581716ef0de31a4a77834f6113578846](https://github.com/lapce/lapce/assets/122451668/805d2c46-e10e-46eb-97ba-91357b0f7c10)

Here I chose the markdown plugin option, but I switched to the UI position

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/2759
