### ISSUE TITLE
No app icon in windows task switcher

### ISSUE THREAD

**Issue by njust** [lapce/lapce#3199]
## Lapce Version
Version 0.3.1

## System information
Windows 10 22H2 (Build 19045)

## Describe the bug
The app icon in the taskbar works as expected, but when pressing ALT+TAB the task switcher does not show the app icon. See the photo below. Sorry for the bad quality, but I'm not sure how to make a screenshot of the task switcher so I made a photo instead.

## Additional information
![IMG_0205](https://github.com/lapce/lapce/assets/2380253/824bba1c-f3da-4dbe-8de9-fd6b800ae153)

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/2933
