### ISSUE TITLE
key `rev` is ignored for dependency (tracing)

### ISSUE THREAD

**Issue by nunotexbsd** [lapce/lapce#3215]
## Lapce Version

0.4.0

## System information

FreeBSD 14.0 / Rust 1.77.0

## Describe the bug

Can't compile:
```
error: failed to load manifest for workspace member `/wrkdirs/usr/ports/editors/lapce/work/lapce-0.4.0/lapce-app`

Caused by:
  failed to parse manifest at `/wrkdirs/usr/ports/editors/lapce/work/lapce-0.4.0/lapce-app/Cargo.toml`

Caused by:
  key `rev` is ignored for dependency (tracing).
```
## Additional information

Trying to compare Cargo.{lock,toml} from 0.3.1 version but can't find what causing this error.

**Comment by panekj** [comment]
Did you try using vendor tarball? It has the Cargo dependency manifest and all dependencies already present, so you could just swap out it in build

**Comment by nunotexbsd** [comment]
I will try vendor tarball and figure out how to interact with our ports framework.

Thanks!

**Comment by panekj** [comment]
Any luck?

**Comment by nunotexbsd** [comment]
@panekj 

It seems that FreeBSD framework is getting in between and changing some stuff.
I was not able to use vendor tarball yet as I will need more time to do that.

In the meanwhile we will use workaround until a better approch if found.

Thanks very much for your help.

Will close PR now.

Cheers
