### ISSUE TITLE
Lapce shows only a pink screen on macOS

### ISSUE THREAD

**Issue by heyitspaul** [lapce/lapce#3231]
## Lapce Version

0.4.0

## System information

macOS Sonoma 14.4.1

## Describe the bug

Updated Lapce from 0.2, app only shows pink screen.

## Additional information

<img width="817" alt="image" src="https://github.com/lapce/lapce/assets/10618389/27dce693-0d21-492f-aeff-bd73f2a413a2">

**Comment by heyitspaul** [comment]
Ran 0.3.0 and 0.3.1, app opened fine there. Still does not run on 0.4.0 afterward.

**Comment by dzhou121** [comment]
It's a new bug in 0.4.0 which is fixed in master #3203

**Comment by heyitspaul** [comment]
Changing theme in 0.3.1 and switching to 0.4.0 does the trick. That's the workaround for anyone coming from Google. Closing as this is fixed.
