### ISSUE TITLE
Unable to use most of numpad, even with num lock enabled

### ISSUE THREAD

**Issue by liliantdn** [lapce/lapce#3238]
## Lapce Version
0.4.0 from flathub.

## System information
Fedora 40, French AZERTY Keyboard layout.

## Describe the bug
Whenever I am trying to input numbers using the numpad (with num lock enabled), it instead acts as if num lock was disabled, except for `5` and `0`. The symbol keys all work except for `.`.

## Additional information
This is my first time using lapce on linux, I've previously used it on windows and did not have this issue.
I mentionned that I am using an AZERTY keyboard layout but if I switch it to QWERTY on my system it does not solve the issue (the physical keyboard is still AZERTY though)

**Comment by fjsevilla-dev** [comment]
I have the same problem on Linux (Arch Linux - Gnome 46 - Wayland), QWERTY keyboard (Spanish layout). This only happens in Lapse 0.4.0,  Lapse 0.3.1 does not show this problem, in the same system.

**Comment by VarLad** [comment]
Same issue here. @dzhou121 can it be a regression in bumping Floem versions?
