### ISSUE TITLE
Remote development doesn't work(MacOS local to Linux remote)

### ISSUE THREAD

**Issue by weinix** [lapce/lapce#3241]
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 
0.4.0(1)

## System information

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04
MacOS Ventura (on Macbook M1 Pro)

## Describe the bug
- Able to open ssh session to remote Linux server
- SSH terminal shows up, and can internet with remote server
- ps shows `/home/user/.local/share/lapce-stable/proxy/lapce --proxy` is running
- on remote server 
```
❯ ~/.local/share/lapce-stable/proxy/lapce --version
Lapce-proxy v0.4.0
```
- Issue:  I can't open folder on remote to start remote development. 
## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
<img width="896" alt="image" src="https://github.com/lapce/lapce/assets/8346873/b1dc09e9-fb7a-4b7c-adef-480499f634d6">

- logs
- theories about what might be going wrong
- workarounds that you used

**Comment by panekj** [comment]
Remote file picker is not implemented, you can open a directory with `lapce <path>` in terminal

**Comment by weinix** [comment]
Ah, Thank you for the quick answer! 
Yes, that worked!

**Comment by weinix** [comment]
I am able to open python code now on remote server, but with python-lsp-server plugin installed on remote server, `Go to Definition` function doesn't do anything. Does remote development support plug-in's yet?
Thanks again!

**Comment by panekj** [comment]
There is nothing preventing from plugins to work with Lapce. Lapce locally behaves the same way as well as remotely (except the connecting and installing lapce remote).
You can open log file to see what is wrong (`F1` > `Open log file`)

**Comment by weinix** [comment]
Thank you! I will dig further and will share what I found.

**Comment by branchus** [comment]
Thank you very much for this little tip. I just tried Lapce and hope it getting better and better
