### ISSUE TITLE
tree-sitter-yaml hash listed in Cargo.toml does not exist; cannot build

### ISSUE THREAD

**Issue by brant-qai** [lapce/lapce#3251]
## Lapce Version

Master (as of 2024-05-07 20:04 UTC), as well as v0.4.0 tag.

## System information

PopOS (Ubuntu Mantis)
EndeavourOS (Arch)

## Describe the bug

In lapce-core the ``Cargo.toml`` file lists hash ``80c8d76847f03e772c5c524cf29bafb56858a8d1`` for tree-sitter-yaml. Specifically it is listed as follows:

```toml
tree-sitter-yaml = { git = "https://github.com/panekj/tree-sitter-yaml", rev = "80c8d76847f03e772c5c524cf29bafb56858a8d1", optional = true }
```

I'm sure this worked at some point but this hash has since been removed from the referenced repository. See: [80c8d76847f03e772c5c524cf29bafb56858a8d1](https://github.com/panekj/tree-sitter-yaml/commit/80c8d76847f03e772c5c524cf29bafb56858a8d1)  which now yields a 404. 

## Additional information
This probably still works for anyone who had already cached a copy of the the tree-sitter-yaml code with that hash, but for a new build it no longer works because the hash cannot be downloaded.  I did try about 40 different commits just to see if I could find one that would build but they all had issues with the ``Some`` type. 

```
~/projects/3rdparty/lapce$ cargo build --release
    Updating git repository `https://github.com/panekj/tree-sitter-yaml`
error: failed to get `tree-sitter-yaml` as a dependency of package `lapce-core v0.4.0 (/home/brant/projects/3rdparty/lapce/lapce-core)`

Caused by:
  failed to load source for dependency `tree-sitter-yaml`

Caused by:
  Unable to update https://github.com/panekj/tree-sitter-yaml?rev=80c8d76847f03e772c5c524cf29bafb56858a8d1#80c8d768

Caused by:
  revspec '80c8d76847f03e772c5c524cf29bafb56858a8d1' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by brant-qai** [comment]
@panekj wow that was astonishingly fast :heart:   thanks!

**Comment by panekj** [comment]
If you care about reproducing the previous release, there is vendor tarball with all dependencies -> https://github.com/lapce/lapce/releases/download/v0.4.0/vendor.tar.gz

**Comment by panekj** [comment]
It should build normally now as well as it's restored here: https://github.com/panekj/tree-sitter-yaml/tree/old
(repo was renamed to <https://github.com/panekj/tree-sitter-yaml-old>)
