### ISSUE TITLE
Add Lapce Shell Command to PATH does not affect external terminal

### ISSUE THREAD

**Issue by s4Dt0y** [lapce/lapce#3254]
I'm on Lapce 0.4.0. I tried to add Lapce to path with the command...there was no success or error message, so I'm like "ok". I tried running the lapce command from the integrated terminal and it worked, but when I try to run it from my external terminal (iterm2), it doesn't work. I checked the path variables, and they were different (the lapce integrated terminal had the lapce path, but the iterm2 one did not). I am on zsh. I did run `exec zsh`, `source ~/.zshrc`, restarted the terminal, and everything I could think of but that didn't work. Soooo...does lapce have a different dotfile that runs on startup, or something like that? Obviously I could just add the path manually, but I am just wondering if I am super dumb and did something wrong.

Echoing path on the lapce integrated terminal (the lapce path is the last one on the list):
```
/Users/xxxxxx/flutter_src/flutter/bin:/usr/local/opt/postgresql@15/bin:/Users/xxxxxx/.gem/ruby/3.1.3/bin:/Users/xxxxxx/.rubies/ruby-3.1.3/lib/ruby/gems/3.1.0/bin:/Users/xxxxxx/.rubies/ruby-3.1.3/bin:/Users/xxxxxx/.pyenv/shims:/Users/xxxxxx/bin:/usr/local/opt/tcl-tk/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/Users/xxxxxx/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Applications/Lapce.app/Contents/MacOS:/Users/xxxxxx/.cargo/bin:/Users/xxxxxx/Applications/RustRover 2023.3 EAP.app/Contents/MacOS
```
Echoing path on external iterm2 (the lapce path is nonexistant):
```
/Users/xxxxxx/flutter_src/flutter/bin:/usr/local/opt/postgresql@15/bin:/Users/xxxxxx/.gem/ruby/3.1.3/bin:/Users/xxxxxx/.rubies/ruby-3.1.3/lib/ruby/gems/3.1.0/bin:/Users/xxxxxx/.rubies/ruby-3.1.3/bin:/Users/xxxxxx/.pyenv/shims:/Users/xxxxxx/bin:/usr/local/opt/tcl-tk/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/Users/xxxxxx/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Users/xxxxxx/.cargo/bin:/Users/xxxxxx/Applications/RustRover 2023.3 EAP.app/Contents/MacOS
```

**Comment by ProgramCrafter** [comment]
Usually, each terminal process has its own PATH (and set of environment variables, actually). Have you modified system PATH or process one?

**Comment by s4Dt0y** [comment]
Hmmm...yes I have modified my path a LOT.

**Comment by s4Dt0y** [comment]
Does this mean that the only fix is to add it manually in the ~/.zshrc file? (Yes, I am using zshrc with omz and p10k)
