### ISSUE TITLE
Cursor on column 0 of non empty line is not displayed

### ISSUE THREAD

**Issue by notorand-it** [lapce/lapce#3271]
## Lapce Version

0.4.0

## System information

OS: ArchLinux (up-to-date)
Kernel Version : 6.8.9.zen1-2
Plasma Version : 6.0.4.1-1
KDE Version : 24.02.2-1
Frameworks Version : 6.2.0-1
Qt5 Version : 5.15.13+kde+r7-1
Qt6 Version : 6.7.0-6
Wayland Version : 1.22.0-1
XOrg/Wayland Version : 23.2.6-2
Mesa Version : 1:24.0.7-3
LibVA Version : 2.21.0-1
VDPAU Version : 1.5-2

## Describe the bug
When cursor is on the first column (0) of a non empty line, the cursor IS NOT displayed.
When cursor is on the first column (0) of an empty line, the cursor IS displayed.

## Additional information

![SHOT-20240515-091215-CEST](https://github.com/lapce/lapce/assets/5338874/e07b6f19-3ddb-4c86-8daf-b642617819f7)

**Comment by notorand-it** [comment]
The bug is actually different from what I have described.
This is my (currently) more precise description.

The cursor is actually displayed but, if you are inside a "code block", the vertical line drawn to highlight the code block extent almost completely hide the cursor if it is a "line" cursor.

# Additional information

As a possible solution workaround you could not draw that vertical line highlighting the block if the cursor would be hidden. Or use a fainter shade of gray for that line.

In the following screenshot you can actually see the cursor if you squint your eyes.

The meaning of that "Char 45" is uncertain. Maybe it is the 45th since the beginning of the file.

![SHOT-20240515-093850-CEST](https://github.com/lapce/lapce/assets/5338874/ea322567-12d3-4ab6-b55a-acc0d60b31ce)

**Comment by panekj** [comment]
What settings you have applied?

**Comment by notorand-it** [comment]
I reinstalled everything and didn't install lapce yet (using kate ATM).
I was using a rather default setup with code blocks and dark theme.
I will reinstall it as soon as a new build will pop up in ArchLinux to check the other bug I reported (https://github.com/lapce/lapce/issues/3272).

> The cursor is actually displayed but, if you are inside a "code block", the vertical line drawn to highlight the code block extent almost completely hide the cursor if it is a "line" cursor.

The cursor is  just barely viewable (by me) as a faint bluish bar overlapping the grayish  vertical bar used to highlight the "{...}" (please, squint you eyes on my screenshot).

I think we need need either a thicker bar cursor (when highlighting code blocks), or a brighter color for it or, better, both.

**Comment by panekj** [comment]
Default:
![image](https://github.com/lapce/lapce/assets/50457605/b9d9a8f5-e2a9-4cad-8ebc-3d149f8da9af)

With `Highlight Scope Lines` enabled
![image](https://github.com/lapce/lapce/assets/50457605/58ce3e8c-8466-4466-be07-c738f8bb1c09)

**Comment by Long0x0** [comment]
Cursor's x < 0 at the first column, so only half of it is shown.
https://github.com/lapce/floem/blob/e647fa442332735aca782d21ce13a3deabad20d5/src/views/editor/view.rs#L1059

vscode just offset the first one by 1px:
![image](https://github.com/lapce/lapce/assets/51022287/2c10ca8f-574b-4e3d-80f4-b8de71eb08d3)

But it's not perfect :(
