### ISSUE TITLE
Fresh installation via Snap on Ubuntu 22.04 Remote (Nomachine) fails to start.

### ISSUE THREAD

**Issue by tamer73** [lapce/lapce#3274]
## Lapce Version 
0.2.4 ( Actual Ubuntu snap Version)

## System information
Ubuntu 22.04

## Describe the bug
Cant start Lapse on my remote Ubuntu after fresh installation wth snap 

## Additional information

`$ lapce -w
(lapce:113225): Gtk-WARNING **: 10:55:22.460: cannot open display: :1001`

```
$ sudo /etc/NX/nxserver --list
NX> 127 Available sessions:

Display Username Remote IP       Session ID                       Node           
------- -------- --------------- -------------------------------- -------------- 
1001    dt       127.0.0.1       5CEED9666B4B90BC829B2536AC5BCF9E localhost:4000
1002    dt       xxx.xxx.xxx.xxx 2DB06A4BF9C0B62F0AE734356D5E1EFD localhost:4000
```

```
$ echo $XDG_CURRENT_DESKTOP 
ubuntu:GNOME
```

**Comment by mrtryhard** [comment]
I remember running into the issue with Firefox as well, and if I remember correctly, this NoMachine KB article helped me make it work https://kb.nomachine.com/AR06T01163

I don't think it's a Lapce issue, more like NoMachine + Snap integrations. 

There are also other instances,
* https://kb.nomachine.com/TR11T10698
* This one indicates a recent change in snap may have rebroken NoMachine: https://kb.nomachine.com/TR03V11118

**Comment by panekj** [comment]
Snap is not supported. Use prebuilt binary or one of the `.deb` packages available on [Releases](https://github.com/lapce/lapce/releases) page
