### ISSUE TITLE
can not open file when click  menu "go to definition"  on a function

### ISSUE THREAD

**Issue by moon989** [lapce/lapce#3281]
## Lapce Version
nightly-9d016fe

## System information
Windows 11, 

## Describe the bug
can not open file when click method on menu "go to definition" 

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots

- logs

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/2954
