### ISSUE TITLE
syntax highlighting for cpp is not working

### ISSUE THREAD

**Issue by goawayearth** [lapce/lapce#3282]
## Lapce Version

Lapce v0.4 

## System information

win11

## Describe the bug
When I open a C++ project, I find that there is no syntax highlighting. What's the matter? Do I have to install and configure a C++ extension?
It seems there is also a problem with file synchronization. Files opened in Lapce do not automatically sync when modified in other editors.

![Snipaste_2024-05-24_00-18-47](https://github.com/lapce/lapce/assets/106306129/75274919-9970-4376-81fe-9443234dddbe)

**Comment by panekj** [comment]
It was fixed in https://github.com/lapce/lapce/commit/3dc59aeb2767995bc82c51f55db91294fa384379

**Comment by OpenSauce04** [comment]
This issue doesn't actually appear to be fixed. Any C++ file I open has zero syntax highlighting. Header files are hightlighted fine:
<img src=https://github.com/user-attachments/assets/aa959d92-9c13-4583-862c-38c11373fb03 width=500px/>
<img src=https://github.com/user-attachments/assets/0c148939-2fa2-4ab6-8596-e9230535b0d7 width=500px/>
I am using 16ebd02775445dca6ba7609afeeea215802c4275

**Comment by panekj** [comment]
It was fixed at the time, it doesn't work currently because there are changes to how grammars an highlighting works

**Comment by OpenSauce04** [comment]
Is there somewhere I can track the progress? I would like to use the editor in its current state, but this is a blocker.

**Comment by OpenSauce04** [comment]
I've tried relaunching several times and the issue doesn't appear to be going away

**Comment by OpenSauce04** [comment]
I also don't seem to have hightlighting for Kotlin, which the pinned roadmap says was merged all the way back in 2022?
Is there a similar issue there as well?

**Comment by OpenSauce04** [comment]
Decided to check back after a few days and rebuild from 3a78eaa, and there is still no highlighting. Are you sure this has been fixed?
