### ISSUE TITLE
Can't open Lapce | Cannot find entry point

### ISSUE THREAD

**Issue by amySpark-ng** [lapce/lapce#329]
Ok so i first downloaded the portable windows version, which didn't seem to work, it threw this error:

lapce.exe - Cannot find entry point | Cannot find procedure entry point "CreatePseudoCode" in dynamic link library C:\Program Files\Lapce\lapce.exe

Sorry if it is badly translated, my first language is Spanish :/ i'll still leave the screenshot here in case it helps, i have windows 8.1

[SCREENSHOT](https://user-images.githubusercontent.com/92493175/160712797-8e9c4fc8-ab0f-45a6-b1b3-3a6af429fa62.png)

**Comment by hasali19** [comment]
It seems that the `CreatePseudoConsole` function is only available on Windows 10.

https://docs.microsoft.com/en-us/windows/console/createpseudoconsole#requirements

Not sure if Lapce intends to support older versions of Windows.

**Comment by amySpark-ng** [comment]
Ohh i see, well damnit, thanks for the answer tho
