### ISSUE TITLE
When launching Lapce, a panic occurred at the slice::from_raw_parts.

### ISSUE THREAD

**Issue by Cliear** [lapce/lapce#3290]
## Lapce Version

Lastest master

## System information

Windows 10 22H2 19045.4412

## Describe the bug
When launching Lapce, a panic occurred at the slice::from_raw_parts.

## Additional information
![2024-05-29 154021](https://github.com/lapce/lapce/assets/48273990/b505f948-50c8-42a8-9078-6069c4a3fba2)

**Comment by panekj** [comment]
Did you run it with release or debug profile? There might be a backtrace available in log file, `F1` > `Open log file`

**Comment by Cliear** [comment]
Can't use the F1, Lapce is crashed while it startup。I discovered this error because the latest release package I downloaded from GitHub a few days ago crashed during runtime. So I downloaded the code to compile it,but the same issue occurred.
