### ISSUE TITLE
Application fails to start (on Linux Mint) 

### ISSUE THREAD

**Issue by johnzan** [lapce/lapce#332]
The application fails to start when trying to launch on Linux Mint.

**System information** 
System:    Kernel: 5.4.0-104-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
           Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: LENOVO product: 4291QW2 v: ThinkPad X220 serial: <filter> Chassis: 
           type: 10 serial: <filter> 
           Mobo: LENOVO model: 4291QW2 serial: <filter> UEFI [Legacy]: LENOVO v: 8DET76WW (1.46 ) 
           date: 06/21/2018 
Battery:   ID-1: BAT0 charge: 10.8 Wh condition: 11.2/62.2 Wh (18%) volts: 12.6/11.1 
           model: SANYO 42T4861 serial: <filter> status: Unknown 
CPU:       Topology: Dual Core model: Intel Core i5-2520M bits: 64 type: MT MCP arch: Sandy Bridge 
           rev: 7 L2 cache: 3072 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19934 
           Speed: 903 MHz min/max: 800/3200 MHz Core speeds (MHz): 1: 801 2: 819 3: 801 4: 800 
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: Lenovo 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0126 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 3000 (SNB GT2) v: 3.3 Mesa 21.2.6 
           compat-v: 3.0 direct render: Yes 

When run with `export RUST_BACKTRACE=full` I get the following

`
$ ./lapce 

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendError(RequestDeviceError)', /home/runner/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/window.rs:92:55
stack backtrace:
   0:     0x557ad586ef5c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557ad586ef5c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557ad586ef5c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x557ad586ef5c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x557ad589b71c - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x557ad5864a53 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x557ad5871a62 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x557ad5871a62 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x557ad5871a62 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x557ad5871645 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x557ad58720b3 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x557ad5871dd0 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x557ad586f404 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x557ad5871b09 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x557ad42a34a1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x557ad42a3593 - core::result::unwrap_failed::ha0327e3803285d6e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
  16:     0x557ad44f2cc8 - druid::window::Window<T>::new::h2db9a7877d26d6e6
  17:     0x557ad43e5556 - druid::win_handler::AppState<T>::build_native_window::h603723e718219ef8
  18:     0x557ad42b6485 - lapce_ui::app::lanuch::hcbe11df89c48fc59
  19:     0x557ad42a3d43 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd458a4cc88aa7051
  20:     0x557ad42a3d79 - std::rt::lang_start::{{closure}}::h3dc07a670cf4b232
  21:     0x557ad586e610 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  22:     0x557ad586e610 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  23:     0x557ad586e610 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  24:     0x557ad586e610 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  25:     0x557ad586e610 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  26:     0x557ad586e610 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  27:     0x557ad586e610 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  28:     0x557ad586e610 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  29:     0x557ad586e610 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  30:     0x557ad42a3d32 - main
  31:     0x7fe32896d0b3 - __libc_start_main
  32:     0x557ad42a3c3e - _start
  33:                0x0 - <unknown>

`

If you need any other information, don't hesitate to ask.
Cheers.

**Comment by Cody-Duncan** [comment]
This is the latest duplicate of issues #210 and #93

**Comment by bugadani** [comment]
Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

**Comment by johnzan** [comment]
Can confirm that the latest build resolves this issue
