### ISSUE TITLE
A white background appear when Lapce  is launched,

### ISSUE THREAD

**Issue by moon989** [lapce/lapce#3330]
## System information  : Win11 

A white background appear when Lapce  is launched,  as follow image . 

![image](https://github.com/lapce/lapce/assets/32634377/4baed691-6988-45df-b18d-b35b34f5d19b)

**Comment by moon989** [comment]
Is not bug ?

**Comment by moon989** [comment]
No other developers on Windows have discovered this problem?

**Comment by jm-observer** [comment]
Have you ever tried using your own compiled version?

**Comment by moon989** [comment]
> Have you ever tried using your own compiled version?

Yes ,but nothing change

**Comment by jm-observer** [comment]
The log path is：
_C:\Users\****\AppData\Local\lapce\Lapce-Nightly\data\logs_
Can you open it?

**Comment by moon989** [comment]
> The log path is： _C:\Users\****\AppData\Local\lapce\Lapce-Nightly\data\logs_ Can you open it?

Yes , it can open

**Comment by moon989** [comment]
> The log path is： _C:\Users\****\AppData\Local\lapce\Lapce-Nightly\data\logs_ Can you open it?

Yes , it can open

**Comment by jm-observer** [comment]
Is there any error message in it

**Comment by panekj** [comment]
There won't be any log for because it's not an issue within Lapce
