### ISSUE TITLE
SIlently exits immediately when launched

### ISSUE THREAD

**Issue by caedmon-kitty** [lapce/lapce#3331]
Silently  exits immediately when launched

## Lapce Version
Don't know it exits.  Tried the  download version from the web site and the version just built using cargo install ... from the Install from Source guide.

## System information

Fedora 39

## Describe the bug
1. launch
2. Flash of window being created
3. Exits

## Additional information

How do I get a traceback or log?

**Comment by panekj** [comment]
run `lapce -w`

**Comment by caedmon-kitty** [comment]
Thank you.
lapce -w
2024-06-16T00:16:51.563444Z ERROR floem_winit::platform_impl::platform: X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}    
2024-06-16T00:16:51.563456Z ERROR floem_winit::platform_impl::platform: X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}    
2024-06-16T00:16:51.563462Z ERROR floem_winit::platform_impl::platform: X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}    
2024-06-16T00:16:51.565634Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//home/michael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/linux/x11/window.rs:1084:14
   0: lapce_app::app::logging::panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: floem::window_handle::WindowHandle::process_update_messages
   8: floem::window_handle::WindowHandle::process_update_no_paint
   9: floem::app_handle::ApplicationHandle::handle_updates_for_all_windows
  10: lapce_app::app::launch
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: main
  13: __libc_start_call_main
  14: __libc_start_main_alias_2
  15: _start

**Comment by caedmon-kitty** [comment]
And from the downloaded version The X11 errors are the same.  The traceback has more info -

2024-06-16T00:19:17.806338Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/linux/x11/window.rs:1084:14
   0: lapce_app::app::panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:785:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:659:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   5: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
   7: floem::window_handle::WindowHandle::process_update_messages
   8: floem::window_handle::WindowHandle::process_update_no_paint
   9: floem::app_handle::ApplicationHandle::idle
  10: lapce_app::app::launch
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: main
  13: __libc_start_call_main
  14: __libc_start_main_alias_2
  15: _start

**Comment by panekj** [comment]
This seems to be #3243
