### ISSUE TITLE
Non-monospace text is blank

### ISSUE THREAD

**Issue by Renarde-dev** [lapce/lapce#3347]
## Lapce Version :

Lapce v0.4.0 (installed via pacman from `extra/lapce` )

## System information :

- OS: Arch Linux x86_64 
- Host: Laptop 13 (AMD Ryzen 7040Series) A5 
- Kernel: 6.9.6-zen1-1-zen 
- DE: GNOME 46.2 (wayland) 
- WM: Mutter 
- WM Theme: Adwaita  
- CPU: AMD Ryzen 5 7640U w/ Radeon 760M Graphics (12) @ 4.9GHz 
- GPU: AMD ATI Phoenix1 
- Memory: 14.93 GiB

[Package list](https://pastebin.com/1WUhtmyZ)

## Describe the bug :

When the font package for `ttf-dejavu` is not installed Lapce will not display non-monospace text 

## Additional information :

The settings page when the font package is not installed :
![Screenshot from the settings page](https://github.com/lapce/lapce/assets/91322598/c6208efb-f2d7-4f77-b3a4-e6423b0337bb)

[Arch maintainer point that the font is supposed to be embed in the package](https://gitlab.archlinux.org/archlinux/packaging/packages/lapce/-/issues/1#note_194484) 

### Workaround
Install the the font package `sudo pacman -S ttf-dejavu`

### Potential fixes :

- Allow font fallback to system default
- Add DejaVu as explicit dependency

**Comment by HanabishiRecca** [comment]
I think it's a duplicate of #607 and will be resolved in the next release. Or if you try the recent nightly build right now.

**Comment by Renarde-dev** [comment]
Sorry for the duplicate, I didn't found #607 when I searched.
Closing.
