### ISSUE TITLE
can't set shell to (git) bash on windows

### ISSUE THREAD

**Issue by rbtcollins** [lapce/lapce#335]
Hi, this project looks promising. Using the terminal shell setting I tried "C:\Program Files\Git\usr\bin\bash.exe", which is the path to the bash.exe used in VSCode. That resulted in powershell running inside lapce.

Setting 'bash.exe' as the terminal did change the terminal shell, but to the WSL one, which I don't want to use :O.

**Comment by theAkito** [comment]
> Setting 'bash.exe' as the terminal did change the terminal shell, but to the WSL one, which I don't want to use :O.

Isn't that what should be the expected and correct behaviour?

**Comment by panekj** [comment]
Closing in favour of #1155 which has more context about the issue
