### ISSUE TITLE
Special Symbols in File Path Bugs the Diagnostics Tab

### ISSUE THREAD

**Issue by chadcat7** [lapce/lapce#3361]
## Lapce Version
Lapce v0.4.0

## System information
Windows 10 Home v 22H2

## Describe the bug
While viewing the errors in the diagnostic tab in the panel below, if the path of the filename has brackets or any symbol in it, they are not parsed properly which does not allow me to open the file.

For example if the file is `src/routes/(app)/gears/+page.svelte` (this is following the sveltelkit guidelines), the file is parsed as `src/routes/%28app%29/gears/%2Bpage.svelte`

## Additional information

another example 
![image](https://github.com/lapce/lapce/assets/68964499/8ad056a5-80f0-4549-a8e1-7459b4866bce)

**Comment by panekj** [comment]
This is fixed in master/nightly: https://github.com/lapce/lapce/commit/f2355aa0b8839aacc5fa684db2c8b75b5258e251
