### ISSUE TITLE
Picking a drive in file picker in Windows causes a panic

### ISSUE THREAD

**Issue by TheOddGarlic** [lapce/lapce#337]
If a drive is selected in the file picker after pressing "Open Folder", lapce panics at 'called `Option::unwrap()` on a `None` value', `lapce-ui\src\tab.rs:861:57`. `Path::filename(&self)` returns the last component of the path, which, in this case, is empty.

**Comment by bugadani** [comment]
I can't reproduce this on master. Which version did you experience this crash with?

**Comment by TheOddGarlic** [comment]
I was on master as well
