### ISSUE TITLE
Add preview mode while edting a markdown file

### ISSUE THREAD

**Issue by it4ch1-007** [lapce/lapce#3378]
## Is your feature request related to a problem? Please describe.

When editing a markdown file, it is very helpful to have its preview on the same window in different pane. It is available in VS code.

## Describe the solution you'd like

There should be an option to be able to see the preview in the left or right pane window while I edit the markdown file inside the same pane window.

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/lapce/issues/2301
