### ISSUE TITLE
Compile error from git latest (build script MSRV check)

### ISSUE THREAD

**Issue by PhilipDaniels** [lapce/lapce#3399]
## Lapce Version

Cloned from git at hash 16ebd027 - 2024-08-02 06:42

## System information

Windows 11

## Describe the bug
Doing `cargo build` gives an error:

```
Compiling lapce-core v0.4.0 (C:\Users\Phili\repos\others\lapce\lapce-core)
error: the `cargo::` syntax for build script output instructions was added in Rust 1.77.0, but the minimum supported Rust version of `lapce-core v0.4.0 (C:\Users\Phili\repos\others\lapce\lapce-core)` is 1.77.
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.
warning: build failed, waiting for other jobs to finish...

```

## Additional information

Amazingly, this can be fixed by updating the top-level workspace `Cargo.toml` to say `rust-version = "1.77.0"` instead of `rust-version = "1.77"`.

Perhaps a cargo bug? I would consider the two equivalent.

**Comment by PhilipDaniels** [comment]
This was with Rust 1.78 by the way, I am checking 1.80 now.

**Comment by panekj** [comment]
https://github.com/rust-lang/cargo/issues/13807

**Comment by PhilipDaniels** [comment]
Good find :-) I can confirm upgrading to rust 1.80 makes lapce compile OK, but I think the `Cargo.toml` ought to be changed too.
