### ISSUE TITLE
[Arch Linux] Won't launch after fresh install of lapce

### ISSUE THREAD

**Issue by ThatOneCalculator** [lapce/lapce#34]
First time trying to launch after installing.
```
$ lapce
start to watch path "/home/kainoa/.config/lapce/settings.toml"
2021-12-15T05:11:19.544115Z DEBUG druid::localization: available locales [], current en-US
2021-12-15T05:11:19.544126Z DEBUG druid::localization: resolved: [en-US]
primitives buffer size 80000
can't start proxy Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by balroggg** [comment]
My build is failed with error on ArchLinux if it helps
```
$ make binary
...
Finished release [optimized] target(s) in 0.39s
make: lipo: No such file or directory
make: *** [Makefile:29: lapce-native] Error 127
```
Run from cargo
```
$ cargo run --release --bin lapce
...
Finished release [optimized] target(s) in 0.37s
     Running `target/release/lapce`
start to watch path "/home/balrog/.config/lapce/settings.toml"
thread 'main' panicked at 'launch failed: WindowDropped', core/src/app.rs:35:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vincens2005** [comment]
I'm having the same issue with the AUR package

**Comment by rbran** [comment]
Aur version of lapse is outdated and don't install `lapse-proxy` that is causing the error.

**Comment by vincens2005** [comment]
how do I avoid installing lapce-proxy?

**Comment by rbran** [comment]
You don't, it is required to work, if using Arch Linux aur, you need to modify PKGBUILD.

**Comment by vincens2005** [comment]
I tried running it straight from this repo and had the same issue

**Comment by ThatOneCalculator** [comment]
same

**Comment by rbran** [comment]
Here the my modified PKGBUILD:
https://gist.github.com/rbran/88b8a19050a92d161ea52b78f28fb5f9

This works on my Arch Linux.

**Comment by vincens2005** [comment]
thanks it worked

**Comment by grawlinson** [comment]
Maintainer of the AUR package here, this is *not* the correct forum for AUR specific issues. Any issues stemming from the AUR package need to be discussed on the AUR.

Since this has been fixed downstream, this issue can be safely closed.
