### ISSUE TITLE
syntax highlighting for c is not working 

### ISSUE THREAD

**Issue by ydong08** [lapce/lapce#3418]
## Lapce Version
Lapce v0.4.1
Windows 10 Pro

## Describe the bug
this issue is same with #3282, now #3282 is closed, so i create new one.

syntax highlighting in lapce:
![1723083461451](https://github.com/user-attachments/assets/726bc029-f0fc-4f57-955d-83276aef97b9)

stdout.log:
```
failed to obtain release info: Failed to retrieve releases for tree-sitter-grammars
```

**Comment by dzhou121** [comment]
It looks like you can't download the tree sitter grammars from Github.

**Comment by jm-observer** [comment]
try to set environment variable `https_proxy`， which allow request to go through the proxy.e.g: http://127.0.0.1:7897

**Comment by ydong08** [comment]
@jm-observer Thanks,it works now!
