### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zhangfq-chemistry** [lapce/lapce#3423]
## Lapce Version 
0.4.1

## System information
Ubuntu 22

error[E0658]: use of unstable library feature 'lazy_cell'
 --> /home/zhangfq/.cargo/git/checkouts/floem-69eea0a757d1e3ee/a207ef4/renderer/src/text/layout.rs:1:23
  |
1 | use std::{ops::Range, sync::LazyLock};
  |                       ^^^^^^^^^^^^^^

**Comment by jm-observer** [comment]
try this: `cargo run --profile fastdev --bin lapce `

**Comment by panekj** [comment]
Duplicate of https://github.com/lapce/floem/issues/543

You need to use Rust 1.80 to compile
