### ISSUE TITLE
Crashed right after installing.

### ISSUE THREAD

**Issue by mukul98s** [lapce/lapce#343]
Steps to Reproduce
1. Install lapce
2. Open Lapce

After these steps its keep crashing. I tried to re-install but no change. 

System Details: 
1. Windows 10 Home
2. amd processor

**Comment by bugadani** [comment]
Which AMD processor, exactly?

**Comment by bugadani** [comment]
@mukul98s I wonder if you can tell me more about this crash. If you start lapce from command line, do you get any error messages? You can try and download the portable version so it's easier to find the exe.

**Comment by kymowang** [comment]
Starting lapce in windows console after installation, lapce crashed without any message even in event viewer.
Microsoft Windows [Version 10.0.19042.1586]

**Comment by mukul98s** [comment]
@bugadani I tried installing it using winget and it works fine.

**Comment by panekj** [comment]
Seems to be fixed
