### ISSUE TITLE
Out of Screen focus prevent command palette opening

### ISSUE THREAD

**Issue by nheuillet** [lapce/lapce#344]
## Issue

Trying to open the command palette does not work unless the focus is on an input field, that is:
- an actual opened file
- The commit message field of the source control menu
- The integrated terminal

In these fields, using the command CTRL+p works as intended. When the focused input field goes out of the screen, the command palette does not work anymore.

My very naive thinking would be that input Keyboard shortcuts handling is only enabled on text fields.

## Steps to reproduce

- Launch Lapce
- Notice opening the command palette works as the focus is on the integrated terminal
- select the source control menu. The focus moves to the commit message field
- select another menu, such as the plugin menu. The commit message field goes out of the screen but the focus is still on it; we cannot write anything anymore
- Opening the command palette does not work anymore

## Software information

- Os: ArchLinux, kernel 5.16.15-arch1-1
- DE: SwayWM, version 1.7, Wayland
- Lapce version: using latest commit 303b7e6acb2df479fce5d1d1598bae2d24664f67, release mode, but confirmed it's also a problem on latest release 0.0.12

**Comment by bugadani** [comment]
Please confirm that this simpler repro is the same issue:
 - select the source control panel so the commit message field is in focus
 - select the plugins panel
 - pressing `ctrl-p` does not open the command palette.

**Comment by nheuillet** [comment]
@bugadani I can confirm both repro are working. I can update my issue with this simpler steps if you prefer!

**Comment by bugadani** [comment]
Thanks, no need to update the issue, I was just curious if I understood the problem correctly.

**Comment by nheuillet** [comment]
Sounds good! Let me know if you need me to test anything.

**Comment by bugadani** [comment]
I would appreciate if you could give the linked [pull request](https://github.com/lapce/lapce/pull/346) a try, but only if you really want to. I'm fairly certain it fixes the issue, at least I wasn't able to break it during my short test.

**Comment by nheuillet** [comment]
I just compiled and tested your pull request. Although it fixes the issue, it introduces a regression on the palette close, where I cannot use Escape to close the command palette anymore.

**Comment by bugadani** [comment]
Right. It helps if I don't take events away from the children views. Should be better now, thanks for trying!

**Comment by nheuillet** [comment]
Everything seems to work great now! One small question though while you are fixing the palette: Coming from vscode I am very used to clicking out of the palette to make it close, and I was wondering if it was a planned feature?

**Comment by bugadani** [comment]
I don't know, I haven't been contributing for long at this point. I can only guess that it is.

**Comment by nheuillet** [comment]
Alright sounds good. Thank you!
