### ISSUE TITLE
Error from Rust Analyzer when closing the lapce window

### ISSUE THREAD

**Issue by PhilipDaniels** [lapce/lapce#349]
I am running KDE neon. Whenever I click the icon to close the window I get this printed in the terminal

```
[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence
client exited without proper shutdown sequence
```

I am running a clone of the latest code with `cargo run --bin lapce`

**Comment by Mercadud** [comment]
I believe that has something to do with the plugin itself (I just started looking at the code for this project) and maybe we should force a shutdown sequence for the plugins?

**Comment by MinusGix** [comment]
I imagine we're intended to send https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#shutdown (or probably the exit command right after it) before completely shutting down so that RA can do whatever it needs to do (cleaning up lock files?) on exit.

**Comment by panekj** [comment]
This was fixed unfortunately I'm not sure where/when because of plugin API refactor so it's not easy to `blame` it
