### ISSUE TITLE
Make line numbering scheme user-selectable

### ISSUE THREAD

**Issue by eutampieri** [lapce/lapce#35]
![image](https://user-images.githubusercontent.com/10284268/146156185-987a6a6a-9b9d-4fe3-b2a8-94137786e44a.png)

**Comment by dzhou121** [comment]
Can you try the latest release? https://github.com/lapce/lapce/releases/tag/v0.0.4

**Comment by eutampieri** [comment]
WiIl do

**Comment by HTG-YT** [comment]
Isn't that Vim line numbers, with `number` and `relativenumber` or something 🤔🤔🤔

**Comment by eutampieri** [comment]
Yes, I think you’re right… it’d definitely be nice to have the more normal option as default

**Comment by bugadani** [comment]
Hi and thank you for reporting this issue!

I have taken the liberty to edit the title, to better describe what I think you are describing. A setting to configure this would indeed be nice.
