### ISSUE TITLE
illegal hardware instruction(core dumped) ./lapce

### ISSUE THREAD

**Issue by DevER-M** [lapce/lapce#352]
specs:
```
OS: Ubuntu 21.10 x86_64 
Host: Dell System Inspiron N411Z 
Kernel: 5.13.0-39-generic 
Uptime: 2 hours, 36 mins 
Packages: 2246 (dpkg), 5 (flatpak), 17 (snap)
Shell: zsh 5.8 
Resolution: 1366x768 
DE: GNOME 
WM: Mutter 
WM Theme: HighContrast 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i3-2350M (4) @ 2.300GHz 
GPU: Intel 2nd Generation Core Processor Family 
Memory: 1116MiB / 3811MiB 
```
so when i run lapce(./lapce)
the app opens and closes immediately and this is the error i get:
![image](https://user-images.githubusercontent.com/78902540/161417399-67f013db-711d-46fd-b73a-d041aee0b4d8.png)
can anyone please help me how to fix this problem  
i also built the binary locally

thanks

**Comment by bugadani** [comment]
Hi and thanks for reporting!

We are seeing similar issues on older hardware and we are working to fix these.

Unfortunately, I don't have a workaround for you at this moment.

**Comment by DevER-M** [comment]
oh, np i will wait till this problem gets fixed :)

**Comment by bugadani** [comment]
Thanks! Just for reference, I'm linking #70 to this because it seems similar.

**Comment by DevER-M** [comment]
@bugadani now i use arch and i installed lapce and it works!!!!!!
