### ISSUE TITLE
Windows Terminal opens when launching Lapce

### ISSUE THREAD

**Issue by heksesang** [lapce/lapce#3571]
## Lapce Version

0.4.2

## System information

Windows 11 23H2

## Describe the bug

Windows Terminal is launched every time I launch Lapce:

1. I open Lapce through the start menu.
2. Windows Terminal launches.
3. It contains a tab with what looks like the Windows Powershell icon, and it closes almost immediately.
4. Windows Terminal is left open with a tab from my default Git Bash shell.
5. Lapce launches

## Additional information

I have seen similar behaviour with flashing Windows Terminal when using the terminal in Zed on Windows, so I'd put my money on it being alacritty-related. But this is more or less just a guess.

**Comment by cedric780** [comment]
Reproduced this with Lapce 0.4.2 installed via [Scoop](https://scoop.sh/) on Windows 10 22H2 : two terminals open and both stay open .
I have to close them manually.

**Comment by Long0x0** [comment]
Adding the `CREATE_NO_WINDOW` flag should help.
https://github.com/lapce/lapce/blob/3a40e6b729530ac176b55b426715dacc22f1c791/lapce-app/src/app.rs#L3994-L4003
https://github.com/lapce/lapce/blob/3a40e6b729530ac176b55b426715dacc22f1c791/lapce-app/src/app.rs#L3706-L3707

But I don't quite understand why we need to load envs from the shell?
