### ISSUE TITLE
`lapce-data` requires code related to icons

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#359]
cc https://github.com/lapce/lapce/pull/357

Icon related code really should belong in the `ui` crate, in my opinion.

**Comment by PhilipDaniels** [comment]
This comes down to this function, which is only used in one place and is trivial to remove

https://github.com/lapce/lapce/blob/202955c823023b7414fd5ed3249ff39fbc6029bf/lapce-data/src/data.rs#L329-L331

and this one

https://github.com/lapce/lapce/blob/202955c823023b7414fd5ed3249ff39fbc6029bf/lapce-data/src/palette.rs#L228-L235

which is also only used in one place (palette.rs in the UI crate) but might be more work to move out. I will try it and see.
