### ISSUE TITLE
Rust Nightly doesn't compile

### ISSUE THREAD

**Issue by jim4067** [lapce/lapce#361]
I tried compiling with the nightly channel of Rust and couldn't get it to build.

Maybe I missed it, but you could add a suggestion for folks building to use the stable channel when building.

**Comment by bugadani** [comment]
Hi! Could you tell us more about your issue? What error messages does the compiler give you? What version of the compiler are you using?

You can switch to stable channel by `rustup default stable` globally, or I believe `rustup override set stable` for a single folder. Please consult rustup's documentation on this (https://rust-lang.github.io/rustup/overrides.html).

**Comment by jim4067** [comment]
Yea Sure. Sorry for the vague Issues. 

this is the version of nightly I am using `nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.60.0-nightly (89b9f7b28 2022-01-10)`

This is a screenshot of the error. I googled it and found a PR that had fixed it. Maybe if I update to `1.61.0` it will work.
 
![errorscreenshot](https://user-images.githubusercontent.com/30603522/161444228-41fe4d51-2d02-4f92-92fa-390cce16569a.jpg)

**Comment by bugadani** [comment]
Thanks for the extra info! May I point out that you are using an almost 3 months old developer version of rustc that is considered very much unstable? :) This is a rustc issue, not a Lapce one, likely related to incremental compilation, or cranelift. I hope you will have a better experience after upgrading, but make sure to let us know if not!

**Comment by jim4067** [comment]
thanks. I haven't been actively using Rust in the last few months and that must be the reason. I switched to the stable version and it compiled without any errors.

**Comment by jim4067** [comment]
thanks. I haven't been actively using Rust in the last few months and that must be the reason. I switched to the stable version and it compiled without any errors.

**Comment by bugadani** [comment]
Glad to hear! I would actually encourage you to occasionally try the nightlies as well, as they may have some advantages when they work, which is surprisingly often. Just make sure to keep it up to date :)
