### ISSUE TITLE
Suggestion and Question.

### ISSUE THREAD

**Issue by jim4067** [lapce/lapce#362]
Also, another suggestion. I use Deepin Linux which currently uses Debian 10, which does not get updated software as much. I tried using the binaries from the download page but I assume they used a recent version of GCC, so I couldn't get them to work. I'd be happy to share the one binaries I just compiled which should work for any Debian 10 based distro.

Also, I can't get lapce to open a folder I am getting this alert. Is there a dev package I am supposed to install, that is not listed in the README?

![Screenshot_20220403224218](https://user-images.githubusercontent.com/30603522/161445273-f7b105a2-f6e9-4313-ab21-f72f6b0b3869.png)

Also not shown clearly in the screenshot above, but the text in the editor appears smudged.

**Comment by bugadani** [comment]
We could really do better on the documentation side, that's true.

The tiny file dialogs warning is interesting, I'm not sure we have seen it yet. To be fair, it at least seems to list what it needs :)

**Comment by jim4067** [comment]
yea, it does. I just did not expect it.

**Comment by ghishadow** [comment]
last time i tried Deepin used to heavily patch Gtk, maybe tiny file dialogs doesn't handle that case, will try later in VM.
try installing `zenity` and using that

**Comment by jim4067** [comment]
thanks @ghishadow . I installed kdialog and it worked. Will definitely try `zenity` later.

**Comment by ghishadow** [comment]
if `kdialog` works, then u don't need zenity (it was minimal dialog opener I can think of), I'm glad it worked out

**Comment by ghishadow** [comment]
this issue can be closed I think
