### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by divee789** [lapce/lapce#374]
Are there any plans to support typescript ?

**Comment by bugadani** [comment]
Hi!

Lapce should already have typescript syntax highlighting. Lapce can also support [TypeScript Language Server](https://github.com/typescript-language-server/typescript-language-server) in principle, but it's not done currently. We are still working on the basics and wider language support should come at a later stage, I believe.

Having said that, contributions to enable LSP support for various languages are welcome!

**Comment by ash-hashtag** [comment]
How to setup typescript?

**Comment by trsh** [comment]
Typescript is a must be :P

**Comment by panekj** [comment]
There is already a typescript plugin https://github.com/panekj/lapce-typescript/tree/wip but it currently doesn't work

**Comment by ghishadow** [comment]
typescript lsp is working for me for sometime. Thanks to @panekj , does this issue require anything else ?
<img width="779" alt="tscompeletion" src="https://user-images.githubusercontent.com/9583775/194459675-0bce1c36-32d0-443d-9e50-d9dbcf68daa4.png">

**Comment by panekj** [comment]
It was fixed via #1263 (probably)
