### ISSUE TITLE
Cursor jumps 2 lines

### ISSUE THREAD

**Issue by bruno-anjos** [lapce/lapce#38]
When I go up or down with the arrow keys it jumps 2 lines always. I copied the `defaults/keymaps-macos.toml` to `~/Library/Application Support/Lapce/`and renamed it `keymaps.toml`. Same thing with `defaults/settings.toml`.

Version 0.0.4
macOS 12.1

**Comment by rbran** [comment]
I also had this problem, this is a bug on lapce that didn't overwrite the default config with the user config.

If a config is on `defaults/keymaps-macos.toml` and `keymaps.toml` it will be duplicated.

For now, you remove the config from `keymaps.toml` all config that is also present on `defaults/keymaps-macos.toml` .

**Comment by dzhou121** [comment]
Fixed by b2d4e92543233c0c1ae85f545f02f648a361dafb

**Comment by bugadani** [comment]
Hi and thank you for reporting this issue! I'm closing this as fixed, but feel free to reopen if you you experience this again! Thank you!
