### ISSUE TITLE
Open menu does not close when clicking outside

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#391]
Steps to reproduce:
 - click on a menu (the current workspace, or the cloud icon)
 - try closing it by clicking outside.

The menu closes when another menu is opened or Esc is pressed, but not by clicking outside the menu area.

**Comment by Domerpig** [comment]
I don't have this issue anymore in v0.2.0.
Maybe it has been fixed by other changes.

**Comment by bugadani** [comment]
Forgot about this, thanks for the reminder. Will test later
