### ISSUE TITLE
Blocky noise on macOS in fullscreen mode

### ISSUE THREAD

**Issue by BlackGoku36** [lapce/lapce#393]
- Blocky noise like this appear when application is in fullscreen mode and mouse is moved or something is typed:
![IMG_0847 Large](https://user-images.githubusercontent.com/36535717/162371538-56e64b76-d3b4-485f-9e8e-747d8791c078.png).
- There is lag when changing between windowed and fullscreen mode.
- Windowed appear normal.
- Appear normal in screenshot (in fullscreen mode).

<img width="246" alt="Screenshot 2022-04-08 at 11 17 26 AM" src="https://user-images.githubusercontent.com/36535717/162372596-d9aa58ac-686e-4abc-b24a-cbc1fd91ee50.png">

**Comment by panekj** [comment]
Closing as we switched to OpenGL which should fix the issue
