### ISSUE TITLE
Crashes on macOS upon undoing (Cmd+Z)

### ISSUE THREAD

**Issue by BlackGoku36** [lapce/lapce#394]
Crashes on macOS when Cmd+z is pressed after typing.
Here is what I get when I start it from terminal
```
thread 'main' panicked at 'byte index 136 is out of bounds of `root=true
[**.zig]
end_of_line=lf
[**]
indent_style=space
indent_size=4
trim_trailing_whitespace=true
insert_final_newline=true



`', /Users/runner/.cargo/git/checkouts/xi-editor-32bce836970a2e41/5578c72/rust/rope/src/rope.rs:663:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

![](https://user-images.githubusercontent.com/36535717/162372596-d9aa58ac-686e-4abc-b24a-cbc1fd91ee50.png)

**Comment by bugadani** [comment]
I'm hoping this is the same as #376 but I can't be sure. Thanks for reporting!

**Comment by BlackGoku36** [comment]
Yeah they are same I think, both give same stack backtrace and error.
