### ISSUE TITLE
Readme readability additions

### ISSUE THREAD

**Issue by kcoderhtml** [lapce/lapce#401]
Added some more parity with the website and some changes to make it easier to read.
Pull request #402

**Comment by bugadani** [comment]
Hi! We welcome all changes, but there's really no need to open an issue if you are also submitting a pull request :)

**Comment by kcoderhtml** [comment]
I'll remember that in the future thanks! I was just following the contributor guidelines which say to open an issue.

**Comment by bugadani** [comment]
Oh, right, good point.
