### ISSUE TITLE
Terminal doesn't unfocus on Ctrl+`

### ISSUE THREAD

**Issue by dakata1337** [lapce/lapce#403]
Terminal doesn't unfocus when Ctrl+` is pressed.

This part of the code is called twice for some reason (this only happens when the terminal panel is focused).
https://github.com/lapce/lapce/blob/38f1142aed4fe884dbf15b7a950a32114b36b7e1/lapce-data/src/data.rs#L1329-L1331

The first time its called `should_hide` is True and `self.hide_panel(ctx, kind);` is called to hide the panel.
The second time `should_hide` is False because we already hid the panel and `self.show_panel(ctx, kind);` is called.
https://github.com/lapce/lapce/blob/38f1142aed4fe884dbf15b7a950a32114b36b7e1/lapce-data/src/data.rs#L1575-L1591

Also  what exactly is the difference between `ToggleTerminalVisual` and `ToggleTerminalFocus`?

**Comment by bugadani** [comment]
The difference is: if you toggle something using `*Focused`, the first call will focus on the panel, even if it's open. If you toggle using `*Visual`, the first call will close the panel if it's already open.
