### ISSUE TITLE
Screen is white if not in a spesific size 

### ISSUE THREAD

**Issue by potofcoding** [lapce/lapce#406]
the screen is white unless i resize it so a smaller size 
![image](https://user-images.githubusercontent.com/100384167/162588922-32f10d8d-ed3f-4627-b322-3166426c2f26.png)
**if i scale it more it breaks** 
![image](https://user-images.githubusercontent.com/100384167/162588942-0309d180-1347-4dca-873e-1f498edd367a.png)
i am running manjaro xfce and i3 both have the same problem **i think this might be because if my screen being 1366 x 768** i did compile it the same thing happens
my pc specs are
![image](https://user-images.githubusercontent.com/100384167/162589108-8792944b-0e08-48cf-97b5-6836047c44db.png)

**Comment by MordragT** [comment]
I have a 2k Monitor and it happens to me aswell

**Comment by bugadani** [comment]
Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

**Comment by potofcoding** [comment]
works amazingly sorry for taking long
