### ISSUE TITLE
Double click on title bar not maximizing/restoring window size on macos

### ISSUE THREAD

**Issue by BenJeau** [lapce/lapce#407]
Love the editor, just a small thing I noticed. On macos, the way to toggle your window to take the whole screen (without going fullscreen or manually resizing the window) is to double click on the window title bar.

Lapce does not maximize/restore window size when double clicking the header.

https://user-images.githubusercontent.com/22248828/162597141-6ed7d789-79d6-4561-a192-78426d5db15b.mov

**Comment by BenJeau** [comment]
I thought this was maybe a limitation on the UI framework Lapce is using, but I just ran some examples from druid and the double clicking behaviour is working as expected. I'm assuming the problem has been introduced because Lapse uses a custom title bar?

**Comment by bugadani** [comment]
Thanks for reporting! I'm marking this as macos-specific, because in Windows Lapce seems to use the OS's title bar.

**Comment by panekj** [comment]
Not sure when this was fixed but it is fixed

**Comment by BenJeau** [comment]
It seems to be fixed for me too
