### ISSUE TITLE
UI elements receive events when Settings is open

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#411]
https://user-images.githubusercontent.com/977627/162638821-0f8d47a9-196d-44d8-b4a2-1f4c7bf2da90.mp4

**Comment by Liberatys** [comment]
@bugadani I'd be happy to work on this :D

**Comment by bugadani** [comment]
Great, thanks! I'll assign you to the issue, then

**Comment by dzhou121** [comment]
This should be fixed now by the latest v0.1.0 release.
