### ISSUE TITLE
ssh entry field (standard) keyboard shortcuts don't work

### ISSUE THREAD

**Issue by clach04** [lapce/lapce#415]
Windows (with https://github.com/lapce/lapce/releases/tag/v0.0.12 portable version), when clicking on ssh button and then typing in host details, the standard Windows/GUI editing key-combos do not work:

* CTRL-a - does not select any text
* CTRL-insert (copy/paste) does not work
* CTRL-V (copy/paste) does not work
* cursorkeys does not navigate
* SHIFT-cursorkeys does not select
* mouse can not move cursor around

**Comment by dzhou121** [comment]
This should be fixed now by the latest v0.1.0 release.

**Comment by panekj** [comment]
Fixed
