### ISSUE TITLE
Feature request: handle temp buffers like Notepad++

### ISSUE THREAD

**Issue by PhilipDaniels** [lapce/lapce#447]
Notepad++ has a great feature that I've often wanted in other editors.

In brief, you can create a new buffer, type text in, and **not save it**, yet if you close Notepad++ and reopen it later, the buffer will still be there. Obviously the buffer gets written to disk in a "scratch area" and reloaded when you restart Notepad++. This behaviour will continue until you either close the tab (at which point the file is permanently deleted) or until you Save the buffer, at which point you will be prompted for a real filename to save the buffer in.

This produces a really nice workflow for temporary notes, or things which you think you might need again later but can't be bothered to think of a good name for yet. In particular it eliminates the annoying "Do you want to save this file?" dialog dance that occurs when you try to quit in other editors while you have scratch notes.

**Comment by dzhou121** [comment]
Can you try the latest v0.1.0

**Comment by PhilipDaniels** [comment]
I built from master. 

At first I thought it was not working, I tried creating a few temp files and quitting (via the Window Manager since there doesn't appear to be any QUIT or EXIT command callable from the command palette) and they didn´t appear to be persisted (or restored). However, after doing this several times the Untitled files DO appear to be persisting as I expect. So it seems to be almost working, but I suspect there is a bug somewhere. Unfortunately I can no longer reproduce it :-(

Also, a suggestion: can we name the new files 'New1', 'New2', 'New3' etc.? so that they are distinct names. I'd be happy to write a PR for that.

**Comment by PhilipDaniels** [comment]
Added a new issue #556 which relates to this functionality. @dzhou121 I don't know if it is related to the bug you mentioned.

Do you think we should close this issue and open individual bugs?

**Comment by dzhou121** [comment]
>>Do you think we should close this issue and open individual bugs?

Yes please

**Comment by PhilipDaniels** [comment]
Broke out separate issues for the comments in this one. Closing since the original feature request is now implemented.
