### ISSUE TITLE
: keyboard shortcut not working on linux

### ISSUE THREAD

**Issue by vincens2005** [lapce/lapce#45]
I was able to compile and run Lapce on Garuda linux, but when running it I press `:` to list commands and nothing happens.
The terminal and git commit editor work fine

**Comment by dzhou121** [comment]
@vincens2005 Can you please try the latest master commit 28575f9b40e146aa00f57c720cc7d1dbef99e230

**Comment by vincens2005** [comment]
I still have the same issue

**Comment by bugadani** [comment]
Hi and thank you for reporting this issue!

@vincens2005 could you please see if you still have this issue?
