### ISSUE TITLE
Drawing text only paints bounding boxes

### ISSUE THREAD

**Issue by zhaojiangbin** [lapce/lapce#450]
Since this commit 4abb0faf0a0b8eae1919d8f34ac92643f3de35bc that switched to opengl backend.

Tested the debug build. Didn't have time for release build.

It compiles but almost all text become "blocks" in the UI, like below:

<img width="979" alt="Screen Shot 2022-04-22 at 15 23 23" src="https://user-images.githubusercontent.com/4935788/164809718-ca6b6c84-1ee8-4fc8-925a-a68266a50a61.png">

The machine info:

<img width="528" alt="Screen Shot 2022-04-22 at 15 26 47" src="https://user-images.githubusercontent.com/4935788/164809823-6e56dfa5-3c9a-4a84-ba21-5d1483b9ae35.png">

**Comment by zhaojiangbin** [comment]
@bugadani, @dzhou121, Can we disable opengl in master until it's properly fixed? Or even if it is only disabled for macOS for now? 

With this change, debug build on macOS works again:

```diff
diff --git a/lapce-data/Cargo.toml b/lapce-data/Cargo.toml
index 6c5d861..b4fdaa0 100644
--- a/lapce-data/Cargo.toml
+++ b/lapce-data/Cargo.toml
@@ -47,7 +47,7 @@ xi-unicode = "0.3.0"
 fuzzy-matcher = "0.3.7"
 uuid = { version = "0.8.2", features = ["v4"] }
 lsp-types = { version = "0.89.2", features = ["proposed"] }
-druid = { git = "https://github.com/lapce/druid", branch = "opengl", features = [ "svg", "im", "serde", ] }
+druid = { git = "https://github.com/lapce/druid", features = [ "svg", "im", "serde", ] }
 # druid = { path = "../../druid/druid", features = ["svg", "im" , "serde"] }
 toml = { version = "0.5.8", features = ["preserve_order"] }
 structdesc = { git = "https://github.com/lapce/structdesc" }
diff --git a/lapce-ui/Cargo.toml b/lapce-ui/Cargo.toml
index cfed13b..3a26772 100644
--- a/lapce-ui/Cargo.toml
+++ b/lapce-ui/Cargo.toml
@@ -43,7 +43,7 @@ xi-rope = { git = "https://github.com/lapce/xi-editor", features = ["serde"] }
 xi-unicode = "0.3.0"
 fuzzy-matcher = "0.3.7"
 lsp-types = { version = "0.89.2", features = ["proposed"] }
-druid = { git = "https://github.com/lapce/druid", branch = "opengl", features = [ "svg", "im", "serde", ] }
+druid = { git = "https://github.com/lapce/druid", features = [ "svg", "im", "serde", ] }
 # druid = { path = "../../druid/druid", features = ["svg", "im" , "serde"] }
 toml = { version = "0.5.8", features = ["preserve_order"] }
 structdesc = { git = "https://github.com/lapce/structdesc" }
```

I cannot figure out a way to disable opengl only for `target_os = "macos"`. The following change does not work:

```diff
diff --git a/lapce-data/Cargo.toml b/lapce-data/Cargo.toml
index b4fdaa0..a49b6e6 100644
--- a/lapce-data/Cargo.toml
+++ b/lapce-data/Cargo.toml
@@ -47,7 +47,6 @@ xi-unicode = "0.3.0"
 fuzzy-matcher = "0.3.7"
 uuid = { version = "0.8.2", features = ["v4"] }
 lsp-types = { version = "0.89.2", features = ["proposed"] }
-druid = { git = "https://github.com/lapce/druid", features = [ "svg", "im", "serde", ] }
 # druid = { path = "../../druid/druid", features = ["svg", "im" , "serde"] }
 toml = { version = "0.5.8", features = ["preserve_order"] }
 structdesc = { git = "https://github.com/lapce/structdesc" }
@@ -57,6 +56,12 @@ lapce-rpc = { path = "../lapce-rpc" }
 lapce-proxy = { path = "../lapce-proxy" }
 bytemuck = "1.8.0"

+[target.'cfg(target_os = "macos")'.dependencies]
+druid = { git = "https://github.com/lapce/druid", features = [ "svg", "im", "serde", ] }
+
+[target.'cfg(not(target_os = "macos"))'.dependencies]
+druid = { git = "https://github.com/lapce/druid", branch = "opengl", features = [ "svg", "im", "serde", ] }
+
 [build-dependencies]
 cc = "1"
 anyhow = "1.0.32"
diff --git a/lapce-ui/Cargo.toml b/lapce-ui/Cargo.toml
index 3a26772..605f580 100644
--- a/lapce-ui/Cargo.toml
+++ b/lapce-ui/Cargo.toml
@@ -43,13 +43,18 @@ xi-rope = { git = "https://github.com/lapce/xi-editor", features = ["serde"] }
 xi-unicode = "0.3.0"
 fuzzy-matcher = "0.3.7"
 lsp-types = { version = "0.89.2", features = ["proposed"] }
-druid = { git = "https://github.com/lapce/druid", features = [ "svg", "im", "serde", ] }
 # druid = { path = "../../druid/druid", features = ["svg", "im" , "serde"] }
 toml = { version = "0.5.8", features = ["preserve_order"] }
 structdesc = { git = "https://github.com/lapce/structdesc" }
 lapce-data = { path = "../lapce-data" }
 lapce-rpc = { path = "../lapce-rpc" }

+[target.'cfg(target_os = "macos")'.dependencies]
+druid = { git = "https://github.com/lapce/druid", features = [ "svg", "im", "serde", ] }
+
+[target.'cfg(not(target_os = "macos"))'.dependencies]
+druid = { git = "https://github.com/lapce/druid", branch = "opengl", features = [ "svg", "im", "serde", ] }
+
 [build-dependencies]
 cc = "1"
 anyhow = "1.0.32"
```

```
$ cargo b
error: failed to load manifest for workspace member `/Users/jzhao/rust/lapce/lapce-ui`

Caused by:
  failed to parse manifest at `/Users/jzhao/rust/lapce/lapce-ui/Cargo.toml`

Caused by:
  Dependency 'druid' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.
```

**Comment by bugadani** [comment]
I think it's a reasonable proposal, given how opengl looks at the moment. Opengl development could happen on a different thread and be merged once it's ready, without blocking potential contributions. And if someone has more trouble with wgpu, they can base their pull requests on top of the opengl branch for the time being, for development. I expect most PRs submitted that way could just as easily be rebased on top on `master` instead so I don't expect the `opengl` branch to contain lots of unreleased features, splitting the development in two.

But this is not up to me :)

**Comment by bugadani** [comment]
@zhaojiangbin maybe you could import druid on macos using a different package name, but that would also need some code changes in lapce. I don't think a platform-dependent dependency is a good solution, especially since we have issues not just on macos.

**Comment by zhaojiangbin** [comment]
I agree. If it requires code change, it's not a good approach.

**Comment by uael** [comment]
It's not macos related, same on linux here

**Comment by univerz** [comment]
btw, someone made [this PR](https://github.com/lapce/piet-wgpu/pull/7) which should fix piet-wgpu on linux => another point for wgpu

**Comment by maxwell8888** [comment]
I have the same problem on Ubuntu

**Comment by dzhou121** [comment]
Can you please try to run this 

https://github.com/dfrg/swash_demo

to see if it has the same issue?

**Comment by maxwell8888** [comment]
> Can you please try to run this
> 
> https://github.com/dfrg/swash_demo
> 
> to see if it has the same issue?

The demo runs fine for me, no issue.

**Comment by peterwilfride** [comment]
So, was anyone able to solve the problem with the font?

**Comment by zhaojiangbin** [comment]
> Can you please try the latest master to see if it fixes it?

This commit eeee850dc6202d32f71983f69ca262d411c3781c? Unfortunately no, it's still the same for me on macOS.

**Comment by peterwilfride** [comment]
> Can you please try the latest master to see if it fixes it?

Yet the same problem.

**Comment by zhaojiangbin** [comment]
@dzhou121 the master branch at commit e8e4d7f80a3427720d5c2781bd9478ef000e85fc no longer compiles without the opengl branch, aka the workaround mentioned above. We really need to have this issue fixed.

I am getting this error:

```
error[E0599]: no method named `set_tab_width` found for struct `piet::text::WgpuTextLayoutBuilder` in the current scope
   --> lapce-data/src/document.rs:824:14
    |
824 |             .set_tab_width(tab_width);
    |              ^^^^^^^^^^^^^ method not found in `piet::text::WgpuTextLayoutBuilder`

error[E0599]: no method named `set_tab_width` found for struct `piet::text::WgpuTextLayoutBuilder` in the current scope
  --> lapce-data/src/history.rs:97:14
   |
97 |             .set_tab_width(tab_width);
   |              ^^^^^^^^^^^^^ method not found in `piet::text::WgpuTextLayoutBuilder`
```

**Comment by dzhou121** [comment]
Can you please try the latest master.

**Comment by maxwell8888** [comment]
works for me now

**Comment by zhaojiangbin** [comment]
Works for me on macOS. The text look more crispy, too.

**Comment by bugadani** [comment]
Thanks for the feedback. I assume this issue is fixed now, but please feel free to reopen if you experience it again!
