### ISSUE TITLE
Weird fonts

### ISSUE THREAD

**Issue by peterwilfride** [lapce/lapce#457]
![1651018245_grim](https://user-images.githubusercontent.com/41086317/165413054-545026f1-3ee6-48db-b188-6872c3dfba21.png)

I just clone and build, but when I start ./lapce from terminal the fonts are messed up.

system info:
OS: EndeavourOS Linux x86_64
WM: sway
Terminal: alacritty
Terminal Font: Fira Code
CPU: Intel i3-2310M (4) @ 2.100GHz
GPU: Intel 2nd Generation Core Processor Family

**Comment by zhaojiangbin** [comment]
See #450.

**Comment by bugadani** [comment]
Yes, this is a duplicate of #450
