### ISSUE TITLE
Using tabs instead of spaces cause miss-rendering of the line

### ISSUE THREAD

**Issue by uael** [lapce/lapce#458]
Using latest master ([95c4cf2](https://github.com/lapce/lapce/commit/95c4cf2d87083e348c0b621d0be0ea17f79ed703)), built from source, the tab character is miss-rendered:
 - added one tab at start of the line
 - cursor at the end of the line:
![Untitled](https://user-images.githubusercontent.com/22837557/165531111-8333b90c-733c-4dc8-b547-13f52f085b02.png)
(look like 4 spaces are added after the tab :thinking:)

**Comment by dzhou121** [comment]
This should be fixed now by the latest v0.1.0 release.
