### ISSUE TITLE
lapce pegs CPU at 100% after starting up

### ISSUE THREAD

**Issue by zhaojiangbin** [lapce/lapce#461]
1. Start top (or activity monitor in macOS)
2. Build this commit dd7d3b0a8be18d92e33fae1e79ad138753001372
3. Start lapce and wait for a few seconds
4. See lapce taking the top spot with CPU at 100%

**Comment by zhaojiangbin** [comment]
Tested the debug build on macOS, intel CPU.

**Comment by bugadani** [comment]
The debug build generates extremely inefficient code, so this isn't that surprising. Unless you experience this with release mode code, I wouldn't consider this an issue.

**Comment by bugadani** [comment]
Also, you can use the `fastdev` profile if you need to have better performance in debug. `cargo build --profile fastdev`

**Comment by zhaojiangbin** [comment]
> The debug build generates extremely inefficient code, so this isn't that surprising. Unless you experience this with release mode code, I wouldn't consider this an issue.

Sorry I wasn't clear. It was not CPU spikes.

When it was supposed to be idle (i.e. I wasn't doing anything with lapce after it started up), the process was keeping the CPUs at 100% according to top and activity monitor until I quit the program. The cooling fans of my laptop were running loudly because of this.

The previous commits do not have this problem.

**Comment by tobealive** [comment]
Same problem with cpu usage going crazy on linux

**Comment by dzhou121** [comment]
Can you please test the latest master? Previously Lapce scans all the font files at startup which now changed to be lazy loading.

**Comment by zhaojiangbin** [comment]
> Can you please test the latest master? Previously Lapce scans all the font files at startup which now changed to be lazy loading.

Yep it is fixed now.

**Comment by tobealive** [comment]
Look good to me too!

**Comment by bugadani** [comment]
Thanks for the feedback. I assume this issue is fixed now, but please feel free to reopen if you experience it again!
