### ISSUE TITLE
Problems with the lettering (maybe the font)

### ISSUE THREAD

**Issue by ismaelxyz** [lapce/lapce#463]
I compiled more than 600 crates, waited more than five hours, and then I got this.
Tell me what's going on, why are there no letters?
Note: I compiled this because the linux binary needs libc2.9 and I have libc2.8
![f](https://user-images.githubusercontent.com/50039280/165833277-2fdaffe8-4eb2-4ab7-9324-153f11d03184.png)

I'm on Deepin GNU/Linux 20.5 (Debian base).
I want to try this, how do I fix the problem?

**Comment by bugadani** [comment]
Duplicate of #450
