### ISSUE TITLE
Cannot link that fatal error LNK1120: 1 unresolved externals

### ISSUE THREAD

**Issue by easykoala** [lapce/lapce#464]
= note:    Creating library F:\rust\lapce-master\target\release\deps\lapce.lib and object F:\rust\lapce-master\target\release\deps\lapce.exp
          libtree_sitter_json-07069347542251e6.rlib(tree_sitter_json-07069347542251e6.tree_sitter_json.e2be5b27-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol tree_sitter_json referenced in function _ZN16tree_sitter_json8language17h5e9cd0f39d07829bE
          F:\rust\lapce-master\target\release\deps\lapce.exe : fatal error LNK1120: 1 unresolved externals

error: could not compile `lapce` due to previous error

evn: windows 10, rust 1.60

**Comment by bugadani** [comment]
Does this happen consistently, i.e. after running `cargo clean`?

**Comment by easykoala** [comment]
after cargo clean & cargo build --release, compling is ok, but when starting up:
![图片](https://user-images.githubusercontent.com/3862129/165908242-e18615b0-a579-4af2-9520-679139686594.png)
