### ISSUE TITLE
Wayland rendering issues

### ISSUE THREAD

**Issue by flukejones** [lapce/lapce#466]
Best described by screenshots:

![Screenshot from 2022-05-05 10-00-20](https://user-images.githubusercontent.com/2015870/166833084-e4a48c5b-48cb-412e-ae9f-f6bdad6c7ecf.png)

![Screenshot from 2022-05-05 10-01-20](https://user-images.githubusercontent.com/2015870/166833087-2279bbb7-21d4-43f5-a737-a0b86ab1bfc9.png)

You can see that what might be a shadow drop is actually rendering the entire background as transparent. This occurs when the settings box is open and the background elements are shadowed also (full window except settings become transparent).

There also appears to be text issue where setting a line height suitable for the main editor view is not suitable for the errors/info list view.

**Comment by flukejones** [comment]
Forcing under xwayland with `env -u WAYLAND_DISPLAY lapce` results in proper drawing as shown:

![Screenshot from 2022-05-05 10-10-01](https://user-images.githubusercontent.com/2015870/166833870-e9a85de7-4b38-4185-a1c5-e1264ff76ea2.png)

**Comment by dzhou121** [comment]
Can you please test the latest master

**Comment by flukejones** [comment]
Appears to be fixed in latest main build

**Comment by jirutka** [comment]
I’ve just installed Lapce 0.3.1 on Alpine Linux v3.19 with Sway/Wayland desktop and I see the same bug – border and shadows are transparent, seeing the desktop background through them.
