### ISSUE TITLE
ANSI not working on Windows

### ISSUE THREAD

**Issue by Osiris-Team** [lapce/lapce#47]
![image](https://user-images.githubusercontent.com/59899645/147958115-d86886c7-4964-4dc4-81bd-cfaef9f726c1.png)
Version 0.0.5

**Comment by Osiris-Team** [comment]
Also having that as an integrated terminal inside the UI would be like a hundred times nicer.

**Comment by bugadani** [comment]
Hi and thanks for reporting this issue!

I believe this issue has been resolved (or at least it's effects hidden), so I'm closing this issue.

 * Log messages are no longer printed to console
 * Lapce no longer opens a terminal window in the release builds
 * Lapce also has an integrated terminal, and I encourage you to try it!

Thank you!
