### ISSUE TITLE
Minimum system version?

### ISSUE THREAD

**Issue by doinkythederp** [lapce/lapce#480]
I use a pretty old computer and can't update past macOS High Sierra 10.13. Will Lapce work on my system? What are minimum supported OS versions?

**Comment by bugadani** [comment]
Unfortunaltey, you'll have to try and see, I think. I know for one that Windows 7 is not supported, but I don't know much else.

**Comment by gerardp** [comment]
I use macOS 10.14.6 and it works perfectly.

**Comment by daiyam** [comment]
It's working on macOS 10.11.

**Comment by panekj** [comment]
macOS target is 10.15

**Comment by daiyam** [comment]
I've just tested the v0.2.0 and I'm getting the error `Segmentation fault: 11` same as #889 or #929
