### ISSUE TITLE
Navigation problem in the in-built terminal 

### ISSUE THREAD

**Issue by VarLad** [lapce/lapce#495]
Fedora Linux 36, GNOME Wayland with AMD APU
Lapce version 0.1.0
Can't navigate the text in the terminal using the left and right keys.

**Comment by bugadani** [comment]
So this is an interesting one because navigation is otherwise implemented - we send ansi sequences to the terminal. I'm guessing your terminal expects something else. Does alacritty work on your OS?

**Comment by VarLad** [comment]
Yes
Also, left key types something like ]]1D when using from a REPL opened in the Lapce editor terminal

**Comment by bugadani** [comment]
The correct sequence Lapce sends to the terminal is `<ESC>[1D` I think, which is the ANSI escape sequence for "Cursor back". This is what [alacritty](https://github.com/alacritty/alacritty/blob/00383ae967fef6216396c3acaf96a7002b013298/alacritty/src/config/bindings.rs#L593) sends as well, I think.

**Comment by VarLad** [comment]
Ah yeah, sorry, it shows [1D when I press left key twice in a REPL
Also, Ctrl+Left/Right key works fine for navigating through words

**Comment by bugadani** [comment]
Alright thanks, that's helpful. I don't know when I'll get around to this, though.

**Comment by newcomb-luke** [comment]
![image](https://user-images.githubusercontent.com/16246849/168400229-70df27ea-8332-4dc6-afff-eb65e5177ce4.png)

It does the same thing for me as well. The only terminal I ever use is Alacritty, and I use the fish shell.

Interestingly, the `home` key doesn't work on mine.

Arch Linux, Lapce 0.1.0

**Comment by VarLad** [comment]
Same here.
Up and down keys and home key don't work either

**Comment by bbrabbitt** [comment]
Same for MacOS with zsh 5.8 and ohmyzsh installed with default settings. None of the cursor keys work and the shell doesn't show anything. When using bash up key will print A, down key will print B, and left and right key will print D and C. The only working shell that I use is nushell, which correctly responses to cursor keys.

**Comment by bugadani** [comment]
Thanks all, I appreciate the detective work. Looks like my assumptions were wrong here. I'm hoping I can repro this on ubuntu/zsh, but if not, I might ask some of you to help me, if you don't mind.

Anyway, I'll try a fix asap.
