### ISSUE TITLE
Program doesn't exit when clicking on the windows' close button

### ISSUE THREAD

**Issue by Osiris-Team** [lapce/lapce#50]
![image](https://user-images.githubusercontent.com/59899645/147965977-471312b9-61c6-483f-8a76-bc02d9137f42.png)
Version: 0.0.5

**Comment by rokonio** [comment]
Same happened on ubuntu 20.04

**Comment by ghishadow** [comment]
try latest update, it worked for me in Linux and Windows

**Comment by bugadani** [comment]
Thanks for reporting!

This has been reported for Windows before in #32 and I believe this issue to be fixed. Feel free to reopen this if you experience it again! Thanks!
