### ISSUE TITLE
Window border is white in dark mode on Fedora 36

### ISSUE THREAD

**Issue by rezbyte** [lapce/lapce#502]
The window appears to be in light mode despite having set GNOME to dark mode.
However, the actual interface is in dark mode.

Running the latest release on Fedora 36 (GNOME  42.1, Wayland).
![LapceWhiteWindowOnDarkMode](https://user-images.githubusercontent.com/48037381/168408881-b2c23b54-85bb-4232-8e54-3da8a5bb0217.png)

**Comment by flukejones** [comment]
This is something to do with no client-side decoration. It probably needs to request the DE to draw borders. But also I see SDL2 is able to draw a dark default border like this in Wayland.

**Comment by VarLad** [comment]
@rezbyte Fixed as of latest master

**Comment by rezbyte** [comment]
Good job guys!
I can confirm that it is fixed in master.
