### ISSUE TITLE
High CPU usage 

### ISSUE THREAD

**Issue by VideoCarp** [lapce/lapce#503]
When simply moving the cursor about Lapce, CPU usage increases dramatically.  In this case, it increased from a resting 0% to
~18% by just moving the cursor. In other cases, it got up to 30%. 
System:
Windows 10, 1.8 GHz CPU, 4 GB RAM, HDD

Reproducing this:
Just open up Task Manager or your OS' equivalent and do the same thing I did in the video

https://user-images.githubusercontent.com/66365570/168419440-fb8a3721-2bfe-4544-9fce-d123581efac8.mp4

.

**Comment by Titaniumtown** [comment]
On my laptop (Arch Linux), lapce sits between 0.1%-1.1% cpu usage. I have an i5-1135G7 and 32gb of ram (but lapce only uses 200mb of ram).

**Comment by VideoCarp** [comment]
> On my laptop (Arch Linux), lapce sits between 0.1%-1.1% cpu usage. I have an i5-1135G7 and 32gb of ram (but lapce only uses 200mb of ram).

Yeah, that makes sense. Your computer is *much* faster. And is this while you move the cursor about the screen?

**Comment by Titaniumtown** [comment]
> > On my laptop (Arch Linux), lapce sits between 0.1%-1.1% cpu usage. I have an i5-1135G7 and 32gb of ram (but lapce only uses 200mb of ram).
> 
> Yeah, that makes sense. Your computer is _much_ faster. And is this while you move the cursor about the screen?

Yes. CPU usage doesn't change at all when moving my cursor. maybe someone else with a lower-powered computer can chime in here. but I would've expected some sort of change in cpu usage even though my laptop is faster.

**Comment by harryhaaren** [comment]
Linux (ubuntu 21.10) laptop with i5-1035G1 cpu/gpu combo here, can confirm ~18% CPU usage, without any cursor movement required (it just always uses ~18%). This looks like a "doing-unnecessary redraws" bug, perhaps depending backend/driver?

This is kinda a big issue for laptop/battery usage, as it will eat batter redrawing all the time.

I tried the below diff as a hack to remove the cursor blinking, to check if the 500ms redraw was it, but didn't make any difference here..

```
diff --git a/lapce-ui/src/editor/view.rs b/lapce-ui/src/editor/view.rs
index cead2d3..717198c 100644
--- a/lapce-ui/src/editor/view.rs
+++ b/lapce-ui/src/editor/view.rs
@@ -543,10 +543,10 @@ impl Widget<LapceTabData> for LapceEditorView {
                 ctx.set_handled();
                 if data.focus == self.view_id {
                     ctx.request_paint();
-                    self.cursor_blink_timer =
-                        ctx.request_timer(Duration::from_millis(500), None);
+                    self.cursor_blink_timer = ctx.request_timer(Duration::from_secs(5), None);
                 } else {
-                    self.cursor_blink_timer = TimerToken::INVALID;
+                    //self.cursor_blink_timer = TimerToken::INVALID;
+                    self.cursor_blink_timer = ctx.request_timer(Duration::from_secs(5), None);
                 }
             }
             _ => (),
@@ -711,10 +711,10 @@ impl Widget<LapceTabData> for LapceEditorView {
             };
 
             if reset {
-                self.cursor_blink_timer =
-                    ctx.request_timer(Duration::from_millis(500), None);
-                *editor_data.editor.last_cursor_instant.borrow_mut() =
-                    Instant::now();
+                //self.cursor_blink_timer = TimerToken::INVALID;
+                self.cursor_blink_timer = ctx.request_timer(Duration::from_secs(5), None);
+                    //ctx.request_timer(Duration::from_millis(500), None);
+                *editor_data.editor.last_cursor_instant.borrow_mut() = Instant::now();
                 ctx.request_paint();
             }
         }
```

**Comment by happyme531** [comment]
Same issue(the performance is just.... even worse than vscode)
CPU: Ryzen 2300u 4x3.3GHz
![图片](https://user-images.githubusercontent.com/20812356/176110757-b6f04cac-8a6e-4cf3-8c49-76d9c467f753.png)

**Comment by NotAgentBilly** [comment]
Windows - Ryzen 5600 / 6700xt. Moving mouse around an empty workspace
![image](https://user-images.githubusercontent.com/82730686/188311908-ca155cdc-3d3d-4e4a-8c55-14206af495bf.png)

Settings tab open, no mouse movement
![image](https://user-images.githubusercontent.com/82730686/188311959-63b6d927-8268-41ee-b6d8-f7549238ba86.png)

**Comment by panekj** [comment]
Should be fixed after few fixes that were implemented (for example: https://github.com/lapce/lapce/pull/1072)
