### ISSUE TITLE
Lapce doesn't show new file

### ISSUE THREAD

**Issue by cseblog** [lapce/lapce#505]
Because I am newbie wit Rust here. 
I love Lapce because it is lightning fast but, i am confused now.
How to create new file for my project with Lapce?
When I do touch <new file> from the terminal, Lapce is not showing new created files at all.

Anyone can help, Am i missing anything here?

**Comment by bugadani** [comment]
Creating new files is not supported yet. It will be in the future, so I ask your patience here, Lapce is still in the early stages of development.
The second half is a duplicate of https://github.com/lapce/lapce/issues/304
