### ISSUE TITLE
Terminal arrow keys is not working with Jetbrains Mono font

### ISSUE THREAD

**Issue by cseblog** [lapce/lapce#510]
Hi there, 
I am trying to switch to Jetbrains Mono font, it is working with the editor but the arrow keys in the terminal is not working at all.
Anything that can fix this? Which is the default font for Lapce in MacOS

**Comment by bugadani** [comment]
Arrow key handling changed in https://github.com/lapce/lapce/pull/507 so if you're trying an older version, this might already be fixed.

Shy do you think the font you use changes behaviour?

**Comment by cseblog** [comment]
I am using the latest release.
Yes, i think so because if I switch to Arial font, the terminal arrow seems working anyway.

**Comment by bugadani** [comment]
That is very weird. We had issues on mac/linux zsh, that doesn't handle ANSI escape sequences in a general enough way (arrow keys are translated to sequences like `\x1b[D`), but that has absolutely no relation to the font used. Could you try Lapce compiled from the master branch please?

**Comment by cseblog** [comment]
I have just built it from the master branch. it is working fine now with Jetbrain Mono font. 
Last time, I downloaded last release, it was not working at all. Can close this issue any way.

**Comment by bugadani** [comment]
Great, thanks! Feel free to open another if you encounter other issues :)

**Comment by cseblog** [comment]
Thanks!
