### ISSUE TITLE
is the Zulip group intended to be invite-only, or is it a bug?

### ISSUE THREAD

**Issue by Not-a-web-Developer** [lapce/lapce#52]
the link to the zulip group says that the organisation requires an input, i've added a screenshot to show the issue:

![image](https://user-images.githubusercontent.com/47886897/148085463-69a7c8b0-f019-4f7a-a048-cc9b9495ddf7.png)

Is this intended behaviour, or is it something that needs to be fixed? being able to use something like zulip to coordinate in realtime would help a lot of people to contribute more easily, which is why i asked.

**Comment by dzhou121** [comment]
No, wasn't aware of this.

Should be fixed now.

**Comment by Not-a-web-Developer** [comment]
Thanks for fixing it! i'm closing the issue now.
