### ISSUE TITLE
Navigation bugs in the editor

### ISSUE THREAD

**Issue by VarLad** [lapce/lapce#521]
## Without modal mode

Holding the left, up and down arrow keys, they cursor doesn't keep in that direction beyond one unit. It works correctly for the right arrow key.

### Insert mode
Same problems as above

### Normal mode
Same as the above problem. Except for the right key this time, the cursor doesn't move the next line after reaching the end of line while holding the right key. 
In case of h, j, k and l keys for navigation, the h, j and l keys work as intended. k key suffers from the same problem, the cursor doesn't go up beyond one unit when holding the k key. h and l keys exhibit the problem of not changing lines when reaching the end of line while holding. (Maybe this behavior is intentional?)

Using Fedora Linux 36 Workstation (Wayland)
Lapce version 0.1.0

**Comment by dzhou121** [comment]
That's expected in normal mode. That's how it works in vim.

**Comment by VarLad** [comment]
Sorry, okay! I use Helix so I thought it does go into the next line! 
I'm closing the issue then :D
