### ISSUE TITLE
Plugin Request: Themes

### ISSUE THREAD

**Issue by VarLad** [lapce/lapce#523]
It would be nice if we could have a repo in https://github.com/lapce called lapce-themes
Users would submit their custom themes on that repo. 
 And a Themes plugin which would simply `git clone`(for first install) and `git pull`(on updates) on that repo. Also, all the themes from the repo would show up in the Command Palette or Core Settings (or we can just have a separate Themes section) 
 
Suggestion: I think the custom themes should always go into the .config/lapce/themes folder. 
We need a new folder for the Themes plugin. 
And if we have a section for it in Settings, we need to differentiate between the ones provided by the Themes plugin and custom ones (if names clash)
Probably append a (Custom) and (Plugin) in front of each theme name in Settings to differentiate

**Comment by MinusGix** [comment]
I think this could be potentially closed due to #600 adding the ability to have themes as plugins?

**Comment by VarLad** [comment]
This got resolved in a different way than proposed, but I like the present implementation too, hence closing this issue
