### ISSUE TITLE
Crashing when opening large json files.

### ISSUE THREAD

**Issue by swork1** [lapce/lapce#525]
Downloaded the .msi and opened a large json file (~5MB) and lapce crashed. Would be nice to be able to handle these bigger files.

**Comment by Titaniumtown** [comment]
Logs?

**Comment by swork1** [comment]
I looked in AppData/Roaming/Lapce/config for the logs. Nothing in there.

The application doesn't exactly crash. It just infinitely spins with the "Not responding" message.

**Comment by Titaniumtown** [comment]
No, like what is the output in your terminal.

**Comment by swork1** [comment]
> No, like what is the output in your terminal.

There is no output

**Comment by Titaniumtown** [comment]
> > No, like what is the output in your terminal.
> 
> There is no output

Can you use `gdb` and see what it says?

**Comment by swork1** [comment]
> > > No, like what is the output in your terminal.
> 
> > 
> 
> > There is no output
> 
> 
> 
> Can you use `gdb` and see what it says?

I'm not sure how to use `gdb`. Is there an easy way to run it

**Comment by Titaniumtown** [comment]
It's the `Gnu Project Debugger` I don't know how you would install it on windows.

**Comment by swork1** [comment]
> It's the `Gnu Project Debugger` I don't know how you would install it on windows.

Yea I'm not sure
