### ISSUE TITLE
Pressing cmd+arrows doesn't work

### ISSUE THREAD

**Issue by liorp** [lapce/lapce#529]
Hi there, 

Great project - really fast editor!
I do have a problem - I'm used to pressing cmd+arrows to go to the beginning and the end of a line, and it doesn't work in the editor.
I'm using macOS Monterey.

**Comment by dzhou121** [comment]
Thanks.

Looks they are not in the default key maps which will fixed.

For now, you can set the key binding yourself in settings. They are "line_end" and "line_start"

**Comment by panekj** [comment]
Keys are now bound by default
