### ISSUE TITLE
Keyboard Layouts that rely on deadkeys are not working properly

### ISSUE THREAD

**Issue by amonobe** [lapce/lapce#530]
If you try to use any Layout that does: 
' ` ' + ' a ' = ' à '
or
' ' ' + ' c ' = ' ç '

Lapce doesn't register the deadkey press.
I tried this on Linux (Manjaro KDE) and Windows 10 both show the same behavior.

A workaround for is to add a Layout with does not rely on deadkeys. In my case I switched from `US International alt. ` to  `US International`.

**Comment by amonobe** [comment]
It seems the issue is not for all Layouts with deadkeys rather it seems to be related to the layout available to my language (Brazilian Portuguese)

**Comment by julientaq** [comment]
I have the same issue running a qwerty-lafayette on OSX  Monterey (not m1)

I can’t really work with anything else as it’s really outside of what other layouts can bring.
