### ISSUE TITLE
Editor bug when i'm trying to get first line empty of main.rs

### ISSUE THREAD

**Issue by cseblog** [lapce/lapce#535]
When new main file is created, from first line, whenever i. enter to have new empty line, the main function's syntax will be broken automatically. 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/10300817/169676858-d5f816d6-774b-41de-a1b9-e1f6b4597ff5.png">

**Comment by informaticalex** [comment]
Yes, this is an irritating bug. Happens with modal editing (pressing `Shift-o` to insert new line above) and in non-modal editing (navigate to beginning of line and pressing `Enter`).

This bug occurs in _any_ open file. Not just `.rs` files.

**Comment by dzhou121** [comment]
Should be fixed by the latest release v0.1.2

**Comment by cseblog** [comment]
Thanks for fixing it.
