### ISSUE TITLE
namespaced features with the `dep:` prefix are only allowed on the nightly channel

### ISSUE THREAD

**Issue by kvark** [lapce/lapce#538]
Unable to build on macOS with Rust-1.59

```
kvark@mac lapce % cargo build --release
error: failed to load manifest for workspace member `/Users/kvark/Code/lapce/lapce-ui`

Caused by:
  failed to load manifest for dependency `lapce-core`

Caused by:
  failed to parse manifest at `/Users/kvark/Code/lapce/lapce-core/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
kvark@mac lapce % rustc --version      
rustc 1.59.0 (9d1b2106e 2022-02-23)
```

**Comment by dzhou121** [comment]
`dep:` should be available in Rust 1.60

**Comment by kvark** [comment]
I recommend the following:
  1. updating the [rust-version](https://github.com/lapce/lapce/blob/8d13b30ec6120db0436b56ac253668fa8408a761/Cargo.toml#L6) in the manifest
  2. making sure your CI always uses this rust version instead of the latest, to prevent further breakage

**Comment by panekj** [comment]
fixed in https://github.com/lapce/lapce/commit/ed55108bcd6ae6b7062c8b4dfee690729e2bc6fc
