### ISSUE TITLE
SCSS highlighting support

### ISSUE THREAD

**Issue by superlou** [lapce/lapce#540]
For web development, it would be great to have SCSS highlighting. I think VSCode is using https://github.com/atom/language-sass based on a comment [here](https://github.com/microsoft/vscode/issues/81038#issuecomment-532155268). That said, the Atom repo does not seem active. I'm not sure if https://github.com/serenadeai/tree-sitter-scss is better or if there is a more official grammar somewhere.

**Comment by bugadani** [comment]
Thanks, tracked in #272

I don't think VSCode uses tree-sitter so I added the second one to the list.
