### ISSUE TITLE
Ctrl-Arrow keys jumps too aggressively 

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#545]
![image](https://user-images.githubusercontent.com/13157904/169904010-061ec8b3-1142-4090-9872-7537d07477fe.png)
Then doing ctrl+right-arrow to skip over the 'word', 
![image](https://user-images.githubusercontent.com/13157904/169904063-ee906e81-60b8-45d8-b968-6adf39ee8301.png)

It ends up on the next line, rather than at the end of the word.

**Comment by informaticalex** [comment]
I haven't kept track of this, but it seems to be working now! 

Pressing `Ctrl-Right-Arrow` jumps to the start of the next word unless:
1. There are no more words and no more lines. In which case: _jump to end of the word._
2. There are no more words, and there is a blank line below. In which case: _jump to next line._

This is constent with In Vi/Vim/Neovim.

**Comment by MinusGix** [comment]
Ah, I see. The issue is a bit different than what I thought. It is mimicking Vim accurately, but not VSCode/Browsers/other editors that I've used and thus gotten used to.  
In VSCode, Ctrl+Right-Arrow usage goes:
`^impl Comp for Thing` -> `impl^ Comp for Thing` -> `impl Comp^ for Thing` -> `impl Comp for^ Thing` -> `impl Comp for Thing^` then to the next line.
While Vim's does:  
`^impl Comp for Thing` -> `impl ^Comp for Thing` -> `impl Comp ^for Thing` -> `impl Comp for ^Thing` -> next line
So, VSCode's behavior is closer to a  'jump to the end of the current or next word' while Vim's behavior is 'jump to the start of the next word'.  
So, I guess the issue is then more that I'd like an option to swap behavior since I find that behavior more intuitive since jumping to the end of a word is more common in my experience. (ex: backspacing it)

**Comment by dzhou121** [comment]
@MinusGix Can you try to bind it to word_end_forward to see if that's the behaviour in VSCode?

**Comment by MinusGix** [comment]
That appears to be basically the same as VSCode, the only difference is the behavior at the end of the line  
Ex:
```rust
// ignore invalid syntax
impl Comp for Thing
^ // vscode goes here after `Thing^`
impl^ Thing { // then to there
```
While Lapce jumps from `Thing^` to `impl^`, which is fine for me though is a bit different from VSCode.  
Thanks!
