### ISSUE TITLE
Add file/directory as arg for lapce

### ISSUE THREAD

**Issue by MrKomodoDragon** [lapce/lapce#546]
This would be helpful so that I don't have to click open folder within lapce, and can simply just type a file path and start editing. (E.g. `lapce ~/foo.rs` or `lapce ~/directory/foo`, etc.) I really look forward for this being implemented and could try my hand at making a PR for it, maybe.

**Comment by panekj** [comment]
fixed in https://github.com/lapce/lapce/pull/1003
