### ISSUE TITLE
Disambiguate files with the same name

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#551]
Currently, if opening two files with the same name (but obviously a different location) there is nothing to tell which one is which if you are not keeping track of their position.  
VSCode does this by adding part of their path to their titles, 
![image](https://user-images.githubusercontent.com/13157904/170444804-32064454-f90b-485d-ad3b-e334b8794979.png)

**Comment by aburd** [comment]
I'm guessing this eventually got solved by https://github.com/lapce/lapce/pull/1521 which is referenced in #557
