### ISSUE TITLE
ui/text: No text is showing inside the editor except for the terminal

### ISSUE THREAD

**Issue by seanmrnda** [lapce/lapce#562]
### Bug description:
![lapce-bug2 0](https://user-images.githubusercontent.com/45195351/170861219-fa8df265-50af-4337-b326-2a4cb7f486b9.png)

I encountered sluggish performance just by navigating throughout inside the editor. Text only shows on the terminal window.
The image above basically tells everything. I have raised this issue on lapce's discord server. I just wanted to raise a formal issue on the repository.

### Machine:
- OS: Arch Linux
- DE: Xfce4
- DM: Lightdm
- DS: Xorg
- CPU: I3 10th gen

**Comment by dzhou121** [comment]
Can I ask the name of your system font?

**Comment by schwrzstrbn** [comment]
> Can I ask the name of your system font?

does it have something to do with my system font? my system font is cantarell.

**Comment by panekj** [comment]
Fixed

**Comment by stickyburn** [comment]
Facing the same issue on arch linux, latest nightly.

`lapce-nightly-bin 20240120-1`
