### ISSUE TITLE
New contributor on-boarding documentation.

### ISSUE THREAD

**Issue by informaticalex** [lapce/lapce#563]
There is little/no documentation for new contributors. 

Examples of possible documentation:
- Block diagram of architecture (this could highlight thoughts in [why-lapce.md](https://github.com/lapce/lapce/blob/master/docs/why-lapce.md)) 
- Directions to important code-files
- List of names of maintainers/key-contributors
- etc.

There is a [contributing.md](https://github.com/lapce/lapce/blob/master/CONTRIBUTING.md) file, with a hyperlink from the readme. This could be a starting point to [flesh out](https://www.merriam-webster.com/dictionary/flesh%20out).

**I will work on this** as I'm exploring the codebase and getting up to speed, I'm opening this issue in case others wish to provide suggestions.

**Comment by informaticalex** [comment]
Noting as well, also need some getting-started docs for **plugin** development.

**Comment by panekj** [comment]
https://github.com/lapce/lapce/pull/2659
https://github.com/lapce/lapce/pull/2658
