### ISSUE TITLE
Add separate font settings for the terminal

### ISSUE THREAD

**Issue by PhilipDaniels** [lapce/lapce#569]
After the implementation of #240, proportional fonts seem to be working well for the main edit area.

However, since the same font setting is used for the terminal that still looks wrong. We need to have the ability to specify a separate font for the terminal area, probably with fallback to the main editor font if none is specified (most people won't bother with a separate font because they are not weird like me, wanting to program in proportional fonts :-)

**Comment by PhilipDaniels** [comment]
Claimed.

**Comment by dzhou121** [comment]
This is implemented in this branch https://github.com/lapce/lapce/tree/new_theme

**Comment by panekj** [comment]
This is fixed already
