### ISSUE TITLE
Weird font size when using Fira Code

### ISSUE THREAD

**Issue by williamd1k0** [lapce/lapce#575]
![image](https://user-images.githubusercontent.com/10428035/172039402-f266f9c5-448a-4f61-912d-8490bee323a5.png)
>Fira Code
***
![image](https://user-images.githubusercontent.com/10428035/172039468-e249ef00-e154-4cbc-81b3-0d9cf27e6280.png)
>Liberation Mono
***

System Info:
- Manjaro Linux 21.2.6
- GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
- Font version: community/ttf-fira-code 6.2-2

**Comment by platlas** [comment]
Same with SF Mono - but that one is .otf
(on macOs 12.4)

**Comment by panekj** [comment]
Should be fixed
