### ISSUE TITLE
Terminal panel position

### ISSUE THREAD

**Issue by mankinskin** [lapce/lapce#576]
I would like to be able to change the position of the terminal. I usually have the terminal on the right half of the screen to get more vertical space.

Additionally it would be great if there was a system to position any panels like the terminal, so the error and search view can also be repositioned like this.

Great editor!

**Comment by panekj** [comment]
This was implemented

**Comment by panekj** [comment]
You can drag the panel icon

**Comment by eldoy** [comment]
@panekj ok, thanks, that works. But multiple panes now split horizontally, is there any way of making them split vertically?
