### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by shemgp** [lapce/lapce#58]
```bash
cargo build --release
    Updating crates.io index
error: failed to select a version for the requirement `reqwest = "=0.11.8"`
candidate versions found which didn't match: 0.11.6, 0.11.5, 0.11.4, ...
location searched: crates.io index
```

**Comment by Relwi** [comment]
I can't build either, the first time I try to build with `cargo build --release` or `cargo run --bin lapce` I have this error: 
`The directory tree-sitter-go is empty, you probably need to use 'git submodule update --init --recursive'?`

So after I run the suggested command and try to build again, I have this one: `
error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/relwi/Documents/Projects/lapce/core/languages/tree-sitter-yaml/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wno-unused-but-set-variable" "-Wno-trigraphs" "-o" "/home/relwi/Documents/Projects/lapce/core/languages/tree-sitter-yaml/src/parser.o" "-c" "/home/relwi/Documents/Projects/lapce/core/languages/tree-sitter-yaml/src/parser.c" with args "c++" did not execute successfully (status code exit status: 1).`

**Comment by dzhou121** [comment]
@Relwi I've changed the way to use tree sitter. Can you try to build with latest?

**Comment by Relwi** [comment]
@dzhou121 yep! It is working now. Thank you!

**Comment by dzhou121** [comment]
@shemgp You would need to upgrade your Rust to at least v1.58.0

**Comment by Dengjianping** [comment]
The project has been migrated to rust 2021, so I think this filed `rust-version = 1.58' that can the version issue.
If @dzhou121 you think this is a workaround, can I submit a pr for it?
