### ISSUE TITLE
could not click anywhere in the window that is opening

### ISSUE THREAD

**Issue by emadbaqeri** [lapce/lapce#580]
I'm using macOS Monterey as my main env for development, I have downloaded the the .dmg file and install but I could not do anything in the window that is opening. This is the video that shows you exactly what I'm talking about.

https://user-images.githubusercontent.com/50639499/172068189-8ebae45b-f9ee-45f6-975b-93cdfaa66cc9.mov

.

**Comment by MinusGix** [comment]
If you launch Lapce from the command line does it work?

**Comment by emadbaqeri** [comment]
Hey @MinusGix, I can't run it from terminal.
Can you help me doing that?
It says:
```bash
zsh: command not found: lapce
```

**Comment by MinusGix** [comment]
I don't know the details of running it from the terminal, I'm primarily curious if it is the same as #578  since it also isn't rendering things right.

**Comment by zmb3** [comment]
To launch from the terminal you just use the full path of the lapce binary in the app package. Something like /Applications/Lapce.app/MacOS/lapce IIRC

**Comment by emadbaqeri** [comment]
thanks @zmb3, this worked for me.
```bash
/Applications/Lapce.app/Contents/MacOS/lapce
```
@MinusGix, as you have mentioned I have tried to run the app from terminal and it worked for me. Is there anyway to solve this problem?

**Comment by MinusGix** [comment]
At the moment no, but we'll look into it.  
Since this seems to be the same issue, we'll track the issue with #578, so I'd suggest subscribing to that one for any updates on it.
