### ISSUE TITLE
How to integrate with vim?

### ISSUE THREAD

**Issue by emadbaqeri** [lapce/lapce#583]
Hey folks, I'm a big fan of Vim and I love the vim key bindings. Is there any way to integrate with vim and use the keybindings?
Something like a plugin maybe

**Comment by panekj** [comment]
Vim keybinds are already integrated in lapce

**Comment by panekj** [comment]
![image](https://user-images.githubusercontent.com/50457605/172170648-1b1b36f8-303e-4990-be62-320871227d20.png)
![image](https://user-images.githubusercontent.com/50457605/172170673-15d4e308-7879-4b71-8111-e43bb92196e2.png)

or F1 > Enable Modal Editing
