### ISSUE TITLE
Some components is missing

### ISSUE THREAD

**Issue by LimingFang** [lapce/lapce#585]
Environment: M1Pro, macos 12.4
I have tried building from source or download `.dmg` directly.

When I open Lapce and try to install plugin(rust LSP), nothing is there..
<img width="408" alt="image" src="https://user-images.githubusercontent.com/28479651/172394235-31f6fdca-5334-430e-b401-70287202637c.png">

**Comment by dzhou121** [comment]
Can you access these two links fine?

https://lapce.github.io/plugins.json
https://raw.githubusercontent.com/lapce/lapce-rust/master/plugin.toml

**Comment by LimingFang** [comment]
Sure, I'm using Clash and I can open these two link.

**Comment by mrxiaozhuox** [comment]
I have the same problem.

**Comment by LimingFang** [comment]
what if i setup proxy in terminal and   launch Lapce in terminal. It also failed.

**Comment by LimingFang** [comment]
> Looks like the issue is that Lapce doesn't use proxy to do the http requests.

Don't you use VPN(clash)?

**Comment by LimingFang** [comment]
I'll test it.

**Comment by dzhou121** [comment]
Looks @mrxiaozhuox had good results with the PR. I've merged it to master now.

**Comment by LimingFang** [comment]
<img width="318" alt="image" src="https://user-images.githubusercontent.com/28479651/172604009-d7873972-6e64-420b-9dd6-833aeabec8ee.png">
 It works!

**Comment by mrxiaozhuox** [comment]
> <img alt="image" width="318" src="https://user-images.githubusercontent.com/28479651/172604009-d7873972-6e64-420b-9dd6-833aeabec8ee.png">
> 
> It works!

which branch you test ? main ?

**Comment by LimingFang** [comment]
> why I can't work on main branch ...

Master
