### ISSUE TITLE
Feature request: Un-indent a line

### ISSUE THREAD

**Issue by RigoLigoRLC** [lapce/lapce#589]
Copy pasting code often causes a messy indentation and in Kate you can Shift-Tab to reduce the indentation. But Lapce isn't showing me a similar option in the command palette, and I can't seem to find a combination key to trigger that too.

**Comment by dzhou121** [comment]
It's ```meta+[``` or macOS and ```ctrl+[``` for Windows and Linux. And you can change they keybinding as well. It's called ```outdent_line```

**Comment by panekj** [comment]
Perhaps it would be better if it was called `increase/decrease indentation`

**Comment by giox069** [comment]
it took me three days to discover that this option is called "outdent". I googled lapce unindent, untab, undo indent and many more but only now I discovered this post.
The `ctrl+[` key combination is very uncommon and uncomfortable:
**Uncommon**: most of other editors users Shift-Tab (kate, notepad++, geany, vscode...) so users expect to find Shift-Tab working. But it does not, and it's frustrating and a good reason to forget about Lapce forever. Somenone like me will insist in searching google and manual, but the "outdent" keyword really is not even considered when seraching.
**Unconfortable**: this keystrokes  `ctrl+[` requires two hands, so you have to remove one hand from the mouse. It's a waste of time when has to un-indent many pieces of code scrolling with the mouse, selecting text with mouse, and then... you need to remove your hand from the mouse to press the un-indent key. Repeat it many times. This hand-moving in and out from the mouse does not happen with Shift-Tab.
**Unconfortable 2**: Even worse: in some keyboard layout, for example Italian, you need to press three keys to unindent it: `Ctrl + AltGr + è` to get `Ctrl + [`. They are three keys with thwo hands. This is simply masochism.

Can we have `Shift-Tab` by default to Un-Indent (outdent) on lapce by default, without reconfiguring every and every client keybinding ?

**Comment by jossensei** [comment]
I totally agree with giox069 ! I use a french layout, Ctrl + AltGr + ( is an ergonomic nightmare.
Shift + Tab is also used by "Jump to prev snippet placeholder", but only "in_snippet", so I don't think that it collides.
The absence of Shift + Tab to Outdent was my first disappointment, and had to come here to find a solution (I didn't thought of the word "outdent" so couldn't find it in the keybindings settings).

**Comment by panekj** [comment]
vscode:
![image](https://user-images.githubusercontent.com/50457605/216469458-1d457eb5-d78a-4ec8-8360-353cd5bea163.png)

**Comment by hbina** [comment]
The only way to fix your woes is to have a community maintained keybindings and have the default of no keybindings at all.
