### ISSUE TITLE
Setting to disable scroll beyond last line

### ISSUE THREAD

**Issue by leighmcculloch** [lapce/lapce#592]
Lapce by default scrolls beyond the last line. Most IDEs have a setting for disabling this. It would be less jarring and make for a smoother user interface for some users who accidentally scroll past the last line frequently.

**Comment by mirchandani-mohnish** [comment]
I feel that Lapce already does this 
![image](https://user-images.githubusercontent.com/80059522/172999135-99a2508d-a51a-4f60-91d7-b2002962b55c.png)


Do you mean that one should not be able to scroll beyond line 176 in the above example?

**Comment by dzhou121** [comment]
It can be turned off now in the latest release v0.1.2

**Comment by Carol25170** [comment]
> It can be turned off now in the latest release v0.1.2
