### ISSUE TITLE
Certain UI elements like the "File Explorer" text overflow their parent element's area

### ISSUE THREAD

**Issue by aelobdog** [lapce/lapce#596]
As can be seen in the screenshot, the text "File Explorer" overflows the boundary of the side panel.  This is also observed in certain other places like the settings sidebar where the text "Terminal Settings" overflows its panel's boundary.

![bug_lapce](https://user-images.githubusercontent.com/33014264/172819497-f9c18229-ea85-40d6-a514-4f7cda616fbd.png)

**Comment by dzhou121** [comment]
Should be fixed by the latest release v0.1.2
