### ISSUE TITLE
noticed there are many warnings when building

### ISSUE THREAD

**Issue by LollipopFt** [lapce/lapce#60]
there are many warnings like ``this `Result` may be an `Err` variant, which should be handled``. can i propose running `cargo clippy` on the code to have better visuals on these?

**Comment by bravomikekilo** [comment]
I fix nearly all unused imports , and some unused variable warning in [#63 fix compiler warnings](https://github.com/lapce/lapce/pull/63)

**Comment by LollipopFt** [comment]
thank you!
