### ISSUE TITLE
Markdown Highlighting Broken

### ISSUE THREAD

**Issue by woojoo666** [lapce/lapce#605]
Markdown support seems to be broken. No syntax highlighting at all. Syntax highlighting for Javascript works fine though so this seems to be a markdown-specific issue.

Platform: Windows (portable version)
Version: 0.1.2

![lapce](https://user-images.githubusercontent.com/2776751/173232217-9e00286b-a9bc-4245-bc42-fd291292a36a.png)

**Comment by ghishadow** [comment]
Looks like `main` branch of https://github.com/MDeiml/tree-sitter-markdown no longer be actively maintained. It is switching to [split_parser branch](https://github.com/MDeiml/tree-sitter-markdown/tree/split_parser). here is example in neovim treesitter by author https://github.com/nvim-treesitter/nvim-treesitter/pull/3048.

**Comment by panekj** [comment]
Fixed in #957
