### ISSUE TITLE
Weird icon wrapping effect with golang and json

### ISSUE THREAD

**Issue by ReCore-sys** [lapce/lapce#606]
#### Issue description
When using both golang and json files in the same directory (not tested with other files) the golang icon is placed slightly too far to the right. It gets cropped and the part of the icon that gets cropped then appears on the left of a json icon. I noticed it when working on my own project so if it doesn't show up for any other folders, try cloning [This Repo](https://github.com/ReCore-sys/Octave) and opening it.

#### Steps to reproduce the issue

1.  Have both golang and json files in one directory
2.  open with lapce

#### What's the expected result?

- Normal icon placement

#### What's the actual result?

- Weird wrapping effect

#### Additional details / screenshot

- ![Screenshot](https://user-images.githubusercontent.com/66930138/173246386-ed0e9297-8170-46a0-bea8-f5d73a85d7b0.png)

**Comment by panekj** [comment]
Closing since icons were reworked
