### ISSUE TITLE
No font displayed in lapce

### ISSUE THREAD

**Issue by EmiOnGit** [lapce/lapce#607]
I did download the lapce precompiled package (as well as compiled myself) and every time I open lapce there is **no font displayed**. 
I believe this is connected to [#504](https://github.com/lapce/lapce/issues/504) as I also got this error in the beginning but somehow got rid of it with tinkering (unfortunately no clue how)
As for my specs: 
I'm also using **Arch linux** with **bspwm** (also tried on lxde but same issue)
I am infact using the **fira font** too.
Besides that I am running on a **Ryzen 3600X** and **Radeon Rx 570** as Gpu

![lapce](https://user-images.githubusercontent.com/95967983/173332914-214ab1a3-2adb-4835-96ea-fe987bfd0b43.png)

**Comment by EmiOnGit** [comment]
Hello guys,
after digging into the error I somewhat discovered a workaround (and maybe the cause).
----
# Workaround:
go into your `settings.toml`(lapce/defaults/settings.toml) and change
``` [ui]
font-family="TheFontYouWant" 
```
you can query your fonts with fc-list

---
# Cause
it seems like the call
``` impl UIConfig {
    pub fn font_family(&self) -> FontFamily {
        if self.font_family.is_empty() {
            FontFamily::SYSTEM_UI // this one #####
        } else {
            FontFamily::new_unchecked(self.font_family.clone())
        }
    }
```
https://github.com/lapce/lapce/blob/bcb54b27cda200f030fe84f545a319a650df528b/lapce-data/src/config.rs#L202
doesnt return any useable font which might success that this is the fault of piet or anything deeper in the architecture
(Also tried FontFamily::MONOSPACE which doesn't work either)

**Comment by tkkcc** [comment]
It seems fixed in https://github.com/lapce/lapce/commit/02a4b1dc372efbf0592e8230996cafc4fcfab229.  `lapce` still render blank font, while `lapce-git` works without extra config. But it use the vendored fonts, not respecting user fontconfig.

**Comment by panekj** [comment]
Closing since the issue was opened for very ancient version of lapce
