### ISSUE TITLE
Unable to connect with WSL

### ISSUE THREAD

**Issue by slingercode** [lapce/lapce#612]
Hello! I'm trying Lapce for the first time in my work computer, however, when I try to connect to WSL for my Ubuntu distro I got a message on the selector that saids "Disconnected WSL" but my distro is working fine. Am I something wrong? 😔

![image](https://user-images.githubusercontent.com/12452210/173617524-c237044c-de3d-423e-b526-dedcd79e9b0c.jpeg)

![image](https://user-images.githubusercontent.com/12452210/173617547-6bee011d-d1bc-4736-9b96-46809f1f7a29.jpeg)

**Comment by panekj** [comment]
WSL should be working properly now
