### ISSUE TITLE
Search freezing

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#627]
When searching for text, Lapce will sometimes freeze up and do nothing (no rendering or interaction).   
I've yet to pin down what the cause of the issue is, but it seems to occur nearby quick changes to the input so maybe some oddity related to updating the search infinitely looping?

**Comment by Kirottu** [comment]
For me this occurred when I inputted space into the find section. Only happened on the master branch though, the current release (0.1.2) seems to work fine.
