### ISSUE TITLE
Moving around the window causes white screens on portion or all of the editor

### ISSUE THREAD

**Issue by BestClaws** [lapce/lapce#630]
Im using Win11

![whitescreen3](https://user-images.githubusercontent.com/40067018/174422251-5c5abb1b-50e7-42c9-a1fa-72fe3f9150b8.png)
![whitescreen1](https://user-images.githubusercontent.com/40067018/174422252-e3bf3345-74a4-4868-a38f-693fc4961012.png)
![whitescreen2](https://user-images.githubusercontent.com/40067018/174422254-2035f485-46e6-4312-8e23-5ada1aa2155e.png)

**Comment by MinusGix** [comment]
Is it temporary (like, it starts rendering after you stop moving it), or does it stay blank?

**Comment by bobyclaws** [comment]
> Is it temporary (like, it starts rendering after you stop moving it), or does it stay blank?

yes it starts rendering when i stop moving it

**Comment by panekj** [comment]
Should be fixed
