### ISSUE TITLE
Characters without font don't render

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#635]
If you input a character that your fonts don't support (ex: 平 on my set font), then rather than rendering a box like the browser it simply renders nothing.   
As well, if you input the missing character on a line it may simply stop rendering the line.

**Comment by dzhou121** [comment]
Do you know the name of your CJK font?

**Comment by MinusGix** [comment]
Luculent is the font set for the editor text, and I believe it simply doesn't have CJK characters. It doesn't appear to be falling back to something like Noto Serif, which is what I believe my browser uses to display the character.

**Comment by dzhou121** [comment]
should be fixed by 2f5dd9f937ada2d197d30b847fc4505e8e694033

**Comment by MinusGix** [comment]
![image](https://user-images.githubusercontent.com/13157904/180804193-3c2081e2-31c8-4a71-be13-8efd9abeff49.png)
![image](https://user-images.githubusercontent.com/13157904/180804239-730a2fd2-0d8c-487f-9449-b8baf551f6d7.png)
  
It does fix the issue, thanks. Though it does seem like there's another bug with the line height being shifted (font: Luculent, font size: 14, line-height: 20)
