### ISSUE TITLE
Add icon to 'open lapce here' command

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#646]
(This is intended to open the folder the user is in inside of lapce, but currently simply opens lapce. This is because we don't have cli argument parsing yet.)  
![image](https://user-images.githubusercontent.com/13157904/174502853-c7d994d7-0976-4052-b4d4-b1f7898aa2e5.png)
Having the Lapce icon show rather than nothing would be good.

**Comment by panekj** [comment]
Fixed for some time now
