### ISSUE TITLE
Code Lense is borked

### ISSUE THREAD

**Issue by Byteron** [lapce/lapce#655]
When entering Code Lense, font rendering is all over the place.
it seems that some lines are shrinked but the font is still rendered in normal size.
<img width="757" alt="image" src="https://user-images.githubusercontent.com/24433899/174584207-b04962e1-9279-4bfb-b7f6-ef88c9485f10.png">

also, when exiting code lense

<img width="559" alt="image" src="https://user-images.githubusercontent.com/24433899/174584387-972cc2fe-2cd9-4d7a-a600-5a6547f2acdb.png">

the line height reverts, but some of the text is still in small font size.

this happens both on macOS and Windows, with the downloaded version of Lapce as well as a recent (a few minutes ago) build from master branch.

**Comment by MinusGix** [comment]
This should be fixed on master.
