### ISSUE TITLE
Uninstall button for plugins

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#660]
There should be a way to uninstall plugins.   
This could be done through simply clicking on the install button again (showing uninstall when you hover?), or through a context menu. It would then need to remove the folder, and remove the plugin from what Lapce's plugins. Should probably introduce a function to generally turn off a plugin, which is easier to add other things to later on and could be used for both disabling the plugin and uninstalling it.

**Comment by 2244josiah** [comment]
Or you could just add an uninstall button next to the installed button.

**Comment by Byteron** [comment]
there is ProxyNotification::InstallPlugin used in lapce-proxy/src/dispatch.rs line 336. I presume that seems to be kicking of the install.
A starting point might be to extend that enum with an UninstallPlugin and work from there.
(I'm new to this too so I can't guarantee that's the right path, just what I had found looking into this briefly)

**Comment by panekj** [comment]
Fixed in https://github.com/lapce/lapce/pull/880
