### ISSUE TITLE
Don't silently download nonexistent files

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#661]
If a plugin specifies files that don't exist then Lapce will silently download them, and write to the file (for example): "404: Not Found". I experienced this with the gruvbox plugin (I've reported the issue to them, though). It would be better to simply not download it and report the error to the user.

**Comment by panekj** [comment]
This one is quite old. Lapce doesn't download files anymore, it's up to the plugin maintainers to properly handle Http code.
