### ISSUE TITLE
Add option to disable format on save

### ISSUE THREAD

**Issue by msrd0** [lapce/lapce#663]
I often press Ctrl+S while writing code. There's nothing more annoying than writing out something like

```rust
if foo.bar {
    
}
```

to have it all get collapsed into one line when one wants to write some code in the empty line next.

You might even consider disabling it by default, I can imagine many people would rather trigger formatting manually.

**Comment by ghishadow** [comment]
It is available in main branch
https://github.com/lapce/lapce/blob/master/defaults/settings.toml#L16 set this to false in your settings.toml

or

![image](https://user-images.githubusercontent.com/9583775/174819924-d7504b7c-d021-41f2-a44a-7a858c7d731b.png)

disabling by default is good idea

**Comment by nheuillet** [comment]
While I will personally leave it on, I think the default behavior should be off: disabling it makes the default experience snappier and simpler to use for onboarding situations, where the editor needs to stay out of the user's way.
Simple, blazing-fast, and easy to customize if we want more should be the default behavior in my opinion.
