### ISSUE TITLE
[WINDOWS] Can't open folder on a non-system drive

### ISSUE THREAD

**Issue by yashwanthreddyg** [lapce/lapce#68]
![image](https://user-images.githubusercontent.com/7929962/154565791-038e4f92-11f4-4f85-9f8b-6696b292a905.png)

**Comment by ghishadow** [comment]
After pulling this latest master
5c86f304bfa6d63d21c95a65218672213b4607dc 

you can change path like this
![image](https://user-images.githubusercontent.com/9583775/154595732-5c2a593e-d652-418a-8789-74c5e5606363.png)

**Comment by Evrey** [comment]
This is why you don’t DIY file browsers but open the OS-provided one.

**Comment by yashwanthreddyg** [comment]
Like @Evrey said, using a system provided file chooser would be a nice way to do it. I am able to change the drive but the text box is buggy. Closing the issue for now.

**Comment by oleid** [comment]
https://crates.io/crates/native-dialog would do the trick.
