### ISSUE TITLE
Cross-file navigation history

### ISSUE THREAD

**Issue by cart** [lapce/lapce#680]
Right now it looks like `jump_location_forward` and `jump_location_backward` are scoped to the current file. When navigating a codebase, you often want to go back to the previous context.

For example,
1. hit `f12` to "go to definition" for a symbol
2. extract relevant info / context from that file (ex: maybe read some docs or implementation details)
3. navigate back to the location in the original file referencing the symbol. 

(3) seems like it is impossible to do with `jump_location_backward`.

**Comment by O-X-E-Y** [comment]
I'll look into this. It's also something I'm missing myself, and doesn't seem too hard to implement

**Comment by dzhou121** [comment]
This was implemented a while ago now.
