### ISSUE TITLE
`insert_mode` command for modal editing should insert "after" the selected character

### ISSUE THREAD

**Issue by cart** [lapce/lapce#683]
Currently `insert_mode` inserts "before" the selected character. This isn't how vim (or vscode's vim-emulation) works and is very surprising. This also has the "weird" effect of "moving the selection left" if you repeatedly enter and exit insert mode. The default mode switching operations shouldn't involve "movement" through the file. Switching between modes should be a "neutral" operation.

**Comment by dzhou121** [comment]
Isn’t it in Vim that i insert before the character and a insert after the character?

**Comment by cart** [comment]
Whoops! looks like ive conflated the "insert" operation with the "append" operation. Lapce does indeed already support the `append` command, which does exactly what I described above. I guess I've always just used append and assumed that was the "insert" op. I use colemak rebinds in vim / vscode, which change things around / decouple "first letters in verbs/ops" from actual keys, although thats not really an excuse / not your problem :)

Sorry for the confusion. I think we can close this out as this is clearly user-error. Thanks for the help!
