### ISSUE TITLE
File watch does not work?

### ISSUE THREAD

**Issue by piaoger** [lapce/lapce#694]
I just tried change local file in another editor such as sublime text and found that the nothing happened in lapce, though it's said that it has already been fixed in earlier version .  [issue 304](https://github.com/lapce/lapce/issues/304)

Environment: Windows 11 
Lapce:  0.1.2 portable

**Comment by piaoger** [comment]
Just dropped and tried 0.1.0, and it does not work as expected.

**Comment by piaoger** [comment]
@nheuillet  Is the fix in latest 0.1.3?

**Comment by nheuillet** [comment]
@piaoger it was released in 0.1.3 yeah. As far as I know you need the latest visual studio tools to fix the build errors, anything older than 2022 will not build. I will try to get a repro at some point because this is surprising.

**Comment by piaoger** [comment]
The build error is caused by tree-sitter-julia, not visualstudio.

I recommend adding below line in somewhere
 if readme, not just in cargo.toml instead.
```bash
  cargo build --no-default-features -p lapce-ui \
     --features lang-rust,lang-toml,lang-markdown,lang-json

```

**Comment by panekj** [comment]
@piaoger the build error is caused by outdated toolchain, if you update MSVC then it should work fine, related: https://github.com/lapce/lapce/issues/671

**Comment by panekj** [comment]
File watcher has been fixed some time ago already

**Comment by piaoger** [comment]
> File watcher has been fixed some time ago already

Still repro in latest nightly build cb7b.
Please check bellow gif.

![sync](https://user-images.githubusercontent.com/179429/193955734-499c3a78-390f-470c-a2bd-cba3687e12e6.gif)

**Comment by nheuillet** [comment]
Is it also happening in the non portable version of Lapce ?

**Comment by panekj** [comment]
> Even worse, there is below security warning while installing:

this has nothing to do with current issue

**Comment by MinusGix** [comment]
Windows will show warnings like that for any executable it doesn't recognize as being common.

**Comment by panekj** [comment]
whether it's portable or not shouldn't matter

**Comment by panekj** [comment]
Until it's explicitly mentioned in changelog or closed by PR, there won't be any change between versions.

**Comment by RichardFevrier** [comment]
Same on linux wayland flatpak (with given folder permissions) v0.2.8

**Comment by RichardFevrier** [comment]
Same on every linux version actually...

**Comment by yuzisee** [comment]
Likely a pre-requisite of https://github.com/lapce/lapce/issues/2288 for what it's worth

**Comment by chintu4** [comment]
Yeah,This problem i got in my editor too. the vscode got quickly refresh this issue today 4-06-2025 brought me to this issue .I was too facing this issue when this issue be solved?
