### ISSUE TITLE
Find All References

### ISSUE THREAD

**Issue by Byteron** [lapce/lapce#699]
When CTRL + Clicking a  symbol, I'd like to get a view of all references of that specific symbol and where they are used.

in VS Code this is done with an in line view of the according file below.

<img width="872" alt="image" src="https://user-images.githubusercontent.com/24433899/176258956-e52302be-6b53-4fc2-95af-0b0ff1293965.png">

<img width="882" alt="image" src="https://user-images.githubusercontent.com/24433899/176259058-f1452386-bc0f-40a2-a6c7-fa7834e2272b.png">

It doesn't have to be like this visually, of course, I'd still like to have the functionality, being able to find all references to a symbol in the code base.

**Comment by dzhou121** [comment]
It should already do this and show the references in the command palette

**Comment by Byteron** [comment]
actually CTRL + Click (or CMD + Click) doesn't seem to do anything on macos.
I will test on windows tomorrow if it works.

**Comment by dzhou121** [comment]
It should be cmd+click on macOS and ctrl+click on windows.

Does it work if right click, "Go to Definition"?

**Comment by Byteron** [comment]
no, when selecting Go to Definition via context menu it just stays where it is.

**Comment by dzhou121** [comment]
Do other LSP features work for you, e.g. completion etc?

**Comment by Byteron** [comment]
now that you mention it, none of it seems to be working.

**Comment by Byteron** [comment]
neither in the downloaded version, nor in a current master build.

**Comment by MinusGix** [comment]
![image](https://user-images.githubusercontent.com/13157904/176319621-0f76b03d-087f-4991-b864-7a69c213ad8d.png) is what it looks like when ctrl+clicking on a type.

**Comment by Byteron** [comment]
OK yes, on windows CTRL + Click on the definition indeed pops up the command palette. So this works.
I'm gonna close this, but open up 2 new ones, since 1) Language Server on macOS doesn't work and 2) Scrollbars on the Command Palette do nothing, when I click on them the palette just closes.
