### ISSUE TITLE
[WIP] Analysis of application startup performance / hang / non-responsive-ness

### ISSUE THREAD

**Issue by follower** [lapce/lapce#707]
_[WIP: Additional data & analysis to be added--unfortunately GitHub doesn't have a "draft" status for issues & if I don't at least *start* an issue now, I'd probably disappear down another rabbit hole before I ever did...]_

----

**TL;DR:** There are multiple issues affecting the (actual & perceived) application start-up time/performance of Lapce and--based on my observations--there are a number of factors that contribute to whether they are observed, including at least:

 * Computer performance (CPU power & RAM).
 * Number of open workspaces.
 * Complexity of projects in the workspaces.
 * Number/complexity of open file(s)?
 * `rust-analyzer` configuration settings.

----

### Context

[TODO]

### Reproducing

 * Have 4-5 active/open workspaces with at least 2-3 "complex" projects (in my case ~280 crates total) among them. e.g. a 3D Bevy project, perhaps include my recent Rusty Game Jam 2 entry "Quacks Like A Duck" among them: <https://gitlab.com/RancidBacon/2022-rusty-game-jam-2> :D.

 * Run the following two commands in separate terminal windows (it's a hacky way to merge the log output together cos AFAICT Lapce log output can't be redirected back to `stderr`?) :
   * `tail --quiet -F ~/.config/lapce/lapce.log log-10.txt |& tee --append log-combined-10.txt` 
   * `RUST_LOG=debug RA_LOG=lsp_server=debug GTK_CSD=0 /<path>/lapce-v0.1.2/Lapce/lapce |& ts | tee --append log-10.txt` (The last part with `ts` applies a timestamp to the `lsp_server` log.) 

 * Do stuff in Lapce. [TODO]

 * After you exit Lapce you will probably want to run this to reduce duplicate lines in the output a little:
   * `uniq --count < log-combined-10.txt |& cat >> counted-duplicates--log-combined-10.txt` 

Having old & outdated hardware probably helps in the reproduction of this issue. :D

[TODO]

### Observations

There's a very visible series of changes that occur over launch:

 1. The initial window appears _or_ frequently _doesn't_ appear--which suggests a potential race condition of some variety? 
 2. The window is non-responsive (& may trigger a "Non-responsive application" dialog).
 3. The file text is visible in the editor but it is grey with no syntax highlighting.
 4. The window is still not responsive.
 5. After an extended period of time the syntax highlighting is suddenly applied.
 6. Prior to the `rust-analyzer` configuration setting change mentioned below, it would be many minutes of 100% CPU usage before it was possible to begin editing.
 7. After the configuration change the editor becomes responsive when the syntax highlighting is applied but any `rust-analyzer` features such as "hover" & "completions" do not appear until about a minute later when the CPU usage drops to a "reasonable" level.

#### A specific log example

My sample log shows the application launch starts ~11:00:31AM:

```
      1 tail: cannot open 'log-09.txt' for reading: No such file or directory
      1 tail: 'log-09.txt' has appeared;  following new file
     27 [2022-06-30][11:00:31][lapce_data::keypress::keypress][WARN] Invalid key modifier:
      1 Jun 30 11:00:31 Parsing RUST_LOG
      1 Jun 30 11:00:31 level='info' for all modules
      1 [2022-06-30][11:00:31][wasmer_compiler_cranelift::translator::func_translator][INFO] translate(8 bytes, u0:12(i64 vmctx) system_v)
      1 [2022-06-30][11:00:31][wasmer_compiler_cranelift::translator::func_translator][INFO] translate(17 bytes, u0:276(i64 vmctx, i32, i32, i32) -> i32 system_v)
[...]
```

The first `paint` span occurs at ~11:00:34AM :

```
     1 [2022-06-30][11:00:34][tracing::span][INFO] paint
```

The `paint` spans occur "regularly" until ~11:00:38AM:

```
      1 [2022-06-30][11:00:38][tracing::span][INFO] paint
```

But then no further `paint` spans occur until another _minute_ passes:

```
      1 [2022-06-30][11:01:38][tracing::span][INFO] paint  
```

During this time communication with the LSP is visible in the logs.

[TODO]

### Suggestions for improving startup performance

 * Avoid processing all open workspaces at startup without prioritization.
 * Prioritize the current/most recently active workspace & files when starting/interacting with LSP Servers/plugins.
 * Use/document more performant default/recommended `rust-analyzer` settings, e.g.:
```
# Add to bottom of `~/.lapce/plugins/lapce-rust/plugin.toml`:
[configuration.options.cache]
warmup = false
```

Without the above configuration Lapce startup would take many _minutes_.

[TODO]

### Related issues

[TODO]

**Comment by panekj** [comment]
Lapce shouldn't be resource eater anymore
