### ISSUE TITLE
CSD on linux

### ISSUE THREAD

**Issue by Titaniumtown** [lapce/lapce#716]
I was wondering if CSD (Client-Side Decoration) could be implemented on Linux. I assume the screenshot in the readme is on MacOS, but this behavior would also be really nice to have over on Linux. Hope it could be included!

**Comment by Titaniumtown** [comment]
#710 has implemented this, but for windows it seems, for linux I assume it's more complicated.

**Comment by Titaniumtown** [comment]
Was doing some fiddling and I got to the error: `[druid_shell::backend::gtk::window][WARN] WindowHandle::handle_titlebar is currently unimplemented for gtk.` on linux. I don't know how to resolve this 😅

**Comment by panekj** [comment]
> I don't know how to resolve this 😅

You can't unless you implement `handle_titlebar` for x11, gtk and wayland
