### ISSUE TITLE
high gpu usage

### ISSUE THREAD

**Issue by zhcy2050** [lapce/lapce#717]
High(about 20%) GPU usage when double click on text. (vscode or other editor not has this problem).
GPU: Intel core i5 11th integrated GPU.
system: win11 home edition.
PS: Use Druid as GUI library maybe not a good idea, you should try QT.
Thanks for your great work.

**Comment by lihe07** [comment]
![img](https://user-images.githubusercontent.com/53819558/177533644-b6e64cbc-f956-450d-9170-d97f1d44617c.png)

Quite strange, 
I even got a high CPU usage and GPU usage without any operations like double click.

**Comment by zhcy2050** [comment]
2022/07/17 update
The new version 0.1.3 has about 80% high gpu usage when use custom titlebar for widows。
Even without any operations.

**Comment by panekj** [comment]
> The new version 0.1.3 has about 80% high gpu usage when use custom titlebar for widows。

Don't use custom titlebar then?

**Comment by zhcy2050** [comment]
@panekj 
Without  custom titlebar ? No change, about 20% (double click on text) or about 40%(scroll around the text).

**Comment by panekj** [comment]
Fixed since it was a Druid issue
