### ISSUE TITLE
Terminal QOL additions

### ISSUE THREAD

**Issue by DaQueenJodi** [lapce/lapce#723]
* instantly scroll to the typing field when you start typing a command 
* smoother scrolling 

also it seems like resizing the terminal doesn't always work (currently on the latest nightly)

**Comment by MinusGix** [comment]
(Resizing the terminal was recently fixed)

**Comment by ConnorSMorrison** [comment]
I couldn't find a way to make it so that when you type a command, but I found a way to make it so when you press enter, it scrolls down. Hope this works for you and hoping somebody finds a way to make it so when you press any key.

**Comment by ConnorSMorrison** [comment]
Turns out I didn't test it thoroughly enough and it scrolls down with the following keys: All the arrow keys, enter, shift, escape, backspace, caps lock, ctrl, windows (meta key), and alt. It might work with more, I'm not sure.

**Comment by DaQueenJodi** [comment]
I think making it scroll down when you're focused on the terminal window and press any key that isn't special (i.e meta, Ctrl, alt, etc) would be ideal

**Comment by ConnorSMorrison** [comment]
So I don't know what change was made but it just started working. The terminal scrolls with (I'm pretty sure) most keys on the keyboard, except for ctrl and shift for some reason. Might want to do some more testing to see if that's what you wanted, but just wanted to let you know. You might need to have the latest changes on your local machine. I don't know if it's in the latest release or just a random commit someone made.

**Comment by DaQueenJodi** [comment]
it works fine for me
personally I dont think cntrl or shift should scroll it down as those could be hotkeys (what if you want to copy with cntrl + c and it scrolls down?), so this behavior is perfect to me
(it also seemed to have been commited quite a bit ago, cant remember when it started working for me)

**Comment by panekj** [comment]
Fixed
