### ISSUE TITLE
syntax hilighting not active for build.rs file

### ISSUE THREAD

**Issue by DaQueenJodi** [lapce/lapce#725]

**Comment by panekj** [comment]
Can you give more information? What OS, which lapce version? What project did you open?

**Comment by DaQueenJodi** [comment]
Ah sorry
I'm on Linux, using the latest nightly release
The project I have open contains 2 crates inside of it
Syntax hilighting is working for everything within the src/ directory of the crates
But the build.rs file doesn't have it (despite rust-analyzer from the rust extension picking it up

Hope that helps

**Comment by panekj** [comment]
Can't reproduce, `build.rs` in lapce repo highlights properly in lapce
