### ISSUE TITLE
Don't show autocomplete after backspacing over whitespace

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#743]
If backspacing deletes a whitespace character (such as deleting indentation) then it shouldn't show autocomplete.

**Comment by abmyii** [comment]
This also occurs when pressing Enter/Return.

**Comment by MinusGix** [comment]
> This also occurs when pressing Enter/Return.

That was fixed by #916, it will be in the next release.

**Comment by abmyii** [comment]
> > This also occurs when pressing Enter/Return.
> 
> That was fixed by #916, it will be in the next release.

Ah I see - thank you for the near-instantaneous reply!
