### ISSUE TITLE
Feature request: custom commands

### ISSUE THREAD

**Issue by awsdert** [lapce/lapce#745]
This is a feature I got used to in geany and have not been able to find in any other editor thus far, I'm looking for a "custom command" prompt that can be assigned a hotkey. For an example install geany on whatever os you want, main or not, and create a simple hello world file, be it in c, c++ or whatever, next click on the "Build" menu at then click on the "Build Commands..." option, under the "Make" command there should be one that ends with "...", delete everything in the box next to it and edit the name to whatever you want, likewise assign whatever hotkey you want. Next under the "Preferences" option in the "Edit" menu click on the "Terminal" tab and make sure "Follow path of the current file" is checked, next with your hello world file selected use your set hotkey and just type in the compiler name and whatever arguments you want to give it in addition to the file name, you've now just used the feature I'm looking for.

**Comment by awsdert** [comment]
Not the same, for those "custom" build commands I have to configure the command in a file somewhere, the "custom command" I mean here is one you type in as you would the terminal, the difference being that the output would not go to the terminal but to the normal compiler output box where you can then click on the output to go to faulty code lines.

**Comment by panekj** [comment]
It would be better if you just described it yourself properly and/or provide visual demo (:

**Comment by awsdert** [comment]
[customcommand-2022-07-05_20.21.41.webm](https://user-images.githubusercontent.com/7422982/177400410-501ad5ae-3731-4fa2-a19a-4d4999ebf6ae.webm)

**Comment by nheuillet** [comment]
A custom command terminal redirecting the output straight to the compiler output box then?
It definitely seems very doable, although as of now there is no compiler output console, and it would be good to start with that

**Comment by awsdert** [comment]
That's fair, I only opened the app and looked through the settings for this feature, didn't check for console output

**Comment by panekj** [comment]
That's why I asked for proper description/visual demo because it sounded like something other editors already do
just accessed in different way (VSC = `commands.json` file, Geany = pop-up window)

For us, I'd say that a simple palette command with palette input will suffice, just need to work on compiler/debug
ouput

**Comment by awsdert** [comment]
However you want to do it is fine by me as long as I can get that prompt with a key combo (I currently use [CTRL] + [SHIFT] + [F9])

**Comment by awsdert** [comment]
I just realised you've marked this a C exclusive, it should be noted that in geany the feature is available for all languages, they have different defaults but a simple edit and they will provide the same "launch custom command" feature, it would be best to make it an abstract dialogue that can have a per language setting in the projects/workspaces

**Comment by panekj** [comment]
It's not a `C` language tag, it's short for "category"
![image](https://user-images.githubusercontent.com/50457605/177492548-20888f35-29ff-424e-815b-3b40ec123b8e.png)

**Comment by awsdert** [comment]
A, my mis-understanding then :)

**Comment by panekj** [comment]
This is implemented

**Comment by awsdert** [comment]
About to re-download (had to re-install my system a couple of times) and take a look

**Comment by awsdert** [comment]
What did you set the key combo as as I've tried my usual, tried looking for it in the hotkeys, not finding it.
