### ISSUE TITLE
Error Lens

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#747]
We could use the inlay hints code (making it more general like described in #721 ) to implement a feature similar to the [ErrorLens](https://marketplace.visualstudio.com/items?itemName=PhilHindle.errorlens) VSCode extension.  
The general idea is to display diagnostics as 'phantom' text inline, so that users don't need to hover over the specific places the diagnostics appear.  
This could be done in a plugin once the plugin API is existent, though I do think it would work nicer implemented Lapce.

**Comment by dzhou121** [comment]
I think implementing it in Lapce is a good idea. 

It’s on by default in Xcode.
