### ISSUE TITLE
GLib warning about open files

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#761]
When running Lapce on Linux with a path (`lapce .`), GLib gives this error:  
`GLib-GIO-CRITICAL **: 20:37:18.936: This application can not open files.`  
Based on a quick search, of which this is the only reference I could find.., I got https://mail.gnome.org/archives/gtkmm-list/2013-June/msg00019.html  
It seems like we need to tell Gtk that we're handling the opening of files rather than whatever its default behavior is. It seems to just be as simple as adding a flag to `Gtk::Application::create`.

**Comment by superlou** [comment]
I'm also getting this on Linux Mint, but inconsistently. It shows up maybe 1 in 4 times anecdotally.

**Comment by panekj** [comment]
Fixed since we don't use GTK anymore
