### ISSUE TITLE
Can't change terminal shell to zsh

### ISSUE THREAD

**Issue by obtusedev** [lapce/lapce#764]
The default terminal shell is `sh`. I can change that to `bash` but I can't change it to `zsh`. I tried `zsh`, `z shell`, `zshell`. Is `zsh` not supported at this time?

**Comment by panekj** [comment]
What happens when you change it to `zsh`

**Comment by MinusGix** [comment]
As well, what method did you use to install it on your OS? Did you use the flatpak? The AUR? Or did you build it from source?

**Comment by obtusedev** [comment]
> As well, what method did you use to install it on your OS? Did you use the flatpak? The AUR? Or did you build it from source?

I installed it using Flatpak 1.6.5 on Ubuntu 20.04.4 LTS.

**Comment by obtusedev** [comment]
> What happens when you change it to `zsh`

It stays with `sh` shell. Checked using `ps -p $$`

**Comment by ghishadow** [comment]
use this for flatpak https://github.com/flathub/dev.lapce.lapce/issues/1#issuecomment-1147641302

**Comment by panekj** [comment]
Fixed in #1084
