### ISSUE TITLE
Kakoune support?

### ISSUE THREAD

**Issue by DakshG07** [lapce/lapce#769]
Whilst, I use Neovim a lot, I’ve also been checking out kakoune and helix, which use a slightly different style of editing. Here’s the gist of it.
Vim is a *verb noun* modal editor, e.g. *delete word*. Kakoune is a *noun verb* editor, e.g. *word delete*. Actions like `w`, `e`, and `b` now select text, and then you use the verb to change the affected text. `x` selects an entire line. There’s lots of stuff to cover, so maybe check the Kakoune docs.

**Comment by superlou** [comment]
There is more discussion on this in #281.

**Comment by yashpalgoyal1304** [comment]
This issue can be closed as duplicate of that above mentioned issue #281
