### ISSUE TITLE
Rename Symbol in Workspace

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#773]
There is an LSP feature to rename a symbol in the current workspace, which is useful for refactoring code.   
See: (I believe) https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rename  
VSCode supports this by showing a little text box below the identifier you're renaming when you press F2.

**Comment by Skallwar** [comment]
I'm new to lapce but I thinks what you are asking for is implemented using the F2 keybinding. I installed the rust plugin (don't know if it is the correct word for it in lapce) and I got a pop-up asking for a new name.

However the shortcut is not registered almost 1/2 of the time. When the pop up does not appear directly it seems I'm able to force it to show by pressing ESC.

**Comment by panekj** [comment]
It's fixed since https://github.com/lapce/lapce/commit/8687b7d33b9f7a6fc33f4c9d012675c1f817098a

**Comment by panekj** [comment]
@MinusGix could you include it in release notes?

**Comment by MinusGix** [comment]
> I'm new to lapce but I thinks what you are asking for is implemented using the F2 keybinding. I installed the rust plugin (don't know if it is the correct word for it in lapce) and I got a pop-up asking for a new name.
> 
> However the shortcut is not registered almost 1/2 of the time. When the pop up does not appear directly it seems I'm able to force it to show by pressing ESC.

This should probably be a new issue so we can keep track of it better.
