### ISSUE TITLE
[Clippy]Too many clippy warnings

### ISSUE THREAD

**Issue by Dengjianping** [lapce/lapce#79]
At some point, those warnings should be resolved.

My terminal is flooded by those warnings.

**Comment by PolyMeilex** [comment]
The same goes for regular warnings too. Once I saw them, I started to doubt if I want to install this software on my computer. I would be open to fixing all of them, and writing a simple CI to prevent this from happening in the future, but it looks like someone already did #63 but was ignored. So if this is the author's conscious decision to ignore those warnings, please simply disable them project wide, so the intentions are well known for both rustc and for us.

**Comment by bugadani** [comment]
Thanks for reporting this!

Some of the clippy warnings have been fixed or force-ignored in #267.
I admit response time on issues and PRs hasn't been ideal until now, but I'm hoping we can improve on that front.
