### ISSUE TITLE
Alt-key combinations not recognized

### ISSUE THREAD

**Issue by marc2o** [lapce/lapce#792]
It is not possible to input characters using the `Alt` key. So neither curly braces `{ }`, square brackets `[ ]` nor something like pipe `|` etc. work within the editor or the terminal. The problem has at least been present since v0.1.2 and persists in the nightly build.

- MacBookAir7,2
- macOS 12.4 (21F79)
- German system language and keyboard layout

**Comment by ceinem** [comment]
same for me, with a Swiss keyboard layout

**Comment by dzhou121** [comment]
Can you try the latest master https://github.com/lapce/lapce/commit/474bb00d099bb222f50735d0fd0b0b7163567a05 ?

**Comment by marc2o** [comment]
I tested with the latest nightly build and can confirm that it works, now — in the editor as well as within the terminal.
