### ISSUE TITLE
Allow lapce-proxy to open a file in lapce frontend

### ISSUE THREAD

**Issue by khuongduybui** [lapce/lapce#795]
In VSCode Remote, somewhere inside ~/.vscode-server there is an executable file that when invoked with a file path, the file will be open in VSCode frontend via the Remote Extension.

Can we have an equivalent of such an executable inside ~/.lapce that via the proxy tells lapce frontend to open the file?

**Comment by panekj** [comment]
That requires interprocess communication which we didn't implement yet but it's planned

**Comment by panekj** [comment]
This should be fixed via #1003
