### ISSUE TITLE
Unable to install Lapce on Windows

### ISSUE THREAD

**Issue by shreyashsaitwal** [lapce/lapce#8]
I tried installing Lapce on my Windows 11 PC using the lapce-windows.msi package, and this is what I get:

![image](https://user-images.githubusercontent.com/40118018/145967559-8fe04e23-3bb5-48e5-bb43-ce547bb7e162.png)

FYI, this is the first time I'm installing Lapce.

**Comment by IngrownMink4** [comment]
@shreyashsaitwal same here
![msiexec_TfQsxIs58a](https://user-images.githubusercontent.com/25466522/146065164-baa77153-190e-4daa-a08e-daf099e865e7.png)

**Comment by dzhou121** [comment]
Can you try the latest release? https://github.com/lapce/lapce/releases/tag/v0.0.4

**Comment by shreyashsaitwal** [comment]
It worked. Thanks.

**Comment by IngrownMink4** [comment]
> Can you try the latest release? https://github.com/lapce/lapce/releases/tag/v0.0.4

It works! Thanks :)

![msiexec_hbDs27uD7F](https://user-images.githubusercontent.com/25466522/146395888-f0e1b298-ade4-4fec-87b7-6d0bd5db7976.png)
