### ISSUE TITLE
[feature] blacklist for file explorer tab

### ISSUE THREAD

**Issue by DaQueenJodi** [lapce/lapce#811]
In VS Code there's a way to blacklist certain directories/files i.e `.git`, `target`, etc from showing up in the file explorer tab and it would be very helpful if that was added to lapce
Either as a global config or as a workspace specific on
If it was per-workspace, I think being able to automatically generate the blacklist from a .gitignore file would also be nice (but not necessary)

**Comment by imgurbot12** [comment]
Having a "VCS Ignore" option to block things in your `.gitignore` would be amazing. Working with python and having to scroll past all of the `__pycache__` folders can be annoying at times.

**Comment by I-Info** [comment]
It looks like there is no relevant info for a long time. 
Is anyone working on it? 
I'm interested about this feature, I'll try to implement or collaborate.

**Comment by jonator** [comment]
Would be nice (and would make sense) if this were to apply to the file-select palette as well.

**Comment by AstroOrbis** [comment]
Any updates concerning this?

**Comment by panekj** [comment]
> Any updates concerning this?

Someone will comment if there will be any

**Comment by MatthewScholefield** [comment]
I looked into this briefly, and I think we could use the [ignore](https://github.com/BurntSushi/ripgrep/tree/master/crates/ignore) crate and from my vague understanding looking through the codebase I *think* we want to modify something around [`FileExplorerData::node_tree`](https://github.com/lapce/lapce/blob/master/lapce-data/src/explorer.rs#L65).

**Comment by panekj** [comment]
The issue has been resolved. If you want more functionality, please open another issue.

**Comment by imgurbot12** [comment]
> The issue has been resolved. If you want more functionality, please open another issue.

@panekj 

As it tends to happen with these things, immeditely after posting I found the context I was missing. looks like there was already a PR to solve the .gitignore issue. nevermind. thanks!
