### ISSUE TITLE
`tree-sitter-md` dependency does not vendor properly 

### ISSUE THREAD

**Issue by DeeUnderscore** [lapce/lapce#813]
Running `cargo vendor` on lapce master or v0.1.3 does not vendor the `tree-sitter-md` dependency ([of lapce-core](https://github.com/lapce/lapce/blob/2caa198bf84908d952d0e7b8795d5d3cf4c82fcd/lapce-core/Cargo.toml#L34)) properly.

This appears to be due to the fact that [`Cargo.toml` in tree-sitter-markdown](https://github.com/dzhou121/tree-sitter-markdown/blob/134c7f870ad17b3c3e40cd90b8bbd08329ac4bbd/Cargo.toml#L12-L16) `include`s two subdirectories that are subpackages (they contain their own `Cargo.toml` files), and Cargo will not include directories that are subpackages by design. Upstream [has a commit](https://github.com/MDeiml/tree-sitter-markdown/commit/b48148a72be54ac148c81c9431f095aadfff765e) that just gets rid of these two `Cargo.toml` files.

I'm opening this against lapce, because it seems the `tree-sitter-md` dependency repo is a fork specifically for lapce and does not have an issue tracker. I ran into this problem when trying to build v0.1.3 for Nix (which runs `cargo vendor` as part of the build process).

**Comment by panekj** [comment]
This should be fixed via #957
