### ISSUE TITLE
Add File Explorer Refresh Button

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#815]
This would help soothe the issues where our watching code is breaking (as mentioned in a few other issues). It would probably require adding an extra beginning section to the file explorer panel to render the button.

**Comment by jmj0502** [comment]
@MinusGix Hey! Do you think this issue will be too tough? I would like to give it a shot c:

**Comment by MinusGix** [comment]
I think it shouldn't be too tough.  
- This could be done either as a button or a context menu option (latter is easier due to not having to do any mouse hit-testing on an icon; and not having to make a containing widget)
- Probably need a `LapceUICommand::FileExplorerRefresh` for the button / context menu option to send out when activated, which is then received by the file explorer  
- I think you just need to call `FileExplorerData::reload` when it receives the command, (which is what we used and fixed a good chunk of the reloading issues, I believe)

**Comment by jmj0502** [comment]
Cool! I'll reach out (through discord or even here) in case I have questions c:

**Comment by sanxiyn** [comment]
I think this issue should be closed.
