### ISSUE TITLE
Idea: Open files in temporary tab first

### ISSUE THREAD

**Issue by fwcd** [lapce/lapce#82]
In VSCode, single-clicking a file in the explorer opens the file in a 'temporary' tab (in the UI the tab label is in italics), which automatically closes once a new 'temporary' tab opens. This is very useful for quickly browsing a codebase without opening a whole lot of tabs. Once the file is edited or the file/tab is double-clicked VSCode turns the tab into a 'permanent' tab.

I'd imagine, it would be very cool to have such a feature in Lapce too.

**Comment by FlixCoder** [comment]
I think this is the current default
