### ISSUE TITLE
Tabs and spaces QOL features

### ISSUE THREAD

**Issue by ConnorSMorrison** [lapce/lapce#829]
I would love it if there was a command to translate tabs to spaces and vice versa. I would also like there to be something showing what is a tab and what is space.

**Comment by panekj** [comment]
> I would love it if there was a command to translate tabs to spaces and vice versa.

Will be handled when we implemented configuration option for space/tab

> I would also like there to be something showing what is a tab and what is space.

Rendering whitespace is implemented
