### ISSUE TITLE
Follow OS standards

### ISSUE THREAD

**Issue by Evrey** [lapce/lapce#83]
Note that this is not about using GTK or KDE themes. I don’t really care for that. What i’m listing here are examples where this editor breaks with the overall desktop usage experience, despite desktop environments offering queryable settings. See it as a TODO list for better desktop integration.

- [ ] Use default OS key bindings where applicable. I have a lot of customised and deleted key bindings which this editor clashes with. And i don’t really feel like spending another half hour just replicating key bindings. See [Qt Docs](https://doc.qt.io/qt-6/qkeysequence.html#standard-shortcuts) for examples of what typical shortcuts are and maybe even how to query these per OS. Related issue, which is a symptom of this: https://github.com/lapce/lapce/issues/76
  - On that note, there does not seem to be a way to delete a key combo, which is usually done by hitting `Esc` in the combo settings. Instead it just accepts `Esc` as a key combo and offers no »delete« button.
- [ ] Use the OS theme settings. I have a light themed OS, the editor starts dark. Changing themes is also a guessing game without drop-down menu.
- [ ] Use the OS font settings. I use Noto Sans and Noto Sans Mono. It uses some other font i never heard of.
- [x] Use the OS-provided file manager for opening workspaces and files. File managers are some of the most important OS interfaces for the user. Breaking with their UX by using something else is for many unacceptable.
- [ ] I18N and using current locale, which in my case is `de_DE.UTF-8`. I assume this is TODO and far from being implemented yet. Or the L10N for German doesn’t exist yet.
- [ ] Put config files etc. in the XDG-designated directory on Linux. Seems to be the case for the editor’s configuration, but not for plugins.
- [x] Use the OS-configured CLI, which is `fish` in my case. Lapce correctly handles this, also nice!
- [ ] **E:** Add a »right click, open (project directory) with lapce« desktop integration.

**Comment by fushinari** [comment]
> Put config files etc. in the XDG-designated directory on Linux. Seems to be the case, nice!

Doesn't seem to be the case for me. `~/.lapce` seems to be the hardcoded path for me.

**Comment by fushinari** [comment]
`~/.lapce` is still hardcoded for plugins but the `directories` crate is used for configuration.

**Comment by Evrey** [comment]
Nice find, didn’t try any plugin stuff.

**Comment by bugadani** [comment]
Thanks for reporting these ideas!

> Use the OS-provided file manager for opening workspaces and files.

I believe Lapce has been using the OS's file picker dialog for some time now. I've taken the liberty to check the box in your post, feel free to correct me if you were thinking of something else!

**Comment by ogarcia** [comment]
> Put config files etc. in the XDG-designated directory on Linux. Seems to be the case for the editor’s configuration, but not for plugins.

And for the cache either. Right now the cache is being stored in `${XDG_DATA_HOME}/lapce-stable/cache/` when it should be in `${XDG_CACHE_HOME}/lapce-stable/`

**Comment by panekj** [comment]
We're not going to follow XDG spec except for basic things like `XDG_CONFIG_HOME`

**Comment by ogarcia** [comment]
> We're not going to follow XDG spec except for basic things like `XDG_CONFIG_HOME`

Following the XDG specification depending on where the wind is blowing is identical to not following it at all.

The XDG specification is designed to make configurations portable and easy to back up. If you put the cache in the `XDG_CONFIG_HOME` directory you are doing a disservice as you are forcing the user to backup cache contents that are not necessary. The same goes for the logs.

I fully understand not being 100% strict with the specification, but I would ask for a minimum of quality.

**Comment by Porkepix** [comment]
Also note that while the UI is dark, it uses light theme for things such as the file browser when opening a new file, with a standard Gnome dark.

It turns out this is affected by the same adwaita legacy we can set for legacy applications within Gnome tweaks I found out there: https://github.com/VSCodium/vscodium/issues/1164#issuecomment-1376468337

Lapce isn't an electron application though, so I don't know in its case if this is just an information to provide when opening up the these elements or if some parts of the code/libs needs an update (to use GTK4, for example?)

**Comment by TotalChaos05** [comment]
> We're not going to follow XDG spec except for basic things like `XDG_CONFIG_HOME`

Is there a reason you won't?

**Comment by AngryAnt** [comment]
Not in the list: Lapce doesn't provide an app name or menu on Plasma (for feeding into a global menu bar). Not sure if that's the same on macOS. Regardless, a case of not following OS standards.

**Comment by Evrey** [comment]
> We're not going to follow XDG spec

Taking that as a Won’t Fix, thus closing this issue.

**Comment by MyApaulogies** [comment]
I just wanted to add that I have remapped some keys via gnome-tweaks, and they don't work in Lapce, which is a bit jarring -- I didn't realize it was possible for an app to ignore them until now.

**Comment by panekj** [comment]
> I just wanted to add that I have remapped some keys via gnome-tweaks, and they don't work in Lapce, which is a bit jarring -- I didn't realize it was possible for an app to ignore them until now.

That's unrelated to this issue, your problem is this https://github.com/lapce/lapce/issues/2731
