### ISSUE TITLE
Don't say 'failed to load plugin information' before the plugin request has been completed/failed

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#830]
Currently we tell the user on startup that we failed to load the plugin information (in the plugin panel), but that is done before the request has even finished. What it should say is that it is loading. Then on actual failure, it should change the text to say there was a failure.

**Comment by bbrabbitt** [comment]
I think we'd better load installed plugins first then load from gh or better cache the plugin info on disk. It can be painful to wait all plugin info loaded from internet as the plugin list is growing rapidly.
