### ISSUE TITLE
Donation options missing

### ISSUE THREAD

**Issue by vn971** [lapce/lapce#854]
Hi! I was trying to find donation options to encourage further lapce development, but I couldn't find any.
If there would be crypto/SEPA donation options available, that'd be great! Otherwise, potentially mentioning that no donations are needed/beneficial to the project could also work.

Thanks to everyone involved in the project regardless! :green_heart: 
Even though I see from many occasions that it's very fresh, I'm already trying to introduce it to certain workflows, and sometimes it works successfully. The start-up times are great and the simplicity is already there!

**Comment by ThePerfectComputer** [comment]
I second this. I would be very happy to donate.

**Comment by panekj** [comment]
It was mostly discussed on Lapce Discord server, and for now there are no plans to collect monetary donations.
All other "donations" forms are welcome (code, documentation, issues contributions)

**Comment by tra** [comment]
Has anyone here used the [GitHub Sponsors](https://github.com/sponsors) service?  Perhaps that could be a way for this project for accepting monetary donations but I'm not familiar with the details and whether or not GitHub takes a cut.

**Comment by panekj** [comment]
> Perhaps that could be a way for this project for accepting monetary donations

The decision is that the project doesn't want to receive money, not that there isn't a way to do so

**Comment by J-Cake** [comment]
Okay sorry, it needs to be said - you guys are amazing
