### ISSUE TITLE
ui/missing: No scrollbar in plugin section

### ISSUE THREAD

**Issue by schwrzstrbn** [lapce/lapce#855]
The scrollbar does not seem to exist in the plugin section

![Screenshot from 2022-07-23 23-30-28](https://user-images.githubusercontent.com/45195351/180611865-a9c3cfa5-2106-4222-b865-14f7adf928d1.png)
.

I'm currently using the v0.1.3 lapce build release, is it fixed in recent commits? Or am I the only one who is encountering this kind of problem?

**Comment by panekj** [comment]
It's fixed already, will be available in next release

**Comment by schwrzstrbn** [comment]
> It's fixed already, will be available in next release

nice, thanks!!
