### ISSUE TITLE
Cannot properly tile window to ¼ the monitor size, because minimum window size is too big.

### ISSUE THREAD

**Issue by Evrey** [lapce/lapce#86]
Title says it all. Ideally there would be no explicit minimum window size limit and it’ll squish as small as the window contents allow. Monitor is 1080p on the machine i’m on now, but i also have a 720p Laptop i tile windows to ¼ on during a normal dev session. So if there must be an explicit limit, don’t know how Druid works, then i suggest making it smaller than a quarter of 720p.

**Comment by ailyas19776** [comment]
I will look into this, see what I can do

**Comment by Domerpig** [comment]
I'd like to work on this.
