### ISSUE TITLE
Support font stacks in settings

### ISSUE THREAD

**Issue by ngryman** [lapce/lapce#862]
Hi,

It seems that Lapce doesn't support font stacks (i.e., a list of font families separated by commas, the first one available on the system being applied).

For reference, I pasted the following stack:
```
'JetBrains Mono', Menlo, Monaco, 'Courier New', monospace
```

I come from VSCode, and like many others, I suppose, I simply pasted some settings from VSCode to Lapce. I was surprised that it doesn't work for font families.

If you don't expect to support font stacks, I would suggest making it clear for new users that they need to specify only one font family, as it might be surprising for VSCode users.

Thanks!

**Comment by StoyK** [comment]
Yeah, that sounds easy on paper, but the problem is with the way Lapce checks for fonts. The code uses FontFamily::new_unchecked which can't determine if a font exists or not. This kills the feature because if you can't know which fonts exist, you can't check the first one in the list and then move on to another if it doesn't exist

**Comment by MinusGix** [comment]
> Yeah, that sounds easy on paper, but the problem is with the way Lapce checks for fonts. The code uses FontFamily::new_unchecked which can't determine if a font exists or not. This kills the feature because if you can't know which fonts exist, you can't check the first one in the list and then move on to another if it doesn't exist

This would primarily be done by storing like a `Vec<FontFamily>` in the config and then modifying our font code (parley probably?) to accept a list of font fallbacks whenever we create text. That already supports fallbacks, and it automatically includes some, but does not properly support adding fallbacks that aren't global. (I've got a partially-working version that does this locally, but it still needs various fixes)

**Comment by panekj** [comment]
This is done now in Floem
