### ISSUE TITLE
C++ code is not properly highlighted

### ISSUE THREAD

**Issue by bbrabbitt** [lapce/lapce#865]
Currently C++ code doesn't highlight well. Only a few keywords are get highlighted compare to other language highlighters, including C. I tested it on Mac, Windows and Linux with and without LSP installed and they all give the same outcome.
<img width="224" alt="Screen Shot 2022-07-25 at 2 05 55 AM" src="https://user-images.githubusercontent.com/10806961/180740531-4d66f6f5-1a82-4f2e-af49-2159b893f3e3.png">   <img width="200" alt="Screen Shot 2022-07-25 at 2 06 06 AM" src="https://user-images.githubusercontent.com/10806961/180740572-7fc5e8ac-438f-4df0-a0c9-8644d1d4a107.png">

**Comment by panekj** [comment]
fixed via #957 & https://github.com/lapce/lapce/pull/1145
