### ISSUE TITLE
Panic when using command line to open path that doesn't exist

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#868]
This should probably simply open the editor. Perhaps it should also show a notification (not that we have a nice method notifications yet?) about the folder not existing.  
(This should also be tested to see if it occurs if you open a nonexistent folder in the open folder dialog, but my file explorer updates quickly enough that I can't do that.)

**Comment by panekj** [comment]
This is fixed (I fixed it but I'll link general cli rewrite by dzhou because I'm too lazy to find my PR) #1003
