### ISSUE TITLE
In the terminal, text is not selectable and copy-paste isn't working

### ISSUE THREAD

**Issue by liyun-miao** [lapce/lapce#871]
In the terminal, I was able to execute commands; however, I wasn't able to select, copy, or paste any content. I would like to be able to select the content in the terminal so that I could copy it to the text editor.
I am using Lapce for Windows (version v0.1.3).

**Comment by BracketMaster** [comment]
Same for MacOS.

**Comment by vejnar** [comment]
Same for Linux.

**Comment by franklinblanco** [comment]
Duplicate of #726

**Comment by panekj** [comment]
Implemented in https://github.com/lapce/lapce/pull/1163

**Comment by Siddhartha351** [comment]
cant even change terminal from windows. its completely blank. help
