### ISSUE TITLE
Setting to control palette preview editor's width

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#872]
It would be useful to have a setting to make the preview editor wider, so that you can view more of the code. Currently it is just the width of the palette, which I think was recently shrunk.

**Comment by MinusGix** [comment]
Sure. You can ask questions here, or on the discord if you want.  
I'd suggest looking at  
- https://github.com/lapce/lapce/blob/master/lapce-data/src/config.rs for adding a new field (probably to the UI structure) for the palette's width
- Adding that field to https://github.com/lapce/lapce/blob/master/defaults/settings.toml with a default-value

And
https://github.com/lapce/lapce/blob/master/lapce-ui/src/palette.rs#L369-L383  
I think you'd need to modify the `bc` to have the width in the config (which you can get through `data.config.ui.whatever_you_name_the_field`) before it is passed to the preview's layout.  
Then maybe modifying the `content_size` widths to be roughly the `max(size.width, preview_width)`

**Comment by jmj0502** [comment]
Cool! I'll proceed to create a fork. I'll reach out in case I have any questions.

**Comment by jmj0502** [comment]
@MinusGix Hey! hope you're doing great! I think I'm almost done. However I have two questions.
1. How can I open the preview editor? (can't find any key bindings or docs about the feature).
2. Do have to write some sort of tests for this particular feature?

**Comment by MinusGix** [comment]
> How can I open the preview editor? (can't find any key bindings or docs about the feature).  
  
It is a part of the command palette for some commands. You can open it via the top bar (if you're on nightly/master) or through Ctrl+P (which is for opening files). Typing `@` will let you jump to a symbol in the current file, if you have the LSP installed and its initialized, and show a preview.  
![image](https://user-images.githubusercontent.com/13157904/181601231-84233c30-4175-4227-8031-049e74619c8c.png)
  
  
> Do have to write some sort of tests for this particular feature?  
  
No, you don't need too. For UI features like this there isn't really much point in writing tests for them.

**Comment by jmj0502** [comment]
@MinusGix Thanks! I'll check the changes in a few hours and if everything seems alright, I'll submit a PR 👍

**Comment by jmj0502** [comment]
@MinusGix 
 ![image](https://user-images.githubusercontent.com/50276574/181658401-15c21e87-a581-48b1-94d4-1bbfca7877ad.png)
I think it looks a little weird (that's on 750px). I will try to also add a `f64::max` comparison on the preview `bc`, since the UI also looks if the preview is smaller than the input bar

**Comment by jmj0502** [comment]
@MinusGix I'm done! ✌️ Had to make some additional changes, in order to keep the UI consistent.
