### ISSUE TITLE
ui: We can learn or take inspirations from jetbrains fleet, UI Aesthetic.

### ISSUE THREAD

**Issue by seanmrnda** [lapce/lapce#874]
Obviously, will not copy the UI but we can learn from it.

![main-window.eb97aaa10b27f40d7410a376690e32d0.png](https://user-images.githubusercontent.com/45195351/180914502-7401c73c-7b0b-44ce-ba11-dc0cebf288ff.png)

**Comment by schwrzstrbn** [comment]
- The "run/execute" button.

**Comment by schwrzstrbn** [comment]
- Downward arrow to the right side of the buttons that has menu.

**Comment by schwrzstrbn** [comment]
- File Icon on the tab session, title bar.

**Comment by panekj** [comment]
> * File Icon on the tab session, title bar.

What do you mean by that?

> * The "run/execute" button.

I'm not sure what are we supposed to take away from this? That's it's a "play" icon?

> * Downward arrow to the right side of the buttons that has menu.

That's tricky because not all our dropdown menus would look good with it, for example the remote button:
![image](https://user-images.githubusercontent.com/50457605/180946085-fe1f5b6b-f678-4902-86fe-056128047901.png)
For now I'm trying to just get hover effects on them so it conveys that those are buttons.

**Comment by schwrzstrbn** [comment]
> > * File Icon on the tab session, title bar.
> 
> What do you mean by that?
> 
> > * The "run/execute" button.
> 
> I'm not sure what are we supposed to take away from this? That's it's a "play" icon?
> 
> > * Downward arrow to the right side of the buttons that has menu.
> 
> That's tricky because not all our dropdown menus would look good with it, for example the remote button: ![image](https://user-images.githubusercontent.com/50457605/180946085-fe1f5b6b-f678-4902-86fe-056128047901.png) For now I'm trying to just get hover effects on them so it conveys that those are buttons.

guess we can only apply it to the right buttons then

**Comment by schwrzstrbn** [comment]
> > * File Icon on the tab session, title bar.
> 
> What do you mean by that?
> 
> > * The "run/execute" button.
> 
> I'm not sure what are we supposed to take away from this? That's it's a "play" icon?
> 
> > * Downward arrow to the right side of the buttons that has menu.
> 
> That's tricky because not all our dropdown menus would look good with it, for example the remote button: ![image](https://user-images.githubusercontent.com/50457605/180946085-fe1f5b6b-f678-4902-86fe-056128047901.png) For now I'm trying to just get hover effects on them so it conveys that those are buttons.

- Downward arrow for the git branch button, right side next to the text `master*`

**Comment by schwrzstrbn** [comment]
> > * File Icon on the tab session, title bar.
> 
> What do you mean by that?
> 
> > * The "run/execute" button.
> 
> I'm not sure what are we supposed to take away from this? That's it's a "play" icon?
> 
> > * Downward arrow to the right side of the buttons that has menu.
> 
> That's tricky because not all our dropdown menus would look good with it, for example the remote button: ![image](https://user-images.githubusercontent.com/50457605/180946085-fe1f5b6b-f678-4902-86fe-056128047901.png) For now I'm trying to just get hover effects on them so it conveys that those are buttons.

- Downward arrow for the git branch button, right side next to the text `master*`

**Comment by schwrzstrbn** [comment]
- Lighten up the font color in the UI. or we can add a way to customize the font of the UI.

**Comment by schwrzstrbn** [comment]
- Lighten up the font color of the UI. or we can add a way to customize the font of the UI.

**Comment by panekj** [comment]
It's already implemented...

**Comment by schwrzstrbn** [comment]
> It's already implemented...

yeah I figured it earlier, my comment deletion did not push thro.

**Comment by panekj** [comment]
Fixed/outdated
