### ISSUE TITLE
text-editor/highlighting: The highlighting looks weird.

### ISSUE THREAD

**Issue by schwrzstrbn** [lapce/lapce#878]
![image](https://user-images.githubusercontent.com/45195351/181057905-38c77b6c-d9b9-400c-982b-bded0a0068c6.png)

Ignore the code. Just focus on the highlighting.

Info:
Theme = "catpuccin mocha"
Build = nightly

**Comment by ghishadow** [comment]
I changed inlay hints background to grayish, upgrade theme and try
![image](https://user-images.githubusercontent.com/9583775/181167232-ac2ec391-f114-48cd-936b-65a019503cae.png)

**Comment by schwrzstrbn** [comment]
> I changed inlay hints background to grayish, upgrade theme and try
> ![image](https://user-images.githubusercontent.com/9583775/181167232-ac2ec391-f114-48cd-936b-65a019503cae.png)
> 

that looks good!

**Comment by schwrzstrbn** [comment]
> I changed inlay hints background to grayish, upgrade theme and try
> ![image](https://user-images.githubusercontent.com/9583775/181167232-ac2ec391-f114-48cd-936b-65a019503cae.png)
> 

what font are you using? I like it.

**Comment by ghishadow** [comment]
> what font are you using? I like it.
In this screenshot I am using Berkeley Mono (it is paid font) as I was unable to use Iosevka Custom on Windows, In Mac I use custom Iosevka build https://github.com/ghishadow/ghishadow-font. Another font I like is Martian Mono https://github.com/evilmartians/mono

**Comment by schwrzstrbn** [comment]
> > what font are you using? I like it.
> In this screenshot I am using Berkeley Mono (it is paid font) as I was unable to use Iosevka Custom on Windows, In Mac I use custom Iosevka build https://github.com/ghishadow/ghishadow-font. Another font I like is Martian Mono https://github.com/evilmartians/mono

thanks!!!!
