### ISSUE TITLE
lapce does not honor `~/.ssh/config` user?

### ISSUE THREAD

**Issue by dholth** [lapce/lapce#882]
When connecting to a Host alias from `~/.ssh/config`, lapce doesn't seem to use the default User. For example

```
Host ec2
	Hostname ...
	User ec2-user
	ForwardAgent yes
```

would have to be connected to as `ec2-user@ec2` instead of just `ec2` in lapce.

**Comment by panekj** [comment]
That's because it currently hardcodes it to `user@host` otherwise it connects as `root@host`, I'll work on this after fixing the directories.

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/1756 and 9a45b602bc42ecc27f3f5f7bc612a1e55820b48f
