### ISSUE TITLE
Compilation fails on macOS 10.14.6

### ISSUE THREAD

**Issue by videobitva** [lapce/lapce#888]
Rustc version: 1.62.1
Git branch: master
Commit: [95f1e7a](https://github.com/lapce/lapce/commit/95f1e7af021b9e681b15e03853cb6a854b9c7bc4)
Build fails while building the `tree-sitter-markdown` dependency
<details><summary>Cargo log</summary>
<p>
    ~/lapce$ cargo build --release                                                                                                                                                                           
    
Thu Jul 28 01:55:07 2022
   Compiling druid-shell v0.7.0 (https://github.com/lapce/druid?branch=shell_opengl#9f86f232)
   Compiling lapce-ui v0.1.3 (/Users/beatrice.raw/lapce/lapce-ui)
   Compiling druid-derive v0.4.0 (https://github.com/lapce/druid?branch=shell_opengl#9f86f232)
   Compiling tree-sitter-md v0.0.1 (https://github.com/dzhou121/tree-sitter-markdown.git#134c7f87)
   Compiling openssl-sys v0.9.74
   Compiling fount v0.1.0 (https://github.com/lapce/fount#02166f0f)
   Compiling lapce-rpc v0.1.3 (/Users/beatrice.raw/lapce/lapce-rpc)
   Compiling wasmer-wasi v2.3.0
   Compiling parley v0.1.0 (https://github.com/lapce/parley#6baaa02b)
   Compiling piet-wgpu v0.1.0 (https://github.com/lapce/piet-wgpu?branch=shell_opengl#6e268b3b)
The following warnings were emitted during compilation:

warning: tree-sitter-markdown/src/scanner.cc:67:6: error: ISO C++ forbids forward references to 'enum' types
warning: enum Block : uint8_t {
warning:      ^
warning: tree-sitter-markdown/src/scanner.cc:67:12: error: expected unqualified-id
warning: enum Block : uint8_t {
warning:            ^
warning: tree-sitter-markdown/src/scanner.cc:91:25: error: variable has incomplete type 'TreeSitterMarkdown::Block'
warning: bool is_list_item(Block block) {
warning:                         ^
warning: tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
warning: enum Block : uint8_t {
warning:      ^
warning: tree-sitter-markdown/src/scanner.cc:92:21: error: use of undeclared identifier 'LIST_ITEM'
warning:     return block >= LIST_ITEM && block <= LIST_ITEM_MAX_INDENTATION;
warning:                     ^
warning: tree-sitter-markdown/src/scanner.cc:92:43: error: use of undeclared identifier 'LIST_ITEM_MAX_INDENTATION'
warning:     return block >= LIST_ITEM && block <= LIST_ITEM_MAX_INDENTATION;
warning:                                           ^
warning: tree-sitter-markdown/src/scanner.cc:97:37: error: variable has incomplete type 'TreeSitterMarkdown::Block'
warning: uint8_t list_item_indentation(Block block) {
warning:                                     ^
warning: tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
warning: enum Block : uint8_t {
warning:      ^
warning: tree-sitter-markdown/src/scanner.cc:98:20: error: use of undeclared identifier 'LIST_ITEM'
warning:     return block - LIST_ITEM + 2;
warning:                    ^
warning: tree-sitter-markdown/src/scanner.cc:188:16: error: invalid application of 'sizeof' to an incomplete type 'TreeSitterMarkdown::Block'
warning:         assert(sizeof(Block) == sizeof(char));
warning:                ^     ~~~~~~~
warning: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
warning:     (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
warning:                         ^
warning: tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
warning: enum Block : uint8_t {
warning:      ^
warning: tree-sitter-markdown/src/scanner.cc:310:58: error: use of undeclared identifier 'INDENTED_CODE_BLOCK'
warning:                     if (!simulate) open_blocks.push_back(INDENTED_CODE_BLOCK);
warning:                                                          ^
warning: tree-sitter-markdown/src/scanner.cc:387:34: error: argument type 'TreeSitterMarkdown::Block' is incomplete
warning:                 if (match(lexer, open_blocks[matched])) {
warning:                                  ^~~~~~~~~~~~~~~~~~~~
warning: tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
warning: enum Block : uint8_t {
warning:      ^
warning: tree-sitter-markdown/src/scanner.cc:413:23: error: variable has incomplete type 'TreeSitterMarkdown::Block'
warning:                 Block block = open_blocks[open_blocks.size() - 1];
warning:                       ^
warning: tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
warning: enum Block : uint8_t {
warning:      ^
warning: tree-sitter-markdown/src/scanner.cc:415:30: error: use of undeclared identifier 'FENCED_CODE_BLOCK'
warning:                 if (block == FENCED_CODE_BLOCK) {
warning:                              ^
warning: tree-sitter-markdown/src/scanner.cc:454:38: error: argument type 'TreeSitterMarkdown::Block' is incomplete
warning:                     if (match(lexer, open_blocks[matched])) {
warning:                                      ^~~~~~~~~~~~~~~~~~~~
warning: tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
warning: enum Block : uint8_t {
warning:      ^
warning: tree-sitter-markdown/src/scanner.cc:510:38: error: variable has incomplete type 'TreeSitterMarkdown::Block'
warning:     bool match(TSLexer *lexer, Block block) {
warning:                                      ^
warning: tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
warning: enum Block : uint8_t {
warning:      ^
warning: tree-sitter-markdown/src/scanner.cc:605:54: error: use of undeclared identifier 'FENCED_CODE_BLOCK'
warning:                 if (!simulate) open_blocks.push_back(FENCED_CODE_BLOCK);
warning:                                                      ^
warning: tree-sitter-markdown/src/scanner.cc:694:56: error: use of undeclared identifier 'LIST_ITEM'
warning:             if (!simulate) open_blocks.push_back(Block(LIST_ITEM + extra_indentation));
warning:                                                        ^
warning: tree-sitter-markdown/src/scanner.cc:735:50: error: use of undeclared identifier 'BLOCK_QUOTE'
warning:             if (!simulate) open_blocks.push_back(BLOCK_QUOTE);
warning:                                                  ^
warning: tree-sitter-markdown/src/scanner.cc:801:60: error: use of undeclared identifier 'LIST_ITEM'
warning:                 if (!simulate) open_blocks.push_back(Block(LIST_ITEM + extra_indentation));
warning:                                                            ^
warning: tree-sitter-markdown/src/scanner.cc:850:68: error: use of undeclared identifier 'LIST_ITEM'
warning:                         if (!simulate) open_blocks.push_back(Block(LIST_ITEM + extra_indentation + digits));
warning:                                                                    ^
warning: fatal error: too many errors emitted, stopping now [-ferror-limit=]
warning: 20 errors generated.

error: failed to run custom build command for `tree-sitter-md v0.0.1 (https://github.com/dzhou121/tree-sitter-markdown.git#134c7f87)`

Caused by:
  process didn't exit successfully: `/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-cad65c7794ed7909/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "tree-sitter-markdown/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wno-trigraphs" "-o" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/tree-sitter-markdown/src/parser.o" "-c" "tree-sitter-markdown/src/parser.c"
  exit status: 0
  AR_x86_64-apple-darwin = None
  AR_x86_64_apple_darwin = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/libparser_block.a" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/tree-sitter-markdown/src/parser.o"
  exit status: 0
  running: "ar" "s" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/libparser_block.a"
  exit status: 0
  cargo:rustc-link-lib=static=parser_block
  cargo:rustc-link-search=native=/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out
  cargo:rerun-if-changed=tree-sitter-markdown/src/parser.c
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "tree-sitter-markdown-inline/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wno-trigraphs" "-o" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/tree-sitter-markdown-inline/src/parser.o" "-c" "tree-sitter-markdown-inline/src/parser.c"
  exit status: 0
  AR_x86_64-apple-darwin = None
  AR_x86_64_apple_darwin = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/libparser_inline.a" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/tree-sitter-markdown-inline/src/parser.o"
  exit status: 0
  running: "ar" "s" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/libparser_inline.a"
  exit status: 0
  cargo:rustc-link-lib=static=parser_inline
  cargo:rustc-link-search=native=/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out
  cargo:rerun-if-changed=tree-sitter-markdown-inline/src/parser.c
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-apple-darwin")
  CXX_x86_64-apple-darwin = None
  CXX_x86_64_apple_darwin = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-apple-darwin = None
  CXXFLAGS_x86_64_apple_darwin = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  CXX_x86_64-apple-darwin = None
  CXX_x86_64_apple_darwin = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-apple-darwin = None
  CXXFLAGS_x86_64_apple_darwin = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  CXX_x86_64-apple-darwin = None
  CXX_x86_64_apple_darwin = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-apple-darwin = None
  CXXFLAGS_x86_64_apple_darwin = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "tree-sitter-markdown/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-o" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/tree-sitter-markdown/src/scanner.o" "-c" "tree-sitter-markdown/src/scanner.cc"
  cargo:warning=tree-sitter-markdown/src/scanner.cc:67:6: error: ISO C++ forbids forward references to 'enum' types
  cargo:warning=enum Block : uint8_t {
  cargo:warning=     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:67:12: error: expected unqualified-id
  cargo:warning=enum Block : uint8_t {
  cargo:warning=           ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:91:25: error: variable has incomplete type 'TreeSitterMarkdown::Block'
  cargo:warning=bool is_list_item(Block block) {
  cargo:warning=                        ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
  cargo:warning=enum Block : uint8_t {
  cargo:warning=     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:92:21: error: use of undeclared identifier 'LIST_ITEM'
  cargo:warning=    return block >= LIST_ITEM && block <= LIST_ITEM_MAX_INDENTATION;
  cargo:warning=                    ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:92:43: error: use of undeclared identifier 'LIST_ITEM_MAX_INDENTATION'
  cargo:warning=    return block >= LIST_ITEM && block <= LIST_ITEM_MAX_INDENTATION;
  cargo:warning=                                          ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:97:37: error: variable has incomplete type 'TreeSitterMarkdown::Block'
  cargo:warning=uint8_t list_item_indentation(Block block) {
  cargo:warning=                                    ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
  cargo:warning=enum Block : uint8_t {
  cargo:warning=     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:98:20: error: use of undeclared identifier 'LIST_ITEM'
  cargo:warning=    return block - LIST_ITEM + 2;
  cargo:warning=                   ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:188:16: error: invalid application of 'sizeof' to an incomplete type 'TreeSitterMarkdown::Block'
  cargo:warning=        assert(sizeof(Block) == sizeof(char));
  cargo:warning=               ^     ~~~~~~~
  cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
  cargo:warning=    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
  cargo:warning=                        ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
  cargo:warning=enum Block : uint8_t {
  cargo:warning=     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:310:58: error: use of undeclared identifier 'INDENTED_CODE_BLOCK'
  cargo:warning=                    if (!simulate) open_blocks.push_back(INDENTED_CODE_BLOCK);
  cargo:warning=                                                         ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:387:34: error: argument type 'TreeSitterMarkdown::Block' is incomplete
  cargo:warning=                if (match(lexer, open_blocks[matched])) {
  cargo:warning=                                 ^~~~~~~~~~~~~~~~~~~~
  cargo:warning=tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
  cargo:warning=enum Block : uint8_t {
  cargo:warning=     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:413:23: error: variable has incomplete type 'TreeSitterMarkdown::Block'
  cargo:warning=                Block block = open_blocks[open_blocks.size() - 1];
  cargo:warning=                      ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
  cargo:warning=enum Block : uint8_t {
  cargo:warning=     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:415:30: error: use of undeclared identifier 'FENCED_CODE_BLOCK'
  cargo:warning=                if (block == FENCED_CODE_BLOCK) {
  cargo:warning=                             ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:454:38: error: argument type 'TreeSitterMarkdown::Block' is incomplete
  cargo:warning=                    if (match(lexer, open_blocks[matched])) {
  cargo:warning=                                     ^~~~~~~~~~~~~~~~~~~~
  cargo:warning=tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
  cargo:warning=enum Block : uint8_t {
  cargo:warning=     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:510:38: error: variable has incomplete type 'TreeSitterMarkdown::Block'
  cargo:warning=    bool match(TSLexer *lexer, Block block) {
  cargo:warning=                                     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:67:6: note: forward declaration of 'TreeSitterMarkdown::Block'
  cargo:warning=enum Block : uint8_t {
  cargo:warning=     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:605:54: error: use of undeclared identifier 'FENCED_CODE_BLOCK'
  cargo:warning=                if (!simulate) open_blocks.push_back(FENCED_CODE_BLOCK);
  cargo:warning=                                                     ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:694:56: error: use of undeclared identifier 'LIST_ITEM'
  cargo:warning=            if (!simulate) open_blocks.push_back(Block(LIST_ITEM + extra_indentation));
  cargo:warning=                                                       ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:735:50: error: use of undeclared identifier 'BLOCK_QUOTE'
  cargo:warning=            if (!simulate) open_blocks.push_back(BLOCK_QUOTE);
  cargo:warning=                                                 ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:801:60: error: use of undeclared identifier 'LIST_ITEM'
  cargo:warning=                if (!simulate) open_blocks.push_back(Block(LIST_ITEM + extra_indentation));
  cargo:warning=                                                           ^
  cargo:warning=tree-sitter-markdown/src/scanner.cc:850:68: error: use of undeclared identifier 'LIST_ITEM'
  cargo:warning=                        if (!simulate) open_blocks.push_back(Block(LIST_ITEM + extra_indentation + digits));
  cargo:warning=                                                                   ^
  cargo:warning=fatal error: too many errors emitted, stopping now [-ferror-limit=]
  cargo:warning=20 errors generated.
  exit status: 1

  --- stderr

error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "tree-sitter-markdown/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-o" "/Users/beatrice.raw/lapce/target/release/build/tree-sitter-md-e0021bdc2e08dcc5/out/tree-sitter-markdown/src/scanner.o" "-c" "tree-sitter-markdown/src/scanner.cc" with args "c++" did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...
</p>
</details>

**Comment by panekj** [comment]
this should be fixed now
