### ISSUE TITLE
Line counter out of sync with source text

### ISSUE THREAD

**Issue by Evrey** [lapce/lapce#89]
![image](https://user-images.githubusercontent.com/6483505/156572006-63ffdeb9-9219-4d77-b96e-4d16e54cf8df.png)
~~My guess: Line counter does not respect font, font size, and line height settings.~~

Displacement seems constant. Same file:
![image](https://user-images.githubusercontent.com/6483505/156572789-8e2e95ab-a082-4e95-9c70-fc7264985cac.png)

**Comment by bugadani** [comment]
Hi and thanks for reporting this issue!

I'm not able to reproduce it. Could you please confirm this issue is still present for you? If so, what fonts and line heights do you use? Thanks!

**Comment by panekj** [comment]
Treating as resolved
