### ISSUE TITLE
Command shortcuts are dead on MacOS

### ISSUE THREAD

**Issue by Ducktape10** [lapce/lapce#894]
In MacOS some of the key shortcuts/symbolds are not working. For me Commands shortcuts are dead. Only the settings cmd shortcut works.

MacOS Monterey v12.4

Macbook Air 2018

**Comment by MinusGix** [comment]
Do you know what key layout you're using? There's some existing bugs for German/Spanish key layouts on MacOS.

**Comment by Ducktape10** [comment]
Hungarian layout, but I use karabiner layout changer because of im new macos user. I tried without it but same problem.

**Comment by panekj** [comment]
Duplicate of #1094
