### ISSUE TITLE
shortcut don't work in other languages

### ISSUE THREAD

**Issue by yzn-h** [lapce/lapce#898]
when I switch to Arabic I cant ctrl+z i have to switch layout to undo :(

**Comment by MinusGix** [comment]
Is this a different keyboard layout? If so, what operating system are you on?

**Comment by yzn-h** [comment]
I'm using pop os
when i use the defulte arabic layout i cant ctrl+z but when using the defulte english layout ctrl+z work

**Comment by Mart-Bogdan** [comment]
I can confirm. Same here, on Windows 10. 
Having Cyrillic keyboard layout.
