### ISSUE TITLE
[feature request] VIM plugin. 

### ISSUE THREAD

**Issue by overheat** [lapce/lapce#90]
Hi,

This is an awesome project!
It will be better if we can have a VIM editor plugin.

**Comment by Evrey** [comment]
It does apparently have built-in Vim modal editing. That what you were asking for?
![image](https://user-images.githubusercontent.com/6483505/156582689-055b66d3-e7ce-426d-b3af-54bc3e8fc62c.png)

**Comment by overheat** [comment]
Yes, I think so.
But it not work on my Macbook.
I will add another issue. Thanks.
