### ISSUE TITLE
Add a command to toggle inlay hints

### ISSUE THREAD

**Issue by rtsuk** [lapce/lapce#904]
I find the inlay hints very distracting most of the time, but could imagine wanting to look at them from time to time.

**Comment by Tatskaari** [comment]
Would love to be able to hold `alt` or something like that. Related to #559.

**Comment by MinusGix** [comment]
> Would love to be able to hold `alt` or something like that. Related to #559.

Hm, that would be a nice general feature to allow having keymaps that 'onholdstart -> Send Command; onholdend -> Send Command again'. (Though some commands aren't really toggle-like)

**Comment by sanxiyn** [comment]
I think this issue should be closed. (The command exists and I use it daily.) Additional ideas should be created as a new issue.

**Comment by panekj** [comment]
This has been implemented
