### ISSUE TITLE
How to sepcific ssh port in remote development?

### ISSUE THREAD

**Issue by Smith-Cruise** [lapce/lapce#906]
How to sepcific ssh port in remote development?

**Comment by panekj** [comment]
Currently not possible

**Comment by dzhou121** [comment]
Doesn’t user@host:port work?

**Comment by Smith-Cruise** [comment]
> Doesn’t user@host:port work?

Maybe you should add it in the doc.
I tried various commands except this one.

**Comment by Smith-Cruise** [comment]
Don't support passphraseless login?

**Comment by panekj** [comment]
It currently uses `ssh` command from your host, so if you have running agent and proper user/key, it should work without password

**Comment by Smith-Cruise** [comment]
> 

I've tried, but it didn't work, sadness.

**Comment by Smith-Cruise** [comment]
> It currently uses `ssh` command from your host, so if you have running agent or ssh config and proper user/key, it should work without password
> 
> > Doesn’t user@host:port work?
> 
> I think last time I tried it, it didn't work, but it could have been different issue (:

I've tried too, but it didn't work.

**Comment by ImBearChild** [comment]
> I think last time I tried it, it didn't work, but it could have been different issue (:

They way that lapce call ssh command make it take `"{user}@{host}"` as one parameter, so something like `"tux@127.0.0.1 -p2222"` will parse as a host called `127.0.0.1 -p2222`.

```
    fn command_builder(user: &str, host: &str) -> Command {
        let mut cmd = new_command("ssh");
        cmd.arg(format!("{}@{}", user, host)).args(Self::SSH_ARGS);
        cmd
    }
```

**Comment by panekj** [comment]
I have a fix ready for this, just need to discuss on the approach

**Comment by ImBearChild** [comment]
> I have a fix ready for this, just need to discuss on the approach

OK, I guess I'm just late for one minute. Should I close my draft pull request now, or just leave it there?

**Comment by panekj** [comment]
You can leave it open, I'm waiting for dzhou to comment on my way of solving it (:

**Comment by guohao117** [comment]
Hi, you can use the ~/.ssh/config to specify different port then use "user@host" to connect remote in Lapce.

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/1755
