### ISSUE TITLE
How to jump between tabs with keyboard shortcuts?

### ISSUE THREAD

**Issue by dpcat237** [lapce/lapce#907]
I want to jump between tabs with keyboard shortcuts but any shortcut didn't work for me. I tried these shortcuts:
editor_tab_previous
editor_tab_next
Go To Next Window Tab
Go To Previous Window Tab

It would be nice if you could clarify if I'm using the wrong shortcuts or are some bug.

**Comment by panekj** [comment]
`editor_tab_previous` and `editor_tab_next` work for me, which version of lapce are you using?

**Comment by dpcat237** [comment]
version: v0.1.3
layout: English (US)
OS: Ubuntu 22.04

I just tried again with different keys but it didn't work for me. What keys do you use for these shortcuts? To try the same.

**Comment by panekj** [comment]
By default they are `Ctrl` + `Tab` and `Ctrl` + `Shift` + `Tab`

**Comment by dpcat237** [comment]
Hhmm. For me, there weren't set. I just set them this way but they don't work :( 
I'm thinking that it's related to Wayland (Ubuntu) but it's strange that some other shortcuts work. Like: open a new tab, closing tab, interactions with text, etc.

**Comment by dpcat237** [comment]
After updating to v0.2.0 switch between tabs works correctly :smiley:
