### ISSUE TITLE
Enable modal editing (Vim like) not works.

### ISSUE THREAD

**Issue by overheat** [lapce/lapce#91]
![image](https://user-images.githubusercontent.com/4322417/156583573-5fd338f7-89eb-406f-a036-5de38ae7c1f8.png)

Version: 0.10.0-dev(1)
MacOS Monterey

**Comment by awsa2ron** [comment]
Also on Ubuntu 20.04.1

**Comment by bugadani** [comment]
Apart from a sligth issue with the settings UI, I can enable modal editing just fine. Could you please confirm this issue is still present for you?

**Comment by anomalyze** [comment]
This seems to work fine for me on Debian 11.3
