### ISSUE TITLE
bug after install rust plugin

### ISSUE THREAD

**Issue by jianshu93** [lapce/lapce#912]
Hello team,

The newest release 0.1.3 on macOS I always have the following highlights, which I cannot make any change using keyboard:

![Screen Shot 2022-08-01 at 1 22 52 AM](https://user-images.githubusercontent.com/38149286/182077748-35c3a34c-5052-4749-b058-2cf7299e818f.png)

I cannot do anything to the blue highlighted text. Even after reinstall it, still the same.

Any idea?

Thanks,

Jianshu

**Comment by panekj** [comment]
Those are inlay hints, they usually show inferred type of variables

**Comment by ghishadow** [comment]
master has toggle inlay hints with which you can disable it if you want

**Comment by jianshu93** [comment]
Thanks！ I do not want to delete the entire type and reenter in a lot of cases.

Thanks

Jianshu

**Comment by jianshu93** [comment]
Hello Team,

I have another question related to installed plugins. How do I uninstall it? I noticed that memory consumption of just one window for rust plugin is already 500M, 2 windows will be like 700M+ and three windows 1+ Gb. This is not very efficient in terms of memory? If 2 windows are showing the same language, why memory increases by that much, assuming that the code hints module of a give language is the same for all windows?

Thanks,

Jianshu

**Comment by panekj** [comment]
Memory increases depending on how much rust-analyzer has to know about workspace.
Disabling/uninstalling plugins will be available in next release.

**Comment by panekj** [comment]
> If 2 windows are showing the same language, why memory increases by that much, assuming that the code hints module of a give language is the same for all windows?

It doesn't work that way

**Comment by jianshu93** [comment]
Thanks for the quick response. I will just work in less than 2 windows and wait for new release (some times only one is needed to code while others windows are for reference et.al.  but any way I get it.)

Thanks,

Jianshu

**Comment by jianshu93** [comment]
Interesting is even though you close the second window but keep only one, memory will still be 700M+ instead of going back to ~500M unless you complete close all windows and reopen. Just for your reference. I am particularly fastidious about memory consumption for code editors and I hate  Visual studio code and other editors because of this.

Thanks,

Jianshu

**Comment by panekj** [comment]
> Interesting is even though you close the second window but keep only one, memory will still be 700M+

Probably because you are using 0.1.3 version that doesn't have fix for closing LSP servers

**Comment by jianshu93** [comment]
Yes I am using 0.1.3. Does the nightly version work?


Jianshu

**Comment by panekj** [comment]
> Does the nightly version work?

It has the fix, yes

**Comment by panekj** [comment]
Performance issues has been fixed
