### ISSUE TITLE
HTML code completion support

### ISSUE THREAD

**Issue by Freemason-12** [lapce/lapce#917]
I'm considering this text editor as an alternative for sublime or vscode, but there seems to be no HTML/CSS/JS code completion like in VSCode. Am I missing something or, if not, when could this be implemented?

**Comment by MinusGix** [comment]
This is primarily dependent on someone making a HTML / CSS / JS plugin using a Language Server for those languages.

**Comment by Freemason-12** [comment]
Oh, well. Are there such plugin for this software then?
I see some code completion demos in README. Is it built in or some plugin is needed?

**Comment by panekj** [comment]
There is a plugin for Rust available which is used in the demo.

**Comment by chirok11** [comment]
HTML either JS LSP could be https://github.com/typescript-language-server/typescript-language-server. Used in VSCode and 
 in many other editors.
I tried to make plugin for Lapce, unfortunately completetion very slow (but in VS it's faster), and treesitter syntax hightlight is get broke.
**https://github.com/chirok11/lapce-tsserver**
But you have to install and place binary in /usr/bin/typescript-language-server, either edit plugin instead with filling new location.
Will work on master (in cause of new language ids commit was not far ago)

**Comment by panekj** [comment]
Typescript/Javascript plugin is available, other plugins might be available at some point
