### ISSUE TITLE
[WINDOWS] Lapce does't respect indentation

### ISSUE THREAD

**Issue by yashwanthreddyg** [lapce/lapce#92]
![image](https://user-images.githubusercontent.com/7929962/156644364-e992d351-631f-4d10-a9a6-f499e2993eb7.png)

Left is Lapce, right is VS Code

**Comment by dzhou121** [comment]
should be fixed by the latest release v0.0.10

**Comment by bugadani** [comment]
Thanks for reporting this issue! I'm closing this because it has been fixed. However, feel free to reopen if you still experience this issue!
