### ISSUE TITLE
Brackets complete

### ISSUE THREAD

**Issue by Monkeyman520** [lapce/lapce#920]
I finished a [gopls-based lapce plugin for go](https://github.com/Monkeyman520/lapce-go), but in the process of using it, I found that bracket completion (typing pairs of brackets at once and moving the input cursor into the middle of the brackets) is a big problem, how should I solve it?

**Comment by nheuillet** [comment]
Hello,

I can't seem to reproduce the issue. What exactly is the problem for you? Also, what is your OS, and Lapce version?

For your information, there is already another [gopls-based lapce plugin for go](https://github.com/nheuillet/lapce-go) :)

**Comment by Monkeyman520** [comment]
Hello.
Here's what I mean by the description,the image above is from lapce,the image below is from vscode,obviously, having the bracket-completion feature gives us developers a better experience,so I hope you can answer my questions about this.
![image](https://user-images.githubusercontent.com/55369727/182613754-a9f2af5d-fe18-4963-b3e2-939ca814a872.png)
![image](https://user-images.githubusercontent.com/55369727/182613769-df2c495b-6fcd-4a4f-8bcf-4e9fbb5deaf6.png)

**Comment by nheuillet** [comment]
Okay, I see what you mean, you'd like Lapce to move in between the brackets automatically. This is not something on the LSP side but on Lapce's side, and should not be too difficult to implement.

@MinusGix I believe this could be labeled as "Good first issue", as it's quite literally moving the cursor by one on the right.

> Following your link, I looked at your plugin code and it was very enlightening, but I still strongly recommend that you use Golang's own env command, as there are no relevant definitions for GOPATH and GOBIN in my computer's environment variables（PATH）.
Yes, there is definitely work to do on that part, but I have not looked into it yet. I've been experimenting with the Plugin API design (which should be coming soon as it's the main priority right now). Once the plugin API is out, the current functions will be obsolete and most likely will break.

Do note that executing commands straight from your plugin will not work as the runtime of each plugin is confined to its own folder.

**Comment by Monkeyman520** [comment]
> Do note that executing commands straight from your plugin will not work as the runtime of each plugin is confined to its own folder.

I was already aware of this problem during the quiz phase, so I strongly suggest that such features (LSP missing etc...) can be Add Command Palette, similar to VScode.
![image](https://user-images.githubusercontent.com/55369727/182629886-a48876d5-8d20-46d3-bb29-1032b32672eb.png)
Hopefully it is built in as a plug-in feature with event listening and presentation by the editor.I think this is a better solution.

**Comment by panekj** [comment]
> I was already aware of this problem during the quiz phase, so I strongly suggest that such features (LSP missing etc...) can be Add Command Palette, similar to VScode.

This depends on plugin API which is still non-existent

**Comment by nheuillet** [comment]
> I was already aware of this problem during the quiz phase, so I strongly suggest that such features (LSP missing etc...) can be Add Command Palette, similar to VScode.

This is one of the features mentioned during the initial brainstorm of the API yes

**Comment by Monkeyman520** [comment]
If you are interested in my ideas, I can implement them as my immediate work

**Comment by Monkeyman520** [comment]
If I want to contribute to this project, which branch should I start from?

**Comment by MinusGix** [comment]
> If I want to contribute to this project, which branch should I start from?

If you're referring to Lapce, then the master branch.

**Comment by panekj** [comment]
> If you are interested in my ideas, I can implement them as my immediate work

You have to wait for plugin API

> If I want to contribute to this project, which branch should I start from?

`master`

**Comment by Monkeyman520** [comment]
Do you have a good idea for the plugin-api or have you implemented it so far?

**Comment by dzhou121** [comment]
> Do you have a good idea for the plugin-api or have you implemented it so far?

It's being actively worked on as part of this PR https://github.com/lapce/lapce/pull/893

**Comment by ki9gpin** [comment]
Is the bracket-completion ("Good First Issue" part ) still non-existent?
I would love to implement . 
Which file should I start with ? 

@nheuillet

**Comment by nheuillet** [comment]
@ki9gpin It's already been implemented actually! The cursors automatically skips to the middle of the brackets and other symbols - [], (), etc.

@panekj This issue can be closed I believe
