### ISSUE TITLE
Show path to active tab file relative to the top folder

### ISSUE THREAD

**Issue by h5rdly** [lapce/lapce#922]
Hi,

First of all.. finally! This project is awesome. 

I wanted to ask whether it would be possible to show the path to the current file.

Sublime does it in the upper title line, where Lapce shows the folder name. 

The line below that, where the settings button is, also seems available :)

Thanks,
Eli

**Comment by cauebs** [comment]
Perhaps the path can be shown when hovering over the tab name.

**Comment by panekj** [comment]
Path is shown in file explorer tab
![image](https://user-images.githubusercontent.com/50457605/188384673-33cbcb6d-04cd-4697-9da4-853c5ab2c9d5.png)

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/pull/1521
