### ISSUE TITLE
Compilation fails in openSUSE Open Build Service

### ISSUE THREAD

**Issue by uncomfyhalomacro** [lapce/lapce#934]
Relevant logs: 
  * https://build.opensuse.org/build/editors/openSUSE_Tumbleweed/aarch64/lapce/_log
  * https://build.opensuse.org/build/editors/openSUSE_Tumbleweed/x86_64/lapce/_log

Build fails while building the `tree-sitter-markdown` dependency.

Probably related to #888 even though that is a different OS

**Comment by uncomfyhalomacro** [comment]
Turns out:

```
[  168s]   running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-unknown-linux-gnu" "-I" "tree-sitter-markdown/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wno-unused-but-set-variable" "-Wno-trigraphs" "-o" "/home/abuild/rpmbuild/BUILD/lapce-e65e40a8d352e6b26a337419c82d5b406d3cf2fc/target/release-lto/build/tree-sitter-md-d3ecf4f6a129f926/out/tree-sitter-markdown/src/parser.o" "-c" "tree-sitter-markdown/src/parser.c"
[  168s]   cargo:warning=clang-14.0: error: no such file or directory: 'tree-sitter-markdown/src/parser.c'
[  168s]   cargo:warning=clang-14.0: error: no input files
[  168s]   exit status: 1
[  168s] 
``` It is missing a directory

```
$ tree                         
.
├── bindings
│   └── rust
│       ├── build.rs
│       └── lib.rs
├── Cargo.lock
└── Cargo.toml

2 directories, 4 files
```

**Comment by uncomfyhalomacro** [comment]
i think i found out why. i will open a pr later to tree-sitter-markdown fork

**Comment by uncomfyhalomacro** [comment]
Turns out it is a bug in cargo vendor. I wonder how to fix it though

**Comment by panekj** [comment]
This should be fixed now
