### ISSUE TITLE
Code Lens on Windows

### ISSUE THREAD

**Issue by 6rube** [lapce/lapce#949]
Code Lens is not working correctly under Windows. After pressing crtl+e it looks like the picture below.  When i try to collapse the Code it stays small until i change something.

Specs:
- Win11 x64
- Intel Core Xeon E-2274G
- NVIDIA GTX 1050 Ti

![image](https://user-images.githubusercontent.com/47418292/183866357-281eb940-ddee-4107-b358-5dae455a5a7a.png)

**Comment by panekj** [comment]
Is that version 0.1.3

**Comment by 6rube** [comment]
yes

**Comment by panekj** [comment]
This should be fixed in 0.2.0
