### ISSUE TITLE
FreeBSD port / vendor OpenSSL issue

### ISSUE THREAD

**Issue by nunotexbsd** [lapce/lapce#967]
Hello,

I'm porting lapce to FreeBSD but ports framework gives me the following warning:
```
Please make sure this port uses the system OpenSSL and consider removing
CARGO_CRATES=openssl-src-111.21.0+1.1.1p (a vendored copy of OpenSSL) from
the build, e.g., by patching Cargo.toml appropriately.
```
Is there a way to avoid:
```
[[package]]
name = "openssl-src"
version = "111.21.0+1.1.1p"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "6d0a8313729211913936f1b95ca47a5fc7f2e04cd658c115388287f8a8361008"
dependencies = [
 "cc",
]
```
and use FreeBSD OpenSSL?

Thanks,
Nuno Teixeira

**Comment by MinusGix** [comment]
You probably need to mess with features for both https://docs.rs/reqwest/latest/reqwest/ and https://github.com/rust-lang/git2-rs/, which we use and depend  on the openssl-src crate. Maybe just reqwest's `native-tls` feature is needed to be enabled?

**Comment by panekj** [comment]
https://github.com/lapce/lapce/blob/796008be88a3e195a24f7aa6584cc029054761bc/.github/workflows/release.yml#L139
this should be just enough

**Comment by nunotexbsd** [comment]
I switched to 796008b but it still fetches openssl-src-111.22.0+1.1.1q from cargo.lock and if I remove it:

```
===>   Updating Cargo.lock
error: no matching package found
searched package name: `openssl-src`
perhaps you meant:      openssl-sys
location searched: registry `crates-io`
required by package `openssl-sys v0.9.75`
    ... which satisfies dependency `openssl-sys = "^0.9.0"` of package `git2 v0.14.4`
    ... which satisfies dependency `git2 = "^0.14.4"` of package `lapce-proxy v0.1.3 (/usr/home/nunotex/Work/freebsd/ports/editors/lapce/work/lapce-796008b/lapce-proxy)`
    ... which satisfies path dependency `lapce-proxy` of package `lapce v0.1.3 (/usr/home/nunotex/Work/freebsd/ports/editors/lapce/work/lapce-796008b)`
*** Error code 101
```

Any hints?

**Comment by panekj** [comment]
It will be fetched no matter what unless you patch out `Cargo.toml`'s to not include any (default) features that can pull in `openssl-src` and update the lockfile.

**Comment by nunotexbsd** [comment]
The only occurrence that I found is: `lapce-proxy/Cargo.toml:git2 = { version = "0.14.4", features = ["vendored-openssl"] }`.

What should be changed?

**Comment by panekj** [comment]
```diff
diff --git a/lapce-proxy/Cargo.toml b/lapce-proxy/Cargo.toml
index ac93cbf..f7b2fd5 100644
--- a/lapce-proxy/Cargo.toml
+++ b/lapce-proxy/Cargo.toml
@@ -32,7 +32,7 @@ serde_json = "1.0.59"
 anyhow = "1.0.32"
 home = "0.5.3"
 toml_edit = { version = "0.14.4", features = ["easy"] }
-git2 = { version = "0.14.4", features = ["vendored-openssl"] }
+git2 = { version = "0.14.4", features = [] }
 lapce-core = { path = "../lapce-core" }
 lapce-rpc = { path = "../lapce-rpc" }
 trash = "2.1"

```

**Comment by nunotexbsd** [comment]
Hi,

Ok. I think it's better to build it without removing vendor openssl for now and for better debugging on what's is happening.
I've made a FreeBSD port at [PR265592](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265892) and there's a url link for build log. I now use poudriere clean environment build tool to make it better for debug.
(Patch for removing vendor openssl is present but not in use.)

What make me to retrocess about removing vendor openssl is because I noticed that there are ports with the same issue like [gitui](https://github.com/extrawurst/gitui) in the port [devel/gitui](https://www.freshports.org/devel/gitui/) so it is better to take that issue when I have a working/buildable port.

I think you help me enough and I thank you for that because I learned more about rust/cargo mechanics.
It will very nice if you could take a look at PR, patch have comments on it to easier debug.

Cheers,
Nuno Teixeira

**Comment by nunotexbsd** [comment]
FreeBSD PR: [265892](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265892)

**Comment by panekj** [comment]
I believe this has been resolved

**Comment by nunotexbsd** [comment]
Hi @panekj!

Yes it is, sorry I forgot to close it.

I'm having troubles adding FreeBSD target to druid, could you please take a look at https://github.com/linebender/druid/pull/2249 when you have the time?

Cheers and thanks for your great help!
