### ISSUE TITLE
Petition to change the project's name

### ISSUE THREAD

**Issue by azizk** [lapce/lapce#973]
Hi!

I'm glad to have discovered this project recently and I've started to take a keen interest in its development.

To me it looks highly promising considering – among other great things – it's written in Rust from scratch and it's using the tree-sitter language grammars.

However, I'm not particularly fond of the name. I hope you'd agree that the name of a software application – even if it's mainly for developers – does play a role in its potential and ability for gaining popularity and a role in its adoption.

I think with "lapce" the main issue is that it's hard to determine how to pronounce it. It just doesn't roll off the tongue. This will affect how presenters, reviewers etc. will talk about it and in turn it will affect the adoption rate.

I realize there's a website domain, screenshots and code and everything, but in my opinion the name is so important that it would be worth the trouble to at least rename the GUI labels and titles.

So here are two alternatives I would like to suggest for now:

1. **lapiz:** from the Spanish *lápiz* which means pencil. I think this one is very apt because the pencil is a writing tool and you're writing code with it so to speak. I've done some research and it seems it's not really taken by other projects. Best thing is that the pronunciation is unambiguous and it still fits the logo.
2. **lapice:** adding the vowel *i* makes it much easier to read / pronounce. But is it pronounced "lap-ice"? Or would people more likely say "lapiece"? It's ambiguous. You could come up with a meaning for the *i* so that the acronym still works.

Personally, I would definitely go with the 1st suggestion.

Hoping you'll consider my petition and also see what others have to say!

**Comment by felipetesc** [comment]
If the idea is to change the name, why not :
3. Rogue Coder
4. Rebel Coder
5. Rough coder
R's from Rust
6. Corrosion Builder
7. Corrosive
8. Alloy Coder
9. Galvanizer
10. Rusting

**Comment by azizk** [comment]
Or simply:

11. Rust Coder

:smile:

**Comment by panekj** [comment]
Hi, I would recommend joining Lapce Discord server as we discuss this, but overall decision is that Lapce will not be renamed (we are still discussing how it's pronounced)

**Comment by panekj** [comment]
> 11\. Rust Coder

I'm not a legal expert but I think that would put us in trouble with `Rust` trademark which I would love to avoid (even though the project is written in Rust programming language it might collide with any future plans)

**Comment by azizk** [comment]
> I'm not a legal expert but I think that would put us in trouble with `Rust` trademark which I would love to avoid (even though the project is written in Rust programming language it might collide with any future plans)

Okay, never mind then. :laughing:

> Hi, I would recommend joining Lapce Discord server as we discuss this, but overall decision is that Lapce will not be renamed (we are still discussing how it's pronounced)

Oh, looks like I missed the party! What's the summary and result? It's a pity if it shouldn't be renamed... but that's okay. I went ahead and called my fork [lapiz](https://github.com/azizk/lapiz). No offence, but the name "lapce" isn't really relatable to me. :slightly_smiling_face:

**Comment by panekj** [comment]
> What's the summary and result?

`Lapce` stays as the name for the project and votes so far are
![image](https://user-images.githubusercontent.com/50457605/185811284-34ff598c-fff2-41fa-8a31-1eb62bd31e8e.png)

> No offence, but the name "lapce" isn't really relatable to me. 🙂

It's supposed to be unique, not relatable.

> I went ahead and called my fork [lapiz](https://github.com/azizk/lapiz).

Doesn't fit the description: "Lightning-fast And Powerful Code Editor"

**Comment by azizk** [comment]
Thanks for the update and the screenshot. Looks like there's a winner, however I don't think that "lapse" is a great choice... considering what it means?

> Doesn't fit the description: "Lightning-fast And Powerful Code Editor"

I know, but I can change that too. At least it gives me peace of mind. :smile:

I just managed to compile lapce on Manjaro. Here we go! :+1:
