### ISSUE TITLE
Windows security pop-up on Windows 11

### ISSUE THREAD

**Issue by DevChaudhary78** [lapce/lapce#975]
I am currently using windows 11 and recently used lapce to test it out, I compiled it from source and I am facing a problem right now, whenever I try to open lapce, my Windows Security goes crazy, like it keeps on spamming Quick Scan required every 10 seconds, it will even continue after closing lapse.

**Comment by MinusGix** [comment]
Did you have any of the language servers installed? They could try touching a lot of files in a project. Though, I'm not entirely sure what causes quick-scan to activate.

**Comment by ghishadow** [comment]
Last time I have this problem was due to https://crates.io/crates/proc-macro-hack, as Window Defender doesn't seem to like the word 'hack' word. Can you check in Windows Security which file/crate it is tagging as threat ?

**Comment by DevChaudhary78** [comment]
> Last time I have this problem was due to https://crates.io/crates/proc-macro-hack, as Window Defender doesn't seem to like the word 'hack' word. Can you check in Windows Security which file/crate it is tagging as threat ?

I don't know why but after recompiling I no longer get that annoying pop-up from Windows Security, so I am closing this issue, thanks for consideration 👍🏻

**Comment by DevChaudhary78** [comment]
somehow it fixed after recompiling the source code.
