### ISSUE TITLE
Crash if git buttom pressed without file loaded

### ISSUE THREAD

**Issue by QuixoticValentine** [lapce/lapce#976]
On Arch Linux (Asahi), opening lapce (0.1.3) via the terminal and clicking the git button without a file loaded causes a crash with the following text

"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /build/.cargo/git/checkouts/druid-f6980810fb848923/9f86f23/druid/src/text/layout.rs:237:56"

EDIT: Changing to lapce-git (0.1.3) fixed the issue.

**Comment by panekj** [comment]
Fixed in master already
