### ISSUE TITLE
install button for CPP plugin does not work.

### ISSUE THREAD

**Issue by lumost** [lapce/lapce#977]
On a fresh download of lapce the install plugin button for CPP did not work.  At the time I had installed the rust plugin and had a workspace for a 5 million loc project open.  Suggest having a progress indicator in the UI, or other feedback for plugin installation success/failure/start.

**Comment by anarchy89** [comment]
I have this issue as well, I am unable to scroll down on the plugins as well.

**Comment by panekj** [comment]
@anarchy89 what lapce version are you using?

There was an issue with `toml` library that failed to parse `plugin.toml` properly

**Comment by anarchy89** [comment]
@panekj the latest version available for windows, I installed a few days ago 0.1.3

**Comment by panekj** [comment]
yeah, unfortunately `0.1.3` uses the abandoned `toml` library and fails to parse plugin manifest
nightly builds will also not work currently because of the plugin API change, I'll try to update the plugin today so it should work with nightly/built from source

**Comment by anarchy89** [comment]
@panekj sweet thanks
