### ISSUE TITLE
Terminal Settings for paths with spaces fail

### ISSUE THREAD

**Issue by Psikik** [lapce/lapce#980]
On Windows, I was trying to set my terminal to git bash which is located in the `Program Files` directory. The code for configuring the shell splits the setting on spaces which: https://github.com/lapce/lapce/blob/master/lapce-proxy/src/terminal.rs#L59, this causes the terminal pane to crash.

**Comment by seomwan** [comment]
I've worked around this with:
`C:/Progra~1/path/to/shell.exe`

The code hasn't changed:

https://github.com/lapce/lapce/blob/fd74be8d7ff29265725013d158b85f1be7348292/lapce-proxy/src/terminal.rs#L59

So we need an escape / quoting mechanism. I think potential solution could be:

1. Double `"` quotes: /
2. Single 
3. Backslash escape (e.g. `test\nwith\ nspace\n `

**Comment by AverageComet250** [comment]
any update on this? I've been trying to set git bash as my terminal too, and I keep ending up with powershell...

**Comment by panekj** [comment]
> any update on this? I've been trying to set git bash as my terminal too, and I keep ending up with powershell...

if there isn't any update in the issue, it means there is no update

**Comment by AverageComet250** [comment]
point noted
