### ISSUE TITLE
TypeScript syntax highlighting incomplete

### ISSUE THREAD

**Issue by ConnorSMorrison** [lapce/lapce#991]
The only things highlighted are most of the keywords, built-in types, and uppercase variables. Missing is for, if, else if, else, while, strings, const, let, var, true, false, this, new, extends, and comments.

**Comment by ConnorSMorrison** [comment]
Actually, there's a lot more I missed. I'm currently working on this issue.

**Comment by MinusGix** [comment]
This is probably due to our tree-sitter scopes not being as in-depth as they should be. We also should be using some set of custom queries to standardize the tree-sitter scopes across different languages (we're deciding between using helix's or nvims, I believe).

**Comment by ConnorSMorrison** [comment]
This actually isn't Lapce's fault. The highlights.scm for tree-sitter-typescript just isn't very detailed. After forking and updating it a little bit, it already looks a lot better. However, I don't know how to use tree-sitter very well, so it probably won't be the greatest.

**Comment by awulkan** [comment]
I also ran into this. I'm not sure hot tree-sitter works either, but it works well for plain JS, so maybe it's possible to borrow code from that implementation?

**Comment by ghishadow** [comment]
This will be fixed after https://github.com/lapce/lapce/pull/957, as we are going to add helix scopes
![image](https://user-images.githubusercontent.com/9583775/188644544-36fe6b9e-2329-4139-8d7e-574d9f3e2186.png)

**Comment by ghishadow** [comment]
anything missing to close this? try typescript syntax highlighting in nightly
